### ISSUE TITLE
Launching the black screen, I executed xwayland in termux

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-x11#10]
#!/bin/sh
$PREFIX/bin/Xwayland &
$PREFIX/bin/am start -n com.termux.x11/.MainActivity

Black screen...
How can I solve it

**Comment by hanxinhao000** [comment]
./startx.sh
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Internal error:   Could not resolve keysym XF86FullScreen
Errors from xkbcomp are not fatal to the X server
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
> Internal error:   Could not resolve keysym Invalid
Errors from xkbcomp are not fatal to the X server
Starting: Intent { cmp=com.termux.x11/.MainActivity }
Warning: Activity not started, its current task has been brought to the front
$

**Comment by xeffyr** [comment]
There should be black screen.

**Comment by xeffyr** [comment]
Window manager should be launched manually.

**Comment by hanxinhao000** [comment]
Want to install xfce4 or something?

**Comment by kcubeterm** [comment]
@hanxinhao000 can anyone share compiled apk file

**Comment by robsmith11** [comment]
If you just want Xwayland running, there is another project that may be more appropriate.  The thread on XDA has instructions for running the pre-built APK or you can get the source from gitlab. 

https://forum.xda-developers.com/android/apps-games/wayland-server-android-t3902720
https://gitlab.com/mogryph/sparkle-w-2

It works quite well.  I've been using it to work on my tablet on a daily basis for the past few months.
