### ISSUE TITLE
Clipboard between Android and Linux

### ISSUE THREAD

**Issue by v8karlo** [termux/termux-x11#100]
#

Can you implement Clipboard between Android and linux in Termux-x11.?

#

I have DEX and Clipboard between Android and Linux is lifesaver, like in VNC .
That way I can combine Android and Linux software with ease in DEX
and use both enviroment at the same time.

Fullscreen option would be great if can be implemented as well ?

#

![image](https://user-images.githubusercontent.com/57914925/159827777-5bd4181c-a176-44b9-8775-a35645a59f97.png)
#

**Comment by twaik** [comment]
It is in todo list.

**Comment by RalfWerner** [comment]
@v8karlo See #54 and #19 The version [1.2.04](https://github.com/termux/termux-x11/actions/runs/1277414726) contains the paste key (Android Clipborad) like in `termux-app`.

**Comment by twaik** [comment]
Fixed in [latest](https://github.com/termux/termux-x11/commit/3dad4e05756feba81abdaeddcc80301eab5a7aaf).

**Comment by twaik** [comment]
@exsilium read https://github.com/termux/termux-x11/issues/347

**Comment by exsilium** [comment]
@twaik thank you for the background and a workaround. Cheers!
