### ISSUE TITLE
Error: couldn't find RGB GLX visual or fbconfig

### ISSUE THREAD

**Issue by shim80** [termux/termux-x11#107]
Hi,
I'm using proot-distro Arch Linux.
I compiled mesa from source with config : 
platforms=x11,wayland -D gallium-drivers=swrast,zink -D vulkan-drivers=freedreno -D dri3=enabled -D egl=enabled -D gles2=enabled -D glvnd=true -D glx=dri -D libunwind=disabled -D osmesa=true -D shared-glapi=enabled -D microsoft-clc=disabled -D valgrind=disabled -D gles1=disabled -D freedreno-kgsl=true
 
and then:
export LOADER_DRIVER_OVERRIDE=zink
export GALLIUM_DRIVER=zink

but when I launch glxgears, I got error:
`Error: couldn't get an RGB, Double-buffered visual`
glxinfo:
`Error: couldn't find RGB GLX visual or fbconfig`
blender:
```
intern/ghost/intern/GHOST_WindowX11.cpp:136: X11 glXQueryVersion() failed, verify working openGL system!
initial window could not find the GLX extension         
Writing: /tmp/blender.crash.txt                         
Segmentation fault
```

After some research, it's seem to be the version of xwayland used in Termux:X11 that's not same as my proot distro.
However, I can't dowgrade packages with Arch, and there's no updates on Termux X11 packages...
Also, I'm not sure they're even same packages : my Arch have xorg-xwayland 22.1.1-1, and Termux use xwayland 1.20.5-12
Any advice ?

Galaxy Note 9 N9600
Android 10
unlocked bootloader with kvm enabled
Qualcomm Snapdragon 845

**Comment by dontknowhy** [comment]
BUT you can launch xfce4 
right?
(i tried glxgears,glxdemo,glmark2
but nothing work)

**Comment by dontknowhy** [comment]
> BUT you can launch xfce4 
> right?
> (i tried glxgears,glxdemo,glmark2
> but nothing work)

(that mean you can only enjoy xfce4 without GLX extension)

**Comment by shim80** [comment]
> BUT you can launch xfce4 right? (i tried glxgears,glxdemo,glmark2 but nothing work)

Yes. Xfce4 work.
Also, with regular mesa package, I got glxgears working well, but it's not above OpenGL 2.1. I need OpenGL 3.3 and up to make Blenders work.
It's why I compiled this one with zink and gallium support

**Comment by dontknowhy** [comment]
> > BUT you can launch xfce4 right? (i tried glxgears,glxdemo,glmark2 but nothing work)
> 
> Yes. Xfce4 work.
> Also, with regular mesa package, I got glxgears working well, but it's not above OpenGL 2.1. I need OpenGL 3.3 and up to make Blenders work.
> It's why I compiled this one with zink and gallium support

I compiled mesa using the following options : 
meson .. -D gallium-drivers=swrast,zink,v3d,vc4,freedreno,etnaviv,nouveau,tegra,virgl,lima,panfrost -D vulkan-drivers=freedreno -D dri3=enabled  -D egl=enabled  -D gles2=enabled -D gles1=enabled -D glvnd=true -D glx=dri  -D libunwind=disabled -D osmesa=true  -D shared-glapi=enabled -D microsoft-clc=disabled  -D valgrind=disabled -D freedreno-kgsl=true(from https://b23.tv/XsnYegp)

after that i use freedreno driver for xfce4…
and it seems like hardware acceleration is working???(i think only framebuffer is working…)
 
i have no idea for this weird Mesa …
many people on bilibili says:"Hardware Acceleration working on Termux!!!",but they  can only run glxgears with the regular version of Mesa…
my own Mesa can't run and zsh said:segmentation fault…(the Gallium driver and mesa_driver_loader_override has been unseted)

I checked out the developer website for Android…
Then Android only supports OpenGL ES 3.1 at the highest…
sorry for this(

(看样子是中国人是吧，看着都从桂树2018那过来的,要不是也无所谓)

**Comment by v8karlo** [comment]
#

Most people installs wrong version of apps for X11 .

#

Here is complete manual for clean install of termux-x11 on Ubuntu 22.04 Jammy 
and links to correct apps for installing .

https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152

Hope it helps . !

#

Also for more info on x11 you can join Udroid Discord channel and ask stuff there .

Join it from here https://discord.gg/y432PhPYCS

#

After few days of using 22.04 Jammy on termux-x11 , can say that is pretty fast and usable .

#

.

**Comment by Kreatifchk** [comment]
You have found a solution ?

**Comment by twaik** [comment]
That is definitely not a problem of termux-x11. That is a problem of xwayland...

**Comment by dontknowhy** [comment]
> That is definitely not a problem of termux-x11. That is a problem of xwayland...

err…
i'm now using the Xwayland completed in Debian(The xwayland from apt is too new )
and glxgears,glxdemo or something used glx doesn't work just like before…
(I'm sorry for my poor English…)

**Comment by dontknowhy** [comment]
> You have found a solution ?

nope
i tried freedreno,panfrost,zink
but GLX didn't work

**Comment by dontknowhy** [comment]
> Hi,
> I'm using proot-distro Arch Linux.
> I compiled mesa from source with config : 
> platforms=x11,wayland -D gallium-drivers=swrast,zink -D vulkan-drivers=freedreno -D dri3=enabled -D egl=enabled -D gles2=enabled -D glvnd=true -D glx=dri -D libunwind=disabled -D osmesa=true -D shared-glapi=enabled -D microsoft-clc=disabled -D valgrind=disabled -D gles1=disabled -D freedreno-kgsl=true
>  
> and then:
> export LOADER_DRIVER_OVERRIDE=zink
> export GALLIUM_DRIVER=zink
> 
> but when I launch glxgears, I got error:
> `Error: couldn't get an RGB, Double-buffered visual`
> glxinfo:
> `Error: couldn't find RGB GLX visual or fbconfig`
> blender:
> ```
> intern/ghost/intern/GHOST_WindowX11.cpp:136: X11 glXQueryVersion() failed, verify working openGL system!
> initial window could not find the GLX extension         
> Writing: /tmp/blender.crash.txt                         
> Segmentation fault
> ```
> 
> After some research, it's seem to be the version of xwayland used in Termux:X11 that's not same as my proot distro.
> However, I can't dowgrade packages with Arch, and there's no updates on Termux X11 packages...
> Also, I'm not sure they're even same packages : my Arch have xorg-xwayland 22.1.1-1, and Termux use xwayland 1.20.5-12
> Any advice ?
> 
> Galaxy Note 9 N9600
> Android 10
> unlocked bootloader with kvm enabled
> Qualcomm Snapdragon 845

new problem:you're using Snapdragon 845 cpu
so you need to recomplete Mesa with platforms=x11,wayland -D gallium-drivers=swrast,zink,freedreno -D vulkan-drivers=freedreno -D dri3=enabled -D egl=enabled -D gles2=enabled -D glvnd=true -D glx=dri -D libunwind=disabled -D osmesa=true -D shared-glapi=enabled -D microsoft-clc=disabled -D valgrind=disabled -D gles1=disabled -D freedreno-kgsl=true
then export MESA_DRIVER_LOADER_OVERRIDE=freedreno&&export GALLIUM_DRIVER=freedreno

**Comment by rjsprojone** [comment]
Inside or outside proot? I don't get it either
