### ISSUE TITLE
allow-external-apps property

### ISSUE THREAD

**Issue by aesvechnikov** [termux/termux-x11#113]
Hi, i just downloaded latest build, trying to run termux-X11 and got the error below. What should i do with that, manually fix the parameter? Or there is another simple way? 

## Report Info

**User Action**: `plugin execution command`  
**Sender**: `RunCommandService`  
**Report Timestamp**: `2022-04-13 17:49:28.948 UTC`  
##

## RUN_COMMAND Execution Intent Command

**Previous State**: `Pre-Execution`  
**Current State**: `Failed`  
**Executable**: `/data/data/com.termux/files/usr/libexec/termux-x11/termux-startx11`  
**Arguments:** -  
**Working Directory**: -  
**inBackground**: `true`  
**isFailsafe**: `false`  
**Session Action**: -  
**isPluginExecutionCommand**: `true`  

**Result PendingIntent Creator:** -  

**Stdout**: -  
**Stderr**: -  
**Exit Code**: -  

**Error Code**: `2`  
**Error Message**:
````
RunCommandService requires `allow-external-apps` property to be set to `true` in `~/.termux/termux.properties` file.
````

### StackTraces

`-`
##

### Plugin API Help

Visit https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent for more info on RUN_COMMAND Intent usage.
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.81+`  
**SDK_INT**: `29`  
**RELEASE**: `10`  
**ID**: `HUAWEIDBY-W09`  
**DISPLAY**: `DBY-W09S 2.0.0.225(C10E3R3P2)`  
**INCREMENTAL**: `102.0.0.225C10`  
**SECURITY_PATCH**: `2020-11-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HUAWEI`  
**MODEL**: `DBY-W09`  
**PRODUCT**: `DBY-W09NM`  
**BOARD**: `DBY`  
**HARDWARE**: `qcom`  
**DEVICE**: `HWDBY`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by agnostic-apollo** [comment]
Open the link provided and read.
