### ISSUE TITLE
Xfce that is not allowed to start???

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-x11#114]
well…
i installed xfce in proot container…
and i run it…
it's working…

and TODAY,i run it again
it just shows:
_IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root
/usr/bin/iceauth:  creating new authority file /tmp/ICEauthority

(xfwm4:11165): xfwm4-WARNING **: 03:50:52.867: GLX extension missing, GLX support disabled.

and nothing shows on display…
help me to fix it,please…

**Comment by dontknowhy** [comment]
https://user-images.githubusercontent.com/85813508/163660690-f4bfcab7-07ab-4629-9ae2-c4b372cccf04.mp4
and it's stopped…

**Comment by wmcbtech30** [comment]
I'm pretty sure it should start. but i think there are 4 possible generic causes which I can guess
* You are using distribution's `xwayland` server which it's not guarantee to work with current Termux X11 protocol
* You seem to start termux x11 and xwayland server on termux but you did not bind mount tmp in your `proot` or `proot-distro` launch and forgot to export `DISPLAY` variable pointing to `termux-x11`
* You started termux x11 and xwayland as well as you bind mounted termux's tmp directory and exported the DISPLAY variable but xwayland fails to initialize
* You probably didn't wait much long (since the video was short and not enough data to analyze it)

My solution is try restarting Termux as it will flush `$PREFIX/tmp` directory, clean out closed ports preventing xwayland from starting

**Comment by dontknowhy** [comment]
> I'm pretty sure it should start. but i think there are 4 possible generic causes which I can guess
> * You are using distribution's `xwayland` server which it's not guarantee to work with current Termux X11 protocol
> * You seem to start termux x11 and xwayland server on termux but you did not bind mount tmp in your `proot` or `proot-distro` launch and forgot to export `DISPLAY` variable pointing to `termux-x11` xwayland port
> * You started termux x11 and xwayland as well as you bind mounted termux's tmp directory and exported the DISPLAY variable but xwayland fails to initialize
> * You probably didn't wait much long (since the video was short, logs is truncated and not enough data to analyze it)
> 
> My solution is try restarting Termux as it will flush `$PREFIX/tmp` directory, clean out closed ports preventing xwayland from starting 

okay
my device's wm size is 1600×1200.that means i can't record my screen for a long time.so the video was short
i mounted my $PREFIX/tmp to proot's /tmp
htop said the processes of the xfce4 started.
but i can't see anything on display,even i setted the DISPLAY to :0

(I had successfully started xfce before, but now I don't know why it won't start )
(and i used freedreno for hardware acceleration )

**Comment by dontknowhy** [comment]
> I'm pretty sure it should start. but i think there are 4 possible generic causes which I can guess
> * You are using distribution's `xwayland` server which it's not guarantee to work with current Termux X11 protocol
> * You seem to start termux x11 and xwayland server on termux but you did not bind mount tmp in your `proot` or `proot-distro` launch and forgot to export `DISPLAY` variable pointing to `termux-x11` xwayland port
> * You started termux x11 and xwayland as well as you bind mounted termux's tmp directory and exported the DISPLAY variable but xwayland fails to initialize
> * You probably didn't wait much long (since the video was short, logs is truncated and not enough data to analyze it)
> 
> My solution is try restarting Termux as it will flush `$PREFIX/tmp` directory, clean out closed ports preventing xwayland from starting 

i'm going to delete all files in &PREFIX/tmp now

**Comment by dontknowhy** [comment]
> > I'm pretty sure it should start. but i think there are 4 possible generic causes which I can guess
> > * You are using distribution's `xwayland` server which it's not guarantee to work with current Termux X11 protocol
> > * You seem to start termux x11 and xwayland server on termux but you did not bind mount tmp in your `proot` or `proot-distro` launch and forgot to export `DISPLAY` variable pointing to `termux-x11` xwayland port
> > * You started termux x11 and xwayland as well as you bind mounted termux's tmp directory and exported the DISPLAY variable but xwayland fails to initialize
> > * You probably didn't wait much long (since the video was short, logs is truncated and not enough data to analyze it)
> > 
> > My solution is try restarting Termux as it will flush `$PREFIX/tmp` directory, clean out closed ports preventing xwayland from starting 
> 
> i'm going to delete all files in &PREFIX/tmp now

Now it's stabilized. 
Still nothing appears on the screen 

htop:
![Screenshot_20220416_131931.jpg](https://user-images.githubusercontent.com/85813508/163662729-4145129e-efa4-42bc-b745-01923273d73a.jpg)

termux-x11 is working :
![Screenshot_20220416_131916.jpg](https://user-images.githubusercontent.com/85813508/163662733-89d4e1d7-9f8c-423e-8389-14a44a73827d.jpg)

stopped xfce4(the Chinese:*Failed: Module initialization failed* ):
![Screenshot_20220416_131912.jpg](https://user-images.githubusercontent.com/85813508/163662740-eabcdffe-06b6-46b6-a962-9be957a6b4b3.jpg)

nothIng works and i don't know why

**Comment by dontknowhy** [comment]
> > > I'm pretty sure it should start. but i think there are 4 possible generic causes which I can guess
> > > * You are using distribution's `xwayland` server which it's not guarantee to work with current Termux X11 protocol
> > > * You seem to start termux x11 and xwayland server on termux but you did not bind mount tmp in your `proot` or `proot-distro` launch and forgot to export `DISPLAY` variable pointing to `termux-x11` xwayland port
> > > * You started termux x11 and xwayland as well as you bind mounted termux's tmp directory and exported the DISPLAY variable but xwayland fails to initialize
> > > * You probably didn't wait much long (since the video was short, logs is truncated and not enough data to analyze it)
> > > 
> > > My solution is try restarting Termux as it will flush `$PREFIX/tmp` directory, clean out closed ports preventing xwayland from starting 
> > 
> > i'm going to delete all files in &PREFIX/tmp now
> 
> Now it's stabilized. 
> Still nothing appears on the screen 
> 
> htop:
> ![Screenshot_20220416_131931.jpg](https://user-images.githubusercontent.com/85813508/163662729-4145129e-efa4-42bc-b745-01923273d73a.jpg)
> 
> termux-x11 is working :
> ![Screenshot_20220416_131916.jpg](https://user-images.githubusercontent.com/85813508/163662733-89d4e1d7-9f8c-423e-8389-14a44a73827d.jpg)
> 
> stopped xfce4(the Chinese:*Failed: Module initialization failed* ):
> ![Screenshot_20220416_131912.jpg](https://user-images.githubusercontent.com/85813508/163662740-eabcdffe-06b6-46b6-a962-9be957a6b4b3.jpg)
> 
> nothIng works and i don't know why

the termux's xfce4 is working
![Screenshot_20220416_132643.jpg](https://user-images.githubusercontent.com/85813508/163662861-9958520d-bc2c-4d61-8983-ab48b961f72d.jpg)
i really don't know why…

**Comment by st0rmc4non** [comment]
> well… i installed xfce in proot container… and i run it… it's working…
> 
> and TODAY,i run it again it just shows: _IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root /usr/bin/iceauth: creating new authority file /tmp/ICEauthority
> 
> (xfwm4:11165): xfwm4-WARNING **: 03:50:52.867: GLX extension missing, GLX support disabled.
> 
> and nothing shows on display… help me to fix it,please…

I think it's not
```
 (xfwm4:11165): xfwm4-WARNING **: 03:50:52.867: GLX extension missing, GLX support disabled.
```

but rather, these errors is what likely it causes for xfce not to show up:
```
(xfsettingsd:29538): xfsettingsd-WARNING **: 16:04:16.889: Unknown mode '1376x682 @ 59.8' for output XWAYLAND0, aborting.

** (xfdesktop:29553): WARNING **: 16:04:18.726: Failed to get system bus: Could not connect: No such file or directory
```

Here's a workaround I discovered a while ago:
```
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :1 &
export DISPLAY=:1
xfsettingsd
env DISPLAY=:1 xfce4-session
```

**Comment by st0rmc4non** [comment]
> and TODAY,i run it again it just shows: _IceTransmkdir: Owner of /tmp/.ICE-unix should be set to root /usr/bin/iceauth: creating new authority file /tmp/ICEauthority

Didn't got this error though

**Comment by v8karlo** [comment]
For me it helps to clear  cache data on termux-x11 and try again . ( x11 / app info / storage / cache )

Here is complete manual for install x11 and links to correct apps for installing .

https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152

Hope it helps . !

.

**Comment by IntinteDAO** [comment]
Yep, it's Termux X11 bug. That's why I go to tigervncserver, because it's fast and doesn't have that problem.

**Comment by dontknowhy** [comment]
> Yep, it's Termux X11 bug. That's why I go to tigervncserver, because it's fast and doesn't have that problem.
> 
> But it works once. I mean for example xfce4-terminal. if you try to re-run it, it doesn't work

That's because tigervnc is using llvmpipe to render image .

**Comment by twaik** [comment]
It is definitely `termux-x11` bug, but not relaated to llvm or rendering.
Looks like `termux-x11` does not send response for `wl_display@get_registry request` second time.
```
~ WAYLAND_DEBUG=1 termux-x11
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
$XDG_RUNTIME_DIR is unset.
Exporting default value (/data/data/com.termux/files/usr/tmp).
termux-x11 is already running
Starting Xwayland
[307872.296]  -> wl_display@1.get_registry(new id wl_registry@2)
[307872.335]  -> wl_display@1.sync(new id wl_callback@3)
```
Can you please check `termux-11` log with `WAYLAND_DEBUG=1` after `xfce4-terminal` restart?
I'll check what exactly I can do.

**Comment by twaik** [comment]
For some reason I can not reproduce this anymore on the most recent version...

**Comment by twaik** [comment]
OK, I reproduced this, but do not know what I can do, it looks like `termux-x11` simply can't read unix socket or stucks at another function. I am not sure how I can trace this. Is there anyone who knows how to build callstack treemap using Android Studio? Maybe something like `uftrace` for Android?

**Comment by dontknowhy** [comment]
> OK, I reproduced this, but do not know what I can do, it looks like `termux-x11` simply can't read unix socket or stucks at another function. I am not sure how I can trace this. Is there anyone who knows how to build callstack treemap using Android Studio? Maybe something like `uftrace` for Android?

emm…
I forgot to tell you:i reinstalled my container,and termux-x11 is working.
I believe it's my container's problem.
Now i have another problem:I need  to make `virgl_test_server` work. But the `virgl_test_server` in Termux's package manager is completed with GLX, and you said:Android doesn't have any GLX support.
So i can't run it in right way.(I did have a working virgl server,but it doesn't support multi clients,so i can't run xfce with it)

**Comment by Zeioth** [comment]
XFCE works fine. Issue can be closed.
