### ISSUE TITLE
Can't input Chinese

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-x11#115]
It seems like termux-x11 Nnot supported Chinese
but i can input Chinese in VNC Server
why?

If Xwayland does not support X input method for input Chinese, please close this issue, if so, please let termux-x11 also support
input Chinese

**Comment by twaik** [comment]
Duplicate #147

**Comment by twaik** [comment]
Check latest build (which is "[Input of custom unicode characters.](https://github.com/termux/termux-x11/actions/runs/4333077282)".
