### ISSUE TITLE
How to use the keyboard?

### ISSUE THREAD

**Issue by radstevee** [termux/termux-x11#117]
I can't seem to input stuff and i don't have an external keyboard. im on xfce

**Comment by RalfWerner** [comment]
There are several versions (#54). In each, the `end/back key` (triangle) is used to switch on/off the OS-KB (external keyboard). The`ekeys` version also contains the Extra-Keys from Termux inclusive `KEYBOARD`

**Comment by lkber** [comment]
What shall I do?

**Comment by RalfWerner** [comment]
To switch on/off the On-Screen-KB, you can touch the end key (triangle). I do not use XFCE, but the function is independent of the Display/Window Manager (WM). Here is a screenshot (landscape) in which the end key is marked **blue**. I use Fluxbox as WM, the [ekeys-X11 version](https://github.com/termux/termux-x11/issues/54) (like termux) and _floating Gboard KB_. In this version is the KB toggle key also in the Extra-Key row included.
![grafik](https://user-images.githubusercontent.com/45426380/172563681-c80e7708-373e-4a8c-b883-6c6930ffe953.png)
