### ISSUE TITLE
Frequent crashing in direct input mode

### ISSUE THREAD

**Issue by personalizedrefrigerator** [termux/termux-x11#118]
# Summary
 * Seemingly random crashes after doing multi-finger gestures in direct input mode
 * Crashing does not occur directly after sending input --- it seems more random
 * I'm unable to reproduce the crash when using "emulate touchpad" mode/when using a physical mouse.

# Additional details
 * Android 12 (with `max_phantom_processes` set to a very large number)
 * Running XFCE4 session
 * I don't know how to get a crash log!

**Comment by RalfWerner** [comment]
This is a known bug and already included in the first version of @twaik on all devices. Only the other two _modes_ are stable.

**Comment by twaik** [comment]
Direct touch mode removed in https://github.com/termux/termux-x11/commit/540dcbebc8a46d8077396154c87ea35dd6427bde

**Comment by RalfWerner** [comment]
Why removed? This is the _only way_ to implement X applications with **multi-touch** functionality! On most of my devices, this is possible without crash.
Is there an alternative for **multi-touch**?

**Comment by twaik** [comment]
I can not fix a bug which I can not reproduce. If you can get detailed log of what exactly crashes I will restore this. Do you know work with debugger?

**Comment by RalfWerner** [comment]
I can try it, but you would have to _reset the commit_ (reopen this issue), before I clone termux-x11. I am currently working with old X11 versions. Mainly with the _**ekeys**_ brunch and I've at least one **_real_** device where I can reproduce it. I would use Android-Studio*)
You may still remember our [SSM](https://github.com/RalfWerner/integrated-process/issues/1) campaign. **Multi-touch** ist not the same but similar.
Long time ago (2019) you've created a check-tool - see the last 15 seconds of this [Video](https://www.dropbox.com/s/bfmq528p9o5vh73/One-Touch.mp4?dl=0)

*) but not on an emulated device! The fingers - up to 10 without feet:) are the _main input device_ on handies! Why should it be limited to just one finger? My test X application works very well with 2-4 fingers. But I don't get much more on it when I hold the device with the other hand.

**Comment by twaik** [comment]
> SSM

It should be fixed by https://github.com/termux/termux-x11/commit/a868f37c8ae4aeb54f2c5e53b0ee02db0dfba0b9 . For some reason sockets came in some broken state and wayland could not drop them. I really tried to fix it but now sometimes it breaks launching sequence. I am already working on something that will fix it.

> Multi-touch ist not the same but similar.

It feels like Android sometime sends touch events in wrong order. I will test it a bit later.

> Mainly with the ekeys brunch

I will work on it only after adding clipboard and sending unicode symbols, it is possibly only with X11 client. It is not real with current project state.

**Comment by RalfWerner** [comment]
Your last version cannot be built! But that from February 8th. In between, the data is reduced from 3.2MB to 1.7MB. I get the message:`Build file 'D:\Android\termux-x11\app\build.gradle' line: 72` What is `ant.patch(...`?

**Comment by twaik** [comment]
It is likely because of submodules. I'l fix it later...
