### ISSUE TITLE
Feature Request: Ability to kill the service from Termux.

### ISSUE THREAD

**Issue by JeffreyO** [termux/termux-x11#121]
I'm having a problem where I can't reconnect without manually killing and restarting the termux-x11 service. 'pkill Xwayland' doesn't work at all to do this.

I used the instructions from here: https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152 to get Ubuntu running. I'm wanting to start everything from a shell script, but I need the ability to stop and restart the service in order to work around a problem I have.

**Comment by twaik** [comment]
Latest builds from [here](https://github.com/twaik/termux-x11/actions) can be killed by `pkill Xwayland`. Does it fit?

**Comment by twaik** [comment]
Duplicate #48
