### ISSUE TITLE
scaled/virtual resolution feature?

### ISSUE THREAD

**Issue by sukualam** [termux/termux-x11#122]
my phone is 1080p, when i use termux x11, it render native resolution. the font is small (yes , change dpi will fix it) 

but is there any option to set custom resolution (scaled down), like 1280x720 .. so like vnc did?

it will make display look bigger and less resource (maybe)

**Comment by twaik** [comment]
Note for myself... https://github.com/termux/termux-x11/issues/89#issuecomment-1412535954

**Comment by twaik** [comment]
Fixed in https://github.com/termux/termux-x11/commit/a14c61a8bb279a2b086464ee28ad5b14bc9e5be9.

**Comment by twaik** [comment]
You can check this feature with latest build.
