### ISSUE TITLE
DEX - Autohide upper title bar ?

### ISSUE THREAD

**Issue by v8karlo** [termux/termux-x11#125]
#

Down NAV bar now can be removed which is excellent !

#

But ,
In DEX upper title bar is visible and annoying .
And it occupies screen without any purpose because it can AUTOHIDE .

Is it possible to autohide it programmaticaly ?
Like in samsung movie player ( it autohides ) .

It must not be removed completely because of maximize button ( sizing ) , but autohide .

I found something  on this page      https://www.javatpoint.com/android-hide-title-bar-example

requestWindowFeature(Window.FEATURE_NO_TITLE);    /will hide the title   
getSupportActionBar().hide();     //hide the title bar  

#

And on this page found something about hidding upper bar .

https://developer.android.com/training/system-ui/status

`You can hide the status bar on Android 4.0 (API level 14) and lower by setting [WindowManager](https://developer.android.com/reference/android/view/WindowManager) flags. You can do this programmatically or by setting an activity theme in your app's manifest file. Setting an activity theme in your app's manifest file is the preferred approach if the status bar should always remain hidden in your app (though strictly speaking, you could programmatically override the theme if you wanted to). For example:`

```
<application
    ...
    android:theme="@android:style/Theme.Holo.NoActionBar.Fullscreen" >
    ...
</application>
```

#

![image](https://user-images.githubusercontent.com/57914925/168875543-67babe2e-6d3e-4302-840c-701345c8c121.png)

#

EXAMPLE from   
https://www.javatpoint.com/android-hide-title-bar-example

Output: Hiding the Title Only

![image](https://user-images.githubusercontent.com/57914925/168876932-1d376951-e542-4f83-8ae7-3f7c48f1fb95.png)

#

Output: Hiding the TitleBar and enabling FullScreen

![image](https://user-images.githubusercontent.com/57914925/168877012-9239e8e4-aa00-4717-8070-e3681921fd4f.png)

#

**Comment by v8karlo** [comment]
If can that be done programatically , PLEASE !

The X11 without that upper bar would be superb !

**Comment by zanfix** [comment]
what i am doing, and for me it works only on dex, is to add the following method in app/src/main/java/com/termux/x11/MainActivity.java:

```
    private void hideSystemBars() {
        getWindow().getDecorView().setSystemUiVisibility(
          View.SYSTEM_UI_FLAG_LAYOUT_STABLE
        | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
        | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
        | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
        | View.SYSTEM_UI_FLAG_FULLSCREEN
        | View.SYSTEM_UI_FLAG_IMMERSIVE);
    }
```

then call it from onCreate() and onWindowFocusChanged()

in onWindowFocusChanged() call it only if hasFocus is true:

```
        if(hasFocus)
            hideSystemBars();
```

It is somewhat glitchy but works for me

**Comment by 5A52** [comment]
Dex hides both bars for the fullscreen apps.The best option will be to have "fullscreen" checkbox in app settings.

**Comment by alan9820** [comment]
If it can be done like what XSDL does would be perfect

on full screen, both Nav and Title bar wont prompt out even the cursor is moved to the edge of screen

**Comment by 5A52** [comment]
m$ RDP for android is doing wery well on DEX. In the full screen it even intercepts hardware keyboards somehow, and you have only magic key or key combo to minimise the session. XSDL closes it self on alt+F4, termux-x11 minimises.

**Comment by youngshall** [comment]
> what i am doing, and for me it works only on dex, is to add the following method in app/src/main/java/com/termux/x11/MainActivity.java:
> 
> ```
>     private void hideSystemBars() {
>         getWindow().getDecorView().setSystemUiVisibility(
>           View.SYSTEM_UI_FLAG_LAYOUT_STABLE
>         | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
>         | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
>         | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
>         | View.SYSTEM_UI_FLAG_FULLSCREEN
>         | View.SYSTEM_UI_FLAG_IMMERSIVE);
>     }
> ```
> 
> then call it from onCreate() and onWindowFocusChanged()
> 
> in onWindowFocusChanged() call it only if hasFocus is true:
> 
> ```
>         if(hasFocus)
>             hideSystemBars();
> ```
> 
> It is somewhat glitchy but works for me

For those using android phones with only cabled video output, but without desktop mode like me:
[zanfix]'s method is enough for hiding title bar, but a black area remains on top!

To fill up all the screen, you need to edit /app/src/main/res/values/styles.xml,
just change all
`<item name="android:fitsSystemWindows">true</item>`
to 
`<item name="android:fitsSystemWindows">false</item>`

This should allow all screen space be filled up.

**Comment by v8karlo** [comment]
#

Samsung S20 DEX

Full screen without upper Nav Bar [ how to remove down Nav Bar is in previous posts ]

#

Install X11 Build#196 [ Enables Full Screen ]
https://github.com/termux/termux-x11/actions/runs/3065627748

#

![image](https://user-images.githubusercontent.com/57914925/190859493-4b896a80-d999-485c-8fe5-eabee87a502a.png)

#

Enabled  Force Desktop Mode [ Experimental Desktop mode on secondary displays ]
Restart DEX [ Build#196 installed ] and start X11

![image](https://user-images.githubusercontent.com/57914925/190859598-5870d171-ef64-4424-b722-7850814b04b5.png)

#

![image](https://user-images.githubusercontent.com/57914925/190860682-555c85f8-8dd0-44f1-b48d-a4f069f6615f.png)

#

**Comment by 5A52** [comment]
The right way: https://developer.samsung.com/samsung-dex/modify-optimizing.html

**Comment by twaik** [comment]
@v8karlo Can you please check if this issue still relevant with the most recent version?

**Comment by zanfix** [comment]
I tested it with the most recent version and I noticed the following:

App goes correctly full screen when first launched, but will revert to maximised window (window border and DEX lower status bar) if you go with the mouse down to the DEX lower status bar, to switch to another android app (android terminal for example)

Once this happens I am not been able to get it back to proper full screen. When into this situation, the mouse cursor (the android one) appears to be off in Y by some amount in respect to the X pointer.

**Comment by zanfix** [comment]
> what i am doing, and for me it works only on dex, is to add the following method in app/src/main/java/com/termux/x11/MainActivity.java:
> 
> ```
>     private void hideSystemBars() {
>         getWindow().getDecorView().setSystemUiVisibility(
>           View.SYSTEM_UI_FLAG_LAYOUT_STABLE
>         | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
>         | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
>         | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
>         | View.SYSTEM_UI_FLAG_FULLSCREEN
>         | View.SYSTEM_UI_FLAG_IMMERSIVE);
>     }
> ```
> 
> then call it from onCreate() and onWindowFocusChanged()
> 
> in onWindowFocusChanged() call it only if hasFocus is true:
> 
> ```
>         if(hasFocus)
>             hideSystemBars();
> ```
> 
> It is somewhat glitchy but works for me

Similarly as I mentioned in this past comment, calling the method setFullScreenForExternalDisplay() from onWindowFocusChanged() method will re-enable the proper fullscreen when switching back to termux-x11 from the DEX taskbar

**Comment by rudolphpienaar** [comment]
Hey @zanfix --

Can you do a PR with this?

Many thanks!

**Comment by 5A52** [comment]
Strange, few years old v1.0 apk, works fine on phone scren/on android second screen/and even on dex. Full scren or windowed (resizing is ok), first start or second, minimised and then recaled. 
Only lacks shared clipboard, and system keys (like alt+f4) interception.

**Comment by twaik** [comment]
> Strange, few years old v1.0 apk, works fine on phone scren/on android second screen/and even on dex. Full scren or windowed (resizing is ok), first start or second, minimised and then recaled. 

I do not see any problem here. What exactly is not right?

> Only lacks shared clipboard

I am already working on something that will make this possible...

> system keys (like alt+f4) interception.

It is already done for Dex.

**Comment by 5A52** [comment]
> I do not see any problem here. What exactly is not right?
That something happened (I do not know what, but really want to know :) ) with at least full screen, today situation is worse than yesterday
> I am already working on something that will make this possible...
im apriciate your work......realy, very very
>It is already done for Dex. 
sorry. nothing personal, it was all about full screen drawbacks

**Comment by zanfix** [comment]
> Hey @zanfix --
> 
> Can you do a PR with this?
> 
> Many thanks!

I think @twaik fixed this. it it working correctly for me in the last release
