### ISSUE TITLE
Termux:X11 is not installed

### ISSUE THREAD

**Issue by DrGeoff** [termux/termux-x11#131]
I installed termux-x11 by

`pkg install termux-x11`

and then tried start it by
`~ $ export XDG_RUNTIME_DIR=${TMPDIR}`
`~ $ termux-x11 :1 &`

which failed with the error message

`Termux:X11 is not installed`

Running under strace gives the smoking gun 
`newfstatat(AT_FDCWD,"/data/data/com.termux.x11/", 0x7f<snip>, 0) = -1 ENOENT (No such file or directory)`

**Comment by Grimler91** [comment]
You need to install the termux:X11 app/apk as well
