### ISSUE TITLE
how to install vs code?

### ISSUE THREAD

**Issue by 3RM1N3** [termux/termux-x11#134]
I tried to install vs code in termux with x11, but i got this:
![mmexport1655382265086](https://user-images.githubusercontent.com/47353218/174069055-a44d31f5-b4cc-4c26-8b74-6daa7e587ceb.jpg)

**Comment by 3RM1N3** [comment]
Or maybe i need to use proot-distro?

**Comment by Grimler91** [comment]
> Or maybe i need to use proot-distro?

Yes, you can't install debs for other distros in termux

**Comment by 3RM1N3** [comment]
> > Or maybe i need to use proot-distro?
> 
> Yes, you can't install debs for other distros in termux

Ok, thank you Grimler😄

**Comment by twaik** [comment]
@Grimler91 can you please move this issue to `termux-packages`?
