### ISSUE TITLE
Strange behaviour of `termux-x11`

### ISSUE THREAD

**Issue by v8karlo** [termux/termux-x11#135]
#

I noticed strange behaviour of Termux and Termux-x11 .

I wrote it in this disscussion :

https://github.com/RandomCoderOrg/ubuntu-on-android/discussions/152#discussioncomment-2976607

Could be Android 12 handling apps issue . ??? Maybe ?

#

**Comment by twaik** [comment]
Can you please confirm if it is relevent for latest build?

**Comment by twaik** [comment]
@v8karlo ?

**Comment by twaik** [comment]
@v8karlo, Can you please test latest build from [here](https://github.com/twaik/termux-x11/actions)?

**Comment by twaik** [comment]
@v8karlo Can you please check if it is reproducible on latest builds?
