### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by hyper-v01** [termux/termux-x11#136]
~ $ termux-x11 :1 &
[3] 4715

~ $ res = 0
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@cc1eb61}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@24ef686}
Got finish request
App sent finishing command

~ $ Failed to connect to Termux:X11.
 Something went wrong.
Failed to connect to Termux:X11. Something went wrong.

**Comment by 2096779623** [comment]
Did you give termux-x11 permission to read termux app files?

**Comment by hyper-v01** [comment]
> Did you give termux-x11 permission to read termux app files?

yet.

**Comment by twaik** [comment]
Not enough information to analyze. Can you please post `termux-info` output and `adb logcat` log?
