### ISSUE TITLE
黑屏

### ISSUE THREAD

**Issue by hyper-v01** [termux/termux-x11#137]
按照说明一步一步做结果发现是黑屏。

**Comment by twaik** [comment]
Closed as non informative...

**Comment by waldhef** [comment]
> 按照说明一步一步做结果发现是黑屏。

@hyper-v01,
try to install `termux-x11.deb` package from the zip-archive you have downloaded.

Instead of `pkg install termux-x11`, do `dpkg -i /path/to/termux-x11/termux-x11.deb`
Eg.: `dpkg -i /sdcard/Download/termux-x11/termux-x11.deb`

Hope it helps.
