### ISSUE TITLE
An error appears whenever I do this command

### ISSUE THREAD

**Issue by DoubleShotgun** [termux/termux-x11#143]
`~ $ termux-x11 :1 &`

`[3] 12580`

`[2]   Exit 1                  termux-x11 :1`

`~ $ Starting: Intent { cmp=com.termux.x11/.MainActivity }`

`~ $ Failed starting Termux:X11: timeout`

**Comment by twaik** [comment]
Did you install `termux-x11` package using `apt install`/`pkg install`? The package installed from apt/pkg is outdated, but you can try installing it from last successful artifact.

**Comment by twaik** [comment]
As I see you use an outdated version of `termux-x11`. Try to install updated artifacts.
