### ISSUE TITLE
command termux-x11 not working

### ISSUE THREAD

**Issue by dexi22** [termux/termux-x11#146]
![IMG_20220807_100158](https://user-images.githubusercontent.com/65784455/183279477-2d4cad21-e77b-463d-9eda-8ec849193f7e.jpg)

**Comment by twaik** [comment]
1. Please, post logs as text. Not images.
2. Please, post output of `termux-info` command.

**Comment by dexi22** [comment]
**Logs**
Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so     java.lang.NoSuchMethodError: No interface method startActivity(Landroid/app/IApplicationThread;Ljava/lang/String;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/os/IBinder;Ljava/lang/String;IILandroid/app/ProfilerInfo;Landroid/os/Bundle;)I in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)                      at com.termux.x11.starter.Compat.startActivity(Compat.java:27)                                                              at com.termux.x11.starter.Starter.startActivity(Starter.java:144)
        at com.termux.x11.starter.Starter.onRun(Starter.java:80)                                                                    at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:42)                                                            at com.termux.x11.starter.Starter$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:919)              Android reported activity started but we did not get any respond                                                            Looks like we failed to start activity.

**Termux-info**
```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=20360
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.aliyun.com/termux/termux-packages-24 stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.aliyun.com/termux/x11-packages x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.24
Android version:
10
Kernel build information:
Linux localhost 4.4.192-perf+ #1 SMP PREEMPT Fri Sep 3 15:22:30 WIB 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
```

**Comment by zairullahdev** [comment]
It's using different version of termux+X11 and it's package, install using the packaged deb and apk

**Comment by twaik** [comment]
> It's using different version of termux-X11 and it's package

No, it's not. The problem is in non sdk api I am using to send Intent starting Activity in main application. I think it should be changed but still not sure how.

**Comment by twaik** [comment]
Can you please check it again with the latest artifact?

**Comment by kde-yyds** [comment]
it now works
thanks
