### ISSUE TITLE
Lack of Chinese input method, consider to add fcitx5

### ISSUE THREAD

**Issue by EdwardZhangLink** [termux/termux-x11#147]
I have installed `TeXLive` and `texstudio`, but I lack a proper Chinese input method to write the documentation. I need a Chinese input method like `fcitx5` to add to the library.

Fcitx5 Wiki Page
[https://fcitx-im.org/wiki/Fcitx_5](https://fcitx-im.org/wiki/Fcitx_5) 
[https://fcitx-im.org/wiki/Fcitx_5/zh-cn](https://fcitx-im.org/wiki/Fcitx_5/zh-cn) 
Fcitx5 Source Code Page
[https://github.com/fcitx/fcitx5](https://github.com/fcitx/fcitx5)

**Comment by twaik** [comment]
I know what is fcitx5, but it will not help. 
Android sends proper keycodes only in the case if you input english characters, in any other case it sends Unicode characters. 
Xwayland can receive input only as linux scancodes. 
I am planning to make additional X client based on `x11vnc` and `xdotool` code which will be able to input every single Unicode symbol.

In the case if you can not wait you can try to use any **linux (not Android)** on screen keyboard solution which supports chinese.

**Comment by EdwardZhangLink** [comment]
> I know what is fcitx5, but it will not help. Android sends proper keycodes only in the case if you input english characters, in any other case it sends Unicode characters. Xwayland can receive input only as linux scancodes. I am planning to make additional X client based on `x11vnc` and `xdotool` code which will be able to input every single Unicode symbol.
> 
> In the case if you can not wait you can try to use any **linux (not Android)** on screen keyboard solution which supports chinese.

First of all, thank you for your reply. I am indeed a bit frustrated. I tried to understand GUI related knowledge, but now they are too complicated for me. Maybe I didn't understand your reply, maybe I didn't express it clearly, actually I don't intend to send Chinese characters to `xwayland` directly through Android keyboard, but give Chinese candidate words in pinyin form by inputting English characters through input method. I think `fcitx5` will work like this, but maybe not so simple, hope I can get some help.
Besides, I found it support `wayland` in `fcitx5` related page, but I don't know if it is helpful. Because the special feature of Chinese input is always to use an input method to finalize Chinese input by giving Chinese character candidates, but Linux on-screen keyboard obviously doesn't have such function. Maybe we can consider to adapt package like `fcitx5` first, and then test whether it is applicable.
Finally, looking forward to your progress!

**Comment by junrenshi** [comment]
It is great to see Termux now includes two basic fcitx5 packages: fcitx5 and fcitx5-data.  However, in order to actually use it to input Chinese,  I have to compile and manually install extra tools including fcitx5-chinese-addons, fcitx5-configtool, fcitx5-gtk, fcitx5-qt, and libime.  All these tools can be downloaded from the github repository of the fcitx project.   It would be ideal if these tools are also included in Termux packages.

**Comment by twaik** [comment]
`termux-x11` is not related to packages in `termux-packages`. Everything I can do is to add Unicode input. Work is already in progress.

**Comment by twaik** [comment]
Check latest build (which is "[Input of custom unicode characters.](https://github.com/termux/termux-x11/actions/runs/4333077282)").

<details>
I do not know chinese, I simply was typing every single symbol I saw in Samsung's keyboard suggestions. Dont laugh on me.

![photo_2023-03-05_00-13-53](https://user-images.githubusercontent.com/9674930/222930963-c9ac4d71-bd4b-44ad-9185-3052be1ac10b.jpg)
</details>

**Comment by twaik** [comment]
Can I close this?

**Comment by twaik** [comment]
@EdwardZhangLink @junrenshi @kde-yyds @dontknowhy Can you please confirm it works?

**Comment by twaik** [comment]
You are welcome. Sorry for waiting for this feature.

**Comment by kde-yyds** [comment]
so which commit fixed it?I can't find it

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/commit/f930dfebdb3becc993746f22329c2005e41267c3#diff-bb9040321da9b7beebb6d6a78ad0256377ac3a5f51f7d78daf0ec921e0ac9e7aR389

**Comment by dontknowhy** [comment]
![Screenshot_20230402_134402.jpg](https://user-images.githubusercontent.com/85813508/229334061-490e10b7-9e1b-4eab-a2e4-13fe359016da.jpg)
A sad story.

**Comment by twaik** [comment]
Try other keyboard.
