### ISSUE TITLE
proot llvmpipe error in termux-x11

### ISSUE THREAD

**Issue by wang42449** [termux/termux-x11#148]
mesa llvmpipe termux run in termux-x11 is ok.
but use proot :Error: couldn't get an RGB, Double-buffered visual
how can i solve this?
thanks

**Comment by twaik** [comment]
You can try to use mesa-swrast.

**Comment by wang42449** [comment]
like GALLIUM_DRIVER=swrast ? will it be slow

**Comment by twaik** [comment]
It will.

**Comment by wang42449** [comment]
thanks i will try

**Comment by wang42449** [comment]
hi i try it it give the same error as llvmpipe

**Comment by twaik** [comment]
Sorry, can not help with it. `termux-x11` was not designed to be used with acceleration.

**Comment by wang42449** [comment]
but llvmpipe is only a 3d support not use hardware ,if it doesn't support ,it means the opengl is not support like xsdl ,oh thats a bad note for me ,thank you for your help and i will try other things

**Comment by wang42449** [comment]
it seemd that us not only termux-x11 error when i use xvfb it still have this bug

**Comment by wang42449** [comment]
Hi i find the solution use xephyr can solce this problem

**Comment by twaik** [comment]
> it seemd that us not only termux-x11 error when i use xvfb it still have this bug

Looks like it is not related to `termux-x11` itself...
