### ISSUE TITLE
URL picker

### ISSUE THREAD

**Issue by yesco** [termux/termux-x11#15]
The URL-picker is a great too, as selecting text to copy is difficult, wish there was a way to do it with external keyboard instead.

In any case, I have an edge case of an URL going past then end of the screen, in *emacs*, and this maybe the case in other editors, and it's not recognized at the emacs sets the back-slash and the last position on the row to indicate that it continues below.

Screen shot attached.

![Screenshot_2020-05-25-23-05-21-986_com termux](https://user-images.githubusercontent.com/2121626/82830558-45416d00-9ee0-11ea-9bd6-de0964dafafc.jpg)

**Comment by xeffyr** [comment]
This isn't possible as unlike Termux, Termux:X11 uses graphical display. There no text, just video output from Xorg or Wayland server.

**Comment by yesco** [comment]
Que? I'm not using any X11, this is an emacs running inside a normal Termux wndow!
