### ISSUE TITLE
incorrectly lighter color?

### ISSUE THREAD

**Issue by youngshall** [termux/termux-x11#150]
I run termux-x11 and desktop environment running in proot ubuntu(xfce4), installed using tmoe script.
The desktop runs smoothly, but the color seems lighter than it should be. 
for example, I set desktop background to black (#000000), but it's still dark gray.
maybe I missed some settings? or this' a bug?

**Comment by twaik** [comment]
Can you please post some screenshots?

**Comment by youngshall** [comment]
> Can you please post some screenshots?

Sorry, I can't reproduce this bug anymore.
I closed and  relaunched termux-x11, and then the color become normal.
Likely this only occurs at first launch after installation.
Now everything is fine!

**Comment by twaik** [comment]
I found it! Android lightens some Views when they receive focus, this code fixes that:
```
setBackground(new ColorDrawable(Color.TRANSPARENT) {
    public boolean isStateful() {
        return true;
    }
    public boolean hasFocusStateSpecified() {
        return true;
    }
});
```

**Comment by youngshall** [comment]
> 

Amazing work! That must be really hard to find this root cause.
I still occasionally encountered this bug, and the only thing I can do is relaunching termux-x11.
Fixing it once and for all is very helpful to me.

**Comment by twaik** [comment]
This issue has been bothering me for several months.
