### ISSUE TITLE
command termux-x11 did not work

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#152]
i installed termux-x11 apk and deb（1.02.06）
but when i execute termux-x11，it outputed:

Loading shared library: /data/data/com.termux/files/usr/libexec/termux-x11/starter.apk!/lib/arm64-v8a/libx11-starter.so
java.lang.NoSuchMethodError: No interface method startActivity(Landroid/app/IApplicationThread;Ljava/lang/String;Ljava/lang/String;Landroid/content/Intent;Ljava/lang/String;Landroid/os/IBinder;Ljava/lang/String;IILandroid/app/ProfilerInfo;Landroid/os/Bundle;)I in class Landroid/app/IActivityTaskManager; or its super classes (declaration of 'android.app.IActivityTaskManager' appears in /system/framework/framework.jar)
        at com.termux.x11.starter.Compat.startActivity(Compat.java:27)
        at com.termux.x11.starter.Starter.startActivity(Starter.java:144)
        at com.termux.x11.starter.Starter.onRun(Starter.java:80)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:42)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda2.run(Unknown Source:2)
        at java.lang.Thread.run(Thread.java:929)
Android reported activity started but we did not get any respond
Looks like we failed to start activity.

termux-info :
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PID=26930
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.bfsu.edu.cn/termux/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
android-tools/stable 31.0.3p1-5 aarch64 [upgradable from: 31.0.3p1-3]
apt/stable 2.5.2 aarch64 [upgradable from: 2.5.0]
aria2/stable 1.36.0-5 aarch64 [upgradable from: 1.36.0-4]
binutils/stable 2.38-1 aarch64 [upgradable from: 2.38]
boost-headers/stable,stable 1.78.0-2 all [upgradable from: 1.78.0-1]
boost/stable 1.78.0-2 aarch64 [upgradable from: 1.78.0-1]
ca-certificates/stable,stable 1:2022.07.19 all [upgradable from: 1:2022.03.29]
clang/stable 14.0.6-2 aarch64 [upgradable from: 14.0.3-1]
cmake/stable 3.23.2-2 aarch64 [upgradable from: 3.23.1]
command-not-found/stable 2.1.0 aarch64 [upgradable from: 1.75]
curl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]
dialog/stable 1.3-20220526-0 aarch64 [upgradable from: 1.3-20220117-0]
dos2unix/stable 7.4.3 aarch64 [upgradable from: 7.4.2]
dpkg/stable 1.21.9 aarch64 [upgradable from: 1.21.7]
ffmpeg/stable 5.1 aarch64 [upgradable from: 5.0.1-1]
fish/stable 3.5.1-1 aarch64 [upgradable from: 3.4.1]
game-music-emu/stable 0.6.3-1 aarch64 [upgradable from: 0.6.3]
git/stable 2.37.1 aarch64 [upgradable from: 2.36.1]
glib/stable 2.72.2 aarch64 [upgradable from: 2.72.1-1]
gnupg/stable 2.3.7 aarch64 [upgradable from: 2.3.6]
googletest/stable 1.12.1-2 aarch64 [upgradable from: 1.11.0-1]
gpgv/stable 2.3.7 aarch64 [upgradable from: 2.3.6]
gstreamer/stable 1.20.3 aarch64 [upgradable from: 1.20.1]
harfbuzz/stable 5.1.0-1 aarch64 [upgradable from: 4.3.0]
imlib2/stable 1.9.1 aarch64 [upgradable from: 1.9.0-1]
inetutils/stable 2.3 aarch64 [upgradable from: 1.9.4-13]
jsoncpp/stable 1.9.5-1 aarch64 [upgradable from: 1.9.5]
libaom/stable 3.4.0-1 aarch64 [upgradable from: 3.3.0]
libc++/stable 25-2 aarch64 [upgradable from: 23b-3]
libcaca/stable 0.99.beta20-1 aarch64 [upgradable from: 0.99.beta20]
libcompiler-rt/stable 14.0.6-2 aarch64 [upgradable from: 14.0.3-1]
libcurl/stable 7.84.0 aarch64 [upgradable from: 7.83.1]
libdb/stable 18.1.40-4 aarch64 [upgradable from: 18.1.40-3]
libflac/stable 1.3.4-1 aarch64 [upgradable from: 1.3.4]
libgit2/stable 1.5.0 aarch64 [upgradable from: 1.4.3]
libgmp/stable 6.2.1-2 aarch64 [upgradable from: 6.2.1-1]
libgraphite/stable 1.3.14-2 aarch64 [upgradable from: 1.3.14-1]
libllvm/stable 14.0.6-2 aarch64 [upgradable from: 14.0.3-1]
liblz4/stable 1.9.4 aarch64 [upgradable from: 1.9.3]
libnghttp2/stable 1.48.0 aarch64 [upgradable from: 1.47.0]
libprotobuf/stable 2:3.19.3-1 aarch64 [upgradable from: 2:3.19.3]
libresolv-wrapper/stable 1.1.7-3 aarch64 [upgradable from: 1.1.7-2]
libtiff/stable 4.3.0-3 aarch64 [upgradable from: 4.3.0-2]
libvpx/stable 1:1.12.0-1 aarch64 [upgradable from: 1.11.0]
libwebp/stable 1.2.4 aarch64 [upgradable from: 1.2.2]
libwebrtc-audio-processing/stable 0.3.1-2 aarch64 [upgradable from: 0.3.1-1]
libx265/stable 3.5-4 aarch64 [upgradable from: 3.5-3]
lld/stable 14.0.6-2 aarch64 [upgradable from: 14.0.3-1]
llvm/stable 14.0.6-2 aarch64 [upgradable from: 14.0.3-1]
mpv/stable 0.34.1-7 aarch64 [upgradable from: 0.34.1-3]
ncpamixer/stable 1.3.3.1-3 aarch64 [upgradable from: 1.3.3.1]
ncurses-ui-libs/stable 6.3-2 aarch64 [upgradable from: 6.3-1]
ncurses-utils/stable 6.3-2 aarch64 [upgradable from: 6.3-1]
ncurses/stable 6.3-2 aarch64 [upgradable from: 6.3-1]
ndk-sysroot/stable 25-1 aarch64 [upgradable from: 23b-7]
o-editor/stable 2.55.1 aarch64 [upgradable from: 2.51.0]
opencl-headers/stable,stable 2022.05.18 all [upgradable from: 2022.01.04]
p7zip/stable 17.04-2 aarch64 [upgradable from: 17.04-1]
perl/stable 5.36.0-1 aarch64 [upgradable from: 5.34.1-1]
procps/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5-1 aarch64 [upgradable from: 23.4]
pulseaudio/stable 16.1-2 aarch64 [upgradable from: 14.2-10]
rhash/stable 1.4.3 aarch64 [upgradable from: 1.4.2-2]
termux-am-socket/stable 1.5.0 aarch64 [upgradable from: 1.3.0]
termux-keyring/stable,stable 3.9 all [upgradable from: 3.4]
termux-licenses/stable,stable 2.0-3 all [upgradable from: 2.0-2]
termux-tools/stable,stable 1.27.0-1 all [upgradable from: 0.179]
unrar/stable 6.1.7-1 aarch64 [upgradable from: 6.1.6]
unzip/stable 6.0-9 aarch64 [upgradable from: 6.0-7]
vim-runtime/stable,stable 9.0.0000 all [upgradable from: 8.2.4650]
vim/stable 9.0.0000 aarch64 [upgradable from: 8.2.4650]
vulkan-headers/stable,stable 1.3.225 all [upgradable from: 1.3.214]
zstd/stable 1.5.2-2 aarch64 [upgradable from: 1.5.2-1]
Android version:
10
Kernel build information:
Linux localhost 4.14.116 #1 SMP PREEMPT Wed Jun 22 22:42:44 CST 2022 aarch64 Android
Device manufacturer:
HUAWEI
Device model:
LIO-AN00

**Comment by twaik** [comment]
Duplicate #146

**Comment by twaik** [comment]
Can you please check it again with the latest artifact?
