### ISSUE TITLE
Hi , how to enable opengl inside a proot container?

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#153]
root@localhost ~# kwin
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 177, resource id: 12583053, major code: 20 (GetProperty), minor code: 0
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 178, resource id: 12583053, major code: 20 (GetProperty), minor code: 0
kwin_xkbcommon: XKB: inet:334:58: unrecognized keysym "XF86EmojiPicker"
kwin_platform_x11_standalone: Compositing disabled: no OpenGL support
kwin_core: Compositing is not possible

**Comment by twaik** [comment]
There is no way to use real GL/GLES inside proot container.

**Comment by kde-yyds** [comment]
I know, but why llvmpipe is not enabled while using termux-x11?

**Comment by twaik** [comment]
`termux-x11` is only a backend for Xwayland. It does not manage acceleration. If you want to enable llvmpipe inside proot container you can ask your distribution's maintainers.

**Comment by endokai** [comment]
In sparkle, OpenGL (llvmpipe) is available by default, but in termux x11 I don't know how to use it
