### ISSUE TITLE
Termux-x11 over WiFi 

### ISSUE THREAD

**Issue by aman-boop** [termux/termux-x11#154]
I started termux-x11 on TV, then I typed "export DISPLAY=192.168.43.1:0 startxfce4" in termux on mobile.
Both are connected with wifi.
But xfce4 says: "couldn't connect to display 192.168.43.1:0
How can I connect termux-x11 over wifi?

**Comment by twaik** [comment]
`termux-x11` itself is not standalone X server, it is backend for Xwayland launcher by `termux-x11` command in termux shell.
