### ISSUE TITLE
Termux-x11

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-x11#156]
Скажите возможно ли убрать верхнюю белую полосу чтобы был полный экран? И можно ли изменить разрешение экрана!
![Screenshot_2022-08-28-08-29-48-284_com termux x11](https://user-images.githubusercontent.com/97088046/187059261-3edc1c40-7968-4025-8862-c84f2d44d2de.jpg)
![Screenshot_2022-08-28-08-30-12-322_com termux x11](https://user-images.githubusercontent.com/97088046/187059270-9b1d79aa-6cdd-4491-9dcd-115591a94411.jpg)

**Comment by twaik** [comment]
В будущих версиях ввероятно можно будет делать и то, и другое. Но пока что такой возможности нет.

**Comment by Dendi777** [comment]
Ожидаемой версии? Когда планируют выпустить?

**Comment by twaik** [comment]
Все версии пока что альфы, релизов как таковых нет. Проект развивается в свободное время, поэтому точных сроков назвать не смогу. Но это уже в TODO.

**Comment by twaik** [comment]
Белая полоса это случаем не строка уведомлений?

**Comment by RalfWerner** [comment]
Ohh! ein internationales _issue_ Die allererste X11-Version konnte _fullscreen_ in den letzen ist nur noch ie Preferenz auswahl enthalten. Ich habe einige X11-Versionen in #54 gesichert. Kann Google gut russisch?

Ох! международная _выпуск_ Самая первая версия X11 могла содержать _fullscreen_ в последних только выбор предпочтения. Я сохранил несколько версий X11 в #54. Google хорошо говорит по-русски?

**Comment by Dendi777** [comment]
Отлично

**Comment by Dendi777** [comment]
Вопрос первая базовая версия x11 работает без ошибок?

**Comment by RalfWerner** [comment]
Ich benutze diese auf einem Huawei mit kleinem Screen. Dort arbeitet sie stabil. Besonders wenn ich die ExtraKeys (auch in Preferences) ausschalte.

**Comment by Dendi777** [comment]
Производительность в первой версии хорошая не тормозит?

**Comment by RalfWerner** [comment]
Ich kann keinen Unterschied feststellen. Mit `proot` wird es langsamer. Das hat aber nichts mit X11 zu tun und der Start ist schneller und einfacher - wie ich in #54 beschrieben habe.

**Comment by Dendi777** [comment]
Оибка установки есть предположение что деб файлы конфликтуют со старой версией

**Comment by RalfWerner** [comment]
Der start war früher viel einfacher. Du brauchtest den `termux-x11.deb` nicht - nur das paket `xwayland`. Auf ein OTS-Script habe ich referiert in der Beschreibung.

**Comment by twaik** [comment]
Looks like I can close this...
