### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-x11#160]
Итак возник такой вопрос у меня установлен Kali Hethunter (в термукс) возможно ли как-то запустить его через x11 проблема также исходит из того что при запуске kali я не могу поделиться с ним временным каталогом термукс! Итак если способ запустить Kali через termux-x11?

**Comment by twaik** [comment]
Duplicate https://github.com/termux/termux-x11/issues/138 .

**Comment by Dendi777** [comment]
Здесь запуск осуществляется через команду nh или nethanter

**Comment by Dendi777** [comment]
Здесь не proot-distro поэтому я не могу делится каталогом от termux

**Comment by twaik** [comment]
I do not think I can help if nethunter uses it's own tools. If nethunter has access to app_process you can try to start termux-x11 the way described in readme.md.
