### ISSUE TITLE
Xwayland package does not support extension GLX

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#163]
Xwayland package does not support extension GLX

Xwayland in termux
![Screenshot_20221002_225105_com termux](https://user-images.githubusercontent.com/106876912/193460822-2d1fc3f7-798b-4c1b-99a6-37bb56ccfe46.jpg)

Xwayland in debian

![Screenshot_20221002_225122_com termux](https://user-images.githubusercontent.com/106876912/193460828-aad25c15-2713-42e1-bff1-5a1aa7ff2c41.jpg)

**Comment by twaik** [comment]
Android does not support GLES only which is inaccessible from X11.
