### ISSUE TITLE
Add support for compiling a package in pacman format

### ISSUE THREAD

**Issue by Maxython** [termux/termux-x11#167]
For pacman users, this development will not be available, which is why they have to use apt, which is extremely risky.  

I would like to know what needs to be done and does it require separate support?

**Comment by twaik** [comment]
I am not sure I am able to support both apt and pacman... I think it will be better to write instruction/script unpacking `.deb` and inner `.tar` archive to termux's prefix...

**Comment by twaik** [comment]
Can you please check latest build? I have apt so can not try it.

**Comment by Maxython** [comment]
The package was not compiled correctly.
![Screenshot_20230306-193312_Termux](https://user-images.githubusercontent.com/60917834/223173497-2e6681b4-b473-4937-b5a9-74dc2ad76ad2.jpg)
The reason for this is that the version is not specified in the `.PKGINFO` file using the `pkgver` value.

**Comment by twaik** [comment]
I thought I checked it twice before commiting... New build is ready.

**Comment by Maxython** [comment]
Architecture error. You specified it as `all`, but for pacman, support for all architectures is `any`.

One question: when updating the package, will you remove the `TERMUX_PKG_REVISION` value or specify 0 in it? Just, it's desirable to always have the value `TERMUX_PKG_REVISION` in the version of the package for pacman.

**Comment by twaik** [comment]
This package will not be distributed through `termux-packages` repos so I am not sure. It is considered to be distributed only through artifacts. But I am considering to make build receipt for `termux-packages` after merging this to master. There is some work to be done.

**Comment by twaik** [comment]
Can you please check latest build?

**Comment by Maxython** [comment]
Did you literally understand that you need a `data` folder (like a pacman system)? If so, then there I meant `data` the folder that is the source of the package (i.e. `data/data/com.termux/files/*`)

**Comment by twaik** [comment]
I am not sure about what exactly you are talking. Package itself should only install 2 files, which are `/data/data/com.termux/files/usr/bin/termux-x11` and `/data/data/com.termux/files/usr/libexec/termux-x11/loader.apk`. And they are present in tar package along with `.BUILDINFO`, `.MTREE`, `.PKGINFO`.

**Comment by twaik** [comment]
Other user reported the package works. Can you please confirm it?

**Comment by Maxython** [comment]
> I am not sure about what exactly you are talking

In short, you need to put `data` from prefix, and not create another `data` folder and put prefix in it. Because of this, pacman tries to install files at the coordinate `/data/data/data/com.termux/*`.

**Comment by twaik** [comment]
You are right. For some reason it has three data folder in depth. It is reusing older code of apt package generator and this folder already was there. How did I miss that...

**Comment by twaik** [comment]
Newer build should fix that.

**Comment by Maxython** [comment]
eeeemmm, why is there a dependency `xorg-xwayland` here, although there should be `xwayland`?

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/issues/264

**Comment by Maxython** [comment]
It looks like you have set up a dependency for arch linux. But we need to configure this package for termux.

**Comment by twaik** [comment]
Done.

**Comment by Maxython** [comment]
Great, now the package is fully configured.
![Screenshot_20230308-184843_Termux](https://user-images.githubusercontent.com/60917834/223761457-ef82a9da-d4d8-4440-ab79-05ad0aad4235.jpg)
