### ISSUE TITLE
Added full screen function

### ISSUE THREAD

**Issue by WindowHZT** [termux/termux-x11#171]
The author is great, can you optimize the overall screen, see Android status bar is very uncomfortable
![-7d863791f2859c65](https://user-images.githubusercontent.com/78307930/200600513-06d5fecf-5f5f-4dfc-8217-d136c2b26942.jpg)

**Comment by Dr4kzor** [comment]
https://github.com/termux/termux-x11/pull/185

Here I found out how to do it, you just need to compile the app and change 1 file.
Note: I compiled from Android Studio just needed to remove 1 line of text from gradle.properties (Android Studio will say it is not suported)

**Comment by twaik** [comment]
Duplicate #29
