### ISSUE TITLE
Unable to install in termux

### ISSUE THREAD

**Issue by thushara5884** [termux/termux-x11#181]
I ran pkg install x11-repo
And then pkg install termux-x11

Which results in unable to locate package termux-x11

Any idea why this happens?

**Comment by twaik** [comment]
Package was removed from termux's repositories to avoid version incompatibility.

**Comment by povarog04** [comment]
ПРОСТО ЗАГРУЗИЛ С FDROID ПРИЛОЖЕНИЯ И ОТКРЫЛ TERMUX ПРИ УСТАНОВКЕ ТОЖЕ ЗАВИСЛА PKG X11
