### ISSUE TITLE
no silent notification on Android 13

### ISSUE THREAD

**Issue by kulturguda** [termux/termux-x11#186]
On Android 12 after starting Termux:X11 a silent notification message did appear, where the settings could be modified. Now I have Android (OxygenOS) 13, this notification does not appear therefore I cannot disable the additional keyboard and modify the mouse emulation.

**Comment by agnostic-apollo** [comment]
Possibly related to Android 13 limitations. You may have disallowed notification permission for the app. Check in Android Settings -> Apps.

https://developer.android.com/develop/ui/views/notifications/notification-permission

**Comment by kulturguda** [comment]
Success! After a hard reset of Termux:X11 the notifications must be enabled BEFORE restarting the app.

**Comment by kulturguda** [comment]
Success! After a hard reset of Termux:X11 the notifications must be enabled BEFORE restarting the app.
