### ISSUE TITLE
Is setxkbmap supported?

### ISSUE THREAD

**Issue by Zeioth** [termux/termux-x11#187]
There are no docs to change keyboard layout and language on termux under X11.

**Comment by twaik** [comment]
If a question is about changing keyboard layout in DE you can do that.
If a question is about using different language layout of Android keyboard it is problematic.

**Comment by selurvedu** [comment]
>  If a question is about using different language layout of Android keyboard it is problematic.
@twaik could you elaborate?

**Comment by twaik** [comment]
I am already working on complex solution. Connecting to existing session + custom language layouts + sending unicode symbols + multiple resolutions (RANDR extension, just like on desktop) + clipboard support + support for chroot/proot and superuser start. But it will take some time.

**Comment by selurvedu** [comment]
I see, thanks for your speedy reply.

**Comment by twaik** [comment]
No problem.
