### ISSUE TITLE
How to disable extra buttons bar at the bottom of the screen?

### ISSUE THREAD

**Issue by aspyct** [termux/termux-x11#188]
Hey, hi,

Let me just start by saying how mind blowing this is! Just, a full linux desktop from my android phone? I didn't expect that! Well done, seriously! It's amazing!

One little quirk, or maybe it's just me being a little simple today, but I could not find how to remove the "extra keys bar" that appears at the bottom of the screen, with Escape, Tab, Ctrl, Alt and arrow keys. It obscures part of the desktop (with xfce at least), and is unnecessary when a physical keyboard is connected.

I tried the same "Volume-up and Q" as for Termux, but it didn't seem to work on my Samsung S21 with Dex running.

But then again... mind blown! Cheers :)

**Comment by rudolphpienaar** [comment]
I've been wanting a solution to this myself for a long time! That and the top window decorator in DeX.

**Comment by kulturguda** [comment]
app notification on status bar -> preferences -> uncheck 'show additional keyboard'

**Comment by rudolphpienaar** [comment]
errr... I feel like I should know where to set this, but I'm failing. Where is this setting?

**Comment by kulturguda** [comment]
> errr... I feel like I should know where to set this, but I'm failing. Where is this setting?

![Screenshot_2023-01-03-22-35-24-73_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/71085362/210445240-34c36448-b806-4a0b-8109-2a65a33e08c3.jpg)

**Comment by kulturguda** [comment]
> errr... I feel like I should know where to set this, but I'm failing. Where is this setting?

![Screenshot_2023-01-03-22-35-24-73_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/71085362/210445347-4653968d-bae1-40da-a788-6ef1cd80b376.jpg)
If you don't see this notification, reinstall the app but do NOT run it yet. First enable its notifications in Android then start it.

**Comment by rudolphpienaar** [comment]
Woohoo! Many thanks! Now if only I can get rid of the DeX "window bar" I'll be a very happy camper!

**Comment by kulturguda** [comment]
> Woohoo! Many thanks! Now if only I can get rid of the DeX "window bar" I'll be a very happy camper!

You're welcome. That won't work unless a fullscreen version of app would be developed.

**Comment by kulturguda** [comment]
> Woohoo! Many thanks! Now if only I can get rid of the DeX "window bar" I'll be a very happy camper!

You're welcome. That won't work unless a fullscreen version of app would be developed.

**Comment by kulturguda** [comment]
fullscreen mode [here](https://github.com/termux/termux-x11/issues/54)

**Comment by kulturguda** [comment]
fullscreen mode [here](https://github.com/termux/termux-x11/issues/54) (1.0)
