### ISSUE TITLE
Starter Bad Fd and registered 0 native functions

### ISSUE THREAD

**Issue by berocl33** [termux/termux-x11#189]
>  12-26 12:19:09.599 13913 13926 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)            
12-26 12:19:09.599 13913 13926 E JavaBinder: java.lang.RuntimeException: Bad file descriptor
12-26 12:19:09.599 13913 13926 E JavaBinder:  at android.os.Parcel.nativeWriteFileDescriptor(Native Method)
12-26 12:19:09.599 13913 13926 E JavaBinder:  at android.os.Parcel.writeFileDescriptor(Parcel.java:809)                                      12-26 12:19:09.599 13913 13926 E JavaBinder:  at android.os.ParcelFileDescriptor.writeToParcel(ParcelFileDescriptor.java:1061)
12-26 12:19:09.599 13913 13926 E JavaBinder:  at com.termux.x11.common.ITermuxX11Internal$Stub.onTransact(ITermuxX11Internal.java:87)
12-26 12:19:09.599 13913 13926 E JavaBinder:  at com.termux.x11.starter.Starter$Service.onTransact(Starter.java:191)
12-26 12:19:09.599 13913 13926 E JavaBinder:  at android.os.Binder.execTransactInternal(Binder.java:1021)
12-26 12:19:09.599 13913 13926 E JavaBinder:  at android.os.Binder.execTransact(Binder.java:994)
12-26 12:19:10.121 31354 31377 D Surface : Surface::disconnect(this=0x9e69b800,api=1)
12-26 12:19:10.144 31354 31354 D Termux:TermuxActivity: onStop
12-26 12:19:10.150 31354 31354 D SoundPool: native_release called
12-26 12:19:10.155 31354 31354 D SoundPool: native_release end
12-26 12:19:10.164 31354 31354 V PhoneWindow: DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@bc0d7af, this = DecorView@138a290[TermuxActivity]                                                                 Failed to connect to Termux:X11. Something went wrong

**Comment by twaik** [comment]
What device you are using?

**Comment by berocl33** [comment]
motorola-android11 & tinno-android9, KeepAliveService never gets started(no shell account to see system logs)...

**Comment by berocl33** [comment]
should reiter xwayland seems to die immediatly after starting...orphaned subprocess being killed on writing to closed stdout/stderr I believe spawning in shell yielded no results although....I am trying to backport to older androidOS for comparison.

**Comment by twaik** [comment]
Can you please provide some logs please? I am not sure I got you right.

**Comment by twaik** [comment]
I am not sure why it happens. I need the full log if you can reproduce this. And I need some additional data about how did you used this and when it crashes.

**Comment by twaik** [comment]
@berocl33 Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by twaik** [comment]
Fixed in latest builds.
