### ISSUE TITLE
Backspace key on real keyboard don't work as expected

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#197]
Maybe someone has an idea what to do, but I suspect it's a Termux X11 error. Well, pressing Backspace acts as if the user is holding it down. This means that it will delete, for example, all content until someone presses another button.

I have only observed this behaviour in Termux X11, so it is not a problem directly with Termux or the keyboard.

**Comment by twaik** [comment]
Can you reproduce it on the latest build from [here](https://github.com/twaik/termux-x11/actions)?

**Comment by IntinteDAO** [comment]
> Can you reproduce it on the latest build from [here](https://github.com/twaik/termux-x11/actions)?

Fixed, closing
