### ISSUE TITLE
Proposition: Rename termux-x11 to termux-display or something more relevant?

### ISSUE THREAD

**Issue by nathaneltitane** [termux/termux-x11#198]
Is X11 still a thing within this project/repository?
If Wayland is the new default, and even with X11 being a fallback, maybe this part of the project could benefit from a more comprehensive name that is agnostic to the method?

termux-display, termux-vdo (virtual display out, wordplay on 'video')...

you get the idea :)

**Comment by twaik** [comment]
`termux-x11` is a backend for `Xwayland`. And it is used only with X clients. `termux-x11` is the most relevant name.

**Comment by anscarlett** [comment]
I'd say termux-xwayland would be the most relevant name

**Comment by twaik** [comment]
Xwayland support is dropped.
