### ISSUE TITLE
conflicting name with termux app, cant install together with termux on redmi-4x

### ISSUE THREAD

**Issue by wong-fi-hung** [termux/termux-x11#200]
i'am trying to install termux-x11 on redmi 4x with installed termux app, but cannot to install.
then, if only wayland or only termux,  the installation process work fine.
and again, i'am trying to install the wayland first, then install termux, the result is same.
Package Manager Log:  unable to install, app with some name has already installed.

**Comment by twaik** [comment]
There is no conflict, likely you are doing something wrong. Use the latest artifact

**Comment by wong-fi-hung** [comment]
> There is no conflict, likely you are doing something wrong. Use the latest artifact

okay, i will try again...

**Comment by twaik** [comment]
Post screenshots and adb log.

**Comment by wong-fi-hung** [comment]
I'am very sorry...
I has wrong send issue to this repo..
I'am now remember, the package with conflicting names is Termux:GUI
![termux-gui-err](https://user-images.githubusercontent.com/68433096/215413175-8a3262a2-0915-4935-97f1-aca3907f7208.png)

**Comment by wong-fi-hung** [comment]
now i'am wil close the issue..
