### ISSUE TITLE
Remove notification bar or hide in settings and alpine bug

### ISSUE THREAD

**Issue by mesflit** [termux/termux-x11#203]
remove notification bar 
I installed alpine xfce i started wayland and crash 
and on back button pressed sometimes keyboard not working

**Comment by polkaulfield** [comment]
Fixed these bugs here: https://github.com/polkaulfield/termux-x11/releases
I sent a pull request already. Test it and tell me if it works

**Comment by twaik** [comment]
Fixed by 9de5f2f0deca3f057d429843d8e3e04d88bdfa98
