### ISSUE TITLE
[Feature request] Using termux-wayland without need to compile it with Termux key.

### ISSUE THREAD

**Issue by twaik** [termux/termux-x11#21]
Hi guys! I have no time to help to the project but I have an idea how to use termux wayland without signing it with the key Termux::App is signed. 
The idea is to use the same connection mech Termux::API uses. Look:
1. Small program in Termux fs creates creates connection to Java service the same way Termux API package does (look here: https://github.com/termux/termux-api-package/blob/master/termux-api.c)
2. The same program creates Xserver well known sockets and sends fds to Java service. 
3. Java service sends these fds to xserver and xserver can make SetNotifyFd to these sockets (look here: https://github.com/freedesktop/xorg-xserver/blob/18d3131f9a332096825c09106a931c427246ddb7/os/connection.c#L282 )
It will let us use Unix sockets even if application has another keys. And it is compliant with SELinux security restrictions. Also in the future it will let us use android-emugl modified for Termux  to let us use fast GLES (it can be modified to use Unix socket). What do you think?

**Comment by twaik** [comment]
Sorry, my fault. I forgot that T::X11 uses Xorg on Termux fs side. We can try to provide wayland socket connection through the Java service.

**Comment by twaik** [comment]
After receiving socket fd in Java service you can push it to wayland server using wl_display_add_socket_fd function on JNI side.

**Comment by twaik** [comment]
Ok. I was not right. It is impossible to send Unix socket fd the same way Termux::API does. But we can try to send [ACTION_VIEW](https://github.com/termux/termux-packages/issues/7437#issuecomment-909527512) broadcast with URI to temporary Unix socket. T::X11 will be able to open it and there we will be able to send fd to our socket. 
T::X11 needs something like [TermuxFileReceiverActivity](https://github.com/termux/termux-app/blob/e7d06aebb59948730f32a2a251eb61f6a36281ad/app/src/main/java/com/termux/filepicker/TermuxFileReceiverActivity.java) but with reaction only on specific mime type (like "termux/x11"). This way it will receive READ permission on our temporary Unix socket.
That is the simplest way to make it work with Termux without resigning it and without making any change to Termux::App.
I'll try to make a demo this weekend.

**Comment by suhan-paradkar** [comment]
Maybe we can make use of this [gist](https://gist.github.com/RajithaKumara/2700e362ff231da265aee25f7aa0a57a)?

**Comment by twaik** [comment]
The problem is SELinux and Android's restrictions. We can not connect to Unix or abstract sockets directly, we will have access denied error. But we can tell Android that there is Uri in private storage that we want to share with other app (send ACTION_VIEW broadcast with mime) and resolve this Uri in another app with ContentResolver. From here we can get it's AssetFileDescriptor, then ParcelFileDescriptor and finally regular file descriptor that can be passed to C. This file descriptor can be used as a transport for initial setup of socket's.

**Comment by Reyhank45** [comment]
How do i use Termux Wayland???

**Comment by twaik** [comment]
You can not.
