### ISSUE TITLE
Latest version More Bugs!

### ISSUE THREAD

**Issue by mesflit** [termux/termux-x11#210]
I installed Termux armv7 version for box86 and wine i starting wayland xfce4 Command:export DISPLAY=:0 crashing or closing 
Log:OpenGl doesnt support

**Comment by twaik** [comment]
termux-x11 never supported Opengl. Post logs please.

**Comment by twaik** [comment]
> starting wayland xfce4

`termux-x11` is not a wayland compositor. It is only a backend for `Xwayland`. Strating wayland sessions is not supported in any form.

**Comment by twaik** [comment]
Any updates?

**Comment by mesflit** [comment]
> 

But I downloaded the old version and it worked

**Comment by mesflit** [comment]
> termux-x11 never supported Opengl. Post logs please.
Is OpenGL support coming soon?

**Comment by twaik** [comment]
> But I downloaded the old version and it worked

Maybe you had `swrast` or `llvmpipe` enabled `mesa` library. Anyway it could not work because real GL/GLES/any other type of hardware acceleration in proot/chroot is impossible without rebuilding the whole Android image...

Do you want to report other bugs?

**Comment by mesflit** [comment]
> > But I downloaded the old version and it worked
> 
> Maybe you had `swrast` or `llvmpipe` enabled `mesa` library. Anyway it could not work because real GL/GLES/any other type of hardware acceleration in proot/chroot is impossible without rebuilding the whole Android image...
> 
> > Is OpenGL support coming soon?
> 
> I do not think so...
> 
> Do you want to report other bugs?

no. I couldn't find any other errors.

**Comment by twaik** [comment]
> no. I couldn't find any other errors.

Ok, I am closing the issue...
