### ISSUE TITLE
Expand to Display cutout area (notch)

### ISSUE THREAD

**Issue by GlennX7** [termux/termux-x11#212]
![IMG_20230202_231816](https://user-images.githubusercontent.com/88073458/216403382-106f8d4f-b20a-46fe-85d0-192d6f9e0f8b.jpg)
It would be great if termux-x11 worked in full screen mode sorry I'm not very good at explaining anything😅

**Comment by twaik** [comment]
Check if you have fullscreen checkbox in preferences.

**Comment by GlennX7** [comment]
> Check if you have fullscreen checkbox in preferences. 

Thank you very much
I have been waiting for fullscreen mode since its release  Finally it is available.
But I found something interesting I don't know if it's a bug/glitch or something normal.
screen record
https://user-images.githubusercontent.com/88073458/216535190-d5d9d9c0-c7a4-4f5e-87c4-9f4e99c40557.mp4


Only happens if "display over other apps" is not allowed for termux

**Comment by twaik** [comment]
Yeah, I am aware of this bug. I found it right after pushing last commit. Thank you.

**Comment by GlennX7** [comment]
I've reopened this issue (⊙ _ ⊙ )

@twaik Have you noticed the notch area and mouse issues?
![Screenshot_2023-02-03-21-44-09-20_00df01c412509efb9bd6450c382822af.jpg](https://user-images.githubusercontent.com/88073458/216752915-63ee2d12-cdad-4e7e-b23a-c02d979c4e49.jpg)

**Comment by twaik** [comment]
I know. I did not see cursor on my devices at all (read commit description).

**Comment by twaik** [comment]
Can you please check if it is relevant for latest build?

**Comment by GlennX7** [comment]
> Can you please check if it is relevant for latest build?

Notch is ok! Mouse is ok!
Just exit from notification isn't working which isn't problem for me

![Screenshot_2023-02-05-12-00-35-93_00df01c412509efb9bd6450c382822af.jpg](https://user-images.githubusercontent.com/88073458/216805314-29d4a01e-3a72-4fe4-b300-f30e3955a951.jpg)

**Comment by twaik** [comment]
> Just exit from notification isn't working which isn't problem for me

It should became to normal, I thought I fixed it in last build...

**Comment by GlennX7** [comment]
> > Just exit from notification isn't working which isn't problem for me
> 
> It should become to normal, I thought I fixed it in last build...

Ok my fault I reinstalled termux-x11 and it's normal now :)
