### ISSUE TITLE
“not connected”

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#216]
Sometimes it displays “not connected” when it is actually connected
<details>
<summary>Screenshot</summary>

![Screenshot_20230204_175159_com termux x11](https://user-images.githubusercontent.com/106876912/216760808-b912f538-e20b-4020-80e7-538f4502c438.jpg)
</details>

**Comment by twaik** [comment]
Can you please check if it is relevant for latest build?

**Comment by kde-yyds** [comment]
Cannot reproduce.
