### ISSUE TITLE
Cursor became too big unnormal with black rectangle background in the newest apk

### ISSUE THREAD

**Issue by wuuconix** [termux/termux-x11#217]
Snapshoot in xfce4:
![014FD7E4693102EA77FF1A876EEB3CCA](https://user-images.githubusercontent.com/80732538/216761885-ff5f3f06-692d-4db1-af39-6db20fb0fbb0.jpg)
Snapshoot in kde:
![FF02A8AEAF545EDF726AC359769D0F11](https://user-images.githubusercontent.com/80732538/216761906-a53f5c6b-6e76-42c5-8082-88bc54217f68.jpg)

Issue occur in the apk https://github.com/termux/termux-x11/actions/runs/4084923811
Related commit https://github.com/termux/termux-x11/commit/3794838b76a008b8f6474b646feba3bac79c64f1
This issue not occur in the older apk https://github.com/termux/termux-x11/actions/runs/4074584338

**Comment by twaik** [comment]
Yeah, I am aware of the problem. On my devices cursor did not appear at all and that was a way to make it visible on my hidpi display. It will be fixed later...

**Comment by twaik** [comment]
Are you running kde and xfce in proot?

**Comment by wuuconix** [comment]
Yes, I run them in the proot distro

**Comment by twaik** [comment]
Can you please tell me how exactly you installed this environment and how you start it? Lot of users use `termux-x11` only in proot and I do not have it.

**Comment by wuuconix** [comment]
I first install a debian using [`proot-distro`](https://github.com/termux/proot-distro)
and login it with flag `--shared-tmp`
```
proot-distro login debian --shared-tmp
```
And in the debian, I install the `xfce4` and `dbus-x11`.

---

In one termux session,  I start the termu-x11 like this:
```
termux-x11 :1 -dpi 200
```
And in another session, I login to the debian. Start the xfce4
```
env DISPLAY=:1 xfce4-session
```
Then I got the desktop graphic in the termux-x11 app.

**Comment by twaik** [comment]
Thank you

**Comment by twaik** [comment]
Can you please check if it is relevant for latest build?

**Comment by wuuconix** [comment]
the cursor becomes normal in the latest build.
thanks for your job!
![Screenshot_2023-02-05-11-17-00-790_com termux x11](https://user-images.githubusercontent.com/80732538/216799666-7d7f055c-cca4-4052-9753-d1083d5b7774.jpg)
