### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-x11#219]
https://user-images.githubusercontent.com/97088046/217887714-3bfe27e9-4a08-4ef6-b104-e25603041f42.mp4

so there were errors again:
1) the cursor is clearly broken is in one place and the click happens a little nearby.
2) I am very glad that the fullscreen mode was added, but now the screen size has become different and blurry, you need to add the ability to select the screen resolution, this is very important!,
3) I also saw a minor bug when moving windows, stripes are visible along the edges, and I also saw a slight decrease in the speed of movement of windows!

**Comment by twaik** [comment]
> I am very glad that the fullscreen mode was added, but now the screen size has become different and blurry, you need to add the ability to select the screen resolution, this is very important!

It is weird, because it should use exact size of visible surface...

>> I also saw a minor bug when moving windows, stripes are visible along the edges, and I also saw a slight decrease in the speed of movement of windows!

That is also weird. Can you please post a video?

**Comment by Dendi777** [comment]
I attached the video above, sorry for the quality, I had to compress the video due to github restrictions, you may notice that when moving the window along its edges, you can see something bug-like, something similar to rendering, but there was no such thing in old builds, and you can also see a problem with the cursor, by the way, I found another bug when opening the desktop cursor it gets big for a few seconds, and yes, after all, we would be very grateful to you if you added the ability to choose the screen resolution yourself!

**Comment by Dendi777** [comment]
And the launch of the environment has become more problematic, starting the environment is now hard to work with only a few attempts!

**Comment by twaik** [comment]
Yeah, that's definitely because of new hang protecting system. It drops problematic socket to avoid #211.
