### ISSUE TITLE
Virtual keyboard disabled in horizontale video mode

### ISSUE THREAD

**Issue by newicody** [termux/termux-x11#220]
Hello,

I am using termux-x11 on a arm phone with I use Lineage Os (Android 11) . I installed Termux-x11, all work perfectly, just I have problem when I rotate the screen : the virtual keyboard is printed but It doesn't works when typing.

Termux-X11 1.02.06
Proot-Distro 3.5.0
Distribution Alpine

**Comment by newicody** [comment]
https://user-images.githubusercontent.com/58338908/217496999-52d7808f-7530-4da8-969f-a2183d9ba67c.mp4

**Comment by twaik** [comment]
Do you use latest build?

**Comment by twaik** [comment]
Can you please put `termux-info` log?

**Comment by newicody** [comment]
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18889
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
Updatable packages:
apt/stable 2.5.6 arm [upgradable from: 2.5.0]
bash/stable 5.2.15 arm [upgradable from: 5.1.16-1]
binutils/stable 2.40 arm [upgradable from: 2.38]
bison/stable 3.8.2-3 arm [upgradable from: 3.8.2-2]
ca-certificates/stable 1:2023.01.10 all [upgradable from: 1:2022.04.26]
clang/stable 15.0.7 arm [upgradable from: 14.0.4]
cmake/stable 3.25.2 arm [upgradable from: 3.23.2]
command-not-found/stable 2.1.0-9 arm [upgradable from: 1.75]
coreutils/stable 9.1-2 arm [upgradable from: 9.1]
cups/stable 2.4.2 arm [upgradable from: 2.3.3-9]
curl/stable 7.87.0 arm [upgradable from: 7.83.1]
dash/stable 0.5.12 arm [upgradable from: 0.5.11.5-1]
dialog/stable 1.3-20221229-0 arm [upgradable from: 1.3-20220117-0]
diffutils/stable 3.9 arm [upgradable from: 3.8]
dos2unix/stable 7.4.3 arm [upgradable from: 7.4.2]
dpkg/stable 1.21.20 arm [upgradable from: 1.21.8]
ed/stable 1.19 arm [upgradable from: 1.18]
file/stable 5.44 arm [upgradable from: 5.41-1]
findutils/stable 4.9.0-2 arm [upgradable from: 4.9.0-1]
fontconfig-utils/stable 2.14.2 arm [upgradable from: 2.14.1-1]
fontconfig/stable 2.14.2 arm [upgradable from: 2.14.1-1]
gawk/stable 5.2.1 arm [upgradable from: 5.1.1-1]
gdbm/stable 1.23 arm [upgradable from: 1.22]
git/stable 2.39.1 arm [upgradable from: 2.36.1]
glib/stable 2.74.5 arm [upgradable from: 2.72.1-1]
gnupg/stable 2.4.0-2 arm [upgradable from: 2.3.6]
gperf/stable 3.1-6 arm [upgradable from: 3.1-5]
gpgv/stable 2.4.0-2 arm [upgradable from: 2.3.6]
grep/stable 3.8-1 arm [upgradable from: 3.7-2]
groff/stable 1.22.4-4 arm [upgradable from: 1.22.4-3]
gzip/stable 1.12-1 arm [upgradable from: 1.12]
imlib2/stable 1.10.0-2 arm [upgradable from: 1.10.0-1]
inetutils/stable 2.4 arm [upgradable from: 1.9.4-13]
jsoncpp/stable 1.9.5-1 arm [upgradable from: 1.9.5]
less/stable 608 arm [upgradable from: 590]
libandroid-execinfo/stable 0.1-1 arm [upgradable from: 0.1]
libandroid-support/stable 28-3 arm [upgradable from: 28-2]
libaom/stable 3.6.0 arm [upgradable from: 3.5.0]
libarchive/stable 3.6.2-1 arm [upgradable from: 3.6.1]
libc++/stable 25c arm [upgradable from: 23b-3]
libcairo/stable 1.17.8 arm [upgradable from: 1.17.6]
libcompiler-rt/stable 15.0.7 arm [upgradable from: 14.0.4]
libcurl/stable 7.87.0 arm [upgradable from: 7.83.1]
libde265/stable 1.0.11 arm [upgradable from: 1.0.9]
libdrm/stable 2.4.114-1 arm [upgradable from: 2.4.114]
libepoxy/x11 1.5.10-1 arm [upgradable from: 1.5.10]
libevent/stable 2.1.12-2 arm [upgradable from: 2.1.12-1]
libexpat/stable 2.5.0 arm [upgradable from: 2.4.8]
libffi/stable 3.4.4 arm [upgradable from: 3.4.2]
libgcrypt/stable 1.10.1-1 arm [upgradable from: 1.10.1]
libgmp/stable 6.2.1-2 arm [upgradable from: 6.2.1-1]
libgpg-error/stable 1.46 arm [upgradable from: 1.45]
libice/stable 1.1.1 arm [upgradable from: 1.0.10-15]
libiconv/stable 1.17 arm [upgradable from: 1.16-3]
libidn2/stable 2.3.4 arm [upgradable from: 2.3.2]
libisl/stable 0.25 arm [upgradable from: 0.24]
libjpeg-turbo/stable 2.1.5 arm [upgradable from: 2.1.4]
libjxl/stable 0.8.1 arm [upgradable from: 0.7.0-1]
libksba/stable 1.6.3 arm [upgradable from: 1.6.0]
libllvm/stable 15.0.7 arm [upgradable from: 14.0.4]
libltdl/stable 2.4.7 arm [upgradable from: 2.4.6-8]
liblz4/stable 1.9.4 arm [upgradable from: 1.9.3]
liblzma/stable 5.4.1 arm [upgradable from: 5.2.5-1]
libmpc/stable 1.3.1 arm [upgradable from: 1.2.1-1]
libmpfr/stable 4.2.0 arm [upgradable from: 4.1.0-1]
libnghttp2/stable 1.51.0 arm [upgradable from: 1.47.0]
libpng/stable 1.6.39 arm [upgradable from: 1.6.37-3]
librav1e/stable 0.6.3 arm [upgradable from: 0.6.2]
libsm/stable 1.2.4-1 arm [upgradable from: 1.2.3-17]
libsqlite/stable 3.40.1 arm [upgradable from: 3.38.5]
libtalloc/stable 2.4.0 arm [upgradable from: 2.3.4]
libtirpc/stable 1.3.3 arm [upgradable from: 1.3.2-1]
libtool/stable 2.4.7 arm [upgradable from: 2.4.6-8]
libuchardet/stable 0.0.8 arm [upgradable from: 0.0.7]
libunistring/stable 1.1 arm [upgradable from: 1.0]
libuv/stable 1.44.2 arm [upgradable from: 1.44.1]
libwayland/x11 1.21.0 arm [upgradable from: 1.17.0-10]
libwebp/stable 1.3.0 arm [upgradable from: 1.2.4-1]
libx11/stable 1.8.4 arm [upgradable from: 1.7.2-1]
libxau/stable 1.0.11 arm [upgradable from: 1.0.9-9]
libxcursor/stable 1.2.1-1 arm [upgradable from: 1.2.0-20]
libxdmcp/stable 1.1.4 arm [upgradable from: 1.1.3-10]
libxext/stable 1.3.5 arm [upgradable from: 1.3.4-11]
libxfixes/stable 6.0.0-1 arm [upgradable from: 5.0.3-25]
libxi/stable 1.8 arm [upgradable from: 1.7.10-23]
libxml2/stable 2.10.3 arm [upgradable from: 2.9.14]
libxpm/x11 3.5.15 arm [upgradable from: 3.5.14]
libxrandr/stable 1.5.3 arm [upgradable from: 1.5.2-24]
libxrender/stable 0.9.11 arm [upgradable from: 0.9.10-14]
libxshmfence/stable 1.3.2-1 arm [upgradable from: 1.3.2]
libxt/stable 1.2.1-2 arm [upgradable from: 1.2.1]
libxtst/stable 1.2.4 arm [upgradable from: 1.2.3-26]
libxxf86vm/stable 1.1.5-1 arm [upgradable from: 1.1.5]
lld/stable 15.0.7 arm [upgradable from: 14.0.4]
llvm/stable 15.0.7 arm [upgradable from: 14.0.4]
lsof/stable 4.98.0 arm [upgradable from: 4.95.0-1]
m4/stable 1.4.19-4 arm [upgradable from: 1.4.19-3]
make/stable 4.4-1 arm [upgradable from: 4.3-2]
mesa/stable 22.3.5 arm [upgradable from: 22.3.2]
nano/stable 7.2 arm [upgradable from: 6.3]
ndk-sysroot/stable 25c arm [upgradable from: 25b-3]
openjdk-17/stable 17.0-25 arm [upgradable from: 17.0-22]
openssh-sftp-server/stable 9.2p1 arm [upgradable from: 9.1p1]
openssh/stable 9.2p1 arm [upgradable from: 9.1p1]
openssl-1.1-static/stable 1:1.1.1t arm [upgradable from: 1.1.1o]
openssl-1.1/stable 1:1.1.1t arm [upgradable from: 1.1.1o]
openssl-static/stable 1:3.0.8 arm [upgradable from: 3.0.3]
openssl/stable 1:3.0.8 arm [upgradable from: 3.0.3]
pcre2/stable 10.42 arm [upgradable from: 10.40]
perl/stable 5.36.0-1 arm [upgradable from: 5.36.0]
pinentry/stable 1.2.1-1 arm [upgradable from: 1.2.0]
pkg-config/stable 0.29.2-2 arm [upgradable from: 0.29.2-1]
procps/stable 3.3.17-2 arm [upgradable from: 3.3.17-1]
proot/stable 5.1.107-55 arm [upgradable from: 5.1.107-54]
psmisc/stable 23.6-1 arm [upgradable from: 23.4]
python/stable 3.11.2-1 arm [upgradable from: 3.10.5]
readline/stable 8.2.1 arm [upgradable from: 8.1.1]
rhash/stable 1.4.3 arm [upgradable from: 1.4.2-2]
sed/stable 4.9 arm [upgradable from: 4.8-2]
tar/stable 1.34-1 arm [upgradable from: 1.34]
termux-am-socket/stable 1.5.0 arm [upgradable from: 1.4.0]
termux-keyring/stable 3.11 all [upgradable from: 3.6]
termux-licenses/stable 2.0-3 all [upgradable from: 2.0-2]
termux-tools/stable 1.36.1 all [upgradable from: 0.186]
tigervnc/x11 1.10.1-33 arm [upgradable from: 1.10.1-31]
uchardet/stable 0.0.8 arm [upgradable from: 0.0.7]
unbound/stable 1.17.1 arm [upgradable from: 1.15.0-1]
unzip/stable 6.0-9 arm [upgradable from: 6.0-7]
util-linux/stable 2.38.1-1 arm [upgradable from: 2.38]
wget/stable 1.21.3-5 arm [upgradable from: 1.21.3-2]
x11-repo/stable 8.4-1 all [upgradable from: 8.4]
xkeyboard-config/x11 2.38 all [upgradable from: 2.37]
xorg-util-macros/stable 1.19.3-1 all [upgradable from: 1.19.3]
xorgproto/stable 2022.2 all [upgradable from: 2020.1-1]
xz-utils/stable 5.4.1 arm [upgradable from: 5.2.5-1]
zlib/stable 1.2.13 arm [upgradable from: 1.2.12]
zstd/stable 1.5.2-2 arm [upgradable from: 1.5.2-1]
termux-tools version:
0.186
Android version:
11
Kernel build information:
Linux localhost 4.9.190-perf-g961732a #1 SMP PREEMPT Wed Jan 20 21:50:42 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 9A

**Comment by twaik** [comment]
Do you use latest build?

**Comment by newicody** [comment]
I plannifiate try :
upgrading from repository
upgrading from source

**Comment by newicody** [comment]
Bug is still present after upgrading from repo
<details>
<summary>termux-info</summary>

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=18889
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.36.1
Android version:
11
Kernel build information:
Linux localhost 4.9.190-perf-g961732a #1 SMP PREEMPT Wed Jan 20 21:50:42 CST 2021 armv8l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 9A
```
</details>

**Comment by twaik** [comment]
Do you use latest build of `termux-x11`? Not `termux-app`...

**Comment by newicody** [comment]
<details>
<summary>apt-cache show termux-x11</summary>

```
Package: termux-x11
Status: install ok installed
Maintainer: Twaik Yont @twaik
Architecture: all
Version: 1.02.06
Depends: xwayland
Description: Companion package for termux-x11 app
Description-md5: 9126119c016873ba4d0522ff4ec18634
Homepage: https://github.com/termux/termux-x11
```
</details>
I dont know what is the last build version.

**Comment by twaik** [comment]
![image](https://user-images.githubusercontent.com/9674930/217952332-80c42343-1773-4716-be6d-d42c19cc2e78.png)

**Comment by newicody** [comment]
I will try

**Comment by newicody** [comment]
installed and broken

**Comment by newicody** [comment]
Ok was just my python launcher was broken.
I started fluxbox but horizontal keyboard doesn't work ( I use the #256 Build )

**Comment by twaik** [comment]
@newicody Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by newicody** [comment]
checked, it's very perfect, thanks you!
