### ISSUE TITLE
Enable Android cursor

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#221]
In brief, the cursor in Termux-X11 is drawn by Termux. It may not be (e.g. in the case of slow hardware) smooth. Some solutions like XServer XSDL, AVNC etc. allow you to enable the physical Android cursor and hide the XServer cursor.

If I'm not mistaken the Android cursor will be rendered on the graphics card, so it is ultra-smooth.

By default, the Termux-X11 (Android) cursor is hidden, so it would be nice if there was an option to enable it (and possibly hide the Termux cursor).

**Comment by twaik** [comment]
>> It may not be (e.g. in the case of slow hardware) smooth

Do you mean cursor related to hardware mouse? I think it is possible, but a bit problematic because regular application has less control on pointer states...

**Comment by IntinteDAO** [comment]
> Do you mean cursor related to hardware mouse? I think it is possible, but a bit problematic because regular application has less control on pointer states...

That would be best. I generally use the mouse on the Termux X11 and it's possible to use it, but you can see that it's not ultra-smooth movement like the native cursor.

**Comment by twaik** [comment]
On my devices it is smooth. It is rendered almodt same way Android renders cursor. Can you please post video showing non-smoothness and post termux-info log?

**Comment by IntinteDAO** [comment]
> On my devices it is smooth.

Hmm, you have right. But what about delay between moving cursor on Android and on Termux X11? In TigerVNC + AVNC "remote" cursor is little slower than Android cursor

**Comment by twaik** [comment]
I am not sure what you are tasking about. Termux:X11 does not get coordinates from Xwayland. It simply moves cursor icon to the last known location of cursor sent to Xwayland. It does not get it from somewhere. Maybe this delay is under View's responsibility. I am not sure if I can override this behaviour.

**Comment by twaik** [comment]
It looks like I found the root of problem. Cursor coordinates are set from compositor's event loop and that is a reason why it has a delay. I will try to set the coordinates before sending them to Xwayland.

**Comment by twaik** [comment]
Check if it happens with latest build from [here](https://github.com/twaik/termux-x11/actions).

**Comment by RaWolFoX** [comment]
@twaik your fork is working fine on my device now. Only problem i found is when full screen option is enabled, screen reseeding not working.
(only your fork is working good. Termux version is still buggy.)

**Comment by twaik** [comment]
Termux version is also mine. The fork is needed because most parts of the code have been changed in one way or another.

**Comment by RaWolFoX** [comment]
> Termux version is also mine. The fork is needed because most parts of the code have been changed in one way or another.

I noticed that 😃👍🏻

**Comment by IntinteDAO** [comment]
> Check if it happens with latest build from [here](https://github.com/twaik/termux-x11/actions).

Well, I can't feel any lagg now, so it might be fixed. Closing?

**Comment by twaik** [comment]
Yeah, Why not. Can you please click close?

**Comment by twaik** [comment]
Ok, I'll do that.
