### ISSUE TITLE
Incorrect resizing latest build

### ISSUE THREAD

**Issue by 5A52** [termux/termux-x11#224]
Comare 2 screenshot, first is oldest build of termux-x11 with full screen option (v1.0 works wery well on DeX in a full screen or windowed, but alt-tab, alt-f4,etc, does not intercept. And does not share clipboard with android.)
![oldest_fool_screen_version1 0](https://user-images.githubusercontent.com/65124087/218389760-19029ef9-f192-417e-b60c-fe8fa6a55240.jpg)
The second one is latest build [8bb8be1](https://github.com/termux/termux-x11/commit/8bb8be1cb13fa4c3f361d725c2a84e724f047701) , full screen works fine (finaly?), intercepts buttons, but windowed is crappy, and no clipboard 
![last_build](https://user-images.githubusercontent.com/65124087/218389806-60f5d981-d7b8-48e2-9fb6-bb8a3935a493.jpg)

**Comment by twaik** [comment]
Thank you. I am already working on it.

**Comment by twaik** [comment]
It is in TODO list.
