### ISSUE TITLE
The mouse display position is offset from the actual position

### ISSUE THREAD

**Issue by Vasilyevski** [termux/termux-x11#226]
The position of the mouse icon displayed on the desktop is offset from the position where the mouse actually clicks, and the closer it is to the bottom of the screen, the more obvious it is

https://user-images.githubusercontent.com/120901575/218807891-e3e49e9c-1b65-4072-9682-54941998c365.mp4

https://user-images.githubusercontent.com/120901575/218807910-e46a64a3-bca9-435d-a3bc-671be71c43bf.mp4

**Comment by twaik** [comment]
Duplicate #218

**Comment by twaik** [comment]
Please, confirm if it happens on latest build or not. Thank you.

**Comment by Vasilyevski** [comment]
> 请确认它是否发生在最新版本上。谢谢。

It has been fixed
