### ISSUE TITLE
touch screen direct input

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#230]
I can only use direct mode when using a physical mouse in the latest build.
I cannot input as a touchscreen as before

**Comment by twaik** [comment]
It is likely because I forgot to change [this](https://github.com/termux/termux-x11/blob/master/app/src/main/res/values/arrays.xml). I will fix it soon.

**Comment by kde-yyds** [comment]
Why the direct mode option was removed
![Screenshot_20230302_221455_com termux x11](https://user-images.githubusercontent.com/106876912/222453221-af00bbe3-625e-4c2a-9c5e-dd4724ecb1f9.jpg)

**Comment by twaik** [comment]
Because it caused crashes.

**Comment by kde-yyds** [comment]
so when will it be added back?

**Comment by twaik** [comment]
I do not think it will happen soon.

**Comment by kde-yyds** [comment]
why not add the option back and warn that it may cause crash?

**Comment by twaik** [comment]
Because it should not cause crash at all.

**Comment by kde-yyds** [comment]
Please reopen it until it is added back. 
It is really convient to input directly on a touchscreen. 
Please add it back soon. Thanks.

**Comment by twaik** [comment]
It is unlikely to get back. I do not see ways to send touch events using `XTEST` extension. That is the only reliable way to send events to X server.

**Comment by RalfWerner** [comment]
My direct mode checks worked well on most devices with the old X11 version. There were craches from some. An analysis of the crashes is only possible if the mode is available again.

**Comment by RalfWerner** [comment]
If direct mode will **not restored**, the old X11 versions are the only chance to realize Multitouch in the Termux environment!

**Comment by twaik** [comment]
As I said before, Xwayland backend support is dropped. EOF. I will start libinput touch research soon.

**Comment by RalfWerner** [comment]
With `pkg up` you @twaik overwites `xwayland` on my device and without backup (have one) there will be no chance to get with old X11 support of generic events (direct mode).

**Comment by twaik** [comment]
Be patient. As I said before I will start research soon.

**Comment by RalfWerner** [comment]
Include this **restore of direct mode** (one major advantage on X11 related to other)?

**Comment by twaik** [comment]
**Be patient**.

**Comment by twaik** [comment]
Sending touch input to Xvfb seems to be impossible, I am planning to make it work with Xwayland again. But Xwayland support will be a bit different.

**Comment by twaik** [comment]
I am making some changes that will make this possible.
