### ISSUE TITLE
got 'X Error of failed request:  BadShmSeg (invalid shared segment parameter)'

### ISSUE THREAD

**Issue by xxfree86** [termux/termux-x11#234]
most x applications works fine with termux-x11 + proot-distro but
when i try to run glxgears, ffplay, blender got error like this.

X Error of failed request:  BadShmSeg (invalid shared segment parameter)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Segment id in failed request:  0x1400010
  Serial number of failed request:  269
  Current serial number in output stream:  270

These applications works in vncviewer but slow. :-/

any suggestion?

LG v50 sd855, android 12, proot-distro : ubuntu

**Comment by Suletta-Majo** [comment]
had same error me too.
i am it posted  reddit r/termux 'kivy' section 
reason i don't know i can't fix it too

i searched this MIT-SIM errors similer example
＞Major opcode of failed request: 130 (MIT-SHM)
famous error and deep spaghetti reason. so i retire search :(

my error number 131.
flet and kivy can't complete run simple samples
yes errors include 'ffplay'

**Comment by shiumano** [comment]
https://github.com/RobotLocomotion/drake/issues/18726
I think this will solve that problem.

**Comment by twaik** [comment]
1. Are you using termux's Xwayland with proot apps? Proot's sysvipc implementation is incompatible with terrmux, I've got something like that while tried to use termux's x11vnc with prooted Xvfb.
2. Termux:X11 itself does not support any kind of GL, GLX, GLES, etc. But some users reported swrast and llvmpipe backends of mesa work (software rendering).

**Comment by twaik** [comment]
Try to install Xwayland inside proot and start termux-x11 from inside. I am not sure if udroid can start termux apps but proot-distro can.

**Comment by kde-yyds** [comment]
It seems that the Xwayland package is not built with glx support.  After building and installing Xwayland with glx support, opengl programs will work (software renderer, of course).

**Comment by kde-yyds** [comment]
It seems that the Xwayland package is not built with glx support.  After building and installing Xwayland with glx support, opengl programs will work (software renderer, of course).

**Comment by xxfree86** [comment]
installed mesa-demos package in termux with pkg install command and it's glxgears runs without error.  avg 300fps.

**Comment by xxfree86** [comment]
> Try to install Xwayland inside proot and start termux-x11 from inside. I am not sure if udroid can start termux apps but proot-distro can.

tried  start termux-x11 inside proot  but not working.

termux-x11 command ended with 'killed.' message to console.

so i checked out this:

`ldd /system/bin/app_process`

displays that  none of linked shared object not found.

**Comment by twaik** [comment]
Killed message means there is a reason in logcat.

**Comment by twaik** [comment]
It should not find something because app_process is linked to bionic. Proot-distro allows to start programs outside a container.

**Comment by twaik** [comment]
> termux-x11 ended with 'killed.' message to console.

Fixed.

**Comment by IntinteDAO** [comment]
> installed mesa-demos package in termux with pkg install command and it's glxgears runs without error. avg 300fps.

You can always use mesa-zink (from TUR repository) to have hardware acceleration

**Comment by twaik** [comment]
Real hardware acceleration is not possible without using private APIs.

**Comment by IntinteDAO** [comment]
> Real hardware acceleration is not possible without using private APIs.

Well - I'm talking about using a graphics card. With (relative) Vulkan support, you can use OpenGL on Vulkan - Zink.

Maybe the use of Turnip will improve Zink performance, we'll see.

**Comment by twaik** [comment]
> Well - I'm talking about using a graphics card

I am talking about this too. Android restricts access to graphics card and does not have public API to access them directly. Even if Vulkan library has can work with real graphics card Vulka library on Android has no X11 support.

**Comment by Suletta-Majo** [comment]
https://www.reddit.com/r/termux/comments/uikny1/opengl_support_on_termux_x11/
mesa wayland with glx compile is this? hard mission for me :\
but wait. i feel user:itsfreepizza posted maybe very nice way for me.

**Comment by xxfree86** [comment]
`--no-sysvipc` option of the proot-distro script seems to bypas the BadShmSeg error.

**Comment by IntinteDAO** [comment]
> mesa wayland with glx compile is this? hard mission for me :

You have packages mesa-zink in TUR repository

**Comment by Suletta-Majo** [comment]
>  TURリポジトリにmesa-zinkパッケージがあります
thank you i'll get

**Comment by ThatMG393** [comment]
@Suletta-Majo 
Check this out: https://github.com/ThatMG393/gpu_accel_termux

**Comment by Suletta-Majo** [comment]
> 
thanx info. out of topic little bit but this script looked include qualcomm SoC. nice :)
myphone aquos wish2 ＞ Snapdragon 690 5G Adreno 619L

many Variety of GPU accel is work qualcomm chip
https://www.reddit.com/r/termux/comments/10hu1x7/termux_prefix_with_preinstalled_ubuntu_2204_proot/
this comments says 'Virgl works well on Adreno 650 (Snapdragon 865)' maybe mine too :-)

**Comment by xxfree86** [comment]
> most x applications works fine with termux-x11 + proot-distro but when i try to run glxgears, ffplay, blender got error like this.
> 
> X Error of failed request: BadShmSeg (invalid shared segment parameter) Major opcode of failed request: 130 (MIT-SHM) Minor opcode of failed request: 3 (X_ShmPutImage) Segment id in failed request: 0x1400010 Serial number of failed request: 269 Current serial number in output stream: 270
> 
> These applications works in vncviewer but slow. :-/
> 
> any suggestion?
> 
> LG v50 sd855, android 12, proot-distro : ubuntu

git cloned mesa-22.0.5 src, built and installed to /usr/local/lib in proot-distro and
glxgear, ffplay, blender, glmark2 runs without error.

i don't know whats going on this but annoying error is gone.

**Comment by twaik** [comment]
So I can close this?

**Comment by xxfree86** [comment]
> So I can close this?

of course. ;-)
