### ISSUE TITLE
[Xwayland?] Termux-x11 unstable

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#237]
Hi. After updating xwayland and the new Termux X11, users are reporting instability.

1) Termux X11 interacts correctly with Xwayland on average once in 4 times.

2) Some applications (e.g. Dosbox-X) are able to "kill" Termux X11 at startup.

3) Cursor on Termux have strange shadow. Probably new X11 Client do that, but I'm reporting xD

I'm recommended to download a movie, because of some kind of bug, the screen looks very bad :/
https://tube.midov.pl/w/im62fFqS6xuNgmRUgPoSeP

**Comment by twaik** [comment]
I am working on pure xcb version to avoid using Xwayland, it will be available soon (I hope).

**Comment by ThatMG393** [comment]
try to use this action build: https://github.com/termux/termux-x11/actions/runs/4212225635

**Comment by twaik** [comment]
Xwayland was updated so it will not work...

**Comment by twaik** [comment]
Video is small, I see nothing. Is it chroot, proot or something? Do you have any logs?

**Comment by twaik** [comment]
> Some applications (e.g. Dosbox-X) are able to "kill" Termux X11 at startup.

Is it launched in chroot or proot?

> Cursor on Termux have strange shadow. Probably new X11 Client do that, but I'm reporting xD

X11 client does nothing, it is located in separate project. But the bug is really interesting...

**Comment by IntinteDAO** [comment]
> Is it launched in chroot or proot?

Native Termux

> X11 client does nothing, it is located in separate project. But the bug is really interesting...

This bug was after Termux X11 upgrading.

___
I will give you a logs soon

**Comment by IntinteDAO** [comment]
Not connected Xwayland to Termux X11? But the process of Xwayland was in ps
![Screenshot_20230224-223432](https://user-images.githubusercontent.com/56807194/221299201-4f453ad2-17c7-4983-8190-f4363a9e9c23.png)

Here: No Termux X11 Window, fast crash I think
![Screenshot_20230224-223657](https://user-images.githubusercontent.com/56807194/221299325-6b21e8c2-2e44-427e-8458-42295de2d6ed.png)

Crash
![Screenshot_20230224-223722](https://user-images.githubusercontent.com/56807194/221299388-1d812b5f-f5ec-4d6e-870a-abd33db7aa42.png)

Dosbox-X Crashed X11:
![Screenshot_20230224-224123](https://user-images.githubusercontent.com/56807194/221299478-feea2376-505b-4dec-b150-c9e849a306e8.png)

Cursor Shadow:
![Screenshot_20230224-223808](https://user-images.githubusercontent.com/56807194/221299507-5b28e17c-bc88-4b1e-88eb-fce76a80c4fd.png)

![Screenshot_20230224-223800](https://user-images.githubusercontent.com/56807194/221299504-05cf203c-df90-4415-9ff9-12c77d513540.png)

**Comment by twaik** [comment]
I meant logcats of com.termux.x11, not logs available in termux.

**Comment by twaik** [comment]
I did not see this UI before, what device do you have?

**Comment by IntinteDAO** [comment]
> I did not see this UI before, what device do you have?

Motorola Moto G100 (Ready Now Desktop)

**Comment by IntinteDAO** [comment]
> I meant logcats of com.termux.x11, not logs available in termux.

https://pastebin.com/sarYWAFa
It's a logcat from whole system. Not sure if helpful

**Comment by twaik** [comment]
I am not sure but I think I found a reason... I am already on it...

**Comment by twaik** [comment]
Do you see that shadow behind a cursor only with physical mouse or with touchpad emulation too?

**Comment by twaik** [comment]
@IntinteDAO Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by IntinteDAO** [comment]
> @IntinteDAO Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

Sorry for waiting.

I check this tommorow. The shadow is when physical touchpad or mouse are connected (even not used). If I use only phone screen, there is no shadow

**Comment by twaik** [comment]
@IntinteDAO ?

**Comment by IntinteDAO** [comment]
> @IntinteDAO ?

In a nutshell. The shadow is only there if a physical device like a physical touchpad or mouse is connected. It does not appear when there is only a touchscreen.

As for stability, it is still unstable* (part 1). It is possible that some process or other sockets release (I don't know) takes a few minutes. If you turn off X11, wait a few minutes and turn it on again - it runs fine.

If you switch off X11 and want to start the other one immediately, there are problems.

As for DosBox X (part 2) - It don't crash X11 now I think.

**Comment by khatija07** [comment]
![Screenshot_2023-03-05-23-14-43-93_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/126348382/222976911-d72aa4ec-d563-4a7e-9f6a-353ba2262a63.jpg)
![Screenshot_2023-03-05-23-11-17-92_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/126348382/222976926-9e1336a1-4332-4e1c-beea-222a4dd84e74.jpg)
![Screenshot_2023-03-05-23-11-04-96_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/126348382/222976928-30686dbb-dc29-418e-9ab6-c449a7041337.jpg)
Cant connect to x11 !!

**Comment by twaik** [comment]
> Cant connect to x11 !!

It looks like you have updates android applications, but not a companion package. Update both.

**Comment by khatija07** [comment]
Packages are up to date in Termux  @twaik

**Comment by twaik** [comment]
Companion package can not be updated from termux's repo. Update it from latest artifact.

**Comment by khatija07** [comment]
Thanks it worked . How can i start display from proot?

**Comment by twaik** [comment]
Actually I am not sure, I did not use it with proot. But I want to start proot test in a few days.

**Comment by IntinteDAO** [comment]
> Thanks it worked . How can i start display from proot?

Well, IMO you can just run Termux X11 from Termux Env and render windows from Proot / Chroot.

If you use shared tmp in Proot / Chroot, you can set DISPLAY variable in Proot and type "xhost +" in your Termux environment and then if you type any X11 command application, it will be shown on your desktop.

**Comment by twaik** [comment]
> The shadow is only there if a physical device like a physical touchpad or mouse is connected. It does not appear when there is only a touchscreen.

I remember there was some semi-transparent white overlay and cursor did some hole in it. But for some I can not reproduce it on my devices.

**Comment by IntinteDAO** [comment]
> > The shadow is only there if a physical device like a physical touchpad or mouse is connected. It does not appear when there is only a touchscreen.
> 
> I remember there was some semi-transparent white overlay and cursor did some hole in it. But for some I can not reproduce it on my devices. And I do not know what prduces this overlay, I checked the code and found nothing.

Well, there is more bugs with cursor.
- Shadow (this ^)
- Cursor bugs
![obraz](https://user-images.githubusercontent.com/56807194/223425355-6bec01cc-1baa-4103-a4d1-e10c4661129b.png)
![obraz](https://user-images.githubusercontent.com/56807194/223425532-032d299d-e196-4f73-b6ca-d640d5850572.png)

If the cursor is default, moving will fix it. 
If it's custom cursor (for example - the game "Ardentryst" use custom cursor in-game), the cursor is fixed when it's out of window

- Scroll in some apps works like a shit (chromium), well - unable to scrolling (on hardware mouse)

**Comment by twaik** [comment]
I need logs.

**Comment by IntinteDAO** [comment]
> I need logs.

logcat or other? If you have the commands straight away, it will be easier.

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/issues/231#issuecomment-1457536532

**Comment by IntinteDAO** [comment]
@twaik 

Lmao, all problems have gone after upgrade ... fuck

Logs if still needed:  https://pastebin.com/HhqhcE7Q

I have one question. 

I don't know if it's supposed to be like that or if it's with me. Termux X11 starts up, but in the background (so to speak - headless mode). To run it on the desktop, I have to launch it from the console and from the launcher launch Termux X11 and then it appears. Additionally (I don't know?) how to enable the settings option in the new Termux, because there is no Termux X11 notification in the notifications.

Is this the way it's supposed to be, or some kind of bug?

**Comment by twaik** [comment]
> Termux X11 starts up, but in the background (so to speak - headless mode).

https://github.com/termux/termux-x11/issues/239#issuecomment-1454935743


> Additionally (I don't know?) how to enable the settings option in the new Termux, because there is no Termux X11 notification in the notifications.

You should give it permission to show notifications. For so.e reason kt does not ask this permission.

**Comment by twaik** [comment]
Did it work?

**Comment by IntinteDAO** [comment]
@twaik Works great, closing

**Comment by twaik** [comment]
Can you please tell how you setup proot? I am failing with MIT-SHM errors.

**Comment by IntinteDAO** [comment]
@twaik 

Usually what you need (reopen?):
- proot-distro installed in Termux. It's install Linux environment

It's from my head, so sorry if something doesn't work
> proot-distro install debian

I think it's install and login into Debian. Exit if you are logged

> proot-distro login debian --shared-tmp

It's running Debian with shared tmp directory. 
You can also use PROOT_NO_SECCOMP=1 environment variable if you have still issues.

**Comment by twaik** [comment]
Somebody told me to use `--no-sysvipc` and it worked. Thank you.

**Comment by khatija07** [comment]
@twaik termux-x11 says aborted!

**Comment by twaik** [comment]
Post `logcat`'s output.
