### ISSUE TITLE
Lost termux "root" window and external monitor (and yes, DeX)

### ISSUE THREAD

**Issue by rudolphpienaar** [termux/termux-x11#239]
# Summary

When using DeX off my Samsung Galaxy Fold Z3 on an external monitor, starting `termux-x11` from CLI seems to result in a "lost" root window. As a side comment, it works all perfectly off my Galaxy Ultra tablet, so I know it can work!

# Equipment

* Samsung Galaxy Fold Z3
* External monitor hooked up (via a dock)
* `termux-x11.zip` artifact downloaded on Feb 22nd, 2023

```
$> md5sum termux-x11.zip
a73ad90f574c13cdeee2d4beb56bf139  termux-x11.zip
```

# Methods

* Completely clean install of `termux-x11`
* Enabled all permissions on fresh install
* DeX up and running off externally connected monitor

# Observations

In a `termux` CLI:

```
$> export XDG_RUNTIME_DIR=${TMPDIR}
$> pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
```

then, starting up `termux-x11`:

```
$> termux-x11 :0 &

res = 0                                                                         
Activity is started                                                                   
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@f409898}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@a8f78f1}
Got finish request
```

A window seems to start to open on the display (occupying about the middle quadrant of the display). It then vanishes. Importantly there is no indication of the running process in the Dex taskbar.

# Details

Importantly, in the notifications curtain, a new "Termux :X11" notification appears, and the process table shows a `wayland` process:

```
ps -Af | grep wayland
u0_a561   9542 21940  0  1970 pts/0    00:00:00 /data/data/com.termux/files/usr/bin/Xwayland :0
```

when I now try and startup `xfce4`  I see all the typical terminal noise as if it were starting up, but the display to which it is drawing is not visible.

# Other bizarreness

If I fire up `termux-x11` then from the DeX applist (GUI based) the `termux-x11` window appears with `xfce4`, but often the colors are washed out. If I kill `termux-x11` and restart it, it appears with correct colors but in the middle of the root window is the `termux-x11` logo and a preferences button.

# Hope

I think `termux-x11` is an amazing app and being able to fully use it off a phone with DeX would be amazing.

Many thanks

**Comment by xxfree86** [comment]
termux(-x11) on android desktop mode  rocks!

**Comment by twaik** [comment]
Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by rudolphpienaar** [comment]
I tried the following builds (`md5sum`):
```
a49dc563d89648f4b211ecedb2871421  termux-x11.zip
4506ace7f880825e0b5a77f3a83cde01  termux-x11.zip.1
```
Both showed similar behaviour:

* when starting from CLI there is no termux:x11 in the DeX taskbar
* I start termux:x11 from the GUI -- I get a black  x11 root window. The root window has keyboard shortcuts on the bottom.
* If I right click on the taskbar termux:x11 and select preferences and try to deselect what I think is the bottom keys I get a a toast mesage for an `adb` command. I tried this command and no effect/change
* When I start `xfce4` I get the normal terminal noise but nothing in the termux:x11 window.

Hope this helps?

**Comment by twaik** [comment]
I'll check this.

**Comment by rudolphpienaar** [comment]
Wonderful -- I tried a recent artifact on my tablet (not the phone) and it "works"  -- xfce4 starts and all is good. But as soon as I start interacting the colors all "wash out". If I kill the window and start termux:x11 again  (from the GUI)  all seems good --colors are good, but the root window has a X11 logo and a preferences button. If this could just go away (like with a preference setting?) that would be perfect. It seems as if the termux:x11 window doesn't know a client session has connected...

**Comment by twaik** [comment]
Can you please post adb logcat of the device when it is not working (right after launching Termux:X11) and post a video and logcat of device where colors all "wash out"?

**Comment by rudolphpienaar** [comment]
ok, I'll see what I can do.

Many thanks!

**Comment by twaik** [comment]
Latest build has an ability to get logcat of `com.termux.x11`. simply do `export TERMUX_X11_DEBUG=1` before invoking `termux-x11`. I need this log to identify a problem...

**Comment by twaik** [comment]
Hi. Any updates?

**Comment by twaik** [comment]
@rudolphpienaar ?

**Comment by rudolphpienaar** [comment]
Thanks for the ping and apologies for the late reply.

I had downloaded a new artifact on 02 Mar

```
md5sum termux-x11.zip
f98405f9810ce31015416c309aff657f  termux-x11.zip
```

On both my phone and tablet this works! There are minor differences to the published `README`  in starting

```
termux-x11 :0 &
```

does not actually seem to "start"/"open" the root window. However, once I start the window manager and _then_ start `termux:x11` from the GUI launcher all seems to work!

No washed out colors. Root window is all good and desktop env works!

**Comment by twaik** [comment]
> does not actually seem to "start"/"open" the root window

If you are talking about starting activity and bringing it to front, it will not happen. `termux-x11` command is designed to start with startx like script once, at device/termux start and simply work in background. Android application you are starting from launcher does not really start any program, it simply connects to `termux-x11` started somewhere in termux or shows "not connected" screen if there is no service it can connect to.
