### ISSUE TITLE
Termux-11 app mouse causes screen with opaqueness

### ISSUE THREAD

**Issue by ivam3** [termux/termux-x11#241]
When executing the latest version published yesterday in actions, it is displayed for a few moments with the mouse pointer in large proportions to the degree of covering half the screen and then leaving the entire screen opaque as shown in the next image:

<details>

![Screenshot_20230225-173901_TermuxX11](https://user-images.githubusercontent.com/27752315/221384961-a65dd46a-3ad0-4342-886a-81e80094cfff.jpg)
</details>

Later, if I send the application to the background, when it returns to the foreground, the opacity problem is solved, however, the image of not connected is superimposed as shown in the next image:

<details>

![Screenshot_20230225-173922_TermuxX11](https://user-images.githubusercontent.com/27752315/221385106-857fb8cf-2ffd-4a87-a316-7e3819ad5652.jpg)
</details>

NOTE: The Termux app is in newest version. The pkg are updated and the termux-x11 deb file too

<details>

- TERMUX INFO
```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.49
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~HHD2a_tXjU6OnHl13hKrzA==/com.termux-1GVFNgsZd6H03DH5c2KLWg==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=30367
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c75,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c75,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10331
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+8421173
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+8421173
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.sdu.edu.cn/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirrors.sdu.edu.cn/termux/termux-x11 x11 main
Updatable packages:
termux-docker-qemu/stable 0.2.0 all [upgradable from: 0.1.4]
vim-gtk/x11 9.0.1350 aarch64 [upgradable from: 9.0.1300]
termux-tools version:
1.37.0
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Thu Nov 24 06:39:00 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so```

</details>

**Comment by twaik** [comment]
Hi. Do you use hardware mouse?

**Comment by ivam3** [comment]
Yes, but not always and the error occurs with or without it

**Comment by twaik** [comment]
Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)?

**Comment by ivam3** [comment]
let me check it , thanks

**Comment by ivam3** [comment]
The problem was caused by the xwayland version 22.1.8 package so I had to downgrade the version to temporarily fix it until now, with this update that you mention the error has been fixed, thank you very much for the assistance.

**Comment by ivam3** [comment]
The case is closed. The issue was solved with termux-x11 app builded [HERE](https://github.com/twaik/termux-x11/actions/runs/4309342747)
