### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Dendi777** [termux/termux-x11#244]
The latest builds are completely unstable, there are a lot of bugs in them when to wait for a more or less stable build?
The cursor does not appear at all and the keyboard is not called, frequent crashes and freezes are also noticeable

**Comment by twaik** [comment]
Soon. I am working on this but it will take some time.

**Comment by Dendi777** [comment]
Well, I hope you can fix it because it's very important for us to make vnc slow and your project is much faster! good luck!

**Comment by twaik** [comment]
If you know C++ and XCB you can help.

**Comment by Dendi777** [comment]
Unfortunately, I do not know c++ for me it is difficult to learn

**Comment by IntinteDAO** [comment]
> because vnc is slow and your project is much faster! good luck!

Well, if your CPU is slow, just reduce quality of VNC image xd

**Comment by twaik** [comment]
I do not think it is an option. And I am already working on a solution...

**Comment by Dendi777** [comment]
> Что ж, если у вас медленный процессор, просто уменьшите качество изображения VNC xd
Why does this not affect the speed of vnc in any way as it was slow and will remain slow

**Comment by twaik** [comment]
@Dendi777 Ты используешь chroot? Если нет то попробуй последний билд [здесь](https://github.com/twaik/termux-x11/actions)? Кстати там долден работать русский ввод если установишь русскую раскладку в иксах. `setxkbmap us,ru`.

**Comment by Dendi777** [comment]
I tested the last build, but I didn't manage to get a session at all, maybe we should contact, for example, in telegram so that I can send a video about each tested build?

**Comment by Dendi777** [comment]
I tried several launch options, but nothing happened once I saw the inscription in the client connection log! However, I never got the session!

**Comment by twaik** [comment]
@twaik in telegram.

**Comment by Dendi777** [comment]
Yes it looks like I found you I wrote Hello to you if it's you answer

**Comment by twaik** [comment]
It seems to be fixed. Can I close this?

**Comment by Dendi777** [comment]
Yes
