### ISSUE TITLE
Authorization required, but no authorization protocol specified

### ISSUE THREAD

**Issue by Bluecommand** [termux/termux-x11#245]
In chroot environment.

**Comment by twaik** [comment]
Logs?

**Comment by twaik** [comment]
That is likely error of some X11 client, maybe you did not pass `-ac` flag to `termux-x11`...

**Comment by twaik** [comment]
@Bluecommand  ?

**Comment by Bluecommand** [comment]
I add -ac to termux-x11 and now it works well. Thanks

**Comment by Bluecommand** [comment]
> @Bluecommand ?

I add -ac to termux-x11 and now it works well. Thanks

**Comment by Bluecommand** [comment]
> That is likely error of some X11 client, maybe you did not pass `-ac` flag to `termux-x11`...

Thanks It works well now
