### ISSUE TITLE
System shortcuts interception

### ISSUE THREAD

**Issue by 5A52** [termux/termux-x11#253]
Intercept system shortcuts is butiful  and very awaited feature. However Is it possible to have a separate chekbox for WIN key? 
 For example for me it is ok to always intercept all keys even without any checkbox as I can't imogine situation when some one will need to close whole desktop (termux-x11 app) by alt+f4. But there must be some "magic" key to be able to put termux-x11 app in the background without touching a mouse. The best candidate in my opinion is a WIN key, as it is not hardly used in a linux, but wery well  used in DEX. WIN+cursor keys are doind tilting (works fine with termux-x11 if keys are not intercepted) WIN+1.....0 start app shortcut from DEX taskbar...e.t.c.

**Comment by twaik** [comment]
I am sorry, but I do not think filtering keys is possible. DexUtils API only lets me specify if application intercepts all keys or not.

**Comment by 5A52** [comment]
Sorry to hear that, butI guessed it is like this. 
Then may be it is a good idea to stop intercepting if app is not fullscreen??

**Comment by twaik** [comment]
I'll check what I can do.

**Comment by twaik** [comment]
I can make it stop intercepting system shortcuts if app loses focus. Does it fit?

**Comment by 5A52** [comment]
I think no, as keys already are not intercepted if app is not in focus. But tilting for example does not work, as window must be in focus to be moved\resized.

**Comment by twaik** [comment]
It seems to me the problem can not be solved.

**Comment by 5A52** [comment]
Why? Is it impossible to stop intercepting (like switching toggle in app preferences manually) if app leaves fullscreen, and switch it back on if enters?

**Comment by twaik** [comment]
A question is about filtering single key, not about conditions of entering or leaving that state.
