### ISSUE TITLE
[question]virglrender and android libEGL library

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#254]
Is it possible to make virglrender work with android's libEGL and libGLES library and without mesa libgbm and libgl?
It seems that `virgl_test_server --use-egl-surfaceless` still uses libGL.so

**Comment by twaik** [comment]
As fa r as I know there are two options to launch `virgl_test_server` in termux.
1. Described [here](https://ivonblog.com/en-us/posts/termux-virglrenderer/), which uses zink as a backend.
2. Using [overlays](https://github.com/alexvorxx/VirGL-Overlay-Rebuild), which requires root. 

`termux-x11` itself is `x11vnc` like app, simply making screenshots when server repots screen is changed and sends input events to back to X server. It does not support any acceleration in any way. That is a work of X server.

**Comment by IntinteDAO** [comment]
@kde-yyds you have now virglrenderer-android with virgl_test_server_android

**Comment by kde-yyds** [comment]
> @kde-yyds you have now virglrenderer-android with virgl_test_server_android

It's great! I can now get chromium work smoothly through virglrender-android. 
But kwin and compiz crash all the time. It's probably a bug of virglrender because the same happens on my computer.

**Comment by dontknowhy** [comment]
> > @kde-yyds you have now virglrenderer-android with virgl_test_server_android
> 
> It's great! I can now get chromium work smoothly through virglrender-android. But kwin and compiz crash all the time. It's probably a bug of virglrender because the same happens on my computer.

Sadly i can't make virglrenderer-android works on my device(

**Comment by pierreduf** [comment]
Me neither :(

> > @kde-yyds you have now virglrenderer-android with virgl_test_server_android
> 
> It's great! I can now get chromium work smoothly through virglrender-android. But kwin and compiz crash all the time. It's probably a bug of virglrender because the same happens on my computer.

Hi @kde-yyds, I'm curious about how you made virglrenderer-android  worked in termux. On my side I did  : 
- Install virglrenderer-android  and mesa with pkg install in termux
- build a mesa driver of the same version (23.0.3) inside the proot

But I've got an error when I use it in my proot with GALLIUM_DRIVER = virpipe.

Would you be able to detail your setup and method (eg. how did you run chromium with acceleration) ?

**Comment by kde-yyds** [comment]
> Me neither :(
> 
> > > @kde-yyds you have now virglrenderer-android with virgl_test_server_android
> > 
> > 
> > It's great! I can now get chromium work smoothly through virglrender-android. But kwin and compiz crash all the time. It's probably a bug of virglrender because the same happens on my computer.
> 
> Hi @kde-yyds, I'm curious about how you made virglrenderer-android worked in termux. On my side I did :
> 
>     * Install virglrenderer-android  and mesa with pkg install in termux
> 
>     * build a mesa driver of the same version (23.0.3) inside the proot
> 
> 
> But I've got an error when I use it in my proot with GALLIUM_DRIVER = virpipe.
> 
> I've also tried those commands : https://github.com/ThieuMinh26/Box4Droid but have the same error (when launching glmark2 eg.) : `cso_unbind_context: assertion `maxsam <= pipe_max_samplers' failed.`
> 
> Would you be able to detail your setup and method (eg. how did you run chromium with acceleration) ?

I didn't build mesa by myself. The mesa package in both debian12 and archlinux support virpipe.
I didn't do anything else. It just works.

**Comment by pierreduf** [comment]
OK thanks for your answer ! I finally managed to make it work by patching those assert and hardcoding "maxsam" and other values to their max possible values. It works great now :D !

I'm in an Ubuntu proot and 23.0.3 was not available hence the problem.
