### ISSUE TITLE
`Shift Key` enabled

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#255]
@twaik 
i tested latest build and found `Shift Key` not released once pressed.(also in Google Keyboard)

 https://github.com/termux/termux-x11/commit/42955a0eefd951eed7412775514b531a3c4e85bc

Here is short video.

https://user-images.githubusercontent.com/61283438/222942268-9ee02749-2a6d-4661-9c85-014440426398.mp4

**Comment by twaik** [comment]
Likely cut-pasting problem, I simply forgot to change parameter after moving it to separate function. The greatest, biggest and longest patch ever.
