### ISSUE TITLE
`Enter` key is not working 

### ISSUE THREAD

**Issue by Blocked** [termux/termux-x11#256]
After finding #34 , simulating ``KEYCODE_DPAD_CENTER`` is working, but  `KEYCODE_ENTER` is not received in Termux X11 app version 1.02.06

**Comment by ask9027** [comment]
> After finding #34 , simulating `KEYCODE_DPAD_CENTER` is working, but `KEYCODE_ENTER` is not received in Termux X11 app version 1.02.06

Steps to Produce: move to any folder in `thunar` and Hit `Enter Key`. folder will not open.

Even `Ctrl` & `Alt` key not working from Hacker Keyboard.(Termux-X11 `Extra Keys` working).

other bug:- i installed android studio in termux with proot-distro, when i scroll code , search bar automatically open alonge scroll.

**Comment by ask9027** [comment]
[2023-03-06-13-24-49.txt](https://github.com/termux/termux-x11/files/10895711/2023-03-06-13-24-49.txt)
Here is catlog from `termux-x11`. Hope this will helpful.

**Comment by twaik** [comment]
> KEYCODE_ENTER is not received in Termux X11 app

Fixed in latest build. 

> Ctrl & Alt key not working from Hacker Keyboard.(Termux-X11 Extra Keys working).

It can not be fixed. Hacker's keyboard does not send any event when you press or release modifier keys so they can not be detected.

> other bug:- i installed android studio in termux with proot-distro, when i scroll code , search bar automatically open alonge scroll.

That is happening because program tries to send horizontal scroll (Shift + Scroll). I did not found a way to send horizontal scroll. You can try to move both fingers up when you are performing vertical scroll. I am already looking for other options.

**Comment by twaik** [comment]
> Here is catlog from termux-x11. Hope this will helpful.

It is not very helpful since it is taken from `com.termux` app, not from `com.termux.x11`. But you can do `export TERMUX_X11_DEBUG=1` before invoking `termux-x11` to get needed logs.

**Comment by Blocked** [comment]
@twaik Thanks. Can confirm it's fixed. @ask9027 Try Multiling O keyboard. It sends CTRL/ALT modifiers properly.

**Comment by ask9027** [comment]
> > Here is catlog from termux-x11. Hope this will helpful.
> 
> It is not very helpful since it is taken from `com.termux` app, not from `com.termux.x11`. But you can do `export TERMUX_X11_DEBUG=1` before invoking `termux-x11` to get needed logs.

Some how i manage to get this 
[2023-03-06-13-40-36.txt](https://github.com/termux/termux-x11/files/10900018/2023-03-06-13-40-36.txt)

from termux-x11. 
if log automatically save in any `.txt`  file. then we can get all log.

**Comment by twaik** [comment]
> Sending keycode 42

Keycode 42 is [KEY_LEFTSHIFT](https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L117). It is definitely sent to emulate horizontal scroll. I can add option to disable it.

**Comment by ask9027** [comment]
> > KEYCODE_ENTER is not received in Termux X11 app
> 
> Fixed in latest build.
> 
> > Ctrl & Alt key not working from Hacker Keyboard.(Termux-X11 Extra Keys working).
> 
> It can not be fixed. Hacker's keyboard does not send any event when you press or release modifier keys so they can not be detected.
> 
> > other bug:- i installed android studio in termux with proot-distro, when i scroll code , search bar automatically open alonge scroll.
> 
> That is happening because program tries to send horizontal scroll (Shift + Scroll). I did not found a way to send horizontal scroll. You can try to move both fingers up when you are performing vertical scroll. I am already looking for other options.

does this log helpfull for `Ctrl` from hHacker's keyboard?
[log.txt](https://github.com/termux/termux-x11/files/10923767/log.txt)

**Comment by twaik** [comment]
No. As I said before it can not be fixed.
