### ISSUE TITLE
Incorrect pacman dependency name for xorg-xwayland

### ISSUE THREAD

**Issue by KatouMegumi-osu** [termux/termux-x11#264]
It should not be called "xwayland" but "xorg-xwayland". Unable to install due to unsatisfied dependency.

**Comment by twaik** [comment]
Sorry, I have apt on my device. Can you please check latest build?

**Comment by KatouMegumi-osu** [comment]
Yep, works now. Thanks! 
![Screenshot_2023-03-08-10-43-56-478_com termux](https://user-images.githubusercontent.com/30472780/223629325-3efad9e9-266c-40dc-93a4-4684a6e3cdac.jpg)

**Comment by Maxython** [comment]
@KatouMegumi-osu, are you using pacman from proot-distro or pacman from termux as your main package manager?

**Comment by Maxython** [comment]
@KatouMegumi-osu, termux-x11 package in pacman format for termux, not for arch linux distribution. For understanding termux has two packages: apt (by default) and pacman.
