### ISSUE TITLE
Monochrome icon(Android 13 themed icon)

### ISSUE THREAD

**Issue by GlennX7** [termux/termux-x11#265]
Is there any plan to add monochrome icon for Termux-x11 like Termux app?

![Screenshot_2023-03-07-23-04-41-88_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/88073458/223507273-f5914e6d-1f3b-402b-9b31-82a72cd02b1e.jpg)

**Comment by twaik** [comment]
I am not sure I can draw something like that. But pull requests are always welcome.

**Comment by GlennX7** [comment]
> I am not sure I can draw something like that. But pull requests are always welcome.

Well I'm not very good at coding etc.
 What do you think about it ?
![Screenshot_2023-03-08-12-38-38-90_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/88073458/223645008-d9262093-4884-4224-b1e1-4bda1655285d.jpg)

Just tried lol

**Comment by twaik** [comment]
It should be svg image.

**Comment by GlennX7** [comment]
> It should be svg image.

I just added

`<monochrome android:drawable="@mipmap/ic_launcher_foreground" />`

As mentioned
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

And done lol lol![Screenshot_2023-03-08-17-53-54-17_b783bf344239542886fee7b48fa4b892.jpg](https://user-images.githubusercontent.com/88073458/223713166-3e67ef1e-3cb6-4fc2-9e2f-f9f87c540d86.jpg)
