### ISSUE TITLE
can you add an option to enable/disable "hide  termux-x11 from rencent list"?

### ISSUE THREAD

**Issue by emacs-newer** [termux/termux-x11#270]
my phone will kill background app automatically,and there are two modes:

1. kill background app showing in recent list by default;

2. kill background app completely until you run it again.

i need run termux-x11 in background for some jobs everyday,but this makes me very boring.

so can you add it please when users like me can set?

thanks!

**Comment by twaik** [comment]
Latest version will simply connect to existing session running in termux so that is not a problem. You can try to kill it to check how it works.

**Comment by emacs-newer** [comment]
yes it does,but i wish that you can still add an option.

because showing in recent list seems to use battery also.

thanks
