### ISSUE TITLE
Package depends on Xwayland

### ISSUE THREAD

**Issue by 5A52** [termux/termux-x11#274]
dpkg: dependency problems prevent configuration of termux-x11:
 termux-x11 depends on xwayland; however:
Package xwayland is not installed.

Howeever   dpkg --force-all -i   ofcourse works.

P.S. termux-x11 Xvfb works much better then Xwayland, Thanks.

**Comment by twaik** [comment]
There is another way to install package, with resolving all dependencies.
```
apt install ./path/to/package.deb
```
Xwayland will be removed from package dependencies.
