### ISSUE TITLE
Local Control 

### ISSUE THREAD

**Issue by hdt25** [termux/termux-x11#277]
Great Software for the Linux on Android.
But one request : 

Please implement hardware keys as mouse buttons in tha X11 app
Such as XServer XSDL 

Volume keys can be used as mouse buttons.
Vol Up for Right Click, Vol Down for Left Click
Vol Up + Vol Down for middle click
Long press Vol Up for Scroll Up
Long press Vol Down for Scroll down

Thanks in advance 🙏

**Comment by twaik** [comment]
You can use tap, two-finger and three'finger taps. If it does not fit you can try to remap keys using 'xmodmap'
