### ISSUE TITLE
How to use it in chroot?

### ISSUE THREAD

**Issue by HilmiRidho** [termux/termux-x11#279]

**Comment by Heasterian** [comment]
If you mean new branch, you need to add `-listen tcp` flag when starting Xvfb in Termux so `DISPLAY=:0 taskset -c 4-7 Xvfb -listen tcp :0 -ac -screen 0 4096x4096x24` for example and you should be able to connect to DISPLAY=:0 from chroot.

**Comment by HilmiRidho** [comment]
> If you mean new branch, you need to add `-listen tcp` flag when starting Xvfb in Termux so `DISPLAY=:0 taskset -c 4-7 Xvfb -listen tcp :0 -ac -screen 0 4096x4096x24` for example and you should be able to connect to DISPLAY=:0 from chroot.



> If you mean new branch, you need to add `-listen tcp` flag when starting Xvfb in Termux so `DISPLAY=:0 taskset -c 4-7 Xvfb -listen tcp :0 -ac -screen 0 4096x4096x24` for example and you should be able to connect to DISPLAY=:0 from chroot.

why is the command so complicated? please make things easy and maybe change the socket to wayland-0 that's better :))

**Comment by HilmiRidho** [comment]
if there is an error in the GUI I can kill it via the termux terminal, now it can only export display 0 and startlxde if you want another command then you have to ctrl+c :(((

**Comment by twaik** [comment]
> and one more thing, i think if you make a concept like sparkle it's good. start by pressing the start button to turn on the socket and stop to turn off the socket

I am not sure I understand what you mean.

**Comment by HilmiRidho** [comment]
> > and one more thing, i think if you make a concept like sparkle it's good. start by pressing the start button to turn on the socket and stop to turn off the socket
> 
> I am not sure I understand what you mean.

![Uploading Screenshot_20230322-202730_Sparkle.jpg…]()

**Comment by HilmiRidho** [comment]
> > and one more thing, i think if you make a concept like sparkle it's good. start by pressing the start button to turn on the socket and stop to turn off the socket
> 
> I am not sure I understand what you mean.

https://youtu.be/IR0mZ_KPaVg

**Comment by twaik** [comment]
> https://youtu.be/IR0mZ_KPaVg

It will not happen. Program must work without root so executing additional commands is mandatory.

**Comment by HilmiRidho** [comment]
> > https://youtu.be/IR0mZ_KPaVg
> 
> Itu tidak akan terjadi. Program harus bekerja tanpa root sehingga menjalankan perintah tambahan adalah wajib.

place the socket in termux /tmp

**Comment by Heasterian** [comment]
>  `-listen tcp` will not work in newer builds.
> [#231 (comment)](https://github.com/termux/termux-x11/issues/231#issuecomment-1436031561)

Could I ask why? Looks like works pretty well at this moment.

**Comment by twaik** [comment]
I did not implement cursor scaling.

**Comment by HilmiRidho** [comment]
:)))
