### ISSUE TITLE
XKB config error

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-x11#288]
Dear developers,
I have found out, that it is not possible to change The keyboard layout when using latest ArchLinux and Mate desktop. XKB config error. I have tried XVFB and default Xwayland but The same error is being presented.
I will try to downgrade to The older version, but may be, that it will not help. But it was worked with version which I have downloaded on 14.3 this year.
But except this issue, project is working outstandingly.

**Comment by twaik** [comment]
Can you please post full log where you get error? Simple setxkbmap should work.

**Comment by JanuszChmiel** [comment]
Dear MR Twaik,
I have used build 340 of Termux-x11.
And Termux-x11 cooperate with Xwayland for Termux without sockets related issues.
So I will rather not perform Xwayland Termux updates.
But The error occur also if I have used XVFB, no Xwayland.
I AM running The latest available packages for Arch Linux AArch64.
I Am using Proot distro and archlinux not Manjaro.

How do I execute The mate desktop environment?

Because Dbus configuration settings are not preconfigured as in Alpine Linux, Debian, Fedora or Ubuntu, I must always type
dbus-run-session mate-session &
After The mate desktop havebeen loaded, I run Orca screen reader.
I use ALT+F2 shortcut of Mate to run orca.
I enable The assistive technology support in The Mate control center, fortunately, Mate is precompiled so many apps work even if user do not have Assistive technology support checkbox checked.
And when The  Xkb error occur?
When I want to add other than US ENglish default keyboard layout.
I Am using official Mate app for such task named mate-keyboard-properties .
I only know, that old termux-x11 release did not caused those bugs, so I will as a experiment return to this release.
If Xwayland will not work, I will use XVFB instead.
If I will still get such error, I will have to accept sad reality, that some .so library have been updated so I will be not able to add new keyboard layout.

**Comment by JanuszChmiel** [comment]
Termux-x11 was The best X11 client because it has allowed to really professionaly set new keyboard layout. I had a notion, that I AM using Linux kernel, because keyboards could be switched so easy. I Am using Evolve Bluetooth keyboard. When I will buy USB on The go USB to C to micro USB cable, I will test also my Delux Chinese keyboard with nano transciever connected to USB on The go cable.
Android kernel fortunately support also many of those mini USB recievers.

**Comment by twaik** [comment]
As I said before I need logs...

**Comment by 5A52** [comment]
Same here, 
`[1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.1.SBw2umMeY]: 2
[1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.3.jATQ7sVhD]: 2
[1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.5.Z6zalH6ln]: 2`
on latest both [master](https://github.com/termux/termux-x11/actions/runs/4524914392) and [x11-client-experimental](https://github.com/termux/termux-x11/actions/runs/4385798707)
Unfortunately I don't know which build of termux-x11 I had before, but it was wayland and same xfce environment worked. Now the latest x11-client-experimental works fine except language switch, and latest master I have just a black screen with X cursor, same "Could not open tmp XKB file" in the log, and "intercept system shortcuts" swich does nothing at all, shotcuts are intercepted anyway. All of this on DeX.
@twaik how to contact you in telegram? You will have much faster feedback, if you need of course.

**Comment by twaik** [comment]
> Same here,
[1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.1.SBw2umMeY]: 2 [1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.3.jATQ7sVhD]: 2 [1679902015,000,/home/builder/.termux-build/libxklavier/src/libxklavier/xklavier_config_xkb.c:xkl_config_get_keyboard/]         Could not open tmp XKB file [/tmp/tmp.5.Z6zalH6ln]: 2

Not related to `termux-x11`.

> same "Could not open tmp XKB file"

I need to see this log.

> intercept system shortcuts" swich does nothing at all

It uses some private API so it can be a bit unstable. I'll check what is happening there...

> how to contact you in telegram

Search the same nickname.

**Comment by JanuszChmiel** [comment]
To fix this issue on Arch Linux.
Use always The following commands before running mate-session and may be also other desktop environments which depend on Message bus system and Dbus.

rm -rf /run/dbus/dbus.pid
dbus-daemon --system
dbus-launch mate-session &
Do not run commands before as Root even in Proot.
Really as normal non root user.

XKB config will run as it should.
I AM very sorry for my reported issue. It is The result of partially professionally implemented cchroots on Termux.
Fortunately, dbus daemon can run even in chroots if non Linux kernel is being used.
