### ISSUE TITLE
Extra keys

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-x11#289]
Most of the users are turned on 3 finger swipe screen shot function or split screen gesture . So can you add some other option to show/hide extra keys. Like volume button?

**Comment by twaik** [comment]
I can add an option to map volume down key to hide ek bar action.

**Comment by twaik** [comment]
> Most of the users

Hardly believe it...

**Comment by RaWolFoX** [comment]
> > Most of the users
> 
> Hardly believe it... 

😁😁🥺

**Comment by twaik** [comment]
Fixed by https://github.com/termux/termux-x11/commit/ee2224e474ce0c184de7a2c9c454c658f8afe249.
