### ISSUE TITLE
Some keyboard keys not working on latest build

### ISSUE THREAD

**Issue by amir-hz** [termux/termux-x11#291]
I have a problem on the last build. I use a physical keyboard with a bluetooth connection, there are several keys that I can't use, including ctrl, alt, esc, and repeat keys. But I can use it when using VNC

**Comment by ask9027** [comment]
issue already opened at #272

**Comment by RalfWerner** [comment]
> issue already opened at #272

This issue related to _virtual KB_! I've checked with my BT-KB (Logitech K375s) and *mc* and *nano* in *xterm* without problems using **ctrl**. But X11 don't support my german Keys (`öäü#` -> `;'[\`) as before in previous version and also in VNC.

**Comment by amir-hz** [comment]
> issue already opened at #272

#272  looks like it's a problem with the virtual keyboard, whereas I'm using a physical keyboard. And I'm using proot-distro xubuntu. This happened after the latest xwayland update, previously had no problems.

**Comment by ivam3** [comment]
i have the issue with touchscreen and physical keyword.
Special keys as ctrl,alt,esc doesnt work

**Comment by twaik** [comment]
Fixed by https://github.com/termux/termux-x11/commit/ee2224e474ce0c184de7a2c9c454c658f8afe249.
