### ISSUE TITLE
Not working in LXC

### ISSUE THREAD

**Issue by Ilya114** [termux/termux-x11#293]
Hi, I using LXC containers on my phone (POCO X3 Pro) and I tried mount `termux-x11` socket using this command: `lxc.mount.entry = /data/data/com.termux/files/usr/tmp/termux-x11 tmp/termux-x11 none bind,optional,rw,create=file` but when I exported $DISPLAY in container and try launch xfce4 I got:
```
root@ubuntu:~# xfce4-session
xfce4-session: Cannot open display: .
Наберіть 'xfce4-session --help' для використання.
```
Same commands (except mount method) working in chroot or proot but I want use termux-x11 in LXC, this is a possible?

**Comment by 2096779623** [comment]
`export DISPLAY=:1`

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/229293049-3ca85e0d-f833-4b47-950e-b8d09e46a348.png)
I dont think what problem in display

**Comment by twaik** [comment]
Both termux-x11 and X display socket must be accessible for termux-x11. You can use `export TMPDIR=/path/to/tmpdir` if it is possible. Or you can mount-bind `/tmp/.X11-unix` of container to some place like `/data/data/com.termux/files/usr/tmp/.X11-unix`.

**Comment by Ilya114** [comment]
I`m mounted /tmp from Termux to container fully but its still not work:
```
root@ubuntu:~# ls -la /tmp
total 25
drwxrwxrwt.  7 root  root  8192 кві  1 14:12 .
drwxr-xr-x. 17 root  root  3488 кві  1 14:11 ..
drwxrwxrwt.  2 root  root  3488 кві  1 14:11 .font-unix
drwxrwxrwt.  2 root  root  3488 кві  1 14:11 .ICE-unix
srwx------.  1 10168 10168    0 кві  1 14:12 termux-x11
-rw-------.  1 10168 10168    0 кві  1 14:12 termux-x11.lock
drwxrwxrwt.  2 root  root  3488 кві  1 14:11 .Test-unix
drwxrwxrwt.  2 root  root  3488 кві  1 14:11 .X11-unix
drwxrwxrwt.  2 root  root  3488 кві  1 14:11 .XIM-unix
root@ubuntu:~# export DISPLAY=:0
root@ubuntu:~# xfce4-session
xfce4-session: Cannot open display: .
Наберіть 'xfce4-session --help' для використання.
root@ubuntu:~# 
```

**Comment by twaik** [comment]
What is inside `/tmp/.X11-unix`?

**Comment by Ilya114** [comment]
![зображення](https://user-images.githubusercontent.com/93242944/229294585-9657b04e-19fb-4494-8169-ebaf890dfb7f.png)
Empty

**Comment by twaik** [comment]
It should not be empty if you started termux-x11.

**Comment by Ilya114** [comment]
But
![зображення](https://user-images.githubusercontent.com/93242944/229294680-545b7db1-2941-401e-b4eb-e8c8580dda06.png)

**Comment by twaik** [comment]
Something is definitely wrong. But I do not think it is possible to see this black screen without existing socket in `/data/data/com.termux/files/usr/tmp`.

**Comment by Ilya114** [comment]
My starting commands: `Xvfb :0 -ac &` `DISPLAY=:0 termux-x11 &`

**Comment by Ilya114** [comment]
Started xfce4 in Termux but `.X11-unix` still empty
<details>
![зображення](https://user-images.githubusercontent.com/93242944/229295582-f53fd204-8cad-4ecb-a06b-793d6f107b3f.png)

</details>

**Comment by twaik** [comment]
Can I connect to your phone with Anydesk?

**Comment by twaik** [comment]
Contact me in Telegram.

**Comment by Ilya114** [comment]
If your username is @twaik I wrote you

**Comment by Ilya114** [comment]
Fixed
