### ISSUE TITLE
Full Wayland Support

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#294]
Of course, Termux X11 focuses on XWayland or a similar solution. It seems to me that the Linux world is slowly but inexorably moving to Wayland directly.

It would be nice if Termux X11 turned into Termux Wayland with full Wayland support, although I think it would be very difficult (or impossible).

**Comment by twaik** [comment]
Wayland support is not planned.

**Comment by IntinteDAO** [comment]
> Wayland support is not planned.

That's what I'm assuming, but I wonder if it will be a problem. WSL2 uses Wayland, Ubuntu or Fedora use Wayland. It may be that the new software will be wayland-only (Waydroid is, but so is Anbox).

I rather added this issue that maybe one day. Although it's probably a lot of work.

**Comment by twaik** [comment]
Termux:X11 is designed to work with termux. Currently termux does not work with Wayland so writing wayland support here has no sense.
