### ISSUE TITLE
emulated touchpad not working on latest build

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-x11#295]
this used to not happen before, just now emulated touchpad doesn't work, only direct touches can be used.

**Comment by twaik** [comment]
He means emulated touchpad of Dex.

**Comment by 5A52** [comment]
Have I close [#297](https://github.com/termux/termux-x11/issues/297)?

**Comment by twaik** [comment]
No, I this I was confised with nicknames.

**Comment by Yisus7u7** [comment]
Well, this error is repeated on a 32-bit huawei Y7, running android 7.

I have another device (Moto g6 plus) 64 bit, android 13 with LineageOS and it works correctly, the error happens is on the huawei.

**Comment by twaik** [comment]
Can you please test latest version?
