### ISSUE TITLE
Unable to get Termux:X11 working in a proot-distro

### ISSUE THREAD

**Issue by LukeShortCloud** [termux/termux-x11#299]
Using Termux:X11 works perfectly when using Termux itself.

```
(termux)$ XDG_RUNTIME_DIR="${TMP}" termux-x11 &
(termux)$ DISPLAY=:0 dbus-launch --exit-with-session xfce4-session
```

[termux.log](https://github.com/termux/termux-x11/files/11227800/termux.log)

When using a proot-distro, nothing happens in Termux:X11. It shows a black screen with the signature Xorg "X" cursor which means that the `termux-x11` process is running and working. Apparently the proot-distro is not able to utilize that Xwayland environment. I do see all of the related Xorg files in `/tmp` in the Arch Linux proot, too.

```
(termux)$ proot-distro login archlinux --shared-tmp
(archlinux)$ XDG_RUNTIME_DIR=/tmp DISPLAY=:0 dbus-launch --exit-with-session xfce4-session
```

[proot-distro-archlinux.log](https://github.com/termux/termux-x11/files/11227772/proot-distro-archlinux.log)

I have attached the standard output and error of running the `xfce4-session` command in both Termux and in the proot-distro for comparison. Thank you in advance for any help you can provide!

**Comment by LukeShortCloud** [comment]
After removing permissions for others, the same warning appears but it complains about the new permissions.

```
dbus[20579]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp" can be written by others (mode 041770)
```

I then tried `chmod 0755` to make the temporary file a normal folder (which can break things for other programs). That removes the above warning entirely. But Termux:X11 is still not working and all I get is a black screen with a mouse cursor.

All of the other warnings still appear about failing to launch various XFCE4 related programs:

```
Unable to launch "<XFCE_PROGRAM>": Failed to close file descriptor for child process (Invalid argument)
```

**Comment by twaik** [comment]
Read this.

**Comment by twaik** [comment]
Maybe it is some error in dbus-launch, try to run `DISPLAY=:0 xfce4-session`

**Comment by LukeShortCloud** [comment]
Thanks everyone for all the hints. Here's everything new I've tested so far based on the latest suggestions:

- `DISPLAY=:0 xfce4-session` (no use of `dbus-launch`) = Same warnings.
- `proot-distro login archlinux --bind /dev/null:/proc/sys/kernel/cap_last_cap --shared-tmp` (Binding this kernel capability to disable it) = Same warnings.
- I made sure that the `dbus-launch` binary was already installed correctly. This comes from the `dbus` package on Arch Linux and `dbus-x11` on Debian.
- `adb shell settings put global settings_enable_monitor_phantom_procs false` (Disable the limit on background processes) = Same warnings but this should help prevent issues I probably would encounter in the future.

I also tried a few things that did end up working:

- `DISPLAY=:0 firefox` = Launching Firefox with the Arch Linux PRoot, which apparently does not rely on dbus at all, works.
- `proot-distro login debian--shared-tmp` = I created and used a Debian PRoot and it worked.

I can only come to the conclusion that either (A) there's a bug in Arch Linux or (B) I'm missing other dependencies in Arch Linux. I've cross-checked many Termux:X11 guides about Arch Linux and installed everything that should be needed.

Here are all of the packages I have installed in Arch Linux:

```
$ sudo pacman -S dbus firefox networkmanager pulseaudio xfce4 xfce4-goodies lightdm xorg xorg-server
```

I don't think a display manager such as LightDM is necessary since we are manually starting a session via the CLI but it was listed in one of the guides I as following.

For reference, here are all of the guides I've been reading over:

- https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/
- https://ivonblog.com/en-us/posts/termux-x11/
- https://udroid-rc.gitbook.io/udroid-wiki/udroid-landing/setting-up-gui/termux-x11
- https://birdsintech.blogspot.com/2022/12/setting-up-termuxx11-wayland-on-android.html
- https://wiki.termux.com/wiki/Graphical_Environment

**Comment by Saikatsaha1996** [comment]
> After removing permissions for others, the same warning appears but it complains about the new permissions.
> 
> ```
> dbus[20579]: Unable to set up transient service directory: XDG_RUNTIME_DIR "/tmp" can be written by others (mode 041770)
> ```
> 
> I then tried `chmod 0755` to make the temporary file a normal folder (which can break things for other programs). That removes the above warning entirely. But Termux:X11 is still not working and all I get is a black screen with a mouse cursor.
> 
> All of the other warnings still appear about failing to launch various XFCE4 related programs:
> 
> ```
> Unable to launch "<XFCE_PROGRAM>": Failed to close file descriptor for child process (Invalid argument)
> ```

I think it is not termux-x11 issue.. same issue with me.. Even vnc also not working.. you can better understand..

https://github.com/termux/proot-distro/issues/293#issue-1669129587

**Comment by LukeShortCloud** [comment]
Agreed. We can rule out Termux:X11 as being the issue because (1) individual X11 apps do work with Arch Linux and (2) the XFCE4 desktop environment does work with Debian. I'll go ahead and close this issue.

Thanks everyone for your help and insight! I'll report back if I can ever get Arch Linux to work.

**Comment by ochakov** [comment]
I have the same issue and would like to add my five cents.
I have a Samsung S7 FE tablet and a Pixel phone.  Running proot-distro Ubuntu 22.04.
With the same setup exactly, the problem only occurs on Samsung, but not on Pixel.
I tried other distros as well with no luck.

Looks like the problem is related to Samsung.

**Comment by Saikatsaha1996** [comment]
> I have the same issue and would like to add my five cents. I have a Samsung S7 FE tablet and a Pixel phone. Running proot-distro Ubuntu 22.04. With the same setup exactly, the problem only occurs on Samsung, but not on Pixel. I tried other distros as well with no luck.
> 
> Looks like the problem is related to Samsung.

No i checked.. it is actually our vendor issue..

Don't have any issues with miui device

**Comment by mio-19** [comment]
> Looks like the problem is related to Samsung.

I also have two devices available and the problem only occurs on Samsung

**Comment by Saikatsaha1996** [comment]
> > Looks like the problem is related to Samsung.
> 
> I also have two devices available and the problem only occurs on Samsung

Gki kernel? Kernel version 5.4 or 5.10 ?

**Comment by szw0407** [comment]
Same on Samsung Galaxy Tab S7 FE, using ArchLinux proot, following the steps of `https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/`

Quite puzzled... Is there anything different between One UI and other Android based Operate systems?

**Comment by mio-19** [comment]
> Same on Samsung Galaxy Tab S7 FE, using ArchLinux proot, following the steps of `https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/`
> 
> Quite puzzled... Is there anything different between One UI and other Android based Operate systems?

It is caused by glib2. You need to disable close range related code blocks in glib/gspawn.c

**Comment by mio-19** [comment]
> Same on Samsung Galaxy Tab S7 FE, using ArchLinux proot, following the steps of `https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/`
> 
> Quite puzzled... Is there anything different between One UI and other Android based Operate systems?

There is something different on 5.4 gki android kernel but I don't know what exactly

**Comment by mio-19** [comment]
> > Same on Samsung Galaxy Tab S7 FE, using ArchLinux proot, following the steps of `https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/`
> > Quite puzzled... Is there anything different between One UI and other Android based Operate systems?
> 
> It is caused by glib2. You need to disable close range related code blocks in glib/gspawn.c

I made a patched package here https://github.com/mio-19/aur-patches-aarch64/tree/3049fa6c9ecfe008aa58cbdf5dce69389088b69b/_kernel5_4/glib2-no-close-range

**Comment by szw0407** [comment]
> > > Same on Samsung Galaxy Tab S7 FE, using ArchLinux proot, following the steps of `https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/`
> > > Quite puzzled... Is there anything different between One UI and other Android based Operate systems?
> > 
> > It is caused by glib2. You need to disable close range related code blocks in glib/gspawn.c
> 
> I made a patched package here https://github.com/mio-19/aur-patches-aarch64/tree/3049fa6c9ecfe008aa58cbdf5dce69389088b69b/_kernel5_4/glib2-no-close-range

Have you ever tried using Debian?

I tried using it following the steps on ivonblog, expecting it to work as many other issues mentioned that would work just fine, but I failed... Is there anything that website didn't mention?

Infact I am quite unfamiliar with Linux... I could hardly deal with such problems by simply reading archwiki...

**Comment by mio-19** [comment]
> Infact I am quite unfamiliar with Linux... I could hardly deal with such problems by simply reading archwiki...

It is a issue specific to a version of android kernel and isn't documented on archwiki.

If you installed an older version of Debian such as Debian 11 it should work fine. The issue was introduced by newer versions of glibc and glib.

**Comment by mio-19** [comment]
@szw0407 Just to confirm, was the error message `Failed to close file descriptor for child process (Invalid argument)` ?

**Comment by Saikatsaha1996** [comment]
> > Infact I am quite unfamiliar with Linux... I could hardly deal with such problems by simply reading archwiki...
> 
> It is a issue specific to a version of android kernel and isn't documented on archwiki.
> 
> If you installed an older version of Debian such as Debian 11 it should work fine. The issue was introduced by newer versions of glibc and glib.

Can you fell back to Android 12 ? In Android 12 with kernel 5.4 newer Ubuntu & Debian working..

**Comment by szw0407** [comment]
> @szw0407 Just to confirm, was the error message `Failed to close file descriptor for child process (Invalid argument)` ?

I opened a discussion under that blog, with all errors, and the x11 app has only black screen and a cursor:

[details](https://github.com/ivon852/netlify-ivon-blog-comments/discussions/550#discussioncomment-7372010)

Similar things happen in Debian 12, and I am unable to deal with it.

**Comment by szw0407** [comment]
> > > Infact I am quite unfamiliar with Linux... I could hardly deal with such problems by simply reading archwiki...
> > 
> > It is a issue specific to a version of android kernel and isn't documented on archwiki.
> > 
> > If you installed an older version of Debian such as Debian 11 it should work fine. The issue was introduced by newer versions of glibc and glib.
> 
> Can you fell back to Android 12 ? In Android 12 with kernel 5.4 newer Ubuntu & Debian working.. 

Perhaps not.

Samsung devices cannot be downgraded unless being rooted, but that would destroy Knox. Unfortunately I am not yet ready for that.

**Comment by mio-19** [comment]
> Similar things happen in Debian 12, and I am unable to deal with it.

Yes all recent glibc versions have problems with close range which 5.4 gki android kernel doesn't have. 

Glibc incorrectly thinks that the program doesn't have the permission instead of the kernel not having this feature. Glib will use a fallback method on kernels without this feature, but glib received the wrong message from glibc.

**Comment by szw0407** [comment]
yeah, and I managed to install xfce4 on Debian 11, everything seemed fine so far...

Thanks for your support. Wish the issue you mentioned be fixed soon in a new release.

**Comment by BBCByComcast** [comment]
I Fix Glibc in All Latest Proot Distro Using Better Desktop Environment, Go My Issues And You See, It's KDE Plasma (or Kubuntu Desktop If You Are Ubuntu), Everything Fine with All Latest Proot Distro,  Do You Accept My Issues?

**Comment by Saikatsaha1996** [comment]
> I Fix Glibc in All Latest Proot Distro Using Better Desktop Environment, Go My Issues And You See, It's KDE Plasma (or Kubuntu Desktop If You Are Ubuntu), Everything Fine with All Latest Proot Distro, Do You Accept My Issues?

Will check..

**Comment by BBCByComcast** [comment]
> > I Fix Glibc in All Latest Proot Distro Using Better Desktop Environment, Go My Issues And You See, It's KDE Plasma (or Kubuntu Desktop If You Are Ubuntu), Everything Fine with All Latest Proot Distro, Do You Accept My Issues?
> 
> Will check..

Sure, That KDE Plasma And Kubuntu Desktop is Better....

**Comment by BBCByComcast** [comment]
Dang Twaik Comment Me, We're Difference Between Recommend Packages And Suggestions Packages:
https://superuser.com/questions/70031/what-is-the-difference-between-recommended-and-suggested-packages-ubuntu

**Comment by mio-19** [comment]
> I Fix Glibc in All Latest Proot Distro Using Better Desktop Environment, Go My Issues And You See, It's KDE Plasma (or Kubuntu Desktop If You Are Ubuntu), Everything Fine with All Latest Proot Distro, Do You Accept My Issues?

Did you used a translator or something?

**Comment by oltenxyz** [comment]
> > I Fix Glibc in All Latest Proot Distro Using Better Desktop Environment, Go My Issues And You See, It's KDE Plasma (or Kubuntu Desktop If You Are Ubuntu), Everything Fine with All Latest Proot Distro, Do You Accept My Issues?
> 
> Did you use a translator or something?

That guy is wreaking havoc all over the repo. Today, I woke up to 27 unintelligible emails, just because I responded to a different issue from him.
