### ISSUE TITLE
How does the application work

### ISSUE THREAD

**Issue by hanxinhao000** [termux/termux-x11#3]
How usr?

**Comment by xeffyr** [comment]
Application isn't available for installation. It is in pre-alpha state.

Usage is like:

1. Open Termux:X11.
2. Switch to Termux and launch `Xwayland`.

**Comment by hanxinhao000** [comment]
Please, teach me how to use this

**Comment by hanxinhao000** [comment]
T.T

**Comment by kcubeterm** [comment]
@hanxinhao000 this is just a simple way, 
```
pkg install x11-repo
pkg install termux-x11
pkg install xwayland
termux-x11
```
afterthat return in termux and open new session
```
Xwayland :1

```
open another session and export DISPLAY
```
export DISPLAY=:1
```
after that run any gui program and check termux x11 apps now, i have tested with `gitk`
it's work,

**Comment by xeffyr** [comment]
I'm noting that application is *unmaintained* and in pre-alpha state. It also crashes in certain conditions on ARM, fix is unavailable.

**Comment by kcubeterm** [comment]
Ooo, but in aarch64, i doesn't get a single issue,
@xeffyr can you tell me some issues, i want to try on my device.
