### ISSUE TITLE
Instant crash on OnePlus 8, Android 10

### ISSUE THREAD

**Issue by Heasterian** [termux/termux-x11#30]
App just instantly crashes after display of white screen at launch on my OnePlus 8. I used last build from GitHub actions.

How I can gather more info to troubleshoot it?

**Comment by agnostic-apollo** [comment]
Restarting termux should show a crash notification but if its happening before that then use `logcat` to find the `Exception` thrown.

https://developer.android.com/studio/command-line/logcat

**Comment by WMCB-Tech** [comment]
Maybe similar to #25 

A logcat would be helpful to catch some exception thrown in Termux:X11

**Comment by Heasterian** [comment]
Sorry for not responding here, but issue was solved meanwhile and now it's starting fine.

I'm closing issue.
