### ISSUE TITLE
how to correctly stop termux-x11 companion

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-x11#302]
Dear elite Java and C developer MR Twaik,
Please, how to correctly stop termux-x11?
Is it really necessary to kill it by typing killall Xwayland?
Do you think, that you could develop simple command line option based routine to stop The process?
for example termux-x11 stop
or termux-x11 -stop
I would like to publicly express very positive emotions which your development activity recalled inside my soul.
Termux-x11 is working so stably and I can use so many applications much more faster than when I have been forced to use Xvnc and Vnc protocol based Android client apps.
But I Am afraid, that new memory protection strategies of The crucial players on The field of WEB browsers will make end of our using WEB browsers on Proot containers.
For example, Chromium will very probably finish supporting --no-sandbox switch and default memory allocations without --no-sandbox do not allow users to run this browser.
Unfortunately, The similar sad situation exists for Firefox, which uses also memory sandbox.
The question is, if is it technically ossible to extend Proot so it would support even so sophisticated memory protection routines like various sandboxes are.
Or if this feature would require too much time or Android kernel on non rooted device do not allow memory sandboxes.

**Comment by twaik** [comment]
Using pkill is the best choise to stop termux-x11. -stop option will not be
implemented.
Termux-x11 development is not related to proot, in any shape or form. You
should open issue in proot-distro repository.
