### ISSUE TITLE
The app doesn't run in the background.

### ISSUE THREAD

**Issue by Sajjad-x** [termux/termux-x11#303]
The issue only happens with the new versions. I'm on Galaxy Note20 Ultra, and all the new versions instantly stop once I hide the app in the background. This didn't happen in versions from March versions.

Even when it doesn't close, the notification disappears once the app loses focus or is not on the screen.

I tried to disable battery optimization and excluded it from RAM cleaner and other optimization apps from the system.
This started to happen when I updated the app. I also tried doing a clean install, but it didn't help.

Edit: the app works fine, it's just that its running notification only appears when it's on the main screen, which makes the system treat it as an unimportant background process, and eventually kills it.
I'm on Android 13, and Notification permission is enabled.

**Comment by twaik** [comment]
It is a normal behaviour for latest version. It does not need to run in background because it does not contain a server.
