### ISSUE TITLE
i cant use display:1 again use

### ISSUE THREAD

**Issue by skskss** [termux/termux-x11#304]
i had succeed using the termux x11 but i accidentally removed the termux-x11 app from recents an now cant find any way to kill :1 and restart it

**Comment by twaik** [comment]
Android app does not contain a server. You can kill Xwayland.

**Comment by skskss** [comment]
please describe how can i do it cause xwayland is a dependency not an application

**Comment by twaik** [comment]
`pkill Xwayland`
