### ISSUE TITLE
Xwayland dying randomly 

### ISSUE THREAD

**Issue by Yamada6612** [termux/termux-x11#305]
![Screenshot_20230419-195823](https://user-images.githubusercontent.com/96498811/233217786-dbaa720e-8517-4901-bb1f-b8d4071b8e85.png)

What can I do about this problem?

**Comment by twaik** [comment]
Maybe that is effect of phantom process killing. https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr

**Comment by Yamada6612** [comment]
> Maybe that is effect of phantom process killing. https://github.com/agnostic-apollo/Android-Docs/blob/master/en/docs/apps/processes/phantom-cached-and-empty-processes.md#commands-to-disable-phantom-process-killing-and-tldr

I already thought about this possibility but it is not the phantom process killer, I disabled it as soon as I installed the termux, maybe the problem is related to Xwayland remaining active even with the termux closed.

**Comment by twaik** [comment]
Not possible. If Android shuts down termux's background service it also kills all the processes termux has started.

**Comment by Yamada6612** [comment]
> Not possible. If Android shuts down termux's background service it also kills all the processes termux has started.

![Screenshot_20230420-123854_Termux](https://user-images.githubusercontent.com/96498811/233417496-a32b8d6b-feee-4027-9b5f-52f2a503aa6c.png)

**Comment by twaik** [comment]
That is not related to hanging Xwayland. That is related to background termux-x11 process. You should kill it.

**Comment by Yamada6612** [comment]
> That is not related to hanging Xwayland. That is related to background termux-x11 process. You should kill it.

even after doing that wayland keeps dying

**Comment by Yamada6612** [comment]
I think I managed to get around this problem, this is very confusing
