### ISSUE TITLE
how to middle click on blender

### ISSUE THREAD

**Issue by skskss** [termux/termux-x11#308]
i have been running blendr 2.79 in proot debian distro and it works perfect with vnc ant termux-x11 both but it is more smooth in termux-x11 but it has a problem that i cant do right clicks or middle click drags for rotating camera angles is there any way to add right and middle click input in additional keys given in termux-x11 app 
![Screenshot_2023-04-27-12-53-15-23](https://user-images.githubusercontent.com/69956184/234789591-29997f1b-721d-4c55-9d2a-1541db6d87fb.png)

**Comment by twaik** [comment]
Did you try tapping with three fingers?

**Comment by maxellabdullah** [comment]
actually we need to press/hold the middle button while dragging the mouse to rotate the viewport in blender. which three fingers only to press and can not be done while sliding

**Comment by twaik** [comment]
You can use external mouse for this. There is no way for middle mouse holding.

**Comment by maxellabdullah** [comment]
> You can use external mouse for this. There is no way for middle mouse holding.

Is it not possible to add mouse button hover option in preferences?? like the mouse buttons in the realvnc app or similar

**Comment by twaik** [comment]
No.
