### ISSUE TITLE
Termux x11 does not recognize keyboard layout

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-x11#311]
When using a keyboard connected by Bluetooth or cable, and configuring it with the appropriate layout, it works normally in any app, even termux, but in termux x11 the keyboard does not.

In termux x11 the entered text does not match the keys pressed, this is very annoying, And you can't change

**Comment by twaik** [comment]
Termux:X11 receives input through `[SurfaceView](https://developer.android.com/reference/android/view/SurfaceView)` which is not recognised as text editor (like `[EditText](https://developer.android.com/reference/android/widget/EditText)`). That is the reason the app receives only keycodes and not unicode characters. Also that means the app can use real (translated) scancodes and acts accordingly. In the case if you need to work with different keyboard layouts you should set them with `setxkbmap` or with DE settings.
