### ISSUE TITLE
[Feature request] Stylus support

### ISSUE THREAD

**Issue by parkerlreed** [termux/termux-x11#315]
Right now stylus works as a mouse including hover. 

Would be great to get that passed along as a pressure sensitive stylus so you can use it in applications like GIMP.

**Comment by twaik** [comment]
I am working on a new version of the termux-x11 that operates on different principles. It will be a full-fledged X server, so I can add support for stylus and touchscreen. Can you please help me with testing stylus support?

**Comment by parkerlreed** [comment]
Absolutely!

**Comment by Revess** [comment]
What type of stylus are you using and di you tweak any settings to make it work? I am currently using an Samsung spen and would love for this feature to work

**Comment by parkerlreed** [comment]
Nothing as of yet. The Samsung stylus should currently just work as a mouse.

Still awaiting some instructions to help test out the support.

**Comment by Dr4kzor** [comment]
Hi I already implemented this, also added a floating button to choose the stylus input type as left,middle or right click, even when this click override is active the mouse and finger work normally :)
Also the stylus hover works and updates mouse position as well (allows to see the click preview for graphic edit apps like Aseprite and Gimp)

Pull request with added stylus support:
#358

**Comment by parkerlreed** [comment]
@Dr4kzor Thanks! Is there a way I can test this without a manual compile?

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/actions/runs/5333290836

**Comment by 5A52** [comment]
> also added a floating button to choose the stylus input type as left,middle or right click

I appreciate your work, and floating buttons is better than nothing, but they are diffucult to real use. Why not use, stylus click as left click, stylus button as right click?

**Comment by ephetic** [comment]
Another option after the stylus click and button could be volume keys.

**Comment by 5A52** [comment]
> Another option after the stylus click and button could be volume keys.

I quickly checked, [all the native styluses have a button](https://news.samsung.com/global/since-2011-looking-back-at-the-s-pens-history-of-innovation) Why you need any workaround?

**Comment by Dr4kzor** [comment]
So the work around for this is because my stylus btn doesn't work (ArrowOs Xiaomi stylus drivers don't recognise the btn click, and stylus works with Bluetooth off) this way you can use it to draw on Aseprite or Gimp and still have the option to use the left and middle click quickly, also your finger or mouse keep their original functions, so having a stylus and making it only right click for example gives your holding hand the ability to work as a mouse with left click(finger) and right click stylus.   It is not perfect, but it's better than nothing 🙂

**Comment by ephetic** [comment]
> I quickly checked, [all the native styluses have a button](https://news.samsung.com/global/since-2011-looking-back-at-the-s-pens-history-of-innovation) Why you need any workaround?

Because the buttons on skinny styli are awkward to use.  Even on my fatter Wacom Bamboo, the button is not fun to press.  On any app that supports mapping the volume keys (or dumb tablets with mappable hardware keys), I'll always take that over a gesture or on-screen button.  

I also disable non-stylus touch, FWIW, which I think is the norm for doing art.

**Comment by Dr4kzor** [comment]
I'm trying to learn how the added full stylus support on [Weylus](https://github.com/H-M-H/Weylus/tree/master) we can already detect when an event was originated by the stylus, so now we just need to know how to do input forward to the other side.

**Comment by parkerlreed** [comment]
Weylus uses the browser as a client. So might not help a lot there but could help on backend for uinput stylus injection.

**Comment by twaik** [comment]
Android applications can not read "/dev/input/*" so uinput stylus injection is pretty much useless.

**Comment by twaik** [comment]
@parkerlreed @Dr4kzor do you have linux PC with stylus support? I need output of `xinput list --long` when stylus is connected and set up.

**Comment by Dr4kzor** [comment]
So at the moment I don't, but when I installed PostmarketOS natively on my Xiaomi pad 5 pro it was working and even GPU acceleration was working (glxgears at 3000 FPS). If no one else can get this I'll wipe 😭 out my data reinstall it and report it back here,

**Comment by 5A52** [comment]
I have send a log to @twaik with native lenovo x220t and old wacom styluses  connected.

**Comment by twaik** [comment]
Merged from #358
