### ISSUE TITLE
Xwayland keep died while run turmux x11 and Xvfb

### ISSUE THREAD

**Issue by TZQPROGRAMMER** [termux/termux-x11#316]
<details>

![Screenshot_2023-05-15-15-13-46-841_com termux](https://github.com/termux/termux-x11/assets/127677180/9dd3e967-fdd2-4a29-b8c7-2f8d5c74a0e0)
</details>
<details>

![Screenshot_2023-05-15-17-46-11-544_com termux](https://github.com/termux/termux-x11/assets/127677180/091c1f2b-c000-45cc-9fac-b508cffddbf6)
</details>
how to fix xwayland keep died while run turmux x11 and Xvfb

**Comment by twaik** [comment]
![238325724-091c1f2b-c000-45cc-9fac-b508cffddbf6](https://github.com/termux/termux-x11/assets/9674930/63ac1d92-179d-4d6d-8e18-2220099605b6)

I think this error is self-explanatory.

**Comment by TZQPROGRAMMER** [comment]
![IMG_20230516_190608](https://github.com/termux/termux-x11/assets/127677180/5a78d50a-e95e-4bfb-90eb-0c12dc32954a)

**Comment by twaik** [comment]
How is netstat related to Xwayland?

**Comment by TZQPROGRAMMER** [comment]
?

**Comment by twaik** [comment]
Netstat will not show Xwayland connection. And it should not.
