### ISSUE TITLE
*It Don't Install*

### ISSUE THREAD

**Issue by PokeyManatee4** [termux/termux-x11#32]
For some reason I'm trying to install on my free tab and it did not install will send screenshot soon

**Comment by PokeyManatee4** [comment]
- [ ] 

- [[](url) ok.com]

**Comment by PokeyManatee4** [comment]
### 

> _****_

**Comment by PokeyManatee4** [comment]
Releases

**Comment by PokeyManatee4** [comment]
>

**Comment by PokeyManatee4** [comment]
`
Go`

**Comment by PokeyManatee4** [comment]
![Screenshot_20210923-060951](https://user-images.githubusercontent.com/64691261/134497368-11845778-ccf2-4886-8e87-aa32854bafd3.png)

**Comment by PokeyManatee4** [comment]
Sorry bout random typing my touchscreen is bad

**Comment by twaik** [comment]
It should be signed with the same key Termux app is signed. I am already trying to implement a workaround but it will take some time.

**Comment by PokeyManatee4** [comment]
It Is Im Downloading It Right Off THe Actions Tab

**Comment by Grimler91** [comment]
> It Is Im Downloading It Right Off THe Actions Tab

Uninstall all termux apps and then install all of them from the actions tab

**Comment by PokeyManatee4** [comment]
Y

**Comment by PokeyManatee4** [comment]
Im Using A  Android 9 Tab And It Is armhf

**Comment by PokeyManatee4** [comment]
With Data

**Comment by PokeyManatee4** [comment]
Updated Last Night

**Comment by PokeyManatee4** [comment]
Wut

**Comment by PokeyManatee4** [comment]
I See What I Did Wrong I Did Not Install The Packages The It Needs

**Comment by PokeyManatee4** [comment]
Srry Did Not Go Deep In The Readme.md

**Comment by PokeyManatee4** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/6c41f82e-9777-41bd-ba3f-aa533d8f6b74-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)*Im Dumb Sry For Wasting Your Time*

**Comment by PokeyManatee4** [comment]
> > It Is Im Downloading It Right Off THe Actions Tab
> 
> Uninstall all termux apps and then install all of them from the actions tab

I Did And It Still Dont Work

**Comment by PokeyManatee4** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/718544a4-4b26-48e5-8e88-f14f24b50766-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)__ HUH

**Comment by PokeyManatee4** [comment]
@Grimler91

**Comment by PokeyManatee4** [comment]
Wait It Worked
I Forgot That Termux Dont Uninstall Off Of Fdorid For Some Reason![bitmoji](https://sdk.bitmoji.com/render/panel/b6dbf504-c36d-498c-acf9-c7350b749221-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)
