### ISSUE TITLE
very poor xrender performance

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#322]
I'm using the latest termux-x11. I'm running xfce4 and kwin(using xrender backend). The effects used to be smooth, but now they are very laggy

https://github.com/termux/termux-x11/assets/106876912/43254662-f250-486f-87c3-82faa7fd46e2

https://github.com/termux/termux-x11/assets/106876912/a5949e8c-b7f1-486f-84e6-bc62f25030dd

**Comment by kde-yyds** [comment]
@twaik

**Comment by twaik** [comment]
No need to ping me, I am receiving this. Just do not what exactly happens and how to fix this.

**Comment by ask9027** [comment]
can check now?

**Comment by twaik** [comment]
That happened before https://github.com/termux/termux-x11/commit/49274325547cdc8b5cc0cee9520b9792c006c328 so it is not fixed.

**Comment by kde-yyds** [comment]
That's great! It's smooth again
https://github.com/termux/termux-x11/assets/106876912/e226f426-4621-434d-8f2d-20f6603173c9

**Comment by Lowertricker** [comment]
How to run kwin on termux debian? Any tutorial?
