### ISSUE TITLE
Return direct input (touchscreen) mode to settings.

### ISSUE THREAD

**Issue by tutacat** [termux/termux-x11#325]
Once it was changed, there is only mouse emulation and touchpad emulation. There used to be no emulation (forward touchscreen to x11) but no longer, it was removed. I propose that the direct (touchscreen) mode is returned to the input settings.

**Comment by twaik** [comment]
That is a screenshot from latest artifact.
<details>

![Screenshot_20230526_141934_TermuxX11](https://github.com/termux/termux-x11/assets/9674930/be76a80b-5667-4901-877f-8602abe84538)
</details>
