### ISSUE TITLE
Cant open termux-x11 without internet. Must enable internet

### ISSUE THREAD

**Issue by dafidzparkerz** [termux/termux-x11#327]
I don't know this is bug or what.
Can't open termux x11 without internet.

Termux-x11 latest
Please fix this. Before update, termux -x11 can open without internet .but now after update no

**Comment by kde-yyds** [comment]
I can also reproduce this

**Comment by ask9027** [comment]
Network is not reachable if No Internet.
<details>
<summary> Bug Report </summary>

![Screenshot_2023-05-26-17-57-07-779_com miui bugreport](https://github.com/termux/termux-x11/assets/61283438/caaa0340-d656-4edb-b782-c15fc3ac3838)

</details>

**Comment by dafidzparkerz** [comment]
Can fix it ?

**Comment by twaik** [comment]
You can not. But I will fix it soon.

**Comment by dafidzparkerz** [comment]
Thank you, I will close casse if fixed. Appreciate your work
