### ISSUE TITLE
Lack of Build tutorial or a prebuilt APK for testing

### ISSUE THREAD

**Issue by viniavila** [termux/termux-x11#33]
There is no tutorial "HOWTO" to build this app and generate an installable apk file. I tried to use Android Studio (I never built any Android app), but there were several errors. The apk was generated but not installed in my Galaxy Tab S6 (unkown sources enabled).

I'm a complete noob in Android development (though can develop desktop apps in C, C++, Python). I would like to generate the apk for this project or ask if anyone can send a built file for me. Any help would be appreciated.

**Comment by viniavila** [comment]
Nevermind. I could build Termux-app and Termux-x11 nicely. I discovered that one MUST install debug versions of BOTH programs, so this Termux-X11 built in debug mode in Android Studio doesn't mix with Termux PlayStore app... one MUST build termux-app aswell.

**Comment by agnostic-apollo** [comment]
Builds are already available at https://github.com/termux/termux-x11/actions?query=branch%3Amaster
