### ISSUE TITLE
external usb mouse middle button not working

### ISSUE THREAD

**Issue by kulturguda** [termux/termux-x11#332]
It has not worked so far. When I am pressing the middle (scroll) button on the mouse, it behaviours as a global home button and shows Android desktop immediately from Termux-X11.

**Comment by twaik** [comment]
Can you please post logcat of `com.termux.x11`? I need to check what event is received when you are sending middle click...
But please, call `adb logcat -c` before clicking to strip unneded logs...

**Comment by kulturguda** [comment]
I tried to catch the event by middle button click:

<details><summary>Details</summary>
<p>
05-28 21:05:36.080 10089 10484 I XLorieTrace: HERE int dispatch(ClientPtr) 30

-----MIDDLE KLICK-----
05-28 21:05:36.829 10089 10527 I XlorieNative: window change: 0xb400007c0e5c6010
05-28 21:05:36.831 10089 10484 D XlorieTest2: renderer_set_window 0xb400007c0e5c6010 -19 -19
05-28 21:05:36.833 10089 10484 E libEGL  : eglCreateWindowSurface: native_window_api_connect (win=0xb400007c0e5c6010) failed (0xffffffed) (already connected to another API?)
05-28 21:05:36.833 10089 10484 E libEGL  : eglCreateWindowSurfaceTmpl:708 error 3003 (EGL_BAD_ALLOC)                                            05-28 21:05:36.833 10089 10484 D gles-renderer: Xlorie: eglCreateWindowSurface failed.
05-28 21:05:36.833 10089 10484 D gles-renderer: Xlorie: egl error on line 308: Cannot allocate resources
05-28 21:05:36.833 10089 10484 D XlorieTest2: renderer_set_buffer0
05-28 21:05:36.833 10089 10484 D gles-renderer: Xlorie: egl error on line 269: EGL not initialized or failed to initialize                      05-28 21:05:36.834 10089 10484 D gles-renderer: Xlorie: egl error on line 270: EGL not initialized or failed to initialize
05-28 21:05:36.834 10089 10484 D XlorieTest2: renderer_set_buffer 1080 2184
05-28 21:05:36.834 10089 10484 D gles-renderer: Xlorie: updating cursor
</p>
</details>

**Comment by twaik** [comment]
That is not the logcat I need. I need logcat from `com.termux.x11`. Logcat of termux will not help here. 
But you can run `TERMUX_X11_DEBUG=1 termux-x11 :0` and it will print the whole log of `com.termux.x11`.

**Comment by kulturguda** [comment]
sry, I hope this is suitable:
<details><summary>middle click</summary>
<p>
05-29 08:47:53.438  9809  9809 E Xlorie-client: Sending mouse event: 437.000000 870.000000 0 0 005-29 08:47:53.553  9809  9809 D TOUCHHANDLER: EVENT false MotionEvent { action=ACTION_HOVER_MOVE, actionButton=0, id[0]=0, x[0]=437.28036, y[0]=870.6554, toolType[0]=TOOL_TYPE_MOUSE, buttonState=0, classification=NONE, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=980820, downTime=980253, deviceId=8, source=0x2002, displayId=0, eventId=309655506 }05-29 08:47:53.583  9809  9809 D VRI[MainActivity]: onFocusEvent false                          05-29 08:47:53.882  9809 16736 D VRI[MainActivity]: dispatchAppVisibility visible:false         05-29 08:47:53.886  9809  9809 I SurfaceView: 11016253 surfaceDestroyed                         05-29 08:47:53.888  9809  9809 D BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) disconnect: api -1   05-29 08:47:53.889  9809  9809 D BufferQueueConsumer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) disconnect           05-29 08:47:53.892  9809  9830 D SurfaceView: 266194799positionLost mSurfaceControl is null return;                                             05-29 08:47:53.892  9809  9830 D BufferQueueProducer: [VRI[MainActivity]#10(BLAST Consumer)10](id:26510000000a,api:1,p:9809,c:9809) disconnect: api 1                                           05-29 08:47:53.896  9809 16736 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) query: BufferQueue has been abandoned                                05-29 08:47:53.897  9809 16736 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) query: BufferQueue has been abandoned                                05-29 08:47:53.898  9809 16736 D BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) disconnect: api 1
05-29 08:47:53.900  9809 16736 E BufferQueueProducer: [SurfaceView[com.termux.x11/com.termux.x11.MainActivity]#11(BLAST Consumer)11](id:26510000000b,api:1,p:11663,c:9809) connect: BufferQueue has been abandoned                              05-29 08:47:53.906  9809  9809 D BufferQueueConsumer: [VRI[MainActivity]#10(BLAST Consumer)10](id:26510000000a,api:0,p:-1,c:9809) disconnect
05-29 08:47:53.913  9809  9809 D VRI[MainActivity]: setWindowStopped stopped:true
</p>
</details>

**Comment by twaik** [comment]
It looks like Android simply does not send middle-click event to application. Unfortunately. 
Everything I can propose you is to enable mouse capturing in preferences.

**Comment by kulturguda** [comment]
"Capture external mouse" has no effect on this. Otherwise on the newer builds neither the middle nor the right click do not work by me (right click does nothing). Now I tested again Termux and Termux-X11 side by side with debug on desktop mode (OnePlus 9 Pro):

While with left click gets `ACTION_BUTTON_PRESS` and `ACTION_BUTTON_RELEASE` recognized as `BUTTON_PRIMARY`, the middle and right click get no response from debug.
