### ISSUE TITLE
"Reseed Screen While Soft Keyboard is open" not working

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-x11#333]
Im using latest build #365. This option not working. Tried disabling and re enabling,still not working.

**Comment by ask9027** [comment]
> Im using latest build #365. This option not working. Tried disabling and re enabling,still not working.

i think you are using `full screen mode`.

**Comment by twaik** [comment]
> i think you are using `full screen mode`.

Correct. Fullscren + reseeding always was a headache.

**Comment by twaik** [comment]
Can you please check latest artifact? It seems to be fixed.

**Comment by ask9027** [comment]
> Can you please check latest artifact? It seems to be fixed.

ya , it's working now with fullscreen mode

**Comment by twaik** [comment]
Ok, so I am closing this.
