### ISSUE TITLE
Request for feature "map back to escape" (same termux)

### ISSUE THREAD

**Issue by enimatek-nl** [termux/termux-x11#338]
Termux has a very useful feature to map the Back sys call (android) to Escape ( [https://wiki.termux.com/wiki/Terminal_Settings#Handling_the_back_key](https://wiki.termux.com/wiki/Terminal_Settings#Handling_the_back_key) )

Sadly this feature does not seem to be brought into the Termux-X11 app.

Is it possible to mirror this very handy feature into Termux-X11, it will make the Xiaomi Pad 5 & 6 with key-cover (where the Esc on the hardware keyboard is recognized a Android_Back) work as expected. Maybe more tablets will benefit from this.

**Comment by twaik** [comment]
KEYCODE_BACK is already mapped to Escape. [1](https://github.com/termux/termux-x11/blob/1645740cce266a07a063d3338dba30ffd29b59c4/app/src/main/cpp/lorie/android-to-linux-keycodes.h#L15), [2](https://github.com/termux/termux-x11/blob/1645740cce266a07a063d3338dba30ffd29b59c4/app/src/main/cpp/lorie/android-to-linux-keycodes.h#L311).

**Comment by enimatek-nl** [comment]
Not sure if this is enabled by default or some tweaks are needed or only some types of keyboard are affected by these mappings.
But it's not working for me as intended.

Both Escape on hardware keyboard and Back on tablet itself (by gesture) result in a normal 'back' functionality. (nightly build from yesterday)

**Comment by twaik** [comment]
Yeah, it looks like for some reason I missed that. Fixing it now.

**Comment by enimatek-nl** [comment]
Thanks 👍 now my typecover works exactly as expected!

Small remark would be that this option is opt-in just like on termux, i'm not sure if other workflows are impacted negatively by this change.
For me this is great, the Pad 5 (and new 6) are complete functional small linux laptop replacements with this change 😁

**Comment by twaik** [comment]
> Small remark would be that this option is opt-in just like on termux

Escape key has no other functionality in `termux-x11`. Ignoring escape key was a bug.
