### ISSUE TITLE
feature request: stay awake and turn screen off while connecting to external monitor

### ISSUE THREAD

**Issue by thiled** [termux/termux-x11#339]
Termux-x11 works great  as a display service. When the phone is connected to an external monitor, turning off the screen can save power and solve the problem of the screen overheating. Keeping the phone unlocked avoids the frequent unlocking problem. I wonder if two options could be added: allowing the screen to be turned off when an external monitor is connected, and keeping the phone awake.

**Comment by twaik** [comment]
Unfortunately Android API does not allow turning screen off without locking it.

**Comment by ask9027** [comment]
> Termux-x11 works great as a display service. When the phone is connected to an external monitor, turning off the screen can save power and solve the problem of the screen overheating. Keeping the phone unlocked avoids the frequent unlocking problem. I wonder if two options could be added: allowing the screen to be turned off when an external monitor is connected, and keeping the phone awake.

if your device screen overheat , just set display brightness to low.
