### ISSUE TITLE
Debian Gnome not work in termux-x11

### ISSUE THREAD

**Issue by binhvo7794** [termux/termux-x11#340]
I try start gnome on termux-x11 but not working, here is output!
<details><summary>Details</summary>

```
(gnome-shell:11627): libupower-glib-WARNING **: 17:44:45.025: Couldn't connect to proxy: Could not connect: Connection refused

(gnome-shell:11627): libupower-glib-WARNING **: 17:44:45.027: Couldn't connect to proxy: Could not connect: Connection refused

(gnome-shell:11627): GLib-GObject-WARNING **: 17:44:45.028: invalid (NULL) pointer instance

(gnome-shell:11627): GLib-GObject-CRITICAL **: 17:44:45.029: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
Xlib:  extension "DPMS" missing on display ":0".
Xlib:  extension "DPMS" missing on display ":0".

(gnome-shell:11627): Gjs-WARNING **: 17:44:47.966: JS ERROR: Gio.IOErrorEnum: Could not connect: Connection refused
get system@resource:///org/gnome/gjs/modules/overrides/Gio.js:354:20
_init@resource:///org/gnome/shell/ui/status/power.js:49:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_init@resource:///org/gnome/shell/ui/panel.js:712:23
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_ensureIndicator@resource:///org/gnome/shell/ui/panel.js:1126:25
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_updateBox@resource:///org/gnome/shell/ui/panel.js:1137:29
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_updatePanel@resource:///org/gnome/shell/ui/panel.js:1047:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@resource:///org/gnome/shell/ui/panel.js:824:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_Base.prototype._construct@resource:///org/gnome/gjs/modules/_legacy.js:18:5
Class.prototype._construct/newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_initializeUI@resource:///org/gnome/shell/ui/main.js:184:13
start@resource:///org/gnome/shell/ui/main.js:133:5
@<main>:1:31

** Message: 17:44:47.967: Execution of main.js threw exception: Script <main> threw an exception

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.001: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.001: The offending signal was destroy on StBoxLayout 0x300173ea30.
== Stack trace for context 0x3000475320 ==

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.002: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.002: The offending signal was destroy on StBoxLayout 0x30017308b0.
== Stack trace for context 0x3000475320 ==

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.003: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.

(gnome-shell:11627): Gjs-CRITICAL **: 17:44:48.003: The offending signal was destroy on StBoxLayout 0x3001736170.
== Stack trace for context 0x3000475320 ==

```
</details> 

But it works on vncserver! I already shared termux tmp!
![Screenshot_20230606-174606_RVNC Viewer](https://github.com/termux/termux-x11/assets/66165345/8e7023af-5297-4b06-801c-6a8abbd2c162)
![Screenshot_20230606-174641_RVNC Viewer](https://github.com/termux/termux-x11/assets/66165345/d5fabcf0-d8d1-49ad-89e0-ba49667e6437)

**Comment by twaik** [comment]
Did you try `termux-x11 -extension MIT-SHM :0`?

**Comment by binhvo7794** [comment]
> Did you try `termux-x11 -extension MIT-SHM :0`?

Still same errors

**Comment by twaik** [comment]
I am not sure what exactly is wrong here, logs are not so informative. Can not fix it.

**Comment by binhvo7794** [comment]
https://github.com/termux/termux-x11/assets/66165345/5396d69d-7d0e-4d0a-a751-e5a12a35d3cf

**Comment by twaik** [comment]
Still not informative. Video will not help here.

**Comment by ask9027** [comment]
> screen-20230606-221822.mp4

how you install gnome in ubuntu in proot-distro(just want)?

**Comment by Saikatsaha1996** [comment]
> 

In my device perfectly working..

Try to login with 

```
proot-distro login debian --bind /dev/null:/dev/dri/card0 --shared-tmp --bind /sdcard:/sdcard --bind /dev/null:/proc/sys/kernel/cap_last_cap
```
But 

Just remove pid file..

Create a file like this..

nano /usr/bin/desktop

```
#!/bin/sh
export XDG_CURRENT_DESKTOP="GNOME"
export XDG_RUNTIME_DIR=/tmp
sudo service dbus start
gnome-shell --x11
```

chmod +x /usr/bin/desktop


creat a xstartup

mkdir .vnc
nano .vnc/xstartup

```
#!/bin/sh
/usr/bin/desktop
```


Then exit from proot the start termux-x11 open termux-x11 u will see black screen with x cursor.. go to preference enable pip mode.. 

Then re-login proot & run

`desktop`

I am sure in your device not working because you mey not mentioned session name or runtime dir


![Screenshot_2023-06-07-15-05-11-01_00df01c412509efb9bd6450c382822af](https://github.com/termux/termux-x11/assets/72664192/28db848d-c306-4564-a49f-6bb9b2296d47)

**Comment by binhvo7794** [comment]
> > 
> 
> In my device debian perfectly working .. My bad luck jammy not working..
> 
> Try to login with
> 
> ```
> proot-distro login debian --bind /dev/null:/dev/dri/card0 --shared-tmp --bind /sdcard:/sdcard --bind /dev/null:/proc/sys/kernel/cap_last_cap
> ```
> 
> But
> 
> Just remove pid file..
> 
> Create a file like this..
> 
> nano /usr/bin/desktop
> 
> ```
> #!/bin/sh
> export XDG_CURRENT_DESKTOP="GNOME"
> export XDG_RUNTIME_DIR=/tmp
> sudo service dbus start
> gnome-shell --x11
> ```
> 
> chmod +x /usr/bin/desktop
> 
> creat a xstartup
> 
> mkdir .vnc nano .vnc/xstartup
> 
> ```
> #!/bin/sh
> /usr/bin/desktop
> ```
> 
> Then exit from proot the start termux-x11 open termux-x11 u will see black screen with x cursor.. go to preference enable pip mode..
> 
> Then re-login proot & run
> 
> `desktop`
> 
> If you login as user use `sudo desktop`
> 
> I am sure in your device not working because you mey not mentioned session name or runtime dir
> 
> ![Screenshot_2023-06-07-15-05-11-01_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/72664192/244003058-28db848d-c306-4564-a49f-6bb9b2296d47.jpg)

https://github.com/termux/termux-x11/assets/66165345/de4dabab-e231-4bdb-afdd-22a2587cc8c2



Thank you, now it worked but it so lagging and can't open any application

**Comment by Saikatsaha1996** [comment]
@twaik remove bug level.. it is not bug..

**Comment by binhvo7794** [comment]
> > 
> 
> Add one more line
> 
> nano /usr/bin/desktop
> 
> ```
> #!/bin/sh
> export GALLIUM_DRIVER=llvmpipe
> export XDG_CURRENT_DESKTOP="GNOME"
> export XDG_RUNTIME_DIR=/tmp
> sudo service dbus start
> gnome-shell --x11
> ```

Not works sir
![Screenshot_20230607-185214_Termux](https://github.com/termux/termux-x11/assets/66165345/b5b8597b-8f82-4430-8bcd-44b7b8af8181)

**Comment by twaik** [comment]
> it so lagging and can't open any application

It is likely not a problem of termux-x11. Besides the methods used to display an image on Android screen, Termux-X11 is a fairly standard X server. The problem is something else.

> remove bug level.. it is not bug..

It was a bug until we knew that it can work with some special parameters...

**Comment by Saikatsaha1996** [comment]
> > > 
> > 
> > 
> > Add one more line
> > nano /usr/bin/desktop
> > ```
> > #!/bin/sh
> > export GALLIUM_DRIVER=llvmpipe
> > export XDG_CURRENT_DESKTOP="GNOME"
> > export XDG_RUNTIME_DIR=/tmp
> > sudo service dbus start
> > gnome-shell --x11
> > ```
> 
> Not works sir ![Screenshot_20230607-185214_Termux](https://user-images.githubusercontent.com/66165345/244048641-b5b8597b-8f82-4430-8bcd-44b7b8af8181.png)

Okay remove `export GALLIUM_DRIVER=llvmpipe`

And add it to .bashrc

Then check.. i hope it will work..

Don't expect better performance with 4 GB Ram ..

**Comment by calvinweb** [comment]
> > > 
> > 
> > 
> > Add one more line
> > nano /usr/bin/desktop
> > ```
> > #!/bin/sh
> > export GALLIUM_DRIVER=llvmpipe
> > export XDG_CURRENT_DESKTOP="GNOME"
> > export XDG_RUNTIME_DIR=/tmp
> > sudo service dbus start
> > gnome-shell --x11
> > ```
> 
> Here is my log, pls see what wrong 🥹, but why u get it work perfectly, can u share what u do?
> Details

I found a way to deal with it just delete the file `/usr/share/dbus-1/system-services/org.freedesktop.login1.service` and it will run
