### ISSUE TITLE
Special keys view doesn't attach on top of the soft keyboard when "Reseed Screen While Soft Keyboard is open" option is off 

### ISSUE THREAD

**Issue by mynameisjuliano** [termux/termux-x11#341]
I think it could be fixed if the special keys view is like attached below the SurfaceView of the server—as in a LinearLayout. If done so, it will also make the special keys view stop blocking the bottom portion of the screen, which can be unfortunate if you're a window manager + tui program user like me, because the main apps that I use has info in that portion (such as nvim and calcurse).

**Comment by twaik** [comment]
You can toggle extra keys bar with swipe down with three fingers or with Volume down key (must enable it in preferences).
