### ISSUE TITLE
Prevent 16:9 display from being stretched

### ISSUE THREAD

**Issue by xDoge26** [termux/termux-x11#345]
Display resolution : 1280x720 but it fill the entire screen instead  

immersive mode enabled 
hide display cutout enabled 

![Screenshot_2023-06-10-23-56-46-913_com termux x11](https://github.com/termux/termux-x11/assets/92904701/0e7c9e6c-82c0-47bf-8bcc-8c0b9719b6bc)

**Comment by twaik** [comment]
Not planned.

**Comment by twaik** [comment]
Fixed by https://github.com/termux/termux-x11/commit/757121b038e4522ff6f18c4ef95946ef580712bf
