### ISSUE TITLE
Termux X11 Black Screen Exagear

### ISSUE THREAD

**Issue by SwedMlite** [termux/termux-x11#346]
Android : 12 .  Device : Xiaomi Redmi Note 8
I wanted to install Termux X11 for Exagear but got a black screen with a cursor. I did everything as in the [video instruction ](https://youtu.be/HIAMSBrZGP4)  on YouTube, but nothing happened.
<details> 

![Screenshot_20230611-143526_Termux](https://github.com/termux/termux-x11/assets/111647816/d9a5bd91-c4df-471c-b3cd-925da8f31c1f)
</details>
<details>

![Screenshot_20230611-143530_Termux_X11](https://github.com/termux/termux-x11/assets/111647816/0069a580-0909-47b6-9547-c5272c67e5a7)
</details>
I also once tried [Box4Droid by Herick75](https://github.com/Herick75/Box4Droid)  , and there was also a black screen with a cursor.
Help me, please

**Comment by twaik** [comment]
Xvfb-based builds are deprecated. Latest builds have builtin X server. Read README.MD.
