### ISSUE TITLE
Copy past from Android to termux-x11

### ISSUE THREAD

**Issue by Revess** [termux/termux-x11#347]
Currently it is not possible to paste anything from the clipboard of android to any application running in termux-x11 (tested in proot).

**Comment by twaik** [comment]
Android block background clipboard access so it is not possible to get clipboard change notification when app is not focused.
But it is pissible to paste text using text input. To access it you should swipe extra keys bar to the left.

**Comment by risharem** [comment]
I've been able to do copy/paste from/to Android using VNC. Sometimes it needs autocutsel. Is AVNC any different than termux-x11 in the way they listen for Android clipboard?

**Comment by twaik** [comment]
Maybe it is relevant for old Androids, but starting from Android 10 listening to Android Clipboard is restricted

**Comment by Blocked** [comment]
@twaik Do we even need background clipboard access? When the X11 is brought to foreground  and when a special key combination like <kbd>CTRL</kbd><kbd>SHIFT</kbd><kbd>ALT</kbd><kbd>V</kbd> is pressed, Is it possible to enable force clipboard syncing from android to termux x11?

**Comment by Blocked** [comment]
@twaik Ok for some reason, <kbd>PASTE</kbd> doesn't work when clicking with a mouse, but it works when touching with finger. 

Even swiping extra keys to left, entering data and pressing enter doesn't send input data to x11. I'm testing this on firefox/x11 URL input, search input and text input in GitHub issues.

Currently I'm using a complex workaround in termux app using

```
echo "Clipboard Data to x11" | xclip -sel clipboard
```

Just `xclip` to ``PRIMARY`` clipboard doesn't work. You have to use ``xclip -sel clipboard``

**Comment by customautosys** [comment]
Hi I don't understand, how do I use this "paste" key? It doesn't seem to appear on any soft keyboards

**Comment by JeremyViehland** [comment]
![Screenshot_20240306-050129_Termux](https://github.com/termux/termux-x11/assets/13064800/70a94413-985f-4307-889f-ef3bfea6d41f)


![Screenshot_20240306-050605_Termux_X11](https://github.com/termux/termux-x11/assets/13064800/0fde70e0-b67e-4e24-a3cf-3f02cd2618b0)

**Comment by JeremyViehland** [comment]
![Screenshot_20240306-050129_Termux](https://github.com/termux/termux-x11/assets/13064800/48b3c646-2014-445f-a88f-4de91fdf0ed7)
![Screenshot_20240306-050605_Termux_X11](https://github.com/termux/termux-x11/assets/13064800/362d6de9-0805-4719-a797-36c8f2881615)
![Screenshot_20240306-051449_Termux](https://github.com/termux/termux-x11/assets/13064800/12de09d0-e2eb-4123-b6f6-6b38a24563c5)

**Comment by twaik** [comment]
@JeremyViehland sorry, deleted your message by mistake

**Comment by JeremyViehland** [comment]
@twaik No problem, was still editing.
Hopefully the screen shots help eliminate the workaround.

**Comment by twaik** [comment]
Check the https://github.com/termux/termux-x11/actions/runs/8281260198 artifact.
