### ISSUE TITLE
Input not working 

### ISSUE THREAD

**Issue by xDoge26** [termux/termux-x11#349]
```
root@localhost:~# (EE) BUG: triggered 'if (!iclients)'
(EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/Xi/exevents.c:1392 in RetrieveTouchDeliveryData()
(EE) BUG: triggered 'if (!iclients)'
(EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/Xi/exevents.c:1392 in RetrieveTouchDeliveryData()
(EE) BUG: triggered 'if (!iclients)'
(EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/Xi/exevents.c:1392 in RetrieveTouchDeliveryData()
(EE) BUG: triggered 'if (!iclients)'
(EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/Xi/exevents.c:1392 in RetrieveTouchDeliveryData()
(EE) BUG: triggered 'if (!iclients)'                       (EE) BUG: /home/runner/work/termux-x11/termux-x11/app/src/main/cpp/xserver/Xi/exevents.c:1392 in RetrieveTouchDeliveryData()

```

**Comment by twaik** [comment]
I can not reproduce it. How did you get this?

**Comment by twaik** [comment]
Wine itself will not trigger error like this. Can you reproduce the error and tell me what exactly is needed to get this?

**Comment by twaik** [comment]
Again. Wine itself will not produce input-related bug. Can you reproduce this?

**Comment by twaik** [comment]
Are you using touchscreen touch mode? Or something simillar?

**Comment by twaik** [comment]
Again. 
Are you using touchscreen touch mode? Or something simillar?

**Comment by twaik** [comment]
I can write some extra code with checks for this but I must know what exactly happens. I need at least log with `TERMUX_X11_DEBUG=1` enabled.

**Comment by twaik** [comment]
There are no lines like this (`(EE) BUG: triggered 'if (!iclients)'`).

**Comment by twaik** [comment]
Everything seems to be file, I simply do not get why it happens...

**Comment by twaik** [comment]
Can you reproduce this on the latest build?

**Comment by twaik** [comment]
> Still doesnt work with `x` and `z`

It seems to be a different issue, not related to the current one. Maybe that is a bug in the wine itself. 

Does touchscreen input work now?
