### ISSUE TITLE
Now I'm Getting Errors

### ISSUE THREAD

**Issue by PokeyManatee4** [termux/termux-x11#35]

**Comment by PokeyManatee4** [comment]
![Screenshot_20210924-154518](https://user-images.githubusercontent.com/64691261/134737738-c118971a-84de-4a8d-ab62-963cdcaf8ee3.png)

**Comment by PokeyManatee4** [comment]
What Do I Do?![bitmoji](https://sdk.bitmoji.com/render/panel/718544a4-4b26-48e5-8e88-f14f24b50766-11611bb8-08a0-4a48-a006-f38848586588-v1.png?transparent=1&palette=1&width=246)

**Comment by PokeyManatee4** [comment]
How Do I Use This Thing @everyone?

**Comment by WMCB-Tech** [comment]
You may need to completely read the README

tldr:
* Open Termux:X11 and a toast message `service was created` must be shown
* Open Termux and run commands
```
export XDG_RUNTIME_DIR=$TMPDIR
Xwayland -ac :1 >/dev/null &
env DISPLAY=:1 startxfce4
```
replace `startxfce4` if you don't use xfce
* Go back to Termux:X11 and Xfce or whatever window manager won't start

> @everyone
You thought this is discord 😂
You can even ask that guy to help you

**Comment by PokeyManatee4** [comment]
I did

**Comment by PokeyManatee4** [comment]
And I started termux x11 before opening termux and Im using defaults that are gave

**Comment by PokeyManatee4** [comment]
And the Toast Popped Up
