### ISSUE TITLE
chromium touchscreen selection not working

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#350]
https://github.com/termux/termux-x11/assets/106876912/ab1bd7fe-9a22-4ea5-9994-0513acc8749a

**Comment by kde-yyds** [comment]
so maybe it's still an issue of termux-x11's touchscreen direct input

**Comment by kde-yyds** [comment]
![Screenshot_20230615_214224_com.termux.x11.jpg](https://github.com/termux/termux-x11/assets/106876912/fdc768ff-b9de-474c-8393-4101aacfe422)
It's strange that this feature in qtwebengine works fine.https://github.com/termux/termux-x11/assets/106876912/80968465-6d0d-48eb-98d3-28487ffe7ff6

**Comment by mio-19** [comment]
> so maybe it's still an issue of termux-x11's touchscreen direct input

I encountered the same issue.

**Comment by mio-19** [comment]
Is there some tool to record mouse/touch events?
I want to compare termux-x11 direct input and a touchscreen on a linux device.

**Comment by RalfWerner** [comment]
> I want to compare termux-X11 direct input and a touchscreen on a **linux device.**

@mio-19 mouse and touch events are different. The mouse is independent of the touchMode of X11, while Direct mode with fingers triggers the Touch-Screen Generic Events. A recording can be switched on via the Dev options of the Android settings. Here is a video of how to do it with a four finger _tap-move-release_ gesture.

https://github.com/termux/termux-x11/assets/45426380/378480ba-9034-4f14-a360-8a5848cc92fb

To represent this by Termux-X11 (XServer), you need an XClient that can process these generic events. That could look [so](https://github.com/termux/termux-x11/assets/45426380/333595c3-d890-49ef-997f-b8e4f7686918). You've a touchscreen on **your linux device** and obviously an XClient for comparison there. If you can install it in Termux, I would also be interested in it.

**Comment by twaik** [comment]
Fixed by ba540180e2a72b6b610e7007872fa95a1492b235.

**Comment by twaik** [comment]
Seems like it is an upstream bug. Reproducible with libinput + Xorg + dummy.
