### ISSUE TITLE
termux-x11-nightly package version on x11-repo

### ISSUE THREAD

**Issue by abhishek-raj** [termux/termux-x11#352]
I wanted to ask how the termux-x11-nightly in the x11-repo is updated from this git repo.

I might be wrong but there seems so many updates to this package in the last few days but the package(termux-x11-nightly) version is same since the first version published to termux-packages repo.

It might be that only the apk code is changed so just updating the apk should be enough. If this is the case then please close this issue.

If code which is changed is in the termux-x11-nightly package too then maybe we can put some kind of process/automation to publish this to the termux-packages too. I am entirely new to termux code(though have been using termux for sometime now) and how the package distribution works here so please feel free to close this issue if not relevant.

If I can help in anyway in publishing this to termux-packages, please let me know. It is so much easier to just do pkg upgrade and this automatically updates to latest version.

Anyway, awesome work and the new version is so much faster and smoother :D

**Comment by twaik** [comment]
Binary present in companion package is a simple loader, it is universal. It should be updated only if loader ABI is changed.
