### ISSUE TITLE
glxgears black screen in Ubuntu proot-distro on Android 8.1

### ISSUE THREAD

**Issue by nerdydumbykier** [termux/termux-x11#359]
Hi, I wanted to try `termux-x11` out on Android 8.1 and I am using Ubuntu proot-distro to run `glxgears`. The problem is it doesn't show up. I have used these commands:
 `termux-x11 -extension MIT-SHM :1 &` in Termux and `DISPLAY=:1 glxgears` in Ubuntu proot-distro.

I am using a Snapdragon 439 (Adreno™ 505) if you need.

**Comment by twaik** [comment]
Llvmpipe's GLX can not worg without MIT-SHM extension. If you really need it start termux-x11 inside proot-distro in non-isolated mode.
```
termux-x11 :0 -xstartup glxgears
```
