### ISSUE TITLE
How Do I Use?

### ISSUE THREAD

**Issue by PokeyManatee4** [termux/termux-x11#36]

**Comment by suhan-paradkar** [comment]
Check https://github.com/termux/termux-x11#setup-instructions on how to setup the app and use it to run GUI applications

**Comment by PokeyManatee4** [comment]
But It Don't Work

**Comment by RalfWerner** [comment]
Shrine your phone. Maybe it works better then. If not **Describe your error** and your device.

**Comment by PokeyManatee4** [comment]
Srry It Was Me Being A Dumb Asshat

**Comment by PokeyManatee4** [comment]
> Scream your phone. Maybe it works better then. If not **Describe your error** and your device.

I forgot the de
