### ISSUE TITLE
Won't even connect any longer

### ISSUE THREAD

**Issue by Markeo220** [termux/termux-x11#360]
Originally following the online tutorial I was able to form a connection.  But it no longer will no matter what I try, the Termux:X11 app seeming to completely ignore everything that I even attempt lately.  The "abort" occurs in the second photo after a couple of seconds as soon as I press return again.  But nothing ever changes now on the screen of the Termux:X11 app. I've traced through the startxcfe4 script and then the script xinitrc that it calls, and each time it is failing to form a connection to the display :0 at the moment it calls the command "xrdb -merge -" within the script. So I have no idea why it is no longer working even though it originally had a little over a month ago for me, at least as far as forming a successful connection had gone and showing the resulting screen. On my phone it helps me at first to use the split-screen option with the Termux:X11 app as the first app selected in the top half, my then adding in the Termux app on the bottom half. I've got both Apps "Locked" in the Recent-Apps drawer, and both allow Background activity, and I've set my phantom Apps limit to the highest value possible, representing infinity basically, as per instructions on the Internet.  So all of those things are squared away and this had previously been able to at least form connections, with it in fact doing so much more easily originally than I was able to using the VNC Viewer App configuration. I can still do so with the VNC Viewer App configuration even right now, so there must be something that has changed in the Termux:X11 app that is no longer allowing the connections to form.  So any help would be greatly appreciated, otherwise I'll have to abandon trying to use the Termux:X11 app any further.  And yes I have been following EXACTLY all of the instructions written within the website tutorial for using it.  Thanks.

<details>

![Screenshot_2023-06-23-15-07-06-03_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/130519771/22494796-f11d-462e-8646-a780aebf6e14)
</details>
<details>

![Screenshot_2023-06-23-15-06-38-78_00df01c412509efb9bd6450c382822af](https://github.com/termux/termux-x11/assets/130519771/13dd8b73-0ad4-4007-be64-d54e81db35e7)
</details>

**Comment by twaik** [comment]
Can you start `termux-x11` with `TERMUX_X11_DEBUG=1`?

**Comment by Markeo220** [comment]
Whether I click on the upper Termux:X11 screen area or just stay inside the Termux window it just always holds for about 3 seconds and then the "Aborted" message pops up in the Termux window as shown each time. Will using that debug variable like you suggested and I just tried put extra information inside of a log file?
![Screenshot_2023-06-24-00-28-09-44_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/130519771/6a2601ad-25dd-4853-81dd-2bd37876d652)

**Comment by twaik** [comment]
Can you try to launch termux's logcat after seeing `Aborted` message?

**Comment by Markeo220** [comment]
Whether I click on the upper Termux:X11 screen area or just stay inside the Termux window it just always holds for about 3 seconds and then the "Aborted" message pops up in the Termux window as shown each time. Will using that debug variable like you suggested and I just tried put extra information inside of a log file?
![Uploading Screenshot_2023-06-24-00-28-09-44_84d3000e3f4017145260f7618db1d683.jpg…]()

**Comment by twaik** [comment]
Screenshot was not uploaded.

**Comment by twaik** [comment]
I need to see what `logcat` prints after unsuccessful start. Screenshots will not be helpful, redirect logcat's output to text file.

**Comment by Markeo220** [comment]
![Screenshot_2023-06-24-01-47-03-91_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/130519771/e742859e-184c-4ac7-be90-8f48b3f18d86)

**Comment by twaik** [comment]
I told you, screenshots are not helpful. Post logcat's log here as a text file...

**Comment by Markeo220** [comment]
You didn't say screenshots were not helpful. And in that screenshot I was showing the size of the captured file if you look closer at it. I was about to ask you if there's a special way to post large text files here. But if you want me to post it as a comment I'll do that in the next comment here.

**Comment by twaik** [comment]
It is only 185 kilobytes so it will be fine to post it here. Post it as a file, not as text.

**Comment by Markeo220** [comment]
Honestly, I've never done that before and I can't find an icon that allows me to post it as a file, and it doesn't offer me any way to copy it to the clipboard otherwise so you need to help me figure that out how to post it as a file please.

**Comment by twaik** [comment]
https://wiki.termux.com/wiki/Internal_and_external_storage, paragraph "Access Termux from a file manager".

**Comment by twaik** [comment]
<details>

![image](https://github.com/termux/termux-x11/assets/9674930/2fbdd1ce-14c6-4725-8bf7-579676e67e6e)
</details>

**Comment by Markeo220** [comment]
I do have a file manager app that allows me to access the termux files directly, but when I select to share it, there's no option to copy it to the clipboard. But it sounds like you don't want me to do that anyway, so I'm at a loss to know what I'm supposed to do. Because my problem isn't that I can access the file, so I don't know how to post it to your website here and GitHub which I'm not experienced at using. So that might take it a bit of more help than I have time for right now because I actually have to get to bed and was about to I didn't expect all of these quick replies. LOL. But I appreciate it to help and I'll check back tomorrow on this to see if you hopefully can help me to know how to post files to github here. Thanks, and have a great night, and I appreciate all the help.  :-)

**Comment by twaik** [comment]
Just copy this file to some place where you can pick it with github's file picker.

**Comment by Markeo220** [comment]
Yeah, I thought about what my problem was as I was getting ready for bed, the fact that I've only ever assumed that those photo icon upload things were for photos only, then I remembered it said attachment which could be anything; so I finally figured it out. I'm just new to uploading anything other than images. Sorry, and good night then. I'll check back later Saturday afternoon. I think it just uploaded the file here, with it first having said it was uploading and then it asked for a comment which I'm putting here now.  :-)

**Comment by twaik** [comment]
/

**Comment by Markeo220** [comment]
I definitely selected it and it said it's uploading it pretty quickly but I don't see it here, do you?

**Comment by twaik** [comment]
<details>

![photo_2023-06-24_13-43-23](https://github.com/termux/termux-x11/assets/9674930/432f018f-2a78-447b-a162-1fbac24438bc)
</details>

**Comment by twaik** [comment]
I do not see it here too.

**Comment by Markeo220** [comment]
I gave it a DOT out in extension instead of a txt extension. Could that be keeping it from uploading?

**Comment by twaik** [comment]
Github does not support DOT extension. 

![image](https://github.com/termux/termux-x11/assets/9674930/8c3897d9-ecb4-41ce-8cf1-c84741b435bd)

**Comment by Markeo220** [comment]
Yeah I didn't have .dot extension but rather a .out extension. That was stupid Google voice typing that had changed it after it had looked correct beforehand. But it probably wants to dot text so I've got that renamed as a DOT txt file now, and I'll try posting it again and then I'm off to sleep so good night and thank you. :-)

**Comment by Markeo220** [comment]
[logcat_out.txt](https://github.com/termux/termux-x11/files/11856514/logcat_out.txt)

**Comment by Markeo220** [comment]
YAY!!!

**Comment by twaik** [comment]
```
06-24 01:43:10.479  7436  7436 W System  : ClassLoader referenced unknown path: /data/data/com.termux/files/usr/libexec/termux-x11/loader.apk
06-24 01:43:10.483  7436  7436 E appproc : ERROR: could not find class 'com.termux.x11.Loader'
06-24 01:43:10.483  7436  7436 F app_process: thread.cc:2477] No pending exception expected: java.lang.ClassNotFoundException: com.termux.x11.Loader
```

How did you install `termux-x11` in termux?

**Comment by Markeo220** [comment]
My eyes are sore and I'm actually rather tired still, I didn't end up getting enough sleep last night unfortunately.  But I'll still work on this at various times tonight although I'll only have a few hours before I'll need to for sure stop earlier this time.  I'm always on the tightest of schedules for sleep, unfortunately.  I see your new question up there, however, and I may not answer this correctly because I don't always know what I'm doing (lol), but I'll try.  I assume that by "termux-x11 in termux" you might mean the special initial installation done via the "dpkg" command?  I had followed the directions at the time on the Tutorial website in detail back then, although it was likely a couple of months ago when I'd done that part of it.  Lately, however, the "Latest" Workflow downloads that I've installed the Termux:X11 App from for my Arm type Android system haven't had any of those other files in them, so all that I've been doing is simply updating this App lately via these Workflow downloads, with my having been the same person who had mentioned a while ago about the "Preferences" crashing the app, by the way, which I shortly thereafter noticed had now been fixed.  So, being that I don't FULLY know what I'm doing in this situation regarding this app and Termux, there's of course a chance that I fail to understand something correctly and might have therefore messed up somehow.  Is that where the evidence from the logcat file seems to be pointing then?  If so, I assure you it's just out of ignorance being that all of this Github stuff is fully new to me, my never having even heard of it in my earlier career.  In fact, this Termux:X11 app is what has been teaching me about it, before of which I hadn't known hardly anything about how Github is setup on the Internet and how to navigate around in it and such.  Anyway, just let me know what to do or try next.  Thanks.  :)

**Comment by twaik** [comment]
`apt purge termux-x11; apt install --reinstall termux-x11-nightly`

**Comment by Markeo220** [comment]
That was it!  :)  Obviously I was missing your nightly stuff.  Did I miss that from the tutorial?  Does it say to do what you just had me do every time that we accept a new latest Workflow download?  If so then I obviously didn't realize it in which case I'm sorry.  But thank you and therefore it obviously is back on track again now, having solved the no-communication issue!  Except...what are those warnings?  Are those anything to be concerned about (see coming screenshot below).

**Comment by Markeo220** [comment]
![Screenshot_2023-06-24-22-51-24-18_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/130519771/c7f096de-2330-4632-a507-1d056d59f820)

**Comment by Markeo220** [comment]
![Screenshot_2023-06-24-23-02-42-51_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/130519771/da1d9de2-12ac-4c18-8716-a5b91a78a523)

**Comment by Markeo220** [comment]
I can likely find time to work further with this tomorrow afternoon/evening, but I really need to make myself stop and go to bed now.  So I appreciate the solution and I've noted it so I'll always do it from now on whenever I accept an update from the project.  Take care, and have a great night.  :)

**Comment by RalfWerner** [comment]
![grafik](https://github.com/termux/termux-x11/assets/45426380/3cac4513-ad28-42f4-ba9a-f68f3560b38c)
In the past, the `*.deb` file was used to create the termux-x11 script that is also in readme (above) in the latest artifacts, this file is no longer included, instead the command of @twaik above.

**Comment by twaik** [comment]
> Except...what are those warnings?

Nothing to worry about, they are harmless...

> In the past, the `*.deb` file was used to create the termux-x11 script that is also in readme (above) in the latest artifacts, this file is no longer included, instead the command of @twaik above.

It is still included, artifact is called `termux-companion packages`

**Comment by twaik** [comment]
> So I appreciate the solution and I've noted it so I'll always do it from now

**Comment by Markeo220** [comment]
Thank you. :-)

**Comment by Markeo220** [comment]
Thank you, and I greatly appreciate your help in having gotten me
straightened out on the update procedures along with my now having a
working Xfc4 screen!  :)
