### ISSUE TITLE
integrate virglrenderer that use android native surface

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#363]
Currently we have virglrenderer-android which uses egl surfaceless rendering, but glReadPixels is quite slow. Is it possible to integrate a virglrenderer that creates an ANativeWindow and render directly to it

**Comment by twaik** [comment]
Pull requests are always welcome.

**Comment by kde-yyds** [comment]
hi, i found app/src/main/cpp/virglrenderer/
is it used? what is it used for?

**Comment by twaik** [comment]
It is legacy code which was used in another project.
