### ISSUE TITLE
shared pixmap not supported

### ISSUE THREAD

**Issue by xMeM** [termux/termux-x11#364]
Use the following code to query the shared pixmap support status. In previous versions, it outputs enable, but in the latest version, it outputs disable.
```c++
   auto shm_cookie = xcb_shm_query_version_unchecked(connection);
   auto shm_reply = xcb_shm_query_version_reply(connection, shm_cookie, nullptr);
   if (shm_reply == nullptr ||
       (shm_reply->major_version != 1 || shm_reply->minor_version < 2 || shm_reply->shared_pixmaps == false))
   {
      free(shm_reply);
      has_shm = false;
      std::cout << "disabled." << std::endl;
   }
   else
   {
      has_shm = true;
      std::cout << "enabled." << std::endl;
   }
``` 
The last version that outputs enable is this [one](https://github.com/termux/termux-x11/actions/runs/5178405378) .

Is this code correct? If it is incorrect, how can I correctly query the support of shared pixmap?

**Comment by twaik** [comment]
X server reports shm support only for for Unix connections. In the case of TCP connection it always reports no MIT-SHM support.

**Comment by twaik** [comment]
Anyway, you are likely doing something wrong. I am checking every version with termux's glxgears (llvmpipe and virpipe). It requires MIT-SHM support.

**Comment by xMeM** [comment]
> 无论如何，你可能做错了什么。我正在使用termux的glxgears（llvmpipe和virpipe）检查每个版本。它需要MIT-SHM的支持。

I used vulkan-loader-generic to load the native Qualcomm vulkan driver in termux, and then tried to use vulkan-wsi-layer. Finally, I successfully ran vkcube and vkmark on my OnePlus11 device, but after I updated termux:x11 version, shared pixmap creation failed.

This is all the code I use, some of which is copied from mesa and termux-gfx-wrapper. Maybe you can help me check it.
 [sysvk](https://github.com/xMeM/sysvk) 
[vulkan-wsi-layer](https://github.com/xMeM/vulkan-wsi-layer)

**Comment by twaik** [comment]
Yeah, you are right. It happens because I initialized root window with offscreen pixmap. Fixing this now.

**Comment by twaik** [comment]
Build is finished. Can you please check this?

**Comment by xMeM** [comment]
> 构建已完成。你能检查一下吗？

Okay, it’s fixed now
![IMG_20230628_21271511](https://github.com/termux/termux-x11/assets/12376597/52ed0000-de1a-4b74-a68f-d2d9733970b5)
