### ISSUE TITLE
how to debug termux-x11

### ISSUE THREAD

**Issue by yangguosdxl** [termux/termux-x11#366]
I had build termux-x11.apk and shell-loader.apk, I copy my shell-loader.apk to /data/data/com.termux/files/usr/libexec/termux-x11/loader.apk and use termux-x11 script launch it. then I use Android Studio for attach the loader, but Android Studio can not find the process, I had connect my pad by usb debug.
![image](https://github.com/termux/termux-x11/assets/1854021/c7d87b1b-5189-4ad1-a5c1-316a78498c73)

**Comment by twaik** [comment]
Currently there is no way to debug this. The only way of debugging is using `printf` for outputting variables. Or you can get stacktrace with `raise(SIGSEGV)` and checking your logcat.

**Comment by yangguosdxl** [comment]
调试 shell-loader的方法：

# 调试shell-loader.apk
## 在移动设备上安装 gdb及gdbserver，将`/data/data/com.termux/files/usr/bin/termux-x11`脚本拷贝到Home目录，并做如下修改：

``` shell
#!/data/data/com.termux/files/usr/bin/sh
export CLASSPATH=/data/data/com.termux/files/usr/libexec/termux-x11/loader.apk
unset LD_LIBRARY_PATH LD_PRELOAD

gdb --args /system/bin/app_process / com.termux.x11.Loader "$@"

```
将pc上编译出来的带符号的本地库｀termux-x11/app/build/intermediates/cxx/Debug/g1m6f6l2/obj/arm64-v8a`传到移动设备上，我放到平板的$Home/solib下。
> $Home 是平板上termux的主目录

``` shell
# 在gdb中设置符号文件搜索路径
set solib-search-path /data/data/com.termux/files/home/solib

# 将源码从PC传到移动设备的$Home/src目录下，并设置路径映射关系
set substitute-path /home/wann/Documents/src/termux-x11/app /data/data/com.termux/files/home/

```
