### ISSUE TITLE
Termux-x11 running XFCE interface flashback

### ISSUE THREAD

**Issue by HKTangyuan** [termux/termux-x11#367]
System:Android13
Termux version:0.118.36
Termux:x11 version:1.02.10

**Comment by twaik** [comment]
Wdym?

**Comment by HKTangyuan** [comment]
Video:
https://github.com/termux/termux-x11/assets/109419998/ba9a0249-b36c-4453-8fac-9fc1ace60a34

**Comment by twaik** [comment]
Restartyour phone and try again.

**Comment by HKTangyuan** [comment]
> Restart your phone and try again.

I got the same result：
https://github.com/termux/termux-x11/assets/109419998/42f4a12f-096a-481c-9d05-5ef8cb3c366b

**Comment by HKTangyuan** [comment]
This looks like a bug. I have tried other versions of termux: x11, but I got the same result.

But I can run it well on the small window screen of Android, but there will be problems when I open it in full screen.

**Comment by twaik** [comment]
It is definitely a bug. I can not reproduce this.

**Comment by twaik** [comment]
Can you please check this?

**Comment by twaik** [comment]
@HKTangyuan can you reproduce this on the latest build?

**Comment by twaik** [comment]
Closing due to the lack of activity.
