### ISSUE TITLE
Where the source code to create the /tmp/.X11-unix/X ?

### ISSUE THREAD

**Issue by yangguosdxl** [termux/termux-x11#371]
hello , recently I read the source code. I found client[1] to be created in Java_com_termux_x11_CmdEntryPoint_getXConnection, it used by shell-loader. but I don't know how it associate with the /tmp/.X11-unix/X. Any guys can help me? 
thanks~

**Comment by twaik** [comment]
X sockets are created by [Xtrans](https://gitlab.freedesktop.org/xorg/lib/libxtrans) library.
