### ISSUE TITLE
not good with proot kde ubuntu

### ISSUE THREAD

**Issue by AdamBosila** [termux/termux-x11#373]
i have installed ubuntu kde with proot
its working with vnc, but with termux x11 every kde app gaves me errors

here are the steps i used

apt update
apt upgrade
pkg install proot-distro
proot-distro install ubuntu
proot-distro login ubuntu --shared-tmp
apt update
apt upgrade
apt-get install kubuntu-desktop tigervnc-standalone-server dbus-x11
echo "XDG_RUNTIME_DIR=/run/user/$(id -u)" >> ~/.pam_environment
echo "export XDG_RUNTIME_DIR=/run/user/$(id -u)" >> ~/.bashrc
source ~/.bashrc
termux-x11 :1 -xstartup /usr/bin/startplasma-x11

have i done anything wrong ?

**Comment by twaik** [comment]
> but with termux x11 every kde app gaves me errors

Whatverrors do you have?

**Comment by twaik** [comment]
Closing this due to the lack of information and lack of activity...
