### ISSUE TITLE
when using direct touch, the cursor doesn't move. i can input inside each window, but moving them is impossible

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#374]
https://github.com/termux/termux-x11/assets/106876912/ff90923f-a140-4e6a-95e1-c8efd5276436

**Comment by twaik** [comment]
In direct touch mode all events are passed directly to X server unchanged, all responsibility on handling it is on DE.

**Comment by kde-yyds** [comment]
https://github.com/termux/termux-x11/assets/106876912/fbafac44-22a9-4a9b-be9d-144a3a7c7c73


the issue is that sometimes a point is always pressed even if not
it's an issue of termux-x11 not an issue of the DE i am using

**Comment by kde-yyds** [comment]
https://github.com/termux/termux-x11/assets/106876912/fbafac44-22a9-4a9b-be9d-144a3a7c7c73


the issue is that sometimes a point is always pressed even if not
it's an issue of termux-x11 not an issue of the DE i am using

it happens every time when i switch termux x11 to backgroubd and open it again

**Comment by kde-yyds** [comment]
@twaik

**Comment by twaik** [comment]
No need to ping me, I see all messages in this repo.

**Comment by twaik** [comment]
You can try latest build.
