### ISSUE TITLE
only showed the keyboard and the cursor.

### ISSUE THREAD

**Issue by boatsky** [termux/termux-x11#375]
When I run termux-x11 and xfce4, termux-x11 shows only the keyboard and xfce4's cursor.But using vnc, it starts normally.
<details>

![Screenshot_2023_0718_000805](https://github.com/termux/termux-x11/assets/135578485/f1fea6c5-dc27-40a3-b05c-06c05a8fae35)
</details>

I used this to start:
```shell
termux-x11 :1 &
env DISPLAY=:1 dbus-launch --exit-with-session xfce4-session
```
Version:
* termux :0.118.0
* termux-x11-nightly on termux app :1.02.07
* termux-x11 app :1.02.11

**Comment by boatsky** [comment]
termux :0.118.0
termux-x11-nightly on termux app :1.02.07
termux-x11 app :1.02.11

**Comment by twaik** [comment]
Post logs.

**Comment by twaik** [comment]
Did you install loader from latest artifact? Or you are using loader from `termux-x11-nightly`?

**Comment by boatsky** [comment]
![Screenshot_2023_0718_093659](https://github.com/termux/termux-x11/assets/135578485/708cce55-c04f-44e6-8b23-ceef468586f8)
I use latest build,all is new,and how to get .log？
I use Android 9 on arm64.

**Comment by boatsky** [comment]
> 根据日志一切正常，请尝试`termux-x11 :1 -xstartup "xfce4-session"`

It still doesn't run xfce4 properly.

**Comment by twaik** [comment]
`TERMUX_X11_DEBUG=1 termux-x11 :1 -xstartup "xfce4-session" > log`, extract `log` file and post it. Do not post a screenshot.

**Comment by boatsky** [comment]
I got this:
[log.log](https://github.com/termux/termux-x11/files/12077935/log.log)

**Comment by twaik** [comment]
The log is incomplete. 
`TERMUX_X11_DEBUG=1 termux-x11 :1 -xstartup "xfce4-session" > log 2>&1`

**Comment by boatsky** [comment]
I run ``TERMUX_X11_DEBUG=1 termux-x11 :1 -xstartup "xfce4-session" > log 2>&1``and kill it after 12 seconds
[log.log](https://github.com/termux/termux-x11/files/12078211/log.log)

**Comment by twaik** [comment]
According to the log everything seems to be fine.

**Comment by twaik** [comment]
I have no idea why that can happen.

**Comment by Aung-Thura** [comment]
I also have the same problem bro.My device is also running in android 9.

**Comment by ask9027** [comment]
if `X` replaced with cursor it means `termux-x11` working properly.

Install `latest build` and update `pkg` in `termux-app`
and install termux-x11 from `pkg install termux-x11*`
you can try to remove `.cache .config` from termux-app

**Comment by TomJo2000** [comment]
> [...] you can try to remove `.cache .config` from termux-app [...]
Please be careful about removing the contents of `.cache` or `.config` in bulk.
Most packages use those directories to store their configuration files and cache files respectively.
You most likely would not want to remove your config files for most installed applications.

**Comment by ask9027** [comment]
> > [...] you can try to remove `.cache .config` from termux-app [...]
> 
> Please be careful about removing the contents of `.cache` or `.config` directories in bulk. Most packages use those directories to store their configuration files and cache files respectively. You most likely would not want to remove your config files for most installed applications.

if these are importent then make backup first

**Comment by boatsky** [comment]
I did them, but I still couldn't access the xfce4 desktop through termux-x11.

**Comment by ask9027** [comment]
> I did them, but I still couldn't access the xfce4 desktop through termux-x11.

i will try it in Android 9. then will try to find out what is happening.
did you tried with proot-distro? are you getting same problem with it.

**Comment by boatsky** [comment]
No,I install proot-distro debian,but I haven't used termux-11 in Debian in nearly half a year.

**Comment by twaik** [comment]
Try to run `termux-x11 :10 -xstartup glxgears`.

**Comment by boatsky** [comment]
How to do it? And then what?

**Comment by twaik** [comment]
`termux-x11 :10 -xstartup glxgears` is the exact command to run. After that swich to `Termux:X11` activity. It should show `glxgears` window.

**Comment by twaik** [comment]
Any updates?

**Comment by ask9027** [comment]
in Android 9 it is working properly 
here is `neofetch`
![Screenshot_2023-07-20-19-21-08-222_com termux x11_072254](https://github.com/termux/termux-x11/assets/61283438/090247c9-c667-497d-8b79-baeef65adb6c)

**Comment by boatsky** [comment]
I didn't find the best solution to the problem, and the first time this happened to my device was after an update to termux-x11.It was once stripped down and I couldn't boot my xfce4 for a long time.

**Comment by twaik** [comment]
Try to run `termux-x11 :10 -xstartup glxgears`. I am still waiting for your response on this.

**Comment by boatsky** [comment]
``sh: 1: glxgears: not found

4947 exited, status=127``

**Comment by twaik** [comment]
`apt install mesa-demos` and try again.

**Comment by boatsky** [comment]
> `apt install mesa-demos`然后重试。

I ran it, then switched to termux-x11, which only showed a "x". The shell displays the following.```608 frames in 5.0 seconds = 121.407 FPS
731 frames in 5.0 seconds = 146.144 FPS
669 frames in 5.0 seconds = 133.641 FPS
918 frames in 5.0 seconds = 183.422 FPS
1001 frames in 5.0 seconds = 199.817 FPS
727 frames in 5.0 seconds = 145.221 FPS
773 frames in 5.0 seconds = 154.296 FPS
523 frames in 5.0 seconds = 104.541 FPS
835 frames in 5.0 seconds = 166.909 FPS```

**Comment by boatsky** [comment]
0

**Comment by twaik** [comment]
I am not sure why that happens. Try to uninstall termux app and install it again with the same environment.

**Comment by boatsky** [comment]
I reinstalled termux-app 5 hours ago.

**Comment by boatsky** [comment]
I reinstalled termux-app 5 hours ago.

**Comment by twaik** [comment]
You can try to use the brand new option I implemented today. Launch `termux-x11 :0 -xstartup xfce4-session -legacy-drawing`. `-legacy-drawing` makes drawing twice slower, but at least it works.

**Comment by boatsky** [comment]
> 您可以尝试使用我今天实现的全新选项。发射。 使绘图速度变慢两倍，但至少它可以工作。`termux-x11 :0 -xstartup xfce4-session -legacy-drawing``-legacy-drawing`

The problem has been solved, but why did it happen?

**Comment by twaik** [comment]
For some reason your device does not want to draw AHardwareBuffer based texture, but does not even report error.

**Comment by boatsky** [comment]
> 由于某种原因，您的设备不想绘制基于AHardwareBuffer的纹理，但甚至不报告错误。

But my device was working fine until I forced out of termux.

**Comment by twaik** [comment]
> until I forced out of termux.

Explain

**Comment by boatsky** [comment]
I was using termux-x11 at the time, but I accidentally cleared the termux-app background in the phone menu.After that termux-x11 cannot work properly.

**Comment by twaik** [comment]
This should not affect the normal workflow of termux-x11. I do this all the time.
