### ISSUE TITLE
Termux-x11 Not working 

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-x11#376]
Termux-x11 not working after using latest builds. After running TERMUX_X11_DEBUG=1 termux-x11 :0, its showing "killed". [log.txt](https://github.com/termux/termux-x11/files/12073477/log.txt)

I updated from https://github.com/termux/termux-x11/actions/runs/5533254771 this build to this https://github.com/termux/termux-x11/actions/runs/5574263983 . skipped some builds between this.

**Comment by twaik** [comment]
You are right. I broke shell-loader's AndroidManifest.xml to make it non-installable, but it looks like it also breaks signature checking...
