### ISSUE TITLE
buggy unicode characters input

### ISSUE THREAD

**Issue by kde-yyds** [termux/termux-x11#377]
https://github.com/termux/termux-x11/assets/106876912/603d06d0-bdcb-46d1-ab4d-ec39c832e4b5

**Comment by twaik** [comment]
I do not undersrand Chinese...

**Comment by kde-yyds** [comment]
![Screenshot_2023-07-18-20-59-26-782_com.termux.x11.jpg](https://github.com/termux/termux-x11/assets/106876912/536768a2-ba4d-4390-9ca5-3fc6f7e37b60)



the  effect is like this

**Comment by kde-yyds** [comment]
what examples can i give?

**Comment by kde-yyds** [comment]
wps is a non-free software and we cannot modify it.
maybe as a workaround we can limit input speed? it means termux-x11 should wait for some milliseconds between sending characters

**Comment by 2096779623** [comment]
> maybe it's a bug of wps office.i cannot reproduce it in any other editors

I can also reproduce this bug when using icalingua++, or try the telegram linux client.

**Comment by kde-yyds** [comment]
yes. i can also reproduce it in electron apps

**Comment by twaik** [comment]
I can add 30 msec delay between sending each symbol.

**Comment by kde-yyds** [comment]
but that is waiting before sending all characters, not waiting between sending each character
@twaik 

(the build does not fix this,i changed it into 1 second and found it
https://github.com/termux/termux-x11/assets/106876912/558478c6-933b-45df-a37c-d42222d99217

**Comment by twaik** [comment]
Where and what did you change?

**Comment by twaik** [comment]
Try again the latest build.

**Comment by kde-yyds** [comment]
but that is waiting before sending all characters, not waiting between sending each character
@twaik 

(the build does not fix this,i changed it into 1 second and found it
https://github.com/termux/termux-x11/assets/106876912/558478c6-933b-45df-a37c-d42222d99217

i changed usleep(30000); into usleep(1000000); and then built it

**Comment by twaik** [comment]
Yeah, I forgot to make it flush connection before calling `usleep`.

**Comment by kde-yyds** [comment]
it works well. thanks
