### ISSUE TITLE
X server broken

### ISSUE THREAD

**Issue by dontknowhy** [termux/termux-x11#379]
I downloaded the latest github action(aka. nightly build) and noticed I can't run almost everything.
termux-info:
```
Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1+4a711e9
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~V35twZNyo2214x8RGA9miA==/com.termux-tKa5OcrdsjKbPwbfIiCNaA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=11282
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c215,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c215,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10471
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+66a9495
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+66a9495
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 main
deb https://mirrors.ustc.edu.cn/termux/apt/termux-unstable unstable main
deb https://mirrors.ustc.edu.cn/termux/apt/termux-games games stable
deb https://mirrors.ustc.edu.cn/termux-its-pointless/24 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Tue May 16 11:31:17 CST 2023 aarch64 Android
Device manufacturer:
HONOR
Device model:
BRT-W09
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:12
com.termux.window versionCode:15
com.termux.api versionCode:51
com.termux.gui versionCode:8
com.termux.tasker versionCode:6
com.termux.styling versionCode:30
com.termux.widget versionCode:13

```
Trace file will be uploaded soon.
Now I can only run xterm.

**Comment by dontknowhy** [comment]
![termux-x11-nightly.zip](https://github.com/termux/termux-x11/files/12092477/termux-x11-nightly.zip)

**Comment by twaik** [comment]
Any updates?

**Comment by dontknowhy** [comment]
![termux-x11.zip](https://github.com/termux/termux-x11/files/12102655/termux-x11.zip)

**Comment by twaik** [comment]
You did not switch to main applicaiton after starting `termux-x11`. Do that and post the log.

**Comment by dontknowhy** [comment]
> ![termux-x11.zip](https://github.com/termux/termux-x11/files/12102655/termux-x11.zip)
> 
> 

07-20 14:24:11.882 25976 25993 W libMEOW : cannot open (libMEOW_gift.so):(/vendor/lib64/egl/libMEOW_gift.so), error (dlopen failed: library "/vendor/lib64/egl/libMEOW_gift.so" not found)

**Comment by twaik** [comment]
`07-20 14:24:11.882 25976 25993 W libMEOW : cannot open (libMEOW_gift.so):(/vendor/lib64/egl/libMEOW_gift.so), error (dlopen failed: library "/vendor/lib64/egl/libMEOW_gift.so" not found)` is not critical IMO.

**Comment by dontknowhy** [comment]
> `07-20 14:24:11.882 25976 25993 W libMEOW : cannot open (libMEOW_gift.so):(/vendor/lib64/egl/libMEOW_gift.so), error (dlopen failed: library "/vendor/lib64/egl/libMEOW_gift.so" not found)` is not critical IMO.

So why?

**Comment by twaik** [comment]
> You did not switch to main applicaiton after starting termux-x11. Do that and post the log.

Do that.

**Comment by dontknowhy** [comment]
> > `07-20 14:24:11.882 25976 25993 W libMEOW : cannot open (libMEOW_gift.so):(/vendor/lib64/egl/libMEOW_gift.so), error (dlopen failed: library "/vendor/lib64/egl/libMEOW_gift.so" not found)` is not critical IMO.
> 
> So why?

I did have a cute X server's default mouse working.
But i haven't seen any images on it

**Comment by twaik** [comment]
Again.

> You did not switch to main applicaiton after starting termux-x11. Do that and post the log.

Do that.

**Comment by dontknowhy** [comment]
> > > `07-20 14:24:11.882 25976 25993 W libMEOW : cannot open (libMEOW_gift.so):(/vendor/lib64/egl/libMEOW_gift.so), error (dlopen failed: library "/vendor/lib64/egl/libMEOW_gift.so" not found)` is not critical IMO.
> > 
> > So why?
> 
> I did have a cute X server's default mouse working.
> But i haven't seen any images on it
https://github.com/termux/termux-x11/assets/85813508/ba16c146-7b16-4569-ba60-3325837744b9

**Comment by twaik** [comment]
I can not help you if you do not do what I am asking.

**Comment by dontknowhy** [comment]
> I can not help you if you do not do what I am asking.

Update：Now I can run normal X application using termux-x11.
But I can only run them in a container.I think there's something wrong with my Termux environment.

**Comment by twaik** [comment]
Try to reinstall your termux environment and try again.

**Comment by dontknowhy** [comment]
> Try to reinstall your termux environment and try again.

I tried to reinstall X components… And it still report BUS error.
I don't want to reinstall Termux.So I think that's it.
I'm happy with an environment with working termux-x11.

**Comment by twaik** [comment]
I did not see any BUS error in the logs.

**Comment by dontknowhy** [comment]
> I did not see any BUS error in the logs. 

idk
