### ISSUE TITLE
The error of package name of shell-loader

### ISSUE THREAD

**Issue by woshigenm** [termux/termux-x11#380]
The package name of shell-loader is the same packagname as termux-x11. Their package name has conflict. So them can't install at the same time
![Screenshot_2023-07-19-16-14-11-462_bin mt plus](https://github.com/termux/termux-x11/assets/99122353/c06acf6c-2802-4876-9b74-4e78b7129ed7)

**Comment by twaik** [comment]
Shell loader is not installabe for a reason. It should be invoked only from commandline.
