### ISSUE TITLE
Weird Screen remapping behavior when keyboard is open

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-x11#383]
When keyboard is opened, the screen is just shrinking. This was not happened before. ![Screenshot_2023-07-20-02-51-57-99_00df01c412509efb9bd6450c382822af.jpg](https://github.com/termux/termux-x11/assets/114433842/4c702165-9b7d-412f-b979-8387d7e0d75c)

![Screenshot_2023-07-20-02-51-52-80_00df01c412509efb9bd6450c382822af.jpg](https://github.com/termux/termux-x11/assets/114433842/7dbd3985-4c87-4aaf-8cf3-75c16b724e02)

Im using latest build https://github.com/termux/termux-x11/actions/runs/5596238384

**Comment by ask9027** [comment]
till @twaik fix this problem use my builds from release.
