### ISSUE TITLE
keyboard not working

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#384]
Suddenly keyboard not working. i try to close termux-x11 then reopen also not working.
so i restart it from termux-app will work but i happened randomly.
connection can receive key codes but not send to linux system.
here is short video

https://github.com/termux/termux-x11/assets/61283438/45e414af-1a59-4f90-b539-0aa0aad26f11

**Comment by twaik** [comment]
Unfortunately I can not reproduce this.

**Comment by twaik** [comment]
It looks like for some reason xcb connection is fault and not being recovered. I'll add some code for this.
