### ISSUE TITLE
Typing special characters closes Termux X11

### ISSUE THREAD

**Issue by gschanuel** [termux/termux-x11#385]
Hello there 
I'm using the latest build for a while now (I upgrade it every week)

I'm running Termux and Termux X11 on a Samsung Galaxy S21, with external display, keyboard and mouse.
I'm brazilian and my keyboard layout is br-abnt2

Every time I type a special character: **ˋ**, **´**, **˜**, **ˆ**, Termux X11 closes.

I'm running xfce4 installed Archlinux via proot-distro.

I'm starting xfce with the following script:
```
#!/data/data/com.termux/files/usr/bin/bash

pkill -9 Xwayland

pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

sleep 3

proot-distro login archlinux --shared-tmp --bind /dev/null:/proc/sys/kernel/cap_last_cap -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - user -c "env DISPLAY=:0 startxfce4"'

;exit 0
```

What can I do to solve this issue?
What other information can I provide to help track it?

Thanks in advance

**Comment by gschanuel** [comment]
Just solved it by enabling "Prefer scancodes when possible" on Termux X11 preferences

**Comment by twaik** [comment]
Also you should pay attention.
1. termux-x11 builds that use Xwayland are deprecated. Now it has builtin x server.
2. XDG_RUNTIME_DIR is not needed (because we do not use Xwayland).
3. There is `-xstartup` option that starts command when xserver is ready and kills x server when command finished its work.
