### ISSUE TITLE
libexpat.so.1 not found

### ISSUE THREAD

**Issue by Jak2k** [termux/termux-x11#386]
When I run `dbus-launch --exit-with-session startxfce4 &` to start xfce I get `CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/dbus-daemon": library "libexpat.so.1" not found: needed by main executable
EOF in dbus-launch reading address from bus daemon`

**Comment by twaik** [comment]
Not related to `termux-x11`. It is a problem of partial upgrade of termux environment. Do `pkg up`.
