### ISSUE TITLE
startxfce4: X server already running on display :0

### ISSUE THREAD

**Issue by lxs602** [termux/termux-x11#388]
I have not been able to launch xfce4 or xterm as connection is refused.

I followed the guide [here](https://ivonblog.com/en-us/posts/termux-proot-distro-archlinux/).

> ~ $ export DISPLAY=:0
~ $ termux-x11 :0 &
[1] 23335
~ $ dbus-launch --exit-with-session startxfce4 &
[2] 23352
~ $ /data/data/com.termux/files/usr/bin/startxfce4: X server already running on display :0
xrdb: Connection refused
xrdb: Can't open display ':0'
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
[2]+  Exit 1                  dbus-launch --exit-with-session startxfce4

I tried the fix in issue [#273](https://github.com/termux/termux-x11/issues/273) but it also failed:

> ~ $ Xvfb :0 -ac -screen 0 4096x4096x24 &
[1] 26437
~ $ dbus-launch --exit-with-session startxfce4 &
[2] 26443
~ $ /data/data/com.termux/files/usr/bin/startxfce4: X server already running on display :0
(xfwm4:26471): xfwm4-WARNING **: 23:13:19.655: Unsupported GL renderer (llvmpipe (LLVM 16.0.6, 128 bits)).
xfce4-notifyd-Message: 23:13:21.658: Your sqlite library does not support OFFSET/LIMIT with DELETE; falling back to less-efficient deletion method
** (xfdesktop:26503): WARNING **: 23:13:22.300: Failed to get system bus: Could not connect: No such file or directory
libclock-Message: 23:13:22.307: could not get proxy for org.freedesktop.login1
(xfce4-panel:26492): libclock-WARNING **: 23:13:22.309: could not instantiate a sleep monitor
(xfce4-session:26443): xfce4-session-WARNING **: 23:13:25.103: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)
(xfce4-session:26443): xfce4-session-WARNING **: 23:13:25.117: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)
(xfce4-session:26443): xfce4-session-WARNING **: 23:13:25.129: failed to run script: Failed to execute child process “/usr/bin/pm-is-supported” (No such file or directory)

What should I try?

**Comment by twaik** [comment]
You should try to read README.md file of this repo. It contains relevant instructions for latest build.

**Comment by lxs602** [comment]
That was fast. OK, outdated help guide in the link.
