### ISSUE TITLE
xfce4-session: Cannot open display: .

### ISSUE THREAD

**Issue by lxs602** [termux/termux-x11#389]
Termux fails to connect to display. Am I doing something wrong?
> ~ $ termux-x11 :1 &
[1] 30677
~ $ env DISPLAY=:1 dbus-launch --exit-with-session xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
[1]+  Killed                  termux-x11 :1
~ $ termux-x11 :1 -xstartup "dbus-launch --exit-with-session xfce4-session"
Killed
~ $ termux-x11 :1 -xstartup "xfce4-session"
Killed

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/blob/master/README.md#logs

**Comment by lxs602** [comment]
I hope this is right. Debug flag does not seem to produce output:

> ~ $ TERMUX_X11_DEBUG=1 termux-x11 :0
Killed
~ $ TERMUX_X11_DEBUG=1 termux-x11 :1 &
[1] 2786
~ $ ^C
~ $ kill -s 9 2786
bash: kill: (2786) - No such process
[1]+  Killed                  TERMUX_X11_DEBUG=1 termux-x11 :1
~ $ TERMUX_X11_DEBUG=1 termux-x11 :1 -xstartup "dbus-launch --exit-with-session xfce4-session"
Killed
~ $ TERMUX_X11_DEBUG=1 termux-x11 :1 &
[1] 2978
~ $  env DISPLAY=:1 dbus-launch --exit-with-session xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
[1]+  Killed                  TERMUX_X11_DEBUG=1 termux-x11 :1
~ $ TERMUX_X11_DEBUG=1 termux-x11 :1 -xstartup "xfce4-session"
Killed

> ~ $ dpkg -l | grep termux
ii  termux-am                  0.4             all          Android Oreo-compatible am command reimplementation
ii  termux-am-socket           1.5.0           aarch64      A faster version of am with less features that only works while Termux is running
ii  termux-auth                1.4-2           aarch64      Password authentication library and utility for Termux
ii  termux-exec                1:1.0           aarch64      An execve() wrapper to make /bin and /usr/bin shebangs work
ii  termux-keyring             3.11            all          GPG public keys for the official Termux repositories
ii  termux-licenses            2.0-3           all          Contains LICENSE files for common licenses
ii  termux-tools               1.38.3          all          Basic system tools for Termux
ii  termux-x11-nightly         1.02.07-0       all          Companion package for termux-x11 app

> ~ $ uname -a
Linux localhost 4.19.191-26023185-abT225XXS4CWF4 #1 SMP PREEMPT Thu Jun 15 18:41:54 KST 2023 aarch64 Android

**Comment by twaik** [comment]
`termux-x11 :1 -xstartup "xfce4-session"& logcat --pid=$!`

**Comment by lxs602** [comment]
> ~ $ termux-x11 :1 -xstartup "xfce4-session"& logcat --pid=$!
[1] 4443
--------- beginning of main
07-21 23:52:56.015  4443  4443 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10281 <<<<<<
07-21 23:52:56.094  4443  4443 I AndroidRuntime: Using default boot image
07-21 23:52:56.094  4443  4443 I AndroidRuntime: Leaving lock profiling enabled
07-21 23:52:56.094  4443  4443 W libc    : Access denied finding property "odsign.verification.success"
07-21 23:52:56.095  4443  4443 D SecNativeFeatureCppIf: encoded
07-21 23:52:56.096  4443  4443 D SecNativeFeatureCppIf: decoding and unzip finish
07-21 23:52:56.096  4443  4443 D SecNativeFeatureCppIf: use unCompDataBuff. encoded
07-21 23:52:56.096  4443  4443 D SecNativeFeatureCppIf: Free unCompDataBuff
07-21 23:52:56.096  4443  4443 D AndroidRuntime: addProductProperty: pBrand1 is not null
07-21 23:52:56.096  4443  4443 D AndroidRuntime: addProductProperty: not brand or 7
07-21 23:52:56.118  4443  4443 W app_process: ART APEX data files are untrusted.
07-21 23:52:56.119  4443  4443 I app_process: Using CollectorTypeCC GC.
07-21 23:52:56.143  4443  4443 E app_process: Error reading named image component header for /system/framework/boot.art, error: Failed to open oat file '/system/framework/arm64/boot-bouncycastle.oat' when validating it for image '/system/framework/boot-bouncycastle.art': In oat file '/system/framework/boot-bouncycastle.oat', dex file checksum 0xf6841481 does not match checksum 0x8ffa6e4e of external dex file '/apex/com.android.art/javalib/bouncycastle.jar'

07-21 23:53:07.563  4443  4443 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-21 23:53:07.563  4443  4443 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-21 23:53:07.607  4443  4443 W ziparchive: Unable to open '/data/data/com.termux/files/usr/libexec/termux-x11/loader.dm': No such file or directory
07-21 23:53:07.667  4443  4443 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
07-21 23:53:07.667  4443  4443 E SemAffinityControl: SemAffinityControl: registerfunction enter
07-21 23:53:07.743  4443  4443 D AndroidRuntime: Calling main entry com.termux.x11.Loader
07-21 23:53:07.745  4443  4443 I Termux:X11 loader: started
07-21 23:53:07.748  4443  4443 W libc    : Access denied finding property "qemu.sf.lcd_density"
07-21 23:53:07.749  4443  4443 W libc    : Access denied finding property "qemu.sf.lcd_density"
07-21 23:53:08.737  4443  4443 W app_process: unable to execute idmap2: Permission denied
07-21 23:53:08.737  4443  4443 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
07-21 23:53:08.738  4443  4443 W libc    : Access denied finding property "ro.vendor.mtk_model"
07-21 23:53:08.777  4443  4443 D SemCscFeature: Encoded
07-21 23:53:08.800  4443  4443 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
07-21 23:53:08.812  4443  4443 E SystemServiceRegistry: systemservice inputdev:true
07-21 23:53:08.839  4443  4443 D SecIpmManagerFrameworkInitializer:  initial
07-21 23:53:08.855  4443  4443 I Typeface: Preloading /system/fonts/Roboto-Regular.ttf
07-21 23:53:08.856  4443  4443 I Typeface: Preloading /system/fonts/RobotoStatic-Regular.ttf
--------- beginning of system
07-21 23:53:09.203  4443  4443 I PackageParser: com.termux.x11: compat added android.permission.WRITE_EXTERNAL_STORAGE android.permission.READ_PHONE_STATE
07-21 23:53:09.345  4443  4443 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-21 23:53:09.346  4443  4443 E AndroidRuntime: FATAL EXCEPTION: main
07-21 23:53:09.346  4443  4443 E AndroidRuntime: PID: 4443
07-21 23:53:09.346  4443  4443 E AndroidRuntime: java.lang.RuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.termux.x11
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at com.termux.x11.Loader.main(Loader.java:66)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
07-21 23:53:09.346  4443  4443 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.termux.x11
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:304)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:264)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:258)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        at com.termux.x11.Loader.main(Loader.java:44)
07-21 23:53:09.346  4443  4443 E AndroidRuntime:        ... 2 more
07-21 23:53:09.348  4443  4443 E AndroidRuntime: Error reporting crash
07-21 23:53:09.348  4443  4443 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:662)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:427)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:202)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:5212)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:5209)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:43)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:5200)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:176)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-21 23:53:09.348  4443  4443 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
07-21 23:53:09.348  4443  4443 I Process : Sending signal. PID: 4443 SIG: 9

**Comment by twaik** [comment]
Did you install main Termux:X11 apk?

**Comment by lxs602** [comment]
Yes, installed with: 

>~ $ git clone --recurse-submodules https://github.com/termux/termux-x11

> ~ $ pkg in x11-repo && pkg in termux-x11-nightly

**Comment by twaik** [comment]
No, you did not. Termux package installed with apt is not main apk. You must install it from lateat build available in Actions page. Exactly as written in README.MD.

**Comment by twaik** [comment]
And `git clone` is needed for fetching source codes, it is not related to installing apk. Read command descriptions carefully.

**Comment by lxs602** [comment]
README.md says:

> Or you can install nightly companion package from repositories with pkg in x11-repo && pkg in termux-x11-nightly

I have now downloaded from
[https://github.com/termux/termux-x11/suites/14444211815/artifacts/815357156](latest artifact): termux-companion packages.zip and termux-x11-v8a-debug.zip, and unzipped and installed termux-x11-nightly-1.02.07-0-all.deb and app-arm64-v8a-debug.apk . Failed to install shell-loader-nightly.apk, as "unable to install app as app with same name already installed"

Error messages do not appear to have changed: 

> .../0/Download $ termux-x11 :1 -xstartup "xfce4-session"& logcat --pid=$!                          [1] 16805
--------- beginning of main
07-22 00:46:34.806 16805 16805 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10281 <<<<<<
07-22 00:46:34.878 16805 16805 I AndroidRuntime: Using default boot image
07-22 00:46:34.878 16805 16805 I AndroidRuntime: Leaving lock profiling enabled
07-22 00:46:34.878 16805 16805 W libc    : Access denied finding property "odsign.verification.success"
07-22 00:46:34.882 16805 16805 D SecNativeFeatureCppIf: encoded
07-22 00:46:34.882 16805 16805 D SecNativeFeatureCppIf: decoding and unzip finish
07-22 00:46:34.882 16805 16805 D SecNativeFeatureCppIf: use unCompDataBuff. encoded
07-22 00:46:34.884 16805 16805 D SecNativeFeatureCppIf: Free unCompDataBuff
07-22 00:46:34.884 16805 16805 D AndroidRuntime: addProductProperty: pBrand1 is not null
07-22 00:46:34.884 16805 16805 D AndroidRuntime: addProductProperty: not brand or 7
07-22 00:46:34.907 16805 16805 W app_process: ART APEX data files are untrusted.
07-22 00:46:34.908 16805 16805 I app_process: Using CollectorTypeCC GC.
07-22 00:46:34.931 16805 16805 E app_process: Error reading named image component header for /system/framework/boot.art, error: Failed to open oat file '/system/framework/arm64/boot-bouncycastle.oat' when validating it for image '/system/framework/boot-bouncycastle.art': In oat file '/system/framework/boot-bouncycastle.oat', dex file checksum 0xf6841481 does not match checksum 0x8ffa6e4e of external dex file '/apex/com.android.art/javalib/bouncycastle.jar'

07-22 00:46:47.450 16805 16805 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
07-22 00:46:47.450 16805 16805 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
07-22 00:46:47.501 16805 16805 W ziparchive: Unable to open '/data/data/com.termux/files/usr/libexec/termux-x11/loader.dm': No such file or directory
07-22 00:46:47.590 16805 16805 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
07-22 00:46:47.591 16805 16805 E SemAffinityControl: SemAffinityControl: registerfunction enter
07-22 00:46:47.668 16805 16805 D AndroidRuntime: Calling main entry com.termux.x11.Loader
07-22 00:46:47.670 16805 16805 I Termux:X11 loader: started
07-22 00:46:47.673 16805 16805 W libc    : Access denied finding property "qemu.sf.lcd_density"
07-22 00:46:47.674 16805 16805 W libc    : Access denied finding property "qemu.sf.lcd_density"
07-22 00:46:48.728 16805 16805 W app_process: unable to execute idmap2: Permission denied
07-22 00:46:48.728 16805 16805 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
07-22 00:46:48.728 16805 16805 W libc    : Access denied finding property "ro.vendor.mtk_model"
07-22 00:46:48.766 16805 16805 D SemCscFeature: Encoded
07-22 00:46:48.788 16805 16805 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
07-22 00:46:48.801 16805 16805 E SystemServiceRegistry: systemservice inputdev:true
07-22 00:46:48.831 16805 16805 D SecIpmManagerFrameworkInitializer:  initial
07-22 00:46:48.850 16805 16805 I Typeface: Preloading /system/fonts/Roboto-Regular.ttf
07-22 00:46:48.851 16805 16805 I Typeface: Preloading /system/fonts/RobotoStatic-Regular.ttf
--------- beginning of system
07-22 00:46:49.199 16805 16805 I PackageParser: com.termux.x11: compat added android.permission.WRITE_EXTERNAL_STORAGE android.permission.READ_PHONE_STATE
07-22 00:46:49.345 16805 16805 D AndroidRuntime: Shutting down VM
--------- beginning of crash
07-22 00:46:49.348 16805 16805 E AndroidRuntime: FATAL EXCEPTION: main
07-22 00:46:49.348 16805 16805 E AndroidRuntime: PID: 16805
07-22 00:46:49.348 16805 16805 E AndroidRuntime: java.lang.RuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.termux.x11
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at com.termux.x11.Loader.main(Loader.java:66)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:378)
07-22 00:46:49.348 16805 16805 E AndroidRuntime: Caused by: android.content.pm.PackageManager$NameNotFoundException: com.termux.x11
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:304)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:264)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:258)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        at com.termux.x11.Loader.main(Loader.java:44)
07-22 00:46:49.348 16805 16805 E AndroidRuntime:        ... 2 more
07-22 00:46:49.350 16805 16805 E AndroidRuntime: Error reporting crash
07-22 00:46:49.350 16805 16805 E AndroidRuntime: java.lang.RuntimeException: Bad file descriptor
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:662)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.IServiceManager$Stub$Proxy.checkService(IServiceManager.java:421)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.ServiceManagerProxy.getService(ServiceManagerNative.java:63)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.ServiceManager.rawGetService(ServiceManager.java:427)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.os.ServiceManager.getService(ServiceManager.java:202)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:5212)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.app.ActivityManager$1.create(ActivityManager.java:5209)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.util.Singleton.get(Singleton.java:43)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at android.app.ActivityManager.getService(ActivityManager.java:5200)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:176)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
07-22 00:46:49.350 16805 16805 E AndroidRuntime:        at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
07-22 00:46:49.351 16805 16805 I Process : Sending signal. PID: 16805 SIG: 9

**Comment by twaik** [comment]
Shell loader is not installable for a reason. It is only for people who uses it with chroot without termux installed.
You already had installed termux-x11-nightly package with apt, there was no need in installing deb again.

**Comment by twaik** [comment]
You are doing something wrong. Make sure there is Termux:X11 app in you launcher.

**Comment by lxs602** [comment]
I have followed instructions exactly as above. I cannot see Termux:X11 app in launcher, only Termux. How has it gone wrong?

**Comment by twaik** [comment]
It looks like you did not install `app-arm64-v8a-debug.apk`

**Comment by lxs602** [comment]
Yes. Thank you very much. I reinstalled pp-arm64-v8a-debug.apk and it succeeded. Termux-x11 appeared in the launcher and it now launches.
