### ISSUE TITLE
cant use ALT+Click and more things

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#391]
### Problems
---
1. unable to use `ALT+Click` to use `insert cursor` in `vscode`.
<details>
<summary>Video</summary>

[ScreenRecord](https://github.com/termux/termux-x11/assets/61283438/20b36a90-9ec8-44b9-9ae0-7aa6fcf63c9f)
</details>

2. also can't use `double click move`.
<details>
<summary>Video</summary>

[ScreenRecord](https://github.com/termux/termux-x11/assets/61283438/ca11cf6d-b6e2-43f5-8f1a-ad7c3c4321ab)
</details>

3. `Single click` at chromium-browser is turn into `move action`.
<details>
<summary>Video</summary>

[ScreenRecord](https://github.com/termux/termux-x11/assets/61283438/f117a39c-bdae-4c96-96ff-f7555674efc7)
</details>

---
### Expected behavior: 
1. should use `insert cursor` in vscode.
2. `double click move` should work as pc.
3. `single click` should not turn into `move`.
---
### Solution
Don't Know

**Comment by twaik** [comment]
> unable to use ALT+Click to use insert cursor in vscode.

Yeah, I checked this and for some reason termux-x11 activity or X server does not send ButtonPress and ButtoRelease event when alt key is in pressed state. I'll check why that happens later.

> 2\. `double click move` should work as pc.
> 3\. `single click` should not turn into `move`.

No, touch gestures work as expected. Gestures for both "simulated touchscreen" and "trackpad" modes are described [here](https://github.com/termux/termux-x11/blob/master/README.md#touch-gestures).

**Comment by twaik** [comment]
Touch gesture handling code was copied directly from [here](https://github.com/chromium/chromium/tree/main/remoting/android/java/src/org/chromium/chromoting). I did not write it and not sure if I can modify it in the right way. And I likely will not do that.

**Comment by ask9027** [comment]
> Touch gesture handling code was copied directly from [here](https://github.com/chromium/chromium/tree/main/remoting/android/java/src/org/chromium/chromoting). I did not write it and not sure if I can modify it in the right way. And I likely will not do that.

i think modification is posible but i dont have deep knowledge of programming.

**Comment by ask9027** [comment]
`Alt+Click` defined in `vscode` keyboard shortcuts 
here is * that tell if `Alt+click` not working then change to `Ctrl+click`, so it is working now. but problem is that it(ctrl+click) is not working with hacker keyboard
working with termux-x11 keys but that not released when event done.

**Comment by twaik** [comment]
`Applications` → `Settings` → `Window Manager Tweaks` → `Accessibility` tab → Switch `Key used to grab and move windows` to `None`.
