### ISSUE TITLE
Cannot forward sound to Termux to play by using Termux-x11 server

### ISSUE THREAD

**Issue by woshigenm** [termux/termux-x11#393]
When I use VNC server, the sound can be forwarded to Temux to play by using Pulseaudio. 
![Screenshot_2023-07-25-16-57-11-637_com gaurav avnc](https://github.com/termux/termux-x11/assets/99122353/3fbb73ef-b379-4ae8-8d13-2a2962854a38)
But when I use Termux-X11 server, it can't find Pulseaudio server. And if it found Pulseaudio server. It also can't forward sound to Termux to play.
![Screenshot_2023-07-25-17-01-01-439_com termux x11](https://github.com/termux/termux-x11/assets/99122353/14ecb28d-e357-4c11-a551-7b6ad65d7a39)

I don't know why. Could you give me some advise? Thanks:-)

**Comment by kde-yyds** [comment]
> Environment: chroot container
> OS: Debian GNU/Linux 12 (bookworm)
> 
> When I use VNC server, the sound can be forwarded to Temux to play by using Pulseaudio. 
> ![Screenshot_2023-07-25-16-57-11-637_com gaurav avnc](https://github.com/termux/termux-x11/assets/99122353/3fbb73ef-b379-4ae8-8d13-2a2962854a38)
> But when I use Termux-X11 server, it can't find Pulseaudio server. And if it found Pulseaudio server. It also can't forward sound to Termux to play.
> ![Screenshot_2023-07-25-17-01-01-439_com termux x11](https://github.com/termux/termux-x11/assets/99122353/14ecb28d-e357-4c11-a551-7b6ad65d7a39)
> 
> I don't know why. Could you give me some advise? Thanks:-)
>  

试试设置这个环境变量
PULSE_SERVER=tcp:127.0.0.1:4713
然后在termux里运行pulseaudio --start

**Comment by twaik** [comment]
Official language here is English.
