### ISSUE TITLE
Termux-x11 failed to respond

### ISSUE THREAD

**Issue by Faun622** [termux/termux-x11#395]
I install debian and xfce4 desktop in termux and connect to termux-x11.Howerer when x11 successfully connect to the desktop and wait for few seconds,the x11 app failed to respond.If I switch to termux and switch back to x11,it worked well and then failed to respond again in few seconds.It is strange that there is not any error information about it in termux.It seemed that the system still worked well.

Device information:
Device:XiaomiPad6Pro
System:Android13,MIUI14.0.6
TermuxVersion:0.118.0
x11version:1.02.12

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/blob/master/README.md#logs

**Comment by Faun622** [comment]
well when I try it agian,it do not happened like that.Maybe there are so many background apps caused less available memory to it.

**Comment by romanovj** [comment]
> well when I try it agian,it do not happened like that.Maybe there are so many background apps caused less available memory to it.

There is hack

Navigate to Settings -> System -> Developer options and then scroll to the Debugging section.

Click on “Select debug app”.

Select termux x11

**Comment by Faun622** [comment]
nonono I mean the x11 app works well instead of not responding
