### ISSUE TITLE
Output glitch when running xfce4-session with zink+turnip on Termux-x11

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#397]
**Host Device :** Galaxy S23 Ultra, Galaxy Tab S8+ 5G, Galaxy S20
**Termux** : PRoot-Distro Ubuntu 22.04 LTS Xwayland XFCE4-SESSION 4.18

XFCE4 with **GALLIUM_DRIVER=virpipe** on virglender-android, it will show fine
If run XFCE4 with **zink+turnip**, there is an output glitch. :(

The command to execute virglender-android is as follows.
```
$ virgl_test_server_android & 
$ XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac & 
$ proot-distro login ubuntu --user id --shared-tmp --no-sysvipc
$ export DISPLAY=:0 GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.6COMPAT MESA_GLES_VERSION_OVERRIDE=3.2
$ dbus-launch --exit-with-session startxfce4 &
``` 
![스크린샷_2023-07-27_14-45-57](https://github.com/termux/termux-x11/assets/101167173/83880f3a-5a18-421d-96f7-32232c0831b7)
![스크린샷_2023-07-27_14-45-57_2](https://github.com/termux/termux-x11/assets/101167173/8e555458-4097-4ea7-8ced-eb782fccad03)
![스크린샷_2023-07-27_14-45-57_1](https://github.com/termux/termux-x11/assets/101167173/a83ce4a9-de87-401a-b161-149ee4160087)

It is well represented by virgl in XFCE4 GPU info.

Also, it is written as virgl even if it is executed without glmark2 environment variable in the terminal.

**https://gitlab.freedesktop.org/Danil/mesa
mesa-turnip-feature-a7xx-basic-support**

at Branches

I have compiled and built the Freedreno turnip kgls driver.

When running a program with environment variables in a terminal
zink+turnip is applied well and vkcube is running well

but
Problem occurs when running XFCE4-SESSION.

The command to execute zink+turnip is as follows.
```
$ XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac & 
$ proot-distro login ubuntu --user id --shared-tmp --no-sysvipc
$ export DISPLAY=:0 MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform MESA_VK_WSI_DEBUG=sw VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/freedreno_icd.aarch64.json
$ dbus-launch --exit-with-session startxfce4 &
``` 

![스크린샷_2023-07-27_15-02-04](https://github.com/termux/termux-x11/assets/101167173/b322eecf-a0e1-4991-acd2-956e75221a25)
![스크린샷_2023-07-27_15-00-46](https://github.com/termux/termux-x11/assets/101167173/762d2948-c4a9-4a45-8f86-e52a82f78a62)
![스크린샷_2023-07-27_15-02-32](https://github.com/termux/termux-x11/assets/101167173/973a339f-93d8-443a-a9f0-32f46f1a2318)
![스크린샷_2023-07-27_14-59-49](https://github.com/termux/termux-x11/assets/101167173/5e012498-7d8b-45e3-b6bd-9d4e2a929633)
![스크린샷_2023-07-27_15-02-04_2](https://github.com/termux/termux-x11/assets/101167173/f5371a1e-ca49-43e6-9aa1-6faf2f5157b3)
![스크린샷_2023-07-27_14-59-49_3](https://github.com/termux/termux-x11/assets/101167173/0a5bd68f-b1da-4af2-8907-054c55563a07)
![스크린샷_2023-07-27_14-59-49_4](https://github.com/termux/termux-x11/assets/101167173/2028eba4-35c8-4322-b61e-b1aa4f34dbb8)

Issues that occurred in XFCE4-SESSION executed with zink+turnip are

**1. Top UI not displayed
2. Bottom panel UI is broken and displayed
3. Application does not display title UI**

GPU information is displayed well by turnip.

glxgears, glmark2, vkcube, etc. also run well in the terminal.
Is there a way to fix the XFCE4 output glitch?

Adreno650, Adreno730 and Adreno740 all have the same symptoms.

**Comment by twaik** [comment]
> Xwayland

Not used in termux-x11 since ee2224e474ce0c184de7a2c9c454c658f8afe249

> If run XFCE4 with **zink+turnip**, there is an output glitch. :(

Probably a problem of zink or turnip. X server can not affect this, only mesa or its components can.

> Also, it is written as virgl even if it is executed without glmark2 environment variable in the terminal.

Probably some problem of your environment. X server has no ways to enforce using virpipe.

> When running a program with environment variables in a terminal zink+turnip is applied well and vkcube is running well
> 
> but Problem occurs when running XFCE4-SESSION.

> Issues that occurred in XFCE4-SESSION executed with zink+turnip are
> 
> **1. Top UI not displayed 
> 2. Bottom panel UI is broken and displayed
> 3. Application does not display title UI**

I am pretty sure with vncserver you will have the same result, not a problem of `termux-x11`.

> Is there a way to fix the XFCE4 output glitch?

You should ask this question in mesa support forum.
