### ISSUE TITLE
Termux-x11 and Xserver not exit completely

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#398]
Currently Termux-API and Termux-Widget  
Start/Exit Ubuntu with one click.

![Screenshot_20230728_100747_One UI Home](https://github.com/termux/termux-x11/assets/101167173/e6aec516-224d-4faa-9f74-243694167305)

![스크린샷_2023-07-10_16-32-14](https://github.com/termux/termux-x11/assets/101167173/9876dd10-00b3-4eb0-891b-23e43c48cf0b)

If you select the Ubuntu startup script in Termux-Widget, it runs Termux-x11 and the Ubuntu GUI is displayed correctly

Even if you run the shutdown script in Termux-Widget after Ubuntu logout
It seems that Termux-x11 and X server are not exit.
![Screenshot_20230728_094707_TermuxX11](https://github.com/termux/termux-x11/assets/101167173/2847950b-b5e3-4ea8-961d-5b503647f457)

![Screenshot_20230728_103817_TermuxX11](https://github.com/termux/termux-x11/assets/101167173/6c54e438-b7a9-4072-b706-d5ebd622c784)

In that state, even if you select the Ubuntu startup script from Termux-Widget Ubuntu GUI is not displayed.

It seems that the X server on Termux-x11 is completely shut down when Termux is forced to stop from the application information.

Termux-Widget's exit script is as follows.
```c
#!/bin/sh
killall -9 termux-x11 pulseaudio virgl_test_server_android
termux-wake-unlock; termux-toast "Stopping X11, virgl, etc."
``` 

If I made a mistake
I was wondering if there is a correct way to exit Termux-x11 and X server completely.

**Comment by ask9027** [comment]
use `kill pidof app_process` to stop termux-x11

**Comment by hansm629** [comment]
> 
May I know a simple example script?

**Comment by hansm629** [comment]
> use `kill pidof app_process` to stop termux-x11

May I know a simple example script?

**Comment by twaik** [comment]
```
#!/bin/sh
kill pidof app_process
```

**Comment by hansm629** [comment]
> ```
> #!/bin/sh
> kill pidof app_process
> ```

Thank you! :)
