### ISSUE TITLE
HP Elite X3 Lapdock Touchpad works weird

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#399]
HP Elite X3 Lapdock is a dock station for phones. It has touchpad.

Also Motorola phone works as a touchpad in Desktop Mode

Motorola's Touchpad works like a charm in Termux X11, but HP's touchpad works very bad. If you need a move of cursor, you need to use 2 fingers (in touchpad mode), you can't use one finger, left click is very hard to use, but maybe it's just "pressed key".

Movie with logs
https://tube.midov.pl/w/6evcFzBxQW6FM7Ejasrj83

**Comment by twaik** [comment]
Try this build.
[app-universal-debug.zip](https://github.com/termux/termux-x11/files/12196128/app-universal-debug.zip)

**Comment by IntinteDAO** [comment]
@twaik 
Well, after upgrade, the TermuX11 doesn't work :/

https://tube.midov.pl/w/wXjPtju3FERFW6297QB8ne
https://tube.midov.pl/w/j5pPuSMqHWXHFNsP151jqu
https://tube.midov.pl/w/e65wvRB5qofiBgbzTAoL6J

**Comment by twaik** [comment]
What is inside x11.sh?

**Comment by IntinteDAO** [comment]
@twaik 

New version (on the movie, cause it's blank after upgrade, so I remove some lines)

```
su -c device_config put activity_manager max_phantom_processes 214181594
export XDG_RUNTIME_DIR=${TMPDIR}
env TERMUX_X11_DEBUG=1 termux-x11 :0 -ac & 2>&1 | tee termux-logs.txt
sleep 15s
env DISPLAY=:0 dbus-launch xfce4-session
```

Old version:

```
su -c device_config put activity_manager max_phantom_processes 214181594
export XDG_RUNTIME_DIR=${TMPDIR}

export MESA_VK_WSI_DEBUG=sw
killall -9 virgl_test_server_android
virgl_test_server_android &
export GALLIUM_DRIVER=virpipe
env TERMUX_X11_DEBUG=1 termux-x11 :0 -ac & 2>&1 | tee termux-logs.txt
sleep 15s
env DISPLAY=:0 dbus-launch xfce4-session
```

**Comment by twaik** [comment]
No need to `sleep`, there is a `-xstartup` option... Check README.

**Comment by twaik** [comment]
Resolved?

**Comment by twaik** [comment]
I am pretty sure it is not fixed.

**Comment by twaik** [comment]
@IntinteDAO?
