### ISSUE TITLE
Mouse Capture - axis are very sensitive

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#400]
It is possible to run Mouse Capture in Termux. If you play a game, for example krunker.io in browser, it's technically too sensitive for use. 

The mouse behaves as if it is switching very aggressively to the other side, making it impossible to play.
https://tube.midov.pl/w/2sJyCDvdbCgwr3Rjc1yQPW

**Comment by twaik** [comment]
I am pretty sure that it is tge same problem as in the case of CS1.6

https://github.com/termux/termux-x11/assets/9674930/d9b47b21-6a43-4872-8d0b-4b18b751356a

Termux:X11 sends absolute coordinates of mouse event and currently there is no way to override this.

**Comment by IntinteDAO** [comment]
Hmm, too bad.

I wonder if Termux X11 can't emulate a Gamepad. On the one hand, that's not what it's for, but on the other hand, maybe it can be made to be a provider?

It wouldn't solve the problem, but for some people maybe it would go around if you could play with the help of a game pad.

**Comment by twaik** [comment]
Some people use so-called "input bridge" with wine for this.

**Comment by IntinteDAO** [comment]
@twaik 
Yep, I know input bridge, but I thinking about physical gamepad, like Xbox pad. I'm not sure how to use USB Gamepad in Termux (termux-usb I think?), but I wondering is it possible to use "fake gamepad" in Termux X11 like a some devices that can be handled by X11 (Tablets, Keyboards, Mouse).

**Comment by twaik** [comment]
I checked it with https://gamaverse.com/parkour-block-2-game/ so I am pretty sure it works well. Mouse acceleration can be adjusted with XFCE settings
![image](https://github.com/termux/termux-x11/assets/9674930/7fd9121d-9f2b-4ccc-a428-8fd2a161a23a)
