### ISSUE TITLE
Is there a way to improve web browser video decoding performance?

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#402]
**host :** Galaxy S23 Ultra, Galaxy Tab S8+ 5G, Galaxy S20
**os :** Termux-x11 PRoot-Distro Ubuntu 22.04 LTS XFCE4-SESSION 4.18 (virgl, zink+turnip)

When I play YouTube with **Firefox-esr v102.14.0**, the screen cracks vertically.

Adding the **GALLIUM_DRIVER=virpipe** environment variable does not improve.

My goal is to play YouTube 1080p videos smoothly, but even considering that there is no hardware decoding in Linux environments, I think the video playback performance is too low.

Is there any way to improve it as it looks like it can play up to 1080p even if it's decoded with just the CPU?

**Comment by twaik** [comment]
X server does not manage how browsers decodes videos.

**Comment by hansm629** [comment]
> X server does not manage how browsers decodes videos.

Could it be an issue related to the issue below?

https://github.com/termux/termux-x11/issues/334

**Comment by twaik** [comment]
No.

**Comment by kde-yyds** [comment]
> **host :** Galaxy S23 Ultra, Galaxy Tab S8+ 5G, Galaxy S20
> **os :** Termux-x11 PRoot-Distro Ubuntu 22.04 LTS XFCE4-SESSION 4.18 (virgl, zink+turnip)
> 
> 
> When I play YouTube with **Firefox-esr v102.14.0**, the screen cracks vertically.
> 
> Adding the **GALLIUM_DRIVER=virpipe** environment variable does not improve.
> 
> My goal is to play YouTube 1080p videos smoothly, but even considering that there is no hardware decoding in Linux environments, I think the video playback performance is too low.
> 
> Is there any way to improve it as it looks like it can play up to 1080p even if it's decoded with just the CPU?
> 



firefox uses software rendering when using turnip zink . it's already slow.  
firefox can use vaapi to decode when possible. but for adreno, there are no drivers now

**Comment by hansm629** [comment]
> > **host :** Galaxy S23 Ultra, Galaxy Tab S8+ 5G, Galaxy S20
> > **os :** Termux-x11 PRoot-Distro Ubuntu 22.04 LTS XFCE4-SESSION 4.18 (virgl, zink+turnip)
> > When I play YouTube with **Firefox-esr v102.14.0**, the screen cracks vertically.
> > Adding the **GALLIUM_DRIVER=virpipe** environment variable does not improve.
> > My goal is to play YouTube 1080p videos smoothly, but even considering that there is no hardware decoding in Linux environments, I think the video playback performance is too low.
> > Is there any way to improve it as it looks like it can play up to 1080p even if it's decoded with just the CPU?
> 
> firefox uses software rendering when using turnip zink or virgl . it's already slow. firefox can use vaapi to decode when possible. but for adreno, there are no drivers now


Is there a replacement?
The Cromium browser does not have any symptoms of vertical cracks when playing YouTube

but
The chromium browser installed with the addition of the debian buster repository is low in version, webGL doesn't work, and only 720p is active on YouTube. T_T

When you install chromium in the debian bookworm repository, it's installed as 113 so it's active up to 4K and plays well up to 1080p

but When installing the chromium
The Python3 package is twisted and the Ubuntu environment is ruined...

**Comment by IntinteDAO** [comment]
> > > **host :** Galaxy S23 Ultra, Galaxy Tab S8+ 5G, Galaxy S20
> > > **os :** Termux-x11 PRoot-Distro Ubuntu 22.04 LTS XFCE4-SESSION 4.18 (virgl, zink+turnip)
> > > When I play YouTube with **Firefox-esr v102.14.0**, the screen cracks vertically.
> > > Adding the **GALLIUM_DRIVER=virpipe** environment variable does not improve.
> > > My goal is to play YouTube 1080p videos smoothly, but even considering that there is no hardware decoding in Linux environments, I think the video playback performance is too low.
> > > Is there any way to improve it as it looks like it can play up to 1080p even if it's decoded with just the CPU?
> > 
> > 
> > firefox uses software rendering when using turnip zink or virgl . it's already slow. firefox can use vaapi to decode when possible. but for adreno, there are no drivers now
> 
> Is there a replacement? The Cromium browser does not have any symptoms of vertical cracks when playing YouTube
> 
> but The chromium browser installed with the addition of the debian buster repository is low in version, webGL doesn't work, and only 720p is active on YouTube. T_T
> 
> When you install chromium in the debian bookworm repository, it's installed as 113 so it's active up to 4K and plays well up to 1080p
> 
> but When installing the chromium The Python3 package is twisted and the Ubuntu environment is ruined...

Try to install h264ify for your browser. It forces to use H264 codec instead vp9, which required a lot of more resources.
