### ISSUE TITLE
Display not showing correctly.

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-x11#407]
This happening on last 2builds.

**Comment by twaik** [comment]
Post logs.

**Comment by RaWolFoX** [comment]
> Any updates?

Hey i reinstalled older build. Im going to install the latest build. Then i will share logs.

**Comment by RaWolFoX** [comment]
Log
![log.txt](https://github.com/termux/termux-x11/files/12241717/log.txt)

Also status bar area is showing a black bar. And when keyboard is visible, can't see desktop. Look this screen record 👇

https://github.com/termux/termux-x11/assets/114433842/0b4e4b4e-8699-4d34-8e72-8d48afab9392

**Comment by twaik** [comment]
Wdym not correctly?

**Comment by RaWolFoX** [comment]
> Wdym not correctly? 

I thought it might be a directory problem.

**Comment by RaWolFoX** [comment]
> Wdym not correctly? 

Look that screen record. Extra key is going top when keyboard visible.
