### ISSUE TITLE
Black screen when deploying the application.

### ISSUE THREAD

**Issue by AnimeAnalPRO** [termux/termux-x11#408]
After deployment, the picture and sound disappear. I use it for box64\86 from Olegos. When upgrading to Android 13, there was such a problem. Before that, there was 12 android, there was no such problem.
I'm using the latest build that came out recently.

**Comment by twaik** [comment]
1. Try `-legacy-drawing` option.
2. If it des not work contact Olegos.

**Comment by AnimeAnalPRO** [comment]
> 1. Try `-legacy-drawing` option.

where to enter this command?

**Comment by AnimeAnalPRO** [comment]
it didn't help.

**Comment by twaik** [comment]
Try that.
1. In termux install xorg-xclock package. `pkg install xorg-xclock`
2. Start termux-x11 with xorg-xclock. `termux-x11 :10 -xstartup xorg-xclock`.
3. If it did not help try again with `termux-x11 :11 -xstartup xorg-xclock -legacy-drawing`

**Comment by AnimeAnalPRO** [comment]
![Screenshot_20230802-182321_Termux](https://github.com/termux/termux-x11/assets/109460250/787d9a85-041c-4fd8-9795-a25915993d96)
![Screenshot_20230802-182358_Termux](https://github.com/termux/termux-x11/assets/109460250/af1e15a7-5d56-407e-9d4e-1c0405b9b2be)

**Comment by twaik** [comment]
Post logs as text, not screenshots.
I messed up with commandline. 
Type xclock instead of xorg-xclock.

**Comment by AnimeAnalPRO** [comment]
yes, it works now, the clock is displayed. And like how does that help me?

**Comment by twaik** [comment]
Now try to install mesa-demos and check again with `glxgears`.

**Comment by twaik** [comment]
`apt install mesa-demos`
`termux-x11 :10 -xstartup glxgears`

**Comment by AnimeAnalPRO** [comment]
`~ $ apt install mesa-demos
Reading package lists... Done                           Building dependency tree... Done
Reading state information... Done
mesa-demos is already the newest version (9.0.0-2).     0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.                                                  ~ $ termux-x11 :10 -xstartup glxgears
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

~ $`

**Comment by twaik** [comment]
Try force-stopping com.termux with system UI.

**Comment by AnimeAnalPRO** [comment]
it's working now.
shows how many frames it draws in 5 seconds. What's next?

**Comment by twaik** [comment]
That means Termux:X11 works fine on your device. 
After this point you should contact Olegos for support.
That's a 3rd-party environment that I offer zero support for.
