### ISSUE TITLE
Fallback for AHardwareBuffer for devices running SDK 25 (Nougat) or lower?

### ISSUE THREAD

**Issue by Yetangitu** [termux/termux-x11#409]
I'm trying to get this X server to run on a device running LineageOS 14.1 (SDK level 25 aka 'Nougat', Android 7.1.2). There seems to be one thing keeping it from working - or at least I have discovered the first thing from making this happen - this being the use of `AHardwareBuffer` in `renderer.c`  and `InitOutput.c`. Given that _termux_ is often used on older hardware like the Galaxy Tab 3 10.1 I'm using it on it would extend the usefulness of _termux-x11_ if this also worked on such devices.

I found another project which deals with the lack of `AHardwareBuffer` on API < 26:

https://github.com/fuyufjh/GraphicBuffer

Would it be of interest to this project to have something like this implemented so as to enable its use on older - but still quite useable - devices?

**Comment by twaik** [comment]
This application supports only Android 8+ devices.

**Comment by Yetangitu** [comment]
Yes, like I described already and most likely due to the use of `AHwardwareBuffer` - comment it out and the project compiles just fine. It doesn't work but that is another story. Including a fallback like the one described in the linked project would probably enable it to work on Android 7- devices, most likely down to 4.4.

**Comment by twaik** [comment]
If you are porting to devices with lower Android version you should understand that I will not support it, it will be fully under your responsibility. 

In the case if your device lacks AHB suport you should pay attention on `legacy-drawing` option. It uses `glTex[Sub]Image2d` to upload image to screen instead of using AHBs. You can use it for drawing.

**Comment by Yetangitu** [comment]
Using the fallback I linked to might enable the use of `android::GraphicsBuffer` - i.e. what AHB boils down to. That seems to be the point of that project.

**Comment by twaik** [comment]
> Including a fallback like the one described in the linked project would probably enable it to work on Android 7- devices, most likely down to 4.4.

AHB is not the only reason to increase minSdkVersion. I am not really interested in supporting older devices.

**Comment by Yetangitu** [comment]
What other reasons are there? As said the project builds just fine when references to AHB are _ifdef_'d out.

**Comment by twaik** [comment]
AHardwareBuffer API is not the only one which is missing on older Android versions. i.e. Pointer Capture API. 

> What other reasons are there?

As I said before I am not really interested in supporting older Android versions.
