### ISSUE TITLE
How to Get the APK 

### ISSUE THREAD

**Issue by LSBR29** [termux/termux-x11#41]
I'm a beginner, I don't know the programming well, how do I get the APK to install Termux: X11?

**Comment by WMCB-Tech** [comment]
You should be able to get apk's through [Actions build workflow](https://github.com/termux/termux-x11/actions/workflows/debug_build.yml). select one successful ci log and find **termux-x11** at the bottom

https://github.com/termux/termux-x11/actions/runs/1289315293
