### ISSUE TITLE
Termux X11 performance is too low

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#410]
Well, these are just my hypotheses and observations. I don't have any major evidence.

When virglrenderer and the relevant patches were created OpenGL performance seems to me on my phone exceeded 180 points in glmark2 after the introduction of SHM.

But I have only benchmarks before SHM patch ;(
https://github.com/termux/termux-packages/issues/14517#issuecomment-1458118632

Whereas now the results after tigervncserver are higher (~100-105 points) than on Termux-X11 (~90-95 points). Usually it was Termux X11 that was faster than VNC.

I wonder if you also have such observations, maybe there is a bottleneck in the performance of Termux X11 that limits OpenGL rendering or a similar thing will work?

**Comment by twaik** [comment]
Did you test performance in proot environment?

**Comment by IntinteDAO** [comment]
> Did you test performance in proot environment?

Sadly no, it's native termux on Moto G100.

**Comment by twaik** [comment]
Wdym by saying SHM patch?

**Comment by twaik** [comment]
This patch is related to virglrenderer package, not to termux-x11. You should open issue in `termux-packages` repository.

**Comment by IntinteDAO** [comment]
@twaik 
Well, yes. But it's little strange that it's slower than VNC (but on Xfce4, on IceWM, OpenBox etc. it's faster, but it's look like VNC is somehow locked ...?).

Is it possible to download somehow older version of Termux X11 without build, I mean version on Xwayland etc?

I see that you can download archive versions, but up to 2 months in advance.

**Comment by twaik** [comment]
Xwayland was updated a few times so it will not work with old termux-x11 build. And I made termux-x11 builtin server to avoid using external dependencies (and to optimize output of image with AHardwareBuffer of course).

**Comment by IntinteDAO** [comment]
Hm, ok. Thanks

**Comment by twaik** [comment]
Older builds were created more than three monthes ago and were expired so I removed them from the list.

**Comment by IntinteDAO** [comment]
@twaik 
i3, 166 points in glmark2
icewm 120
xfce4 100
android native glmark2 2000

Interesting why are so differences between wms

**Comment by twaik** [comment]
Try to start it without wm.

**Comment by IntinteDAO** [comment]
without any wm - 109
i3wm - now 114
Xterm - 110
i3wm again - 120

No ... idea ...
Maybe I should create a discuss about it on Termux? Maybe more results will be better.
