### ISSUE TITLE
New termux-x11-nightly package did not work

### ISSUE THREAD

**Issue by atamshkai** [termux/termux-x11#413]
When i upgraded to termux-x11-nightly 1.03.00,it killed itself.

**Comment by twaik** [comment]
Post logs of logcat.

**Comment by twaik** [comment]
Any updates?

**Comment by twaik** [comment]
@atamshkai ?

**Comment by twaik** [comment]
@atamshkai ?

**Comment by twaik** [comment]
Can you please post some logs?

**Comment by twaik** [comment]
Closing this due to the lack of activity.
