### ISSUE TITLE
Dragging is not working.

### ISSUE THREAD

**Issue by xbit1010** [termux/termux-x11#414]
I am using termux-x11 in Samsung Dex Mode with hardware mouse and keyboard.
Since Build #466, dragging is not working in some applications.(drawing in gimp, chromium's contents, code-oss's text, Ristretto Image Viewer's image move, icon drag and drop in Thunar)
But other applications is working. xfce's application window(window manager), xfce's background icon(Home, Trash..), firefox's contents, xfce-terminal's text)

**Comment by xbit1010** [comment]
Enabling the option "Capture external mouse when possible" works fine.
Before Build #466, it was possible without enabling it.

Additionally, termux-x11 is running on an external monitor.(in Samsung Dex Mode)

**Comment by twaik** [comment]
Check the latest artifact.
