### ISSUE TITLE
[Clipboard] Termux X11 crashing on this file

### ISSUE THREAD

**Issue by IntinteDAO** [termux/termux-x11#415]
GUESS WHO'S BACK ;)

Movie:
https://tube.midov.pl/w/m3MDsTy78VMyzP7h5vid9a

File:
https://paste.ottertelecom.com/?ee59cd39e55b1ec7#Agou7T26EUhn1U7TDVDBtL7W179n5Qrnb13uePKRgbV6

The secondary clipboard works great (middle mouse), crashing only on primary clipboard.
Automatic uploading clipboard to Android is Disabled.

**Comment by twaik** [comment]
I need the log.

**Comment by IntinteDAO** [comment]
@twaik 
log:
https://bin.0xfc.de/?545f10fba1cf26e2#J8xGpRws95wzP8nWgnYfSNjzT3UkdufW4gnGjARbcnND

**Comment by twaik** [comment]
I need **the whole** log.

**Comment by ask9027** [comment]
+1
[log (1).txt](https://github.com/termux/termux-x11/files/12268886/log.1.txt)

**Comment by IntinteDAO** [comment]
Whole log also :P
https://paste.techbag.app/?2a04ad2ea2a24d83#3Mm458tUFWCYusKQY2grJvNsXSsmdXykHspC3y8cx4z1

**Comment by twaik** [comment]
Ok, I've got this. 
https://stackoverflow.com/questions/60722231/jni-detected-error-in-application-input-is-not-valid-modified-utf-8-illegal-st

**Comment by ask9027** [comment]
> +1 [log (1).txt](https://github.com/termux/termux-x11/files/12268886/log.1.txt)

com.termux.x11: java_vm_ext.cc:594] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf9

**Comment by twaik** [comment]
Check the latest artifact.

**Comment by ask9027** [comment]
Working Now...
