### ISSUE TITLE
Can it used in proot termux environment?

### ISSUE THREAD

**Issue by sukualam** [termux/termux-x11#42]
While this works on termux desktop, can it run on proot inside termux? Like debian..? Thx

**Comment by WMCB-Tech** [comment]
Yes, you just need to bind UNIX sockets from `$PREFIX/tmp` to your debian's `/tmp`
a proot argument to expose host tmpdir as:
`proot -b $PREFIX/tmp:/tmp`

in proot distro, you can do `proot-distro login debian --shared-tmp`

then export the DISPLAY to your program and start your desired GUI application
