### ISSUE TITLE
[Question] How to access termux x11 via ssh

### ISSUE THREAD

**Issue by SUMITDEY69** [termux/termux-x11#422]
Hey devs,
How can I access termux x11 via SSH on another device(another Android) remotely ?

Hoping for your response 🤞

**Comment by twaik** [comment]
You should start X server as stated in README.md and it will be available.

**Comment by SUMITDEY69** [comment]
Isn't

**Comment by twaik** [comment]
Give some details.

**Comment by twaik** [comment]
@SUMITDEY69 ?

**Comment by SUMITDEY69** [comment]
In my scenerio, I want to access XFCE4 desktop environment from my phone 📱 to another phone via ssh

**Comment by SUMITDEY69** [comment]
Local programs on remote

**Comment by twaik** [comment]
In this case `ssh -X` does not fit here. 
1. Start termux-x11 on one phone with TCP listening and disabling access control. `termux-x11 :0 -listen tcp -ac -xstartup xfce4-session`
2. Forward local 6000 (X server's 0 display port) to remote 6000 port (remote = phone with Termux:X11 running). `ssh -L 6000:localhost:6000 10.0.0.44` . It will start regular ssh session, do not close it.
3. Open new termux session and start program you need. `DISPLAY=:0 pcmanfm`.

**Comment by twaik** [comment]
Pay attention that you may have some delays because of forwarding ports to remote device. And of course some extensions like DRI3, GLX and MIT-SHM will be not available (because they require local X server).
