### ISSUE TITLE
gralloc-mapper is missing

### ISSUE THREAD

**Issue by aman-boop** [termux/termux-x11#425]
getting error when try to run termux-x11 server

```  
gralloc-mapper is missing
(EE)
Fatal server error:
(EE) Caught signal 6 (Aborted). Server aborting
(EE)
Segmentation fault 
```

**Comment by twaik** [comment]
Can you please post the whole log?

**Comment by twaik** [comment]
And I need you to say which build you used.

**Comment by twaik** [comment]
It would be much better to extract debug log.
https://github.com/termux/termux-x11/blob/master/README.md#logs

**Comment by twaik** [comment]
Do you use `proot` or `proot-distro`?

**Comment by aman-boop** [comment]
proot-distro

**Comment by twaik** [comment]
Does `termux-x11` work outside of proot-distro?

**Comment by aman-boop** [comment]
yes, i just used with xfce4.

**Comment by twaik** [comment]
Well, I can say that it is some problem of `proot-distro`. You should create new issue in `proot-distro`'s repo and probably pin `strace -e trace=file` log of termux-x11 of both inside and outside `proot-distro` runs. Probably `proot-distro` simply does not bind some folder which contains your gralloc-related libraries.
