### ISSUE TITLE
X11 screen error when setting up full screen in Galaxy Tab S9 Ultra

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#428]
I bought a new `Galaxy Tab S9 Ultra 5G`
After installing and running `Termux PRoot Linux`

There was a problem.
If you set the `Termux-X11` to `full screen` on the new device

Like the video below, the screen is blinking, and the top and bottom navigation bars are blinking
Symptoms of continuous exposure occur. (00:08~00:25)

https://github.com/termux/termux-x11/assets/101167173/dde3a568-b725-4c1b-805f-21f3fc5e8966

If you turn off the full screen option, there are no applicable symptoms
In `DeX mode`, turning on the full screen option does not cause the symptoms.

This appears to be a problem with a full screen in normal Android mode.

I'm forwarding the log file.
[log_20230818.txt](https://github.com/termux/termux-x11/files/12372585/log_20230818.txt)

**Comment by twaik** [comment]
[app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12462514/app-arm64-v8a-debug.zip)
Please, check if it happens with apk from this archive.

**Comment by hansm629** [comment]
> [app-arm64-v8a-debug.zip](https://github.com/termux/termux-x11/files/12462514/app-arm64-v8a-debug.zip) Please, check if it happens with apk from this archive.

oh!
No symptoms will occur! I think it's fixed! :)
