### ISSUE TITLE
Do not display a prompt bar for Chinese input methods

### ISSUE THREAD

**Issue by SongZihui-sudo** [termux/termux-x11#431]
I use [termux-x11-arm64-v8a-debug](https://github.com/termux/termux-x11/suites/15160667057/artifacts/866352990.)（Adding tap-to-move behaviour for touchpads #484）in full screen.
When it comes to the lower version, it's okay, but I can't switch to the latest version.   
The input method is fcitx5   
My device is Huawei Matepad11   
I have set the resolution to 1680x1050   
I used the window manager openbox   
Like this:
![Screenshot_20230821_153359_com termux x11](https://github.com/termux/termux-x11/assets/77034643/c9757f42-f523-46eb-8b4d-04a7eb35526f)   
![Screenshot_20230821_153405_com termux x11](https://github.com/termux/termux-x11/assets/77034643/00dd27cb-fac4-4341-8d5d-a7684990c751)   
There is no response or a black bar appears below, and clicking on the input method right-click menu in the taskbar displays an error

**Comment by twaik** [comment]
Termux:X11 is a X server. Unfortunately it is not responsible for your input method.

**Comment by twaik** [comment]
Wait, is it ok on older builds?

**Comment by SongZihui-sudo** [comment]
> Wait, is it ok on older builds?

Previously, I used 1.02 as OK, but today I downloaded 1.03

**Comment by twaik** [comment]
Can you find the exact build in Actions tab which was the last one which works?

**Comment by SongZihui-sudo** [comment]
> Can you find the exact build in Actions tab which was the last one which works?

Previously, it was 1.2.06

![Screenshot_20230821_221256](https://github.com/termux/termux-x11/assets/77034643/c9a93906-e3c6-4676-9a7b-90d0e903bcd2)

**Comment by twaik** [comment]
Not a version. A build. From "Actions" tab. 
![Uploading Screenshot_20230821_173536_Chrome.png…]()

**Comment by twaik** [comment]
![Screenshot_20230821_173536_Chrome](https://github.com/termux/termux-x11/assets/9674930/16817cef-3f15-4eac-bd50-53d99310f92f)

**Comment by SongZihui-sudo** [comment]
> ![Screenshot_20230821_173536_Chrome](https://user-images.githubusercontent.com/9674930/262056103-16817cef-3f15-4eac-bd50-53d99310f92f.png)

![Screenshot_20230821_233936](https://github.com/termux/termux-x11/assets/77034643/7542d10e-f125-40de-a150-8010a02cb6c5)

I've tried a lot, but it doesn't work

**Comment by twaik** [comment]
Companion package is a simple loader. Install the main package (which is `termux-x11-<arch>-debug.apk`...

**Comment by SongZihui-sudo** [comment]
I've changed several apps. I'll try reinstalling the input method, or switch to xfce4.




---Original---
From: "Twaik ***@***.***&gt;
Date: Tue, Aug 22, 2023 02:39 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [termux/termux-x11] Do not display a prompt bar for Chinese inputmethods (Issue #431)




 
Companion package is a simple loader. Install the main package (which is termux-x11-<arch&gt;-debug.apk...

**Comment by SongZihui-sudo** [comment]
OK, I'll try something else.



---Original---
From: "Twaik ***@***.***&gt;
Date: Tue, Aug 22, 2023 02:45 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [termux/termux-x11] Do not display a prompt bar for Chinese inputmethods (Issue #431)




 
"Several" is not to much. It may be broken 50 builds before latest build...

**Comment by twaik** [comment]
Check this build. https://github.com/termux/termux-x11/actions/runs/5632869495

**Comment by SongZihui-sudo** [comment]
Ok, I'll try it tomorrow. My time is 02:52 now.




---Original---
From: "Twaik ***@***.***&gt;
Date: Tue, Aug 22, 2023 02:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [termux/termux-x11] Do not display a prompt bar for Chinese inputmethods (Issue #431)




 
Check this build. https://github.com/termux/termux-x11/actions/runs/5632869495

**Comment by SongZihui-sudo** [comment]
> Check this build. https://github.com/termux/termux-x11/actions/runs/5632869495

![Screenshot_20230822_110202_com termux x11](https://github.com/termux/termux-x11/assets/77034643/1aadc366-3f34-49ba-8df3-1e9f2613a73c)   

I unticked in the config after pressing the screen dpi to use, it shows up and is no longer a black box.   

![Screenshot_20230822_110608_com termux x11](https://github.com/termux/termux-x11/assets/77034643/6e11f941-0a92-410a-916b-7c9aa2fde47e)    

[There is an issue under FCITX5](https://github.com/fcitx/fcitx5/issues/47)

**Comment by SongZihui-sudo** [comment]
> Check this build. https://github.com/termux/termux-x11/actions/runs/5632869495

Thank you.

**Comment by twaik** [comment]
Does it work?

**Comment by SongZihui-sudo** [comment]
> Does it work?

It's also ok in [Adding tap-to-move behaviour for touchpads #484
](https://github.com/termux/termux-x11/actions/runs/5882929170)

**Comment by SongZihui-sudo** [comment]
> Does it work?

It's just that the position is a bit incorrect
