### ISSUE TITLE
Termux-X11 app crash when you click the touchpad after activating the "Capture external mouse when possible" option

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#432]
I bought Galaxy Tab S9 Ultra 5G

I received the keyboard cover today.

Tested after installing the latest build of Termux-X11

If you click the touchpad with the `Capture external mouse when possible` option enabled, the Termux-X11 app will crash as it is forced to shut down.

This is a symptom video.

https://github.com/termux/termux-x11/assets/101167173/f69860d8-b4df-4339-93f8-55b1bc55d458

Please check.

**Comment by hansm629** [comment]
> Post debug log please (with `TERMUX_X11_DEBUG=1`).

[log_20230823.txt](https://github.com/termux/termux-x11/files/12411163/log_20230823.txt)

is here :)

**Comment by twaik** [comment]
Please, check the latest build. https://github.com/termux/termux-x11/actions/runs/5942053514

**Comment by hansm629** [comment]
> Please, check the latest build. https://github.com/termux/termux-x11/actions/runs/5942053514

Thank you.
Crash symptoms are gone

But you have other symptoms.
Touchpad compatibility issue. (Invert xy axis, tap gesture not working, pointer too fast)

I will test this case more and post an issue separately :)

**Comment by twaik** [comment]
Touchpad axis inversion fix was reversed vecause it caused bugs on some other devices. I am planning to add touchpad inversion option to preferences.

**Comment by hansm629** [comment]
> Touchpad axis inversion fix was reversed vecause it caused bugs on some other devices. I am planning to add touchpad inversion option to preferences.

Thank you for checking

Then, after you finish your work today
Other compatibility issues will be posted separately!

The issue that has been identified is

- Tab Gesture Inoperative
- Pointer speed out of control

I think these are the two!

I'll upload it soon with the log file.

**Comment by twaik** [comment]
Logging will not show problems with that. There is no touch event debugging.

**Comment by hansm629** [comment]
> Logging will not show problems with that. There is no touch event debugging.

This is the log file.
[log_20230823_2.txt](https://github.com/termux/termux-x11/files/12411436/log_20230823_2.txt)

More than issues where tap gestures don't work
There's a bigger issues


Pointer speed is operating at an uncontrollable speed.

The mouse sensitivity setting in Ubuntu xfce is also not applicable.
