### ISSUE TITLE
Turnip issue

### ISSUE THREAD

**Issue by Sparda991** [termux/termux-x11#437]
Hi. I have problems with turnip on my phone. Turnip and turnip dri3 are bugged.
Out of four kernels, only one works properly. Is it possible to solve this issue? Here is a ss of my problem.
![Screenshot_20230825-184512_Termux_X11](https://github.com/termux/termux-x11/assets/96723119/f0075781-e0bd-4b6c-920f-50fcb4828d94)

**Comment by twaik** [comment]
It is related to turnip driver, not to termux-x11.
