### ISSUE TITLE
Overlayed Termux-x11

### ISSUE THREAD

**Issue by DrSay123** [termux/termux-x11#442]
I recently conducted the following test: I launched a banal benchmark of gears as usual (I went to termux, then to termux x11), and then I tried to run all this in picture-in-picture mode (instead of termux-x11 I switched to termux). Fps itself grow by as much as 40-80%.I concluded: on my Android firmware, Termux get fewer resources in the background than it can. This also explains why my sound lags when I'm in termux-x11, but stops lagging as soon as I switch to termux.I would really like the author of termux-x11 to do something like virgl overlay. Then android will assume that we are in termux itself and we will get from this 
1) Maximum performance 
2) Normal sound (specifically in my case)
So is this possible? PiP mode is not what I need because I can't stretch it on full screen + I can't control mouse/other things in PiP mode.

**Comment by twaik** [comment]
Not going to be implemented.

**Comment by DrSay123** [comment]
> you can try to use termux:float, it could be minimized just don't forget to kill termux
> 
> killall com.termux
Thats not fix actually( Because audio in this case starts to doubling

**Comment by romanovj** [comment]
> Because audio in this case starts to doubling

shouldn't

**Comment by twaik** [comment]
I implemented sharedUserId flavor of termux-x11 which does not let Android think termux is in foreground, so termux processes do not get throttled.
It is installable only with github termux version, but anyways is should be fine.
Enjoy.

**Comment by twaik** [comment]
Fixed by d24418e4fdc2a84313048d787430d1d69ad6dab8.
