### ISSUE TITLE
Mouse controls

### ISSUE THREAD

**Issue by Sparda991** [termux/termux-x11#443]
Hi. I was just wondering if you could make a bit better mouse controls for mouse?
Like button for right click (can toggle it on or off) and two finger tap, hold one and move other finger to drag? It would make something like Termuxbox or Box64Droid viable for strategy games and similiar.

**Comment by twaik** [comment]
It is possible to make some overlay view for this. I will check what I can do.

**Comment by twaik** [comment]
Check the latest build. 
![image](https://github.com/termux/termux-x11/assets/9674930/90b05eda-ac26-4714-8ae3-0b244a8d5776)

![image](https://github.com/termux/termux-x11/assets/9674930/9c351813-7478-4433-ad92-f3c5ad13cf93)
