### ISSUE TITLE
Hardware back-keys doesnt show software keyboard instead it respond as ESC keys

### ISSUE THREAD

**Issue by HariMatoson** [termux/termux-x11#444]
Hardware back-keys doesnt show software keyboard instead it respond as ESC keys is this a feature? while if i use navigation bar it shows my keboard.

Android 10 api:29

**Comment by twaik** [comment]
What exactly do you mean by saying "hardware back-keys"?

**Comment by twaik** [comment]
?

**Comment by HariMatoson** [comment]
> What exactly do you mean by saying "hardware back-keys"?

sorry i meant is a physical back keys in old android phones

**Comment by twaik** [comment]
Can you please check the latest build?

**Comment by twaik** [comment]
@HariMatoson ?

**Comment by twaik** [comment]
Fixed by 44d0d951c8e43f17eccc2381668dbff83ead6bab

**Comment by HariMatoson** [comment]
> @HariMatoson ?

I'm really so sorry, I was very busy lately at school, I'll give it a test on newer build

**Comment by HariMatoson** [comment]
> Fixed by [44d0d95](https://github.com/termux/termux-x11/commit/44d0d951c8e43f17eccc2381668dbff83ead6bab)

Unfortunately the problem still persist

**Comment by twaik** [comment]
[app-universal-debug.zip](https://github.com/termux/termux-x11/files/12505259/app-universal-debug.zip)
Install this apk, start termux-x11 with `TERMUX_X11_DEBUG=1` as stated in `https://github.com/termux/termux-x11#logs` (without DE or any program), press "Back key" a few times and post the log here.

**Comment by HariMatoson** [comment]
> [app-universal-debug.zip](https://github.com/termux/termux-x11/files/12505259/app-universal-debug.zip) Install this apk, start termux-x11 with `TERMUX_X11_DEBUG=1` as stated in `https://github.com/termux/termux-x11#logs` (without DE or any program), press "Back key" a few times and post the log here.

[x11.log](https://github.com/termux/termux-x11/files/12506044/x11.log)

**Comment by twaik** [comment]
Ok, it is recognised as `KEY_BACK` (158) so I can use this.

**Comment by twaik** [comment]
Ok, https://github.com/termux/termux-x11/actions/runs/6064846586 should fix this.

**Comment by HariMatoson** [comment]
> Ok, https://github.com/termux/termux-x11/actions/runs/6064846586 should fix this.

It did not work I tried it twice and I double check it, just a minute let me get a logs for this

**Comment by HariMatoson** [comment]
> > Ok, https://github.com/termux/termux-x11/actions/runs/6064846586 should fix this.
> 
> It did not work I tried it twice and I double check it, just a minute let me get a logs for this
[x11-2.log](https://github.com/termux/termux-x11/files/12506352/x11-2.log)

**Comment by HariMatoson** [comment]
It now works on https://github.com/termux/termux-x11/actions/runs/6065381487
Thank you :D
