### ISSUE TITLE
There was an error parsing the package

### ISSUE THREAD

**Issue by Mrcubix** [termux/termux-x11#445]
Getting this error while trying to install the app on my older android 7.1.2 tablet running Lineage

Will try to install the app via adb to see if it provide me with an error whenever i have a pc on hand.

**Comment by twaik** [comment]
Termux:X11 is targetet to Android 8+ devices

**Comment by Mrcubix** [comment]
Weird, did not see any of it in the manifest.
Also, this should appear in the readme

**Comment by twaik** [comment]
It is not in manifest, it is in `build.gradle`. I'll add it to the readme.
