### ISSUE TITLE
Mouse acceleration canceller

### ISSUE THREAD

**Issue by shiumano** [termux/termux-x11#447]
I don't know what part of Android controls the mouse with what function
If we could parse it out and create a function that does the opposite, I think we could eliminate mouse acceleration.
If mouse acceleration is eliminated, Minecraft, osu, etc. will be played better.

**Comment by twaik** [comment]
Mouse accelleration is controlled by DE settings.

**Comment by shiumano** [comment]
WHAT
I am talking about a physical mouse.
Right now it's in a double configuration with Android settings and DE settings.

**Comment by twaik** [comment]
It can not configured with Android settings since it is only applicable in `capturing` mode...
