### ISSUE TITLE
mobile keyboard not opened

### ISSUE THREAD

**Issue by ask9027** [termux/termux-x11#448]
after commit d224248 , keyboard not opened onBackPressed.

**Comment by ask9027** [comment]
Actualy, OnBackPressed it act like Esc key

**Comment by HariMatoson** [comment]
> Actualy, OnBackPressed it act like Esc key
> 
> ```shell
> 09-03 20:21:53.796  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:53.796  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> 09-03 20:21:54.441  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:54.441  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> 09-03 20:21:55.068  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:55.068  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> ```


weird it also occurred on mine as well when i switch over to software navigation button

**Comment by HariMatoson** [comment]
> Actualy, OnBackPressed it act like Esc key
> 
> ```shell
> 09-03 20:21:53.796  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:53.796  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> 09-03 20:21:54.441  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:54.441  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> 09-03 20:21:55.068  2996  2996 D LorieNative: Sending key: 9 (0 4 1)
> 09-03 20:21:55.068  2996  2996 D LorieNative: Sending key: 9 (0 4 0)
> ```


weird it also occurred on mine as well when i switch over to software navigation button

**Comment by HariMatoson** [comment]
weird it also occurred on mine as well when I switched over back to soft-navigation keys, even when I used hardware keys it still respond as ESC-keys

**Comment by twaik** [comment]
`OnBackPressed` is not used, all keys are handled in `OnKeyListener`.
