### ISSUE TITLE
Custom Keyboard Layout for Termux x11 possible Like Exagear?

### ISSUE THREAD

**Issue by Luihart** [termux/termux-x11#451]
Hi there,
I Hope its Not much to ask for. Since we already got a nice and better Mouse Control now, i Wonder If its possible to Get alternative Keyboard Buttons on the side Like Exagear instead Just on the Button. 

So playing RTS Games on an Android Phone with Essential Keys Like CTRL, ESC, Enter, backspace, Numbers and arrows can be used while have the gamescreen in the middle.

Screenshot from Exagear as Idea:
![Screenshot_2023-09-06-19-45-13-693_com ludashi benchmark](https://github.com/termux/termux-x11/assets/97235637/602e6bd7-aa5c-4d08-b623-893f3f3a20d1)

**Comment by twaik** [comment]
Not planned.

**Comment by RalfWerner** [comment]
@Luihart [Most keys](https://github.com/termux/termux-x11/assets/45426380/a3f936fb-4864-4c21-b586-76887d1ac6e8) can be covered with [config](https://github.com/termux/termux-x11/assets/45426380/20f97d2c-7b8b-4798-8295-a93dc1e44a9b) and switched on and off with "three fingers down".
