### ISSUE TITLE
what is shell-loader?

### ISSUE THREAD

**Issue by aicynide** [termux/termux-x11#452]

**Comment by twaik** [comment]
You should read the comment which explains what it does.
https://github.com/termux/termux-x11/blob/e74df02c41235102e8ad883859b8ee288f11afac/shell-loader/src/main/java/com/termux/x11/Loader.java#L4-14

**Comment by aicynide** [comment]
Why is it separate apk?

**Comment by twaik** [comment]
Bacause it should load the code located in main apk which is inaccessible without invoking some Android API (Java), also it checks main apk signature to make sure it is not loading some malicious code.
