### ISSUE TITLE
I would like to inquire about intermittent frame drops in Termux-x11.

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#456]
I am using Termux-x11 developed by you very well.

Thanks to this, you can use X11 in an Android environment without the need for VNC.
recently Turnip driver has become even closer to perfection after patching DRI3 :)

However, 
the xfce4 session executed in Termux  and PRoot Linux

When you move the program window
Occasionally, the GUI frame may drop or the program window may become distorted.

If it works well, even if you move the program window,
It seems to operate at around 60~120fps.

If the frame rate drops, it will feel slower by about 15 to 30 fps.
Sometimes, the program window gets torn as the program window moves.

Is there room for further performance improvement in the future?

**Comment by hansm629** [comment]
> It is a problem of patched turnip, not of `termux-x11`.

It happens the same with virpipe and llvmpipe.

**Comment by twaik** [comment]
Try `legacy-drawing` option.

**Comment by hansm629** [comment]
Here is my PRoot Linux run script:

```
# /bin/sh
killall -9 termux-x11 pulseaudio virgl_test_server_android
termux-wake-lock; termux-toast "Starting Linux"
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity

termux-x11 :0 -ac & 
virgl_test_server_android &

sleep 3
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

proot-distro login debian --user suid --shared-tmp --no-sysvipc -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4713; GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.6COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 dbus-launch --exit-with-session startxfce4"
``` 

I would like to ask if I can modify it by adding `legacy-drawing` as shown below.

```
# /bin/sh
killall -9 termux-x11 pulseaudio virgl_test_server_android
termux-wake-lock; termux-toast "Starting Linux"
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity

termux-x11 :0 -ac & 
virgl_test_server_android &

sleep 3
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

proot-distro login debian --user suid --shared-tmp --no-sysvipc -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4713; GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.6COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 dbus-launch --exit-with-session -legacy-drawing startxfce4"
```

**Comment by twaik** [comment]
One guy had simillar problems with chroot environment. Try using libandroid-shmem. Reference: https://github.com/termux/termux-x11/issues/334

**Comment by hansm629** [comment]
Thank you for answer.
I'm trying to build and set up the PRoot Debian environment.

Are there any related tutorials?
Maybe I can't find the link.

**Comment by twaik** [comment]
Sorry, I do not have any links or guides.

**Comment by hansm629** [comment]
that's ok
I will inquire directly.

thank you

**Comment by hansm629** [comment]
@twaik 

I tested it with the `legacy-drawing` option and it seems to have fixed the symptom!
The GUI no longer suffers from intermittent frame drops!

`termux-x11 :0 -legacy-drawing &`
I ran it with .


```
# /bin/sh
killall -9 termux-x11 pulseaudio virgl_test_server_android
termux-wake-lock; termux-toast "Starting Linux"
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity

termux-x11 :0 -legacy-drawing &
virgl_test_server_android &

sleep 3
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1
pacmd load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1

proot-distro login debian --user suid --shared-tmp --no-sysvipc -- bash -c "export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4713; GALLIUM_DRIVER=virpipe MESA_GL_VERSION_OVERRIDE=4.6COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 dbus-launch --exit-with-session startxfce4"
``` 

This is a slightly separate question.

For DRI3, which is currently supported as an experimental feature in Termux-x11
I understand that it works in a way that requires a separate patch to Turnip.

meybe a 
Future Termux-x11 roadmap
Even without a separate DRI3 patch from Turnip
Can DRI3 work in Termux-x11 just by enabling dri3 in mesa meson build option?

We are always grateful for your development efforts :)
