### ISSUE TITLE
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/dbus-daemon": library "libexpat.so.1" not found EOF in dbus-launch reading address from bus daemon

### ISSUE THREAD

**Issue by MuhammedEmirArtan** [termux/termux-x11#459]
I am created a bash file that automatically starts the debian 12 and created a x Server.
#!/data/data/com.termux/files/usr/bin/bash

# Enable PulseAudio over Network
pulseaudio --start --load="module-native-protocol-tcp auth-ip-acl=127.0.0.1 auth-anonymous=1" --exit-idle-time=-1

# Prepare termux-x11 session
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :0 >/dev/null &

# Wait a bit until termux-x11 gets started.
sleep 3

# Login in PRoot Environment. Do some initialization for PulseAudio, /tmp directory
# and run xfce as user galaxy.
# See also: https://github.com/termux/proot-distro
# Argument -- acts as terminator of proot-distro login options processing.
# All arguments behind it would not be treated as options of PRoot Distro.
proot-distro login debian --shared-tmp -- /bin/bash -c  'export PULSE_SERVER=127.0.0.1 && export XDG_RUNTIME_DIR=${TMPDIR} && su - root -c "env DISPLAY=:0 gnome-session"'

exit 0

It crashes with
 CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/dbus-daemon": library "libexpat.so.1" not found
EOF in dbus-launch reading address from bus daemon

**Comment by twaik** [comment]
Not related to `termux-x11`. Probably a problem of a partial upgrade which is not supported in termux.
