### ISSUE TITLE
C++ SFML Issue

### ISSUE THREAD

**Issue by binhvo7794** [termux/termux-x11#466]
Sfml program can't run on termux-x11 (openbox)
![Screenshot_20230920-223611_Launcher 3](https://github.com/termux/termux-x11/assets/66165345/eedf7d65-4913-4980-9ed6-72aaf8b297e3)

**Comment by binhvo7794** [comment]
This is my code
![Screenshot_20230920-224545_Launcher 3](https://github.com/termux/termux-x11/assets/66165345/3f473795-7384-49e2-b477-e7df9ee382f2)

**Comment by twaik** [comment]
Did you export DISPLAY? Try to run that from X11 shell.

**Comment by binhvo7794** [comment]
> Did you export DISPLAY? Try to run that from X11 terminal.

Already, window manager is visible in termux-x11

**Comment by binhvo7794** [comment]
![Screenshot_20230920-231720_Launcher 3](https://github.com/termux/termux-x11/assets/66165345/d72c6afc-9c87-492d-b922-e234b60ee7ce)

**Comment by twaik** [comment]
Environment variables exported inside script are only visible inside programs executed inside this script. Export DISPLAY manually.

**Comment by twaik** [comment]
I did not ask if you see window manager. I asked you to open terminal in that window manager and start your program there...

**Comment by binhvo7794** [comment]
> I did not ask if you see window manager. I asked you to open terminal in that window manager and start your program there...

It worked 🤩
![Screenshot_20230921-003009_Launcher 3](https://github.com/termux/termux-x11/assets/66165345/58baf9ed-32cd-4b92-a3db-47924489a88d)
