### ISSUE TITLE
Winetricks

### ISSUE THREAD

**Issue by Sparda991** [termux/termux-x11#467]
Hi. Do you maybe know a fix for Winetricks not working with newer versions of Termux X11? Previous 1.02.00 works with no issues, 1.03.00 crashes termux x11 when selecting anything in Winetricks

**Comment by twaik** [comment]
Does it happen with the latest nightly?

**Comment by Sparda991** [comment]
> Does it happen with the latest nightly?


> Does it happen with the latest nightly?

I am using build #507 from actions tab

**Comment by twaik** [comment]
Do you have a crash log?

**Comment by Sparda991** [comment]
> Do you have a crash log?

Sorry, I dont know how to take logs. How to do it?

**Comment by twaik** [comment]
I'm not familiar with winetricks. You should figure it out on your own.

**Comment by Sparda991** [comment]
> I'm not familiar with winetricks. You should figure it out on your own.

[debug.log](https://github.com/termux/termux-x11/files/12706718/debug.log)

Does this help? 

Issue is, winetricks gui appears, and when I press OK on "Select the default prefix", termux x11 crashes

**Comment by twaik** [comment]
Is that a crash of termux-x11 or a crash of winetricks? 
According to the log you provided there is no crash, only error about the wrong usage.
```
Unknown arg ZINK:
Usage: ./winetricks [options] [command|verb|path-to-verb] ...
Executes given verbs.  Each verb installs an application or changes a setting.
```

**Comment by twaik** [comment]
Winetricks is a 3rd-party app that I offer zero support for.
In other words: Use at your own risk and we take zero responsibility for what that app does to Termux or your device.

**Comment by twaik** [comment]
Also I see that you are using BOX64 which is 3rd-party app too.
