### ISSUE TITLE
Rebind volume down key for toggling additional keyboard

### ISSUE THREAD

**Issue by ikcikoR** [termux/termux-x11#472]
Would be amazing to be able to rebind the additional keyboard toggle to something else, in case one actually wants to lowe volume of some program.

The key that a lot of android phones have to launch voice assistant would likely be perfect as I'm guessing there is a small overlap between people who use Google Assistant or whatever and people who are into Linux-related stuff is likely rather small

**Comment by twaik** [comment]
There is three-finger swipe down for toggling keyboard.

**Comment by twaik** [comment]
Fixed by 033ee166a8351f0304aa6a0ccafb02170e483369 .
