### ISSUE TITLE
[Bug]: crash when opening 'preferences' after upgrading from old version

### ISSUE THREAD

**Issue by AlphaBs** [termux/termux-x11#475]
### Problem description

Termux:X11 application crashed when I press 'PREFERENCES' after upgrading the application.
[logcat](https://pastebin.com/eqXEaPxy)

The application must be reinstalled to solve 

### What steps will reproduce the bug?

1. Install old Termux:X11 application
2. Upgrade Termux:X11 application to the latest version (1.03.00)
3. Open the application and press 'PREFERENCES' button

### What is the expected behavior?

maybe the format of preferences in old version is incompatible with newer version.

**Comment by ask9027** [comment]
clear all data or uninstall and reinstall again
