### ISSUE TITLE
termux-x11 command gets killed everytime i switch to termux:x11 app

### ISSUE THREAD

**Issue by FindingMeaning** [termux/termux-x11#478]
![Screenshot_20231001-213211.png](https://github.com/termux/termux-x11/assets/146155413/6893a1de-0f13-41b7-95bb-1699192f61b3)

This is the script i'm using :

```
#!/data/data/com.termux/files/usr/bin/bash

export XDG_RUNTIME_DIR=${TMPDIR}

termux-x11 :0 &> /dev/null &

sleep 3

DISPLAY=:0 startxfce4 &> /dev/null

exit 0
```

i run this script then as soon as i open termux:x11 app the command gets killed.

NOTE: somehow when i use split-screen the command run without being killed.

![Screenshot_20231001-214431.png](https://github.com/termux/termux-x11/assets/146155413/a3756a85-f7ac-4546-acf5-67241a1995de)

Am i doing something wrong here ?

Btw I wanted to thank the whole termux team and community all because of you geniuses i can learn programming in my phone. ❤️

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/blob/master/README.md#logs

**Comment by FindingMeaning** [comment]
termux-x11 :1 -xstartup "dbus-launch --exit-with-session xfce4-session"

This worked !!! Thank you very much !!! ❤️
