### ISSUE TITLE
[Bug]: Network socket issue when connecting to X11

### ISSUE THREAD

**Issue by AbdulWahabButt17** [termux/termux-x11#479]
### Problem description

This issue was not present around 2 months ago but it has suddenly appeared out of nowhere. I use an custom XCFE environment on my termux installation and install it around 3 months ago and had been using since but had to reset my device so i have to reinstall it, it was all the setup but not an issue has appeared that is not letting me use the XCFE environment at all. And i have tried almost all other XCFE environments as well so i have reason to believe the issue is with Termux and Termux X-11.

Error message:
(xfwm4:3206): xfwm4-WARNING **: 05:07:54.382: Failed to connect to session manager: Failed to connect to the session manager: Could not open network socket

I'm not 100% sure whats causing this and have tried almost everything but nothing seems to work unfortunately.

### Steps to reproduce the behavior.

1. Install Termux and Termux X11
2. Install the Custom XCFE environment By PhoenoxByrd on GitHub
3. After completing setup just enter "start" in the terminal to automatically start the X11 server, XCFE environment and X11 app.

### What is the expected behavior?

The start command should launch the X11 server, start the VirGL renderer, Start the XCFE environment and then launch the X11 app, all automatically.

### System information

* Termux application version: v0.118.0
* Android OS version: Android 10
* Device model: LG V40 ThinQ (LM-V405UA), Snapdragon 845(arm64-v8a), 6/64.

**Comment by twaik** [comment]
What is `start`? There is no such script in termux packages.

**Comment by AbdulWahabButt17** [comment]
> What is `start`? There is no such script in termux packages.

That is a custom script that combines multiple scripts with seconds of delay. The problem is not with that but when ever main XFCE environment is started it cannot connect to X11 and gives a Network error or if started again without force closing Termux gives no screens to manage error, all of this used to work flawlessly before it has just now broken.

**Comment by twaik** [comment]
Termux:X11 is not a session manages. It is a X server.
Post the script.

**Comment by AbdulWahabButt17** [comment]
> Termux:X11 is not a session manages. It is a X server.
> Post the script.
> 

Apologies, I was going to do that but forgot, here is the full script that runs from the start command:

```#!/bin/bash

MESA_NO_ERROR=1 MESA_GL_VERSION_OVERRIDE=4.3COMPAT MESA_GLES_VERSION_OVERRIDE=3.2 virgl_test_server_android --angle-gl & > /dev/null 2>&1
sleep 1
XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :1.0 &
sleep 1
am start --user 0 -n com.termux.x11/com.termux.x11.MainActivity > /dev/null 2>&1
sleep 1
env DISPLAY=:1.0 GALLIUM_DRIVER=virpipe dbus-launch --exit-with-session xfce4-session & > /dev/null 2>&1```

**Comment by twaik** [comment]
Sleep is not reliable in this case. Start termux-x11 as it is written in readme.
