### ISSUE TITLE
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by GoldenVadim** [termux/termux-x11#481]
Hello! I'm getting this error while running X11 (program works):
`
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)                                           at libcore.io.IoBridge.open(IoBridge.java:574)          at java.io.FileInputStream.<init>(FileInputStream.java:160)                                                     at java.io.FileInputStream.<init>(FileInputStream.java:115)                                                     at java.io.FileReader.<init>(FileReader.java:60)        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)                      at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)           at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)                       at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)                                     at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)                                    at android.content.res.MiuiResources.<init>(MiuiResources.java:58)                                              at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)                             at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)                           at android.content.res.Resources.getSystem(Resources.java:251)                                                  at android.app.LoadedApk.<init>(LoadedApk.java:253)                                                             at android.app.ContextImpl.createSystemContext(ContextImpl.java:3062)                                           at android.app.ActivityThread.getSystemContext(ActivityThread.java:2854)                                        at com.termux.x11.Loader.createContext(Loader.java:135)                                                         at com.termux.x11.Loader.main(Loader.java:52)           at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)                                          at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:366)                                       Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)                               at libcore.io.Linux.open(Native Method)                 at libcore.io.ForwardingOs.open(ForwardingOs.java:563)                                                          at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)                                                          at libcore.io.IoBridge.open(IoBridge.java:560)          ... 19 more
`

**Comment by twaik** [comment]
Update companion package (`pkg up && pkg i termux-x11-nightly`).
