### ISSUE TITLE
[Bug]: X server only starts when I first launch it. After it pops up a error.

### ISSUE THREAD

**Issue by ilikecoding-197** [termux/termux-x11#484]
### Problem description

I have set up a termux and proot-distro setup. When I first launch termux-x11 in proot-distro, it runs fine. But after that, it crashes with the error:
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

I run proot distro like this :
proot-distro login debian --shared-tmp
And start X with this:
termux-x11 :1 -xstartup xterm

The first time I did it, it worked and displayed a terminal on the x11 app.
After that time, it never worked again, with that error I displayed earlier.

 Termux About section:

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.118.0`  
**VERSION_CODE**: `118`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.19.191-26242230-abS134DLUDS8DWI2`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TP1A.220624.014`  
**DISPLAY**: `TP1A.220624.014.S134DLUDS8DWI2`  
**INCREMENTAL**: `S134DLUDS8DWI2`  
**SECURITY_PATCH**: `2023-07-01`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `samsung`  
**BRAND**: `samsung`  
**MODEL**: `SM-S134DL`  
**PRODUCT**: `a03sutfn`  
**BOARD**: `a03su`  
**HARDWARE**: `mt6765`  
**DEVICE**: `a03su`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi
`

### What steps will reproduce the bug?

Don't really know.

### What is the expected behavior?

To run the X server without it crashing.

**Comment by twaik** [comment]
This error
```
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
```
means `termux-x11` is already running somewhere in background. You can kill its instance with
```
kill `pidof app_process`
```
If it does not work you can stop it by force-stopping Termux (not Termux:X11!) application.

**Comment by ilikecoding-197** [comment]
Thank you!
Im gonna try that.

**Comment by ilikecoding-197** [comment]
Well, that didn't fix it. Now, it pops up this:
`28531 exited, status=0`
I suspect `28531` is the termux-x11 process id.
But when i run ps -A, it still the xterm process i used as xstartup.

**Comment by twaik** [comment]
`28531` is the process started with `-xstartup` option.
