### ISSUE TITLE
Bug:Termux-x11 command just freezes the terminal

### ISSUE THREAD

**Issue by GuythatUhmCreatesRandomStuff** [termux/termux-x11#486]
### Problem description

typing any termux-x11 command makes the terminal just unusable, i can still type stuff into the terminal but they are ignored.

### What steps will reproduce the bug?

Type a termux-x11 command type
Freeze

### What is the expected behavior?

make the terminal just unusable(probally due to termux forcing itself under the required RAM, CPU and GPU to execute the command, even with android settings its working very underpowered even with it only being the only app open)

**Comment by twaik** [comment]
That is not a bug. Termux:X11 is a graphical application that does not accept terminal input. After executing it programs runs in the terminal foreground just like any other program.
