### ISSUE TITLE
The XKEYBOARD keymap compiler (xkbcomp) reports

### ISSUE THREAD

**Issue by HarryMatson** [termux/termux-x11#488]
### Problem description

Device Android version: 10 (running a custom rom)
Termux-x11: 1.03.00-2

Thank you for your wonderful project 🥇 it really helps me on my daily basis learning and exploring new things :)

yesterday I've encountered problems with termux-x11,
xkbcomp keep spamming warning and I've never had this one before, when the time this thing came pop up and spamming, i couldnt connect termux-x11 to proot-distro with xfce4 desktop environment, anymore, but i was able to connect on termux without proot-distro(still spam xkb...).
at first i thought I probably touch something that I didn't noticed so I tried factory reset my phone and it still pops up 
next I flash different roms and even stock yet still occurs

I borrowed my friend phone just to see if he also face this kind of issue, I wasn't shock when I saw that it also occurred on his phone 

will try to grab logs...

### What steps will reproduce the bug?

typing ***termux-x11 :0 &*** was enough to occurred the problem
xkbcomp start spamming and I couldn't connect to chroot and proot 

### What is the expected behavior?

it supposed to be connecting without spamming.

Edit: i tried reinstalling xkeyboard-config and using older version of termux-x11 still persist

**Comment by HarryMatson** [comment]
i hope it helps
![termux.txt](https://github.com/termux/termux-x11/files/12999285/termux.txt)

![log.txt](https://github.com/termux/termux-x11/files/12999288/log.txt)

**Comment by twaik** [comment]
`apt install --reinstall xkeyboard-config`

**Comment by twaik** [comment]
Xkbcomp errors are not critical. Treat them as warnings.
