### ISSUE TITLE
Termux-X11 lag on a running Termux box and box64droi

### ISSUE THREAD

**Issue by ArmanIOL** [termux/termux-x11#491]
### Problem description

Hello everyone. My phone is oneplus nord CE2 5G
Rooted stock, Oxygen 12, Dimensity 900 processor, 8 gigs of RAM and 128 gigs of internal memory
Moving the mouse, pressing start, microfreezes appear over time, and it is also noticed that this is also in the box64droid
I tried installing older versions, but they don’t work at all with the termux box, I haven’t tested it with the box64droid.
I've put together a video to show you how to do it in detail.
https://github.com/termux/termux-x11/assets/99141319/55373a5d-56de-4ee1-8d05-60027b0a964f
How to get logs?

### What steps will reproduce the bug?

Any step causes freezes

### What is the expected behavior?

When the friezes start, the whole desktop, the whole thing! Starts to freeze for a couple of seconds

**Comment by twaik** [comment]
Can you please make the same video, but with glxgears?

**Comment by ArmanIOL** [comment]
How?

**Comment by twaik** [comment]
Just start glxgears and make video with mouse movements...

**Comment by ewt45** [comment]
it's because termux-x11 is running in termux process, and after you switch termux to background, android think termux is no longer important and freeze it in a few senconds.
disable the termux battery optimiaztion, or keep termux as a foreground floating app

**Comment by ArmanIOL** [comment]
I turned off battery optimization, it didn't help me at all.

**Comment by twaik** [comment]
> Just start glxgears and make video with mouse movements...

**Comment by ArmanIOL** [comment]
> Just start glxgears and make video with mouse movements...

I'll do it right now

**Comment by ArmanIOL** [comment]
> Just start glxgears and make video with mouse movements...

I'll do it right now

**Comment by ArmanIOL** [comment]
> > Just start glxgears and make video with mouse movements...

What about x11?
![Screenshot_2023-11-11-13-37-28-72_00df01c412509efb9bd6450c382822af.jpg](https://github.com/termux/termux-x11/assets/99141319/967557eb-b82d-404b-883f-327d71c69069)

**Comment by twaik** [comment]
> What about x11?

??

**Comment by twaik** [comment]
Most likely it is not a problem of termux-x11, it is a problem of your proot environment.

**Comment by ArmanIOL** [comment]
> Most likely it is not a problem of termux-x11, it is a problem of your proot environment.

How then to switch to chroot?

**Comment by ArmanIOL** [comment]
> Most likely it is not a problem of termux-x11, it is a problem of your proot environment.

How then to switch to chroot?

**Comment by twaik** [comment]
> How then to switch to chroot?

Offtopic here.

**Comment by ArmanIOL** [comment]
> Most likely it is not a problem of termux-x11, it is a problem of your proot environment.

How to switch to chroot container?

**Comment by ArmanIOL** [comment]
> Most likely it is not a problem of termux-x11, it is a problem of your proot environment.

How to switch to chroot container?

**Comment by ArmanIOL** [comment]
> > How then to switch to chroot?
> 
> Offtopic here.

Sorry then

**Comment by ArmanIOL** [comment]
> > How then to switch to chroot?
> 
> Offtopic here.

Sorry then

**Comment by twaik** [comment]
Why do you post mesages twice?

**Comment by ArmanIOL** [comment]
> Why do you post mesages twice?

I don’t know myself, he sends doubles
