### ISSUE TITLE
[Bug]: mesa reports unknown fbconfig attribute from server when LIBGL_DEBUG=verbose is set

### ISSUE THREAD

**Issue by 500InternalError** [termux/termux-x11#492]
### Problem description

To be clear it's just a warning from mesa. I tried to run xfce on zink with a mesa built with xmem's patch, and got ```MESA: error: kopper: could not create texture from pixmap (4)```. So I enabled debug message with ```LIBGL_DEBUG=verbose``` and got ```WARNING: unknown fbconfig attribute from server: tag 0x8060 value 0x8062```. I want to ask could the failed to create texture from pixmap problem be related to this unknown fbconfig attribute problem?

### What steps will reproduce the bug?

Build mesa with xmem's patch, run ```LIBGL_DEBUG=verbose MESA_LOADER_DRIVER_OVERRIDE=zink termux-x11 -xstartup "xfce4-session" &```

**Comment by 500InternalError** [comment]
BTW mesa also warns ```did not find extension DRI_CopySubBuffer version 1```

**Comment by twaik** [comment]
It is a problem of xmem's mesa, not of termux-x11.
