### ISSUE TITLE
[Bug]: can't open preferences , application crashes.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-x11#493]
### Problem description

I'm on Android 9. After I click in the preference button the application crashes.

### What steps will reproduce the bug?

Open preferences.

**Comment by twaik** [comment]
Try to remove application and install it again.

**Comment by Anonymous2716** [comment]
@twaik that fixed it.

**Comment by Anonymous2716** [comment]
@twaik it works now.
