### ISSUE TITLE
[Bug]: Red and blue color channels swapped on build #523 on Exynos

### ISSUE THREAD

**Issue by lengors** [termux/termux-x11#495]
### Problem description

I own a Galaxy S22+ with an Exynos CPU and with build #523 from 20231006 (last successful build from master branch) referent to commit [84901c2](https://github.com/termux/termux-x11/commit/84901c2f1c3761b49477d798efd051daf92be3b8), the red and blue color channels seem to be swapped (red colors become blue and vice-versa, other tones of colors like dark blue-purple ish becomes orange, etc). With the build previous to that one though, there are no issues (#522 from 20231002 referent to commit [4acf4b2](https://github.com/termux/termux-x11/commit/4acf4b2422a70f18065b40b6b29898dc1c5a0b22)).

Some notes:
- I'm using the `-legacy-drawing` flag as without it I get a black screen (this is true independently of which build I choose)
- I have only tested with proot (both on debian and archlinux) using xfce4, but not with termux session or other desktop environment
- I know there's a recent build from 5/6 days ago, but it's from a dependabot branch and not master, so I haven't tried that one

### What steps will reproduce the bug?

- Install termux app
- Install termux-x11 app
- Install `x11-repo` and the `termux-x11` deb package referent to the given `termux-x11` app (from termux-companion packages)
- Give appropriates permissions to apps and setup `termux.properties`
- Install debian (or archlinux) proot with `proot-distro`
- Install `xfce4` desktop environment inside proot
- Open termux-x11 app
- Initialize termux-x11 with command: `termux-x11 :0 -legacy-drawing`
- Start xfce4 session inside proot with `env DISPLAY=:0 dbus-launch --exit-with-session startxfce4`
- Background should have a dark blue-purple ish tint to it, but has orange which indicates red-blue channels are swapped (another way to see this is by going to youtube, duckduckgo or some other website and see the logos have the wrong colors, same with video, thumbnails, what else)

### What is the expected behavior?

Red and blue color channels should be swapped as to give the correct color on, well, anything really.

**Comment by twaik** [comment]
Does it work fine with termux's own xfce4?

**Comment by lengors** [comment]
> Does it work fine with termux's own xfce4? Post screenshots.

No, it also has the same issue (just tested).

Here's a screenshot of what the behavior is (Build #523):
![Screenshot_20231112_154652_Termux](https://github.com/termux/termux-x11/assets/24527258/351fd2ae-d5f7-4c56-8eb2-6b5d5e87c849)

And here's a screenshot of what the behavior should be (Build #522):
![Screenshot_20231112_155054_Termux](https://github.com/termux/termux-x11/assets/24527258/b017c6e5-2604-4f95-a479-9df0ec3be419)

**Comment by twaik** [comment]
Post logs.

**Comment by lengors** [comment]
> Post logs.

From both builds or just the one that doesn't work?

**Comment by twaik** [comment]
The latest one.

**Comment by lengors** [comment]
> The latest one.

Here:

`--------- beginning of main
11-12 16:05:35.028 20018 20018 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10470 <<<<<<
11-12 16:05:35.072 20018 20018 I AndroidRuntime: Using default boot image
11-12 16:05:35.072 20018 20018 I AndroidRuntime: Leaving lock profiling enabled
11-12 16:05:35.072 20018 20018 W libc    : Access denied finding property "odsign.verification.success"
11-12 16:05:35.076 20018 20018 D SecNativeFeatureCppIf: encoded
11-12 16:05:35.076 20018 20018 D SecNativeFeatureCppIf: decoding and unzip finish
11-12 16:05:35.076 20018 20018 D SecNativeFeatureCppIf: use unCompDataBuff. encoded
11-12 16:05:35.077 20018 20018 D SecNativeFeatureCppIf: Free unCompDataBuff
11-12 16:05:35.077 20018 20018 D AndroidRuntime: addProductProperty: pBrand1 is not null
11-12 16:05:35.077 20018 20018 D AndroidRuntime: addProductProperty: not brand or 7
11-12 16:05:35.086 20018 20018 W app_process: ART APEX data files are untrusted.
11-12 16:05:35.088 20018 20018 I app_process: Using CollectorTypeCC GC.
11-12 16:05:35.323 20018 20018 D app_process: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
11-12 16:05:35.323 20018 20018 D app_process: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt70l.dat
11-12 16:05:35.356 20018 20018 W ziparchive: Unable to open '/data/data/com.termux/files/usr/libexec/termux-x11/loader.dm': No such file or directory
11-12 16:05:35.393 20018 20018 E SemDvfsManager_JNI: SemDvfsManager: registerfunction enter
11-12 16:05:35.393 20018 20018 E SemAffinityControl: SemAffinityControl: registerfunction enter
11-12 16:05:35.404 20018 20018 D AndroidRuntime: Calling main entry com.termux.x11.Loader
11-12 16:05:35.410 20018 20018 I Termux:X11 loader: loading /data/app/~~0aP_SQbPsZjLOXrcCYahEw==/com.termux.x11-7YJlSlX1rX6Cx8VcQKqa6g==/base.apk::com.termux.x11.CmdEntryPoint::main of com.termux.x11 application (commit 84901c2f1c3761b49477d798efd051daf92be3b8)
11-12 16:05:35.411 20018 20018 W ziparchive: Unable to open '/data/app/~~0aP_SQbPsZjLOXrcCYahEw==/com.termux.x11-7YJlSlX1rX6Cx8VcQKqa6g==/base.dm': No such file or directory
11-12 16:05:35.411 20018 20018 W ziparchive: Unable to open '/data/app/~~0aP_SQbPsZjLOXrcCYahEw==/com.termux.x11-7YJlSlX1rX6Cx8VcQKqa6g==/base.dm': No such file or directory
11-12 16:05:35.429 20018 20018 W libc    : Access denied finding property "qemu.sf.lcd_density"
11-12 16:05:35.429 20018 20018 W libc    : Access denied finding property "qemu.sf.lcd_density"
11-12 16:05:35.433 20018 20018 D SemCscFeature: Encoded
11-12 16:05:35.434 20018 20018 D SemCscFeature: Encoded
11-12 16:05:35.663 20018 20018 W app_process: unable to execute idmap2: Permission denied
11-12 16:05:35.663 20018 20018 W OverlayConfig: 'idmap2 create-multiple' failed: no mutable="false" overlays targeting "android" will be loaded
11-12 16:05:35.663 20018 20018 W libc    : Access denied finding property "ro.vendor.mtk_model"
11-12 16:05:35.674 20018 20018 I SemTelecomManager: hasSamsungTelecomSystemFeature : true
11-12 16:05:35.683 20018 20018 E SystemServiceRegistry: SemDisplayQualityFeature.ENABLED:false,PLATFORM:
11-12 16:05:35.683 20018 20018 E SystemServiceRegistry: systemservice inputdev:true
11-12 16:05:35.691 20018 20018 D SecIpmManagerFrameworkInitializer:  initial
11-12 16:05:35.695 20018 20018 D nativeloader: Configuring classloader-namespace for other apk . target_sdk_version=0, uses_libraries=ALL, library_path=, permitted_path=/data:/mnt/expand
11-12 16:05:35.697 20018 20018 D nativeloader: Extending system_exposed_libraries: libhumantracking.arcsoft.so:libPortraitDistortionCorrection.arcsoft.so:libPortraitDistortionCorrectionCali.arcsoft.so:libface_landmark.arcsoft.so:libFacialStickerEngine.arcsoft.so:libfrtracking_engine.arcsoft.so:libFaceRecognition.arcsoft.so:libveengine.arcsoft.so:lib_pet_detection.arcsoft.so:libae_bracket_hdr.arcsoft.so:libhigh_res.arcsoft.so:libhybrid_high_dynamic_range.arcsoft.so:libimage_enhancement.arcsoft.so:liblow_light_hdr.arcsoft.so:libhigh_dynamic_range.arcsoft.so:libsuperresolution_raw.arcsoft.so:libobjectcapture.arcsoft.so:libobjectcapture_jni.arcsoft.so:libFacialAttributeDetection.arcsoft.so:libBeauty_v4.camera.samsung.so:libexifa.camera.samsung.so:libjpega.camera.samsung.so:libOpenCv.camera.samsung.so:libVideoClassifier.camera.samsung.so:libtensorflowLite.dynamic_viewing.camera.samsung.so:libImageScreener.camera.samsung.so:libMyFilter.camera.samsung.so:libtflite2.myfilters.camera.samsung.so:libCandidSnapJNI.camera.samsung.so:libHIDTSnapJNI.camera.samsung.so:l
11-12 16:05:35.703 20018 20018 I CmdEntryPoint: commit 84901c2f1c3761b49477d798efd051daf92be3b8
11-12 16:05:35.707 20018 20018 V LorieNative: Using TMPDIR="/data/data/com.termux/files/usr/tmp"
11-12 16:05:35.709 20018 20050 E CmdEntryPoint: Listening port 7892
11-12 16:05:35.710 20018 20050 D TrafficStats: tagSocket(51) with statsTag=0xffffffff, statsUid=-1
11-12 16:05:35.718 20018 20049 D libEGL  : loaded /vendor/lib64/egl/libEGL_samsung.so
11-12 16:05:35.734 20018 20049 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_samsung.so
11-12 16:05:35.734 20018 20045 D LorieNative: window change: 0xb400007a32190020
11-12 16:05:35.736 20018 20049 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_samsung.so
11-12 16:05:35.744 20018 20049 D libEGL  : dlopen (libGLESv2_samsung.so) success at 0x13f281f1aaaf006b
11-12 16:05:35.766 20018 20045 D LorieNative: window change: 0xb400007a3219ee90
11-12 16:05:35.813 20018 20049 W libc    : Access denied finding property "vendor.sbwchelper.debug.enabled"
11-12 16:05:35.813 20018 20049 W libc    : Access denied finding property "vendor.sbwchelper.trace.enabled"
11-12 16:05:35.822 20018 20049 V SVK     : OpenDevice
11-12 16:05:35.822 20018 20049 V SVK     : ------------------------------------------------------------------
11-12 16:05:35.822 20018 20049 V SVK     : Samsung Vulkan version merge SHA1      = None
11-12 16:05:35.822 20018 20049 V SVK     : Samsung Vulkan version revision number = 80e0794
11-12 16:05:35.822 20018 20049 V SVK     : ------------------------------------------------------------------
11-12 16:05:35.822 20018 20049 V SVK     : Entering: Create
11-12 16:05:35.822 20018 20049 V SVK     : --------------------------------------------------------
11-12 16:05:35.822 20018 20049 V SVK     : Application Name:
11-12 16:05:35.822 20018 20049 V SVK     : Vulkan API 1.3 version
11-12 16:05:35.822 20018 20049 V SVK     : --------------------------------------------------------
11-12 16:05:35.828 20018 20049 V SVK     : Exiting: Create
11-12 16:05:35.829 20018 20049 V SVK     : ------------------------------------------------------------------
11-12 16:05:35.829 20018 20049 V SVK     : Samsung Vulkan version merge SHA1      = None
11-12 16:05:35.829 20018 20049 V SVK     : Samsung Vulkan version revision number = 80e0794
11-12 16:05:35.829 20018 20049 V SVK     : ------------------------------------------------------------------
11-12 16:05:35.829 20018 20049 V SVK     : Entering: Create
11-12 16:05:35.829 20018 20049 V SVK     : --------------------------------------------------------
11-12 16:05:35.829 20018 20049 V SVK     : Application Name: app_process
11-12 16:05:35.829 20018 20049 V SVK     : Vulkan API 1.1 version
11-12 16:05:35.829 20018 20049 V SVK     : --------------------------------------------------------
11-12 16:05:35.829 20018 20049 V SVK     : Exiting: Create
11-12 16:05:35.830 20018 20049 D PAL     : m_perSubmitCmdStream size = { TotalChunkDwords:24, AvailableDwords:2017 } (RebuildCommandStreams:1591)
11-12 16:05:35.830 20018 20049 D PAL     : m_acePreambleCmdStream size = { TotalChunkDwords:16, AvailableDwords:2029 } (RebuildCommandStreams:1616)
11-12 16:05:35.830 20018 20049 D PAL     : m_dePostambleCmdStream size = { TotalChunkDwords:24, AvailableDwords:2024 } (RebuildCommandStreams:1729)
11-12 16:05:35.830 20018 20049 D PAL     : m_deCmdStream size = { TotalChunkDwords:200, AvailableDwords:1843 } (RebuildCommandStreams:1732)
11-12 16:05:35.830 20018 20049 D PAL     : m_perSubmitCmdStream size = { TotalChunkDwords:24, AvailableDwords:2017 } (RebuildCommandStreams:1591)
11-12 16:05:35.830 20018 20049 D PAL     : m_acePreambleCmdStream size = { TotalChunkDwords:16, AvailableDwords:2029 } (RebuildCommandStreams:1616)
11-12 16:05:35.830 20018 20049 D PAL     : m_dePostambleCmdStream size = { TotalChunkDwords:24, AvailableDwords:2024 } (RebuildCommandStreams:1729)
11-12 16:05:35.830 20018 20049 D PAL     : m_deCmdStream size = { TotalChunkDwords:200, AvailableDwords:1843 } (RebuildCommandStreams:1732)
11-12 16:05:35.830 20018 20049 D PAL     : m_perSubmitCmdStream size = { TotalChunkDwords:24, AvailableDwords:2017 } (RebuildCommandStreams:1591)
11-12 16:05:35.830 20018 20049 D PAL     : m_acePreambleCmdStream size = { TotalChunkDwords:16, AvailableDwords:2029 } (RebuildCommandStreams:1616)
11-12 16:05:35.830 20018 20049 D PAL     : m_dePostambleCmdStream size = { TotalChunkDwords:24, AvailableDwords:2024 } (RebuildCommandStreams:1729)
11-12 16:05:35.830 20018 20049 D PAL     : m_deCmdStream size = { TotalChunkDwords:200, AvailableDwords:1843 } (RebuildCommandStreams:1732)
11-12 16:05:35.834 20018 20049 I ANGLE   : Version (git hash: 50101db6df97), Renderer (ANGLE (Samsung Xclipse 920) on Vulkan 1.1.179)
11-12 16:05:35.834 20018 20049 D gles-renderer: Xlorie: Initialized EGL version 1.5
11-12 16:05:35.834 20018 20049 D gles-renderer: Xlorie: egl error on line 189: EGL not initialized or failed to initialize
11-12 16:05:35.834 20018 20049 D gles-renderer: Xlorie: egl error on line 199: EGL not initialized or failed to initialize
11-12 16:05:35.834 20018 20049 D gles-renderer: Xlorie: egl error on line 202: EGL not initialized or failed to initialize
11-12 16:05:35.834 20018 20049 D gles-renderer: Xlorie: egl error on line 214: EGL not initialized or failed to initialize
11-12 16:05:35.835 20018 20049 I app_process: [HIDL_FETCH_IMapper] android.hardware.graphics.mapper@4.0: Loaded Mapper successfully.
11-12 16:05:35.837 20018 20049 D libEGL  : ANGLE Info:Debug.cpp:490 (insertMessage): EGL ERROR: eglCreateImageKHR: Sampling from AHardwareBuffer externalFormat 0x5 is unsupported
11-12 16:05:35.837 20018 20049 E gles-renderer: Sampling from HAL_PIXEL_FORMAT_BGRA_8888 is not supported, forcing AHARDWAREBUFFER_FORMAT_R8G8B8X8_UNORM
11-12 16:05:35.885 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:05:35.887 20018 20049 D gles-renderer: renderer_set_window 0xb400007a32190020 -19 -19
11-12 16:05:35.887 20018 20049 D gles-renderer: Xlorie: eglCreateWindowSurface failed.
11-12 16:05:35.887 20018 20049 D gles-renderer: Xlorie: egl error on line 368: Invalid native window
11-12 16:05:35.887 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:05:35.888 20018 20049 D gles-renderer: renderer_set_window 0xb400007a3219ee90 1080 1101
11-12 16:05:35.888 20018 20049 W vulkan  : CreateSwapchainKHR(VkSwapchainCreateInfoKHR.imageColorSpace = 1000104013) failed: Unsupported color space, but assume as Success for ANGLE.
11-12 16:05:35.917 20018 20049 D gles-renderer: Xlorie: new surface applied: 0xb400007922192e10
11-12 16:05:35.919 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:05:35.925 20018 20049 I blob    : initializing random seed using 1108636968141003
11-12 16:05:35.926 20018 20049 I blob    : get: caller's buffer is too small for value: 0 (needs 2015)
11-12 16:05:35.926 20018 20049 I blob    : get: copying 2015 bytes to caller's buffer
11-12 16:05:35.926 20018 20049 I blob    : get: caller's buffer is too small for value: 0 (needs 2015)
11-12 16:05:35.926 20018 20049 I blob    : get: copying 2015 bytes to caller's buffer
11-12 16:05:35.928 20018 20049 D PAL     : pSubmitInfo->stackSizeInDwords = 0 (PreProcessSubmit:1279)
11-12 16:05:35.928 20018 20049 D PAL     : m_perSubmitCmdStream size = { TotalChunkDwords:24, AvailableDwords:2017 } (RebuildCommandStreams:1591)
11-12 16:05:35.928 20018 20049 D PAL     : m_acePreambleCmdStream size = { TotalChunkDwords:16, AvailableDwords:2029 } (RebuildCommandStreams:1616)
11-12 16:05:35.928 20018 20049 D PAL     : m_dePostambleCmdStream size = { TotalChunkDwords:24, AvailableDwords:2024 } (RebuildCommandStreams:1729)
11-12 16:05:35.928 20018 20049 D PAL     : m_deCmdStream size = { TotalChunkDwords:200, AvailableDwords:1843 } (RebuildCommandStreams:1732)
11-12 16:05:35.929 20018 20049 W vulkan  : CreateSwapchainKHR(VkSwapchainCreateInfoKHR.imageColorSpace = 1000104013) failed: Unsupported color space, but assume as Success for ANGLE.
11-12 16:05:35.933 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:05:35.934 20018 20049 E tx11-request: window changed: 1080 1101
11-12 16:05:35.937 20018 20049 V LorieNative: New framerate is 120
11-12 16:05:35.937 20018 20049 E tx11-request: window changed: 1080 1101
11-12 16:05:35.937 20018 20049 V LorieNative: New framerate is 120
11-12 16:05:40.843 20018 20049 D gles-renderer: 2 frames in 5.0 seconds = 0.4 FPS
11-12 16:06:11.756 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:11.833 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:11.833 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:14.097 20018 20049 E tx11-request: window changed: 1080 1101
11-12 16:06:14.097 20018 20049 V LorieNative: New framerate is 120
11-12 16:06:14.098 20018 20045 D LorieNative: window change: 0xb400007a321d4220
11-12 16:06:14.106 20018 20049 D gles-renderer: renderer_set_window 0xb400007a321d4220 1080 1101
11-12 16:06:14.108 20018 20049 W vulkan  : CreateSwapchainKHR(VkSwapchainCreateInfoKHR.imageColorSpace = 1000104013) failed: Unsupported color space, but assume as Success for ANGLE.
11-12 16:06:14.109 20018 20049 D gles-renderer: Xlorie: new surface applied: 0xb4000079221a1660
11-12 16:06:14.111 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:14.115 20018 20049 W vulkan  : CreateSwapchainKHR(VkSwapchainCreateInfoKHR.imageColorSpace = 1000104013) failed: Unsupported color space, but assume as Success for ANGLE.
11-12 16:06:15.847 20018 20049 D gles-renderer: 170 frames in 5.0 seconds = 34.0 FPS
11-12 16:06:18.999 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:19.549 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:20.847 20018 20049 D gles-renderer: 273 frames in 5.0 seconds = 54.6 FPS
11-12 16:06:21.677 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:21.677 20018 20049 D gles-renderer: Xlorie: updating cursor
11-12 16:06:25.848 20018 20049 D gles-renderer: 41 frames in 5.0 seconds = 8.2 FPS`

**Comment by sfantu** [comment]
Yep ... I'm also having this issue .

**Comment by arenddeboer** [comment]
Confirmed on S22 Ultra (Exynos)

**Comment by arenddeboer** [comment]
I've been playing with the source, bumped the SDK, changed some code and somehow got the color swap issue fixed. The problem is, I'm not sure what made the difference. I'm also a total greenhorn in this domain. Will report back if I have more details.

**Comment by Raceyrae** [comment]
You play with the source Merediv is playing with the sauce

**Comment by hansm629** [comment]
@arenddeboer 

hello.
I am a S24+ Exynos2400 model user.

Even on S24+
As with the S22 series Exynos2200 model, there is an issue where the X server color is displayed strangely.

if
Please share the APK with the modified contents reflected.
Could you please reflect the modified code details in Git?

**Comment by arenddeboer** [comment]
I wish I could just send a pr with the changes, but a quick diff didn't give me anything to work with. 
This is a link to the latest Termux X11 APK that I currently use: https://drive.google.com/file/d/1WOb2T3PUpCzMvwsIq9EOP8D6kMQOS0S1/view?usp=drivesdk
Let me know if it works for you.

**Comment by hansm629** [comment]
@arenddeboer 

thank you! :)

Thanks for solving it!
XFCE4 colors on PRoot-Distro Debian on S24+ Exynos2400 display well!

![스크린샷_2024-02-01_03-20-06](https://github.com/termux/termux-x11/assets/101167173/9b76506f-e946-4066-b885-0837327a4558)


ah!
I have one question.
How is the GPU performance in PRoot-Distro of Exynos2200 Xclipse 920?


Exynos2400 Xclipse 940
`virglrenderer-android` environment and
`mesa-zink + virglrenderer-mesa-zink + vulkan-loader-android` environment

Both show the worst performance and compatibility.


`virglrenderer-android` has glmark2 performance of about 70~80fps.
There is an issue where the texture color appears black.
supertuxkart was completely unplayable with a purple screen appearing.

`mesa-zink + virglrenderer-mesa-zink + vulkan-loader-android`had a performance of about 60~66fps and glmark2 was impossible to complete, and supertuxkart entered the game screen, but the UI was broken and the game map and characters were not displayed. So it was impossible to play.


For Exynos2200 Xclipse 920
When combining `mesa-zink + virglrenderer-mesa-zink + vulkan-loader-android`
I heard rumors that it shows good performance and compatibility.

**Comment by arenddeboer** [comment]
Glad it works for you too!
To be honest I haven't experimented much with render options. But proot is indeed very slow and I try to use native XFCE4 where possible.

**Comment by whjou** [comment]
I'm using S24, have the same issue. 

https://drive.google.com/file/d/1WOb2T3PUpCzMvwsIq9EOP8D6kMQOS0S1/view?usp=drivesdk didn't seem to resolve it. I'm using native XFCE4. 

![Screenshot_20240213_210000_TermuxX11](https://github.com/termux/termux-x11/assets/696695/f1034353-1de5-42fb-b1c8-ed7f9a1293b6)

For comparison, top half shows a photo in GIMP using tigervnc server & MultiVNC client (expected colours), bottom half shows the same using termux-X11 (unexpected colours).

**Comment by hansm629** [comment]
@whjou 

This is PRoot-Distro Debian Sid installed on Galaxy S24+ (SM-S926N).

I have XFCE4 session colors displayed correctly in the APK shared above.

![Screenshot_20240213_231448_TermuxX11](https://github.com/termux/termux-x11/assets/101167173/fc0d6250-d1b3-4804-bf0c-32423280af19)

**Comment by whjou** [comment]
@arenddeboer @hansm629
Turned out I wasn't testing properly. On retesting https://drive.google.com/file/d/1WOb2T3PUpCzMvwsIq9EOP8D6kMQOS0S1/view?usp=drivesdk it worked after all.

Using https://github.com/termux/termux-x11/releases/download/nightly/app-universal-debug.apk for native, proot-distro debian & proot-distro ubuntu:
![Screenshot_20240216_225623_TermuxX11](https://github.com/termux/termux-x11/assets/696695/282c6226-71d6-4153-bad1-f07a4e67abef)
![Screenshot_20240216_225101_TermuxX11](https://github.com/termux/termux-x11/assets/696695/2ca8d77f-9800-4884-a5e4-f8ff0b264769)
![Screenshot_20240216_225358_TermuxX11](https://github.com/termux/termux-x11/assets/696695/1831c6d7-60fa-41eb-8ae2-b2bbfffe9885)

Using https://drive.google.com/file/d/1WOb2T3PUpCzMvwsIq9EOP8D6kMQOS0S1/view?usp=drivesdk for native, proot-distro debian & proot-distro ubuntu:

![Screenshot_20240216_215844_TermuxX11](https://github.com/termux/termux-x11/assets/696695/05feb2ab-b281-4de5-a053-5db35c8b198b)
![Screenshot_20240216_221018_TermuxX11](https://github.com/termux/termux-x11/assets/696695/4f127917-0bc9-43a0-bae0-23ccd444e0df)
![Screenshot_20240216_224648_TermuxX11](https://github.com/termux/termux-x11/assets/696695/4af18e75-8177-4100-8f33-b168ea6b5770)

**Comment by twaik** [comment]
After https://github.com/termux/termux-x11/commit/6fcf1b7961f18d909ecedea037bff3cda6156472 you can use `-force-bgra` option to make it swap colours.

**Comment by whjou** [comment]
@twaik thanks for the fix. Just a minor comment that the README.md line 59 mentioned the wrong flag. It should be

For some reason some devices show screen with swapped colours, in this case you should pass `-force-bgra` option.

**Comment by twaik** [comment]
Do you see readme of master branch or the readme of commit itself?

**Comment by whjou** [comment]
Apologies I looked at the commit at https://github.com/termux/termux-x11/commit/6fcf1b7961f18d909ecedea037bff3cda6156472.

Noted the main page at https://github.com/termux/termux-x11/ is showing correct option.

**Comment by twaik** [comment]
@lengors @sfantu @arenddeboer @hansm629 @whjou can you please confirm problem existing on the latest build? With `-legacy-drawing`/`-force-bgra` and without them?

**Comment by arenddeboer** [comment]
@twaik When I install the latest build from https://github.com/termux/termux-x11/releases, -force-bgra only doesn't work for me, but -legacy-drawing shows the colors correctly. Without needing -force-bgra. Or am I doing something wrong, I was expecting to need the option -force-bgra for the colors to show up correctly.

**Comment by twaik** [comment]
@arenddeboer does it work without flags `-legacy-drawing`? I added one check to enable legacy drawing method automatically but I can not test it on my devices.

**Comment by arenddeboer** [comment]
@twaik ```-legacy-drawing``` is still required. I get a black screen without.

**Comment by twaik** [comment]
Ok, so that means texture format is fine, but drawing it on actual surface with shaders is problematic. I'll check what can be done.

**Comment by whjou** [comment]
> @lengors @sfantu @arenddeboer @hansm629 @whjou can you please confirm problem existing on the latest build? With `-legacy-drawing`/`-force-bgra` and without them?

- https://github.com/termux/termux-x11/actions/runs/7964543153 didn't work for me. Thought it was just me.
- https://github.com/termux/termux-x11/actions/runs/7988796698 worked with `-legacy-drawing` flag. Explicitly stating `-force-bgra` flag is not required.

**Comment by sfantu** [comment]
Working here ... with -legacy-drawing ... haven't test without yet.

**Comment by twaik** [comment]
I fixed one little thing so termux may work on Exynos without `-legacy-drawing`. Check [build 594](https://github.com/termux/termux-x11/actions/runs/8431417771). I am waiting for your confirmations.

**Comment by whjou** [comment]
Tested, it works on my Samsung Galaxy S24 without the `-legacy-drawing` flag. I'm keeping this build. Thanks!

> I fixed one little thing so termux may work on Exynos without `-legacy-drawing`. Check [build 594](https://github.com/termux/termux-x11/actions/runs/8431417771). I am waiting for your confirmations.

**Comment by sfantu** [comment]
yep working here without the -legacy-drawing flag.
