### ISSUE TITLE
[feature]: Inquiry about GPU acceleration using Android host Vulkan driver

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#497]
### Problem description

hello.

This is a feature-related inquiry, not a bug inquiry.
Suddenly, there's something I've been thinking about for a long time.

Currently, you can load the `Android host Vulkan driver` in Termux via `vulkan-loader-android`.

but
Starting with `Mesa 22.1` version, `kopper` has been merged
To use Vulkan or Zink on an X11 server, `X11 WSI` support is required in the instance of the Vulkan driver.

Therefore, in fact, the Android host Vulkan driver cannot be used on the X11 server and is not compatible with zink...

This is a simple assumption....

A workaround would be to implement `X11 WSI in SW` and use `AHardwareBuffer` to get `dmabuf` or display screen via `DRI3` in Termux-x11.

If you use this method
It looks like you can use the Android host Vulkan driver and Zink on the X11 server.

Although there may be some performance loss while implementing X11 WSI in SW, we cautiously expect that it will show much higher performance and higher compatibility than GPU acceleration through virglrenderer-android and virpipe.

I think it can be easily implemented not only in Termux but also in the PRoot environment by using `symbolic link`.

I would like to inquire whether it is possible to implement this technology in the mid to long term. 

:)

### What steps will reproduce the bug?

feature inquiry

**Comment by twaik** [comment]
It is a problem of GL library, not of X server.

**Comment by hansm629** [comment]
@twaik 
I thought I couldn't use zink because the Vulkan driver didn't support X11 WSI.

Did I misunderstand?

**Comment by twaik** [comment]
Vulkan driver does not support X11 WSI. Not X server does not support vulkan driver.

**Comment by hansm629** [comment]
@twaik 
Let me summarize.

If I am mistaken, please correct me.
=====================================================

1. Android Vulkan driver does not support X11 WSI (VK_KHR_xcb_surface)

2. X11 WSI support is required to use zink starting from mesa 22.1 version.
https://www.phoronix.com/news/Mesa-Kopper-Merged

3. Therefore, it is impossible to implement OpenGL & OpenGL ES when combining the current Android Vulkan driver and the latest mesa zink.

=====================================================

I was aware of it as above.
Therefore, in order to be compatible with the latest Mesa 23 version of Zink,

Implement VK_KHR_xcb_surface in software (exception handling through VK_KHR_surface)

I was suggesting getting dmbuf using AHardwareBuffer.

**Comment by twaik** [comment]
AFAIK VK_KHR_xcb_surface is not the only missing extension (on most Android devices) required by Zink.
