### ISSUE TITLE
[Question] Does termux-x11 has the "process completed - signal 9" issue?

### ISSUE THREAD

**Issue by MuubNito** [termux/termux-x11#498]

**Comment by twaik** [comment]
What exatly do you mean?

**Comment by MuubNito** [comment]
> What exatly do you mean?

    Sometimes, when using stuff like andronix, you can get that issue:
![Screenshot_2023-11-15-16-32-20-519_com.termux-edit.jpg](https://github.com/termux/termux-x11/assets/122548283/2c11ea97-ad5a-45b7-a148-2cd012a8a81c)

If i remember it correctly it is because of phantom process killer in newer versions of android (cant check that now, the andronix website is dead now).

Does termux x11 has that issue?

**Comment by twaik** [comment]
Main server code is executed inside termux so yes, it is affected by phantom process killer.
