### ISSUE TITLE
How to use from termux

### ISSUE THREAD

**Issue by strikersix23** [termux/termux-x11#5]
I compiled this add-on and using the termux-x11 pkg how do I launch and x11 app and use this add-on

**Comment by strikersix23** [comment]
I also compiled termux and termux-api and signed with my own keystore

**Comment by twaik** [comment]
If maintainers did not remove termux-x11 package you should install it using apt. Then you will be able to use termux-x11 comand. It should behave just like Xwayland.

**Comment by strikersix23** [comment]
So the command is just likely startx

**Comment by twaik** [comment]
No. startx starts both X-server and WM. Xwayland, Xorg, Xfb start just a xserver.

**Comment by strikersix23** [comment]
Ok I launch wayland and nothing pops up on the add-on

**Comment by xeffyr** [comment]
Nothing will pop up because Termux:X11 is frontend for bare Xwayland.
Applications & wm should be configured and launched manually.
