### ISSUE TITLE
right click in direct mode

### ISSUE THREAD

**Issue by ELWAER-M** [termux/termux-x11#50]
how do i right click in direct mode?

**Comment by twaik** [comment]
Lorie delivers touch events as is in direct mode. There is no handler for right clicks.

**Comment by ELWAER-M** [comment]
ok thanks

**Comment by Anonymous2716** [comment]
Yeah couldn't get it working. maybe a little simpler explanation would help.

**Comment by twaik** [comment]
There is no "right click" in direct mode. It is implemented by DE.

**Comment by Anonymous2716** [comment]
Then how do I get the same results m

**Comment by twaik** [comment]
It depends on DE you are using. Discussing DEs is offtopic here
