### ISSUE TITLE
why does xfce4-power-manager crashes everything?

### ISSUE THREAD

**Issue by FindingMeaning** [termux/termux-x11#500]
I have recently reinstalled xfce4 in debian proot-distro with task-xfce-desktop.

when I executed xfce4-power-manager it was crashing all apps and my android restarts all background processes like I rebooted my phone.

when I stopped xfce4-power-manager somehow everything started to work fine.

why does this happen? just wanted to know.

**Comment by twaik** [comment]
Not a problem of `termux-x11`.
