### ISSUE TITLE
Picture stops updating

### ISSUE THREAD

**Issue by regs01** [termux/termux-x11#501]
### Problem description

Faced a wired thing. Termux-x11 is only working for couple of second, then picture freezes indefinitely. Unless I switch to another app and back or open and close notification panel. This happen even with empty server, so just black screen with cross cursor, so is not a shell. Everything else is working on the background. It's just picture that is not refreshing, not repainting. But once pull down notification panel, you can see all the changes that were done while the picture was frozen.

What's more it does not happen in side-by-side or windowed modes. Only in normal or full screen immersive.

It's Harmony OS 3.1 (Android 12), MatePad 11.5.

### What steps will reproduce the bug?

Just launch the server `termux-x11 :1`
Switch to Termux-x11
Start moving mouse and couple of archons after picture freezes.

### What is the expected behavior?

Ideally it shouldn't freeze

**Comment by twaik** [comment]
Try `-legacy-drawing`.

**Comment by regs01** [comment]
I think it was a disabled display over other apps permission for Termux itself. Enabled it and it's now working. May be something like it was trying to bring Termux to foreground and Termux-x11 was being suspended from painting? Anyway, rebooted and it's still working. 


That is how it was
https://github.com/termux/termux-x11/assets/10468217/76f73d8f-43d4-4a4b-8ac6-c0c5248c7fa3

Now
![Screenshot_20231119_015251_com termux x11](https://github.com/termux/termux-x11/assets/10468217/59f80fd8-7bea-4d33-8d90-fee07288e019)


So I guess case closed
