### ISSUE TITLE
[Bug]: I Can't Disable Child Process Restrictions, Something Went Wrong with Android 14

### ISSUE THREAD

**Issue by BBCByComcast** [termux/termux-x11#503]
### Problem description

I Need Your Help, When I Enable Child Process Restrictions, Google Say "Termux And Termux X11 Are Dangerous to Start KDE Plasma in Android" And They Force Us to Disable **Child Process Restrictions** Using **Google Auto Detection** Then Google Planned to Start Linux Terminal Call "TermDroid" in Android Once Google Prevent Termux And Termux X11, We Can't Disable Child Process Restrictions During Termux Start Upcoming Desktop Environment, Help Me.....

https://github.com/termux/termux-x11/assets/137778363/0ee3d5d4-8176-400c-9d73-8a4a220cd5c1

### What steps will reproduce the bug?

Google Reproduce Termux And Termux X11 During Termux Start Upcoming Desktop Environment, Termux And Termux X11 Something Went Wrong with Android 14 And It's Decided to Switch iOS Soon...

### What is the expected behavior?

as Google Behaviour, Google Behaviour Would Prevent Termux Resources, And There a Most Problem After Google Remove Glibc Features in Android 13 5.4 GKI Kernel, They Have Solution is KDE Plasma And IceWM So Google Behaviour Would Prevent Termux Solution And We Can't Use Termux Anymore.....

**Comment by twaik** [comment]
1. Not a problem of `termux-x11`.
2. I do not understand what you write. Use Google Translate.
