### ISSUE TITLE
[Bug]: XKEYBOARD keymap compiler error

### ISSUE THREAD

**Issue by MuhammedEmirArtan** [termux/termux-x11#506]
### Problem description

The XKEYBOARD keymap compiler (xkbcomp) reports:"
"> "Warning:          Could not resolve keysym XF86CameraAccessEnable
"> "Warning:          Could not resolve keysym XF86CameraAccessDisable
"> "Warning:          Could not resolve keysym XF86CameraAccessToggle
"> "Warning:          Could not resolve keysym XF86NextElement
"> "Warning:          Could not resolve keysym XF86PreviousElement
"> "Warning:          Could not resolve keysym XF86AutopilotEngageToggle
"> "Warning:          Could not resolve keysym XF86MarkWaypoint
"> "Warning:          Could not resolve keysym XF86Sos
"> "Warning:          Could not resolve keysym XF86NavChart
"> "Warning:          Could not resolve keysym XF86FishingChart
"> "Warning:          Could not resolve keysym XF86SingleRangeRadar
"> "Warning:          Could not resolve keysym XF86DualRangeRadar
"> "Warning:          Could not resolve keysym XF86RadarOverlay
"> "Warning:          Could not resolve keysym XF86TraditionalSonar
"> "Warning:          Could not resolve keysym XF86ClearvuSonar
"> "Warning:          Could not resolve keysym XF86SidevuSonar
"> "Warning:          Could not resolve keysym XF86NavInfo
"Errors from xkbcomp are not fatal to the X server"

### What steps will reproduce the bug?

termux-x11 > /dev/null &

### What is the expected behavior?

running perfectly

**Comment by twaik** [comment]
That is a problem of `xkeyboard-config`, not of `termux-x11`.
