### ISSUE TITLE
Built-in Qwerty Keyboard like Xserver XSDL

### ISSUE THREAD

**Issue by sukualam** [termux/termux-x11#52]
Can this feature added in future Termux X11 app? Maybe just like Extra Keys but show more keys (in this case is full QWERTY keyboard, or maybe can be customized too)..

Because android soft keyboard is something bug if i try use WASD movement.. (actually i tried to play some small linux games)

And for mouse trackpad emulation, it looks bugged when i try to move the camera in some FPS game or 3rd person movement or some mouse captured games... I try assault cube and its run fine,,, (btw just soft-rendering with llvmpipe ~20fps), but the problem is i cant move the camera, the mouse seems like locked and jumping

Thx

**Comment by sukualam** [comment]
I just use direct mode in input option and install package onboard on my debian chroot.

**Comment by twaik** [comment]
@sukualam Did you try to invoke back button?
