### ISSUE TITLE
[Bug]: Class Not Found CmdEntryPoint

### ISSUE THREAD

**Issue by 77wisher77** [termux/termux-x11#520]
### Problem description

running the proot command `termux-x11 :1 -xstartup "dbus-launch --exit-with-session xfce4-session"` results in the following error:

```
java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:536)
        at com.termux.x11.Loader.main(Loader.java:24)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:411)
Caused by: java.lang.ClassNotFoundException: com.termux.x11.CmdEntryPoint
        ... 5 more
```

### What steps will reproduce the bug?

- install the x11 repo in termux
- install the .apk to the android device
- install via pacman the https://github.com/termux/termux-x11/actions/runs/7216067412 termux-nightly.pkg.tar.xz
- attempt to run `termux-x11 :1 -xstartup "dbus-launch --exit-with-session xfce4-session"` and get an error

### What is the expected behavior?

The error im getting shouldn't be produced

**Comment by twaik** [comment]
Does termux-x11 work without proot or proot-distro?

**Comment by 77wisher77** [comment]
The android app boots and has a preferences screen if thats what you mean

**Comment by twaik** [comment]
Does termux-x11 work with termux's xfce or any other program?

**Comment by 77wisher77** [comment]
ahh in the termux itself, i get `XKB_CONFIG_ROOT is not set. Normally it is pointing to /usr/share/X11/xkb of a container`

so im trying to run termux-x11 inside an arch installation inside a container of termux

**Comment by twaik** [comment]
Install xorg-xclock and xkeyboard-config and try again with `xclock` program.

**Comment by 77wisher77** [comment]
installing those to the arch container and running `xclock` produces `Error: can't open display`

**Comment by twaik** [comment]
Not to the arch container. To termux...

**Comment by twaik** [comment]
`termux-x11 :1 -xstartup xclock`

**Comment by 77wisher77** [comment]
running that in termux gives me a clock in termux:x11

**Comment by twaik** [comment]
That means the problem is in proot or the way you start it. Not in termux-x11.
