### ISSUE TITLE
[Bug]: Termux X11 killing itself after an Big Load.

### ISSUE THREAD

**Issue by ProSteveBedrock** [termux/termux-x11#526]
### Problem description

XFCE4 is crashing when i launch heavy apps or i launch multiple apps. I think Termux X11 might cause the problem.

### What steps will reproduce the bug?

1. Launch Termux
2. Start XFCE 4 Session (mine is an script together with Termux X11 launch)
3. Launch Firefox, Minetest(Proot), or multiple apps(armcord, chromium in yt, prismlauncher, glmark2)
4. Crashed.

### What is the expected behavior?

Work normally, watch youtube in peace, and code in VSCode without crashes.

### Evidence:

This video is too big. Try again with a file size less than 10MB. Bruh

**Comment by ProSteveBedrock** [comment]
Device Info:

Oppo A5 2020
3GB RAM (1.5GB AVAILABLE)
64GB STORAGE (17GB AVAILABLE)
Snapdragon 660
Adreno 610
Android 10 (ColorOS 7.2)

Termux: 0.118
Termux-X11 app: Somewhere in github that claims have DRI3 support.
Termux-Styling: Latest
Termux-API: Latest
Termux-Tasker: Latest
Termux-GUI: Latest
Termux-Widget: Latest

**Comment by ProSteveBedrock** [comment]
XFCE4 - Desktop:
![Screenshot_2023-12-28-12-51-53-09](https://github.com/termux/termux-x11/assets/123849671/4c39af7e-2aaf-4fcd-9606-68977b996e70)

Error/Crash log:
![Screenshot_2023-12-28-12-53-09-47](https://github.com/termux/termux-x11/assets/123849671/a32683fd-ff85-4499-b578-a68ee219a4ec)

**Comment by twaik** [comment]
This behaviour is caused by Out Of Memory killer. It kills everything it sees or hears except critical and most important system apps in the case if there is no available memory. It is NOT a problem of `termux-x11`.

**Comment by zavocc** [comment]
https://github.com/termux/termux-app/issues/2015

This is likely due to `com.coloros.athena` service which kills background processes, you can disable this through `adb`
