### ISSUE TITLE
[Bug]: Exiting due to channel error.

### ISSUE THREAD

**Issue by MartinMilesi** [termux/termux-x11#529]
### Problem description

I'm loosing connection in termux-x11, everything is running fine but when i go to home from termux-x11 and then to termux-x11 a couple of times i lost the session, this can happen when changing to other android app to and going back to termux-x11.

This started when my s23ultra updated to oneui6.0 before new year, xfce is running in termux not proot and since then i deleted all termux apps and reinstalled everything manually. im using last action downloadable from twaik.

This could be related to the memory of surfaceflinger bug but i dont know:

01-05 20:23:50.857 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid

down is the log file and a fragment.

![Screenshot_20240105_181801_Termux](https://github.com/termux/termux-x11/assets/126598909/d59b7ee4-f06d-4c68-8f84-64300688cb63)

![Screenshot_20240103_142236_Termux](https://github.com/termux/termux-x11/assets/126598909/ce31a50a-4b3c-470a-8f8d-f3bedffc9502)

Here is termux_x11.log: 

[termu_x11.log](https://github.com/termux/termux-x11/files/13847576/termu_x11.log)

01-05 20:23:50.842 20577 20597 D gles-renderer: We've got EGL_BAD_SURFACE so window is to be destroyed. Native window disconnected/abandoned, probably activity is destroyed or in background
01-05 20:23:50.842 20577 20597 D gles-renderer: renderer_set_window 0x0 0 0
01-05 20:23:50.842 20577 20597 D gles-renderer: renderer_set_buffer 0xb400007216881300 1440 2935
01-05 20:23:50.842 20577 20597 D gles-renderer: Xlorie: updating cursor
01-05 20:23:50.842 20577 20597 E tx11-request: window changed: 0 0
01-05 20:23:50.842 20577 20597 V LorieNative: New framerate is 120
--------- beginning of crash
01-05 20:23:50.848 20577 20587 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80134fa4 in tid 20587 (HeapTaskDaemon), pid 20577 (main)
01-05 20:23:50.850 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: Relayout returned: old=(0,0,1440,3088) new=(0,0,1440,3088) req=(1440,3088)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0
01-05 20:23:50.850 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: Relayout returned: old=(0,0,1440,3088) new=(0,0,1440,3088) req=(1440,3088)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0
01-05 20:23:50.851 18509 18509 I SurfaceView@907ccf7: windowStopped(true) false com.termux.x11.LorieView{907ccf7 VFE...... .F....ID 0,0-1440,2935 #7f09007a app:id/lorieView aid=1073741825} of ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.851 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.851 18509 18509 I SurfaceView@907ccf7: windowStopped(true) false com.termux.x11.LorieView{907ccf7 VFE...... .F....ID 0,0-1440,2935 #7f09007a app:id/lorieView aid=1073741825} of ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.851 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.851 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.851 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.851 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.851 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.852 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.852 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.853 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: stopped(true) old = false
01-05 20:23:50.853 18509 18509 D ViewRootImpl@7eb05b0[MainActivity]: WindowStopped on com.termux.x11/com.termux.x11.MainActivity set to true
01-05 20:23:50.853 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: stopped(true) old = false
01-05 20:23:50.853 18509 18509 D ViewRootImpl@7eb05b0[MainActivity]: WindowStopped on com.termux.x11/com.termux.x11.MainActivity set to true
01-05 20:23:50.857 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.857 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.857 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid
01-05 20:23:50.857 18509 18509 I SurfaceView@907ccf7: releaseSurfaces: viewRoot = ViewRootImpl@7eb05b0[MainActivity]
01-05 20:23:50.887 20577 20597 D gles-renderer: Xlorie: updating cursor
01-05 20:23:50.938 20577 20597 D gles-renderer: Xlorie: updating cursor
01-05 20:23:50.989 20577 20597 D gles-renderer: Xlorie: updating cursor
01-05 20:23:51.039 20577 20597 D gles-renderer: Xlorie: updating cursor
01-05 20:23:51.089 20577 20597 D gles-renderer: Xlorie: updating cursor

### What steps will reproduce the bug?

Just go to home and back to termux-x11 it happens when changing to other apps and back to termux-x11 several times, it can happen too when unlocking screen and going back to termux-x11.

### What is the expected behavior?

Not to loose the xserver?...

**Comment by twaik** [comment]
Unfortunately I can not fix this unless I have physical device for tests...

**Comment by MartinMilesi** [comment]
No problem this is not happening in dex mode and there is where i use termux the most so is not killing me, this is probably related to a change in oneui of samsung.

**Comment by MartinMilesi** [comment]
@twaik Could you help me a little pointing me on the right direction or telling me if what i am thinking is nonsense ?

as for what i understand of this part of the log (after --------- beginning of crash) im loosing the xserver because when i go back to the app the surface is updated or re-draw-ed but some function in MainActivity or LorieView  (i suspect this one because it has functions like "surfaceChanged" or "getDimensionsFromSettings" etc) when is looking to update the surface is getting valors like "new=(0,0,1440,3088)" or "old=(0,0,1440,3088)" when is requiring "req=(1440,3088) " could i modify those functions or the one that manages the surface update to ignore the "0,0" that is receiving with the correct resolution "1440,3088" so the surface received is valid and it can be updated? can something like that work like a temporal fix or is crap?

01-05 20:23:50.848 20577 20587 F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80134fa4 in tid 20587 (HeapTaskDaemon), pid 20577 (main)

01-05 20:23:50.850 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: Relayout returned: old=(0,0,1440,3088) new=(0,0,1440,3088) req=(1440,3088)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0

01-05 20:23:50.850 18509 18509 I ViewRootImpl@7eb05b0[MainActivity]: Relayout returned: old=(0,0,1440,3088) new=(0,0,1440,3088) req=(1440,3088)8 dur=8 res=0x402 s={false 0x0} ch=true seqId=0

01-05 20:23:50.851 18509 18509 I SurfaceView@907ccf7: windowStopped(true) false com.termux.x11.LorieView{907ccf7 VFE...... .F....ID 0,0-1440,2935 #7f09007a app:id/lorieView aid=1073741825} of ViewRootImpl@7eb05b0[MainActivity]

01-05 20:23:50.851 18509 18509 D SurfaceView@907ccf7: updateSurface: surface is not valid

**Comment by MartinMilesi** [comment]
i went to developer options and activated the surface update viewer.

(i had to lower video quality for file size)

https://github.com/termux/termux-x11/assets/126598909/3c4d8474-7c3f-4cd6-8938-b7398125040d

is normal behavior for termux-x11 to update is surface continuously like that? i seems to be updating the surface continuously even when there is not input or movement in the screen.

**Comment by twaik** [comment]
> could i modify those functions or the one that manages the surface update to ignore the "0,0" that is receiving with the correct resolution

This case is already handled.



> 01-05 20:23:50.848 20577 20587 F libc : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x80134fa4 in tid 20587 (HeapTaskDaemon), pid 20577 (main)

That means some crap happens in Android internals, I have no idea how to debug this.

> is normal behavior for termux-x11 to update is surface continuously like that? i seems to be updating the surface continuously even when there is not input or movement in the screen.

Surface is updated if there was a surface change, X11 app sent X11 window update, cursor was moved or changed. As far as I see your cursor changes its colours continuously.

**Comment by MartinMilesi** [comment]
ok thanks for the info. since the problem seems to be caused in android side and resetting the phone and not updating to oneui6.0 takes the problem away im closing the issue.

**Comment by MartinMilesi** [comment]
..
