### ISSUE TITLE
[Bug]: Screen zoomed in

### ISSUE THREAD

**Issue by romeoga05** [termux/termux-x11#536]
### Problem description

Everytime i Start it there is a black screen but when i move the mouse around my whole screen gets white

### What steps will reproduce the bug?

When i Start it

**Comment by twaik** [comment]
Can you record your screen to show it?

**Comment by romeoga05** [comment]
Uploading Screen_Recording_20240115_074334_Termux.mp4…

**Comment by romeoga05** [comment]
https://github.com/termux/termux-x11/assets/78824521/ba758308-c8c1-4682-bdc4-328f064e2888

**Comment by twaik** [comment]
Mobox is 3rd oarty product I offer zero support for.
