### ISSUE TITLE
[Bug]: Не запускается mobox

### ISSUE THREAD

**Issue by Prostop194** [termux/termux-x11#538]
### Problem description

Нажал старт вайн меня, перекенуло в термукс х11 и нечего не произошло пишет что нет подключения 

### What steps will reproduce the bug?

.

**Comment by Prostop194** [comment]
https://github.com/termux/termux-x11/assets/121510853/1827f3dd-19f1-40fb-a921-e4eb3872b931

**Comment by twaik** [comment]
1. Official language of all termux repositories is English.
2. Mobox is 3rd party product we offer zero support for.
