### ISSUE TITLE
blinking surface

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#541]
Hi, first of all thanks for your awesome app.
I have this issue with app display. when i change resolution under 1080p, something like 1200x720, the app surface start to blinking. its very little and i can't record this issue, but when open htop in some terminal like lxterminal, it's easily noticeable with eyes.

Device: Xiaomi Redmi Note 10 Pro CN
CPU: Dimensity 1100
RAM: 6G

**Comment by twaik** [comment]
Please, use bug report template and attach video of the bug.
