### ISSUE TITLE
Blinking Surface

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#542]
Hi, first of all thanks for your awesome app.
I have this issue with app display. when i change app resolution under 1080p (something like 1200x720), app surface start to blinking. its very little and i can't record this issue but when open htop in some terminal like lxterminal, it's easily noticeable with eyes.

Device: Xiaomi Redmi Note 10 Pro CN
Cpu: Dimensity 1100
Ram: 6g

**Comment by twaik** [comment]
![Uploading image.png…]()

**Comment by twaik** [comment]
![image](https://github.com/termux/termux-x11/assets/9674930/0e932cd8-8014-42d1-a3b1-e7b4da6e0ca4)
