### ISSUE TITLE
[Enhancement] Automatically navigate back when connection is lost

### ISSUE THREAD

**Issue by EzeKoren** [termux/termux-x11#545]
You will lose the connection if you log out of your window manager, just as you'd expect. It would be a nice feature (if toggleable in the settings) to automatically close the app when the connection is lost. If you opened the app from the launcher it should close, however you may want to open the app straight from a termux script, in which case it should reopen the session

**Comment by twaik** [comment]
Not going to be implemented. "Connection lost" event may happen a lot of times during runtime. The application always tries to reconnect and only if it does not happen it shows "Not connected" screen, and even in this case it still tries to reconnect continuously. In the case if modification like this will be applied application will exit without a visible reason for a bunch of users.
