### ISSUE TITLE
Change settings from terminal

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#547]
Please add some kind of functionality to change termux-x11 settings from terminal.
Some kind of IPC or using fifo file.

**Comment by twaik** [comment]
Not going to be implemented.

**Comment by twaik** [comment]
Check https://github.com/termux/termux-x11/actions/runs/7962643808 artifact.

**Comment by twaik** [comment]
Try https://github.com/termux/termux-x11/blob/master/termux-x11-preference script to change preferences.

**Comment by RalfWerner** [comment]
Great that is very good. I've only checked what I need with your script as `x`. With:
`x extra_keys_config:[[KEYBOARD,DRAWER]] displayScale:400` is possible but 400 is not displayed by `x list`. With the Preferenzen `x touchMode:2` I get `data="touchMode: can not be set to 2"` but is actual. Unfortunately, the desired **extra_keys** with >10 spaces inside cannot be set as `value`. I've tried `",',\ `.
<details><summary> x list </summary>

```
[~]$ x list
"displayResolutionMode"="scaled"
"displayScale"="200"
"displayResolutionExact"="1280x1024"
"displayResolutionCustom"="1280x1024"
"displayStretch"="false"
"Reseed"="true"
"PIP"="true"
"fullscreen"="true"
"forceLandscape"="false"
"hideCutout"="false"
"keepScreenOn"="true"
"touchMode"="2"
"scaleTouchpad"="true"
"showStylusClickOverride"="false"
"showMouseHelper"="false"
"pointerCapture"="false"
"tapToMove"="true"
"showAdditionalKbd"="true"
"hideEKOnVolDown"="false"
"showIMEWhileExternalConnected"="true"
"preferScancodes"="true"
"dexMetaKeyCapture"="false"
"enableAccessibilityService"="null"
"enableAccessibilityServiceAutomatically"="false"
"filterOutWinkey"="false"
"extra_keys_config"="[[{macro:CTRL,display:'^',popup:{macro:'CTRL d',display:d}},{key:TAB,popup:PASTE},{key:LEFT,popup:BKSP},{key:RIGHT,popup:{macro:'o ENTER',display:off}},{key:UP,popup:PGUP}, {key:DOWN,popup:PGDN},{key:END,popup:HOME},{key:ENTER,popup:{macro:'CTRL n',display:'->'}},{key:KEYBOARD,popup:DRAWER},{macro:'mc SPACE i ENTER',display:M,popup:F10},{display:X,macro:'t SPACE 0 ENTER',popup:{macro:'t SPACE w ENTER',display:W}}]]"
"clipboardSync"="false"
"requestNotificationPermission"="null"
```
</details>
