### ISSUE TITLE
Share the clipboard with Android

### ISSUE THREAD

**Issue by ghost** [termux/termux-x11#55]
Synchronize the clipboard.

**Comment by RalfWerner** [comment]
@nagasawa This is not the only one and absolutely best option ( `*VNC` do it for compare). In [ekeys](https://github.com/termux/termux-x11/pull/19#issuecomment-921708037) branch, the `PASTE` _**key**_ for inserting Android-clipboard is possible and the `termux-clipboard-set` (API plugin) can _**set** this storage._
Unfortunately, the branch is not yet completed and currently not _"in work"_. But you can check it with this [Artifact](https://github.com/termux/termux-x11/actions/runs/1277414726).

**Comment by nagasawa** [comment]
Excellent.

**Comment by twaik** [comment]
Duplicate #100.
