### ISSUE TITLE
Trackpad variable speed issue (with display scale 150%)

### ISSUE THREAD

**Issue by jeroen256** [termux/termux-x11#554]
Trackpad variable speed (with display scale 100%) I find a nice feature and works well.

But when I use a higher display scale, for example 150%, it becomes increasingly difficult to move the cursor at low speed. Try moving the cursor slowly using trackpad at display scale 200%, it almost gets stuck.

I think this is a bug, otherwise an option to disable the variable speed of the cursor I would appreciate.

If I may propose a possible solution: maybe a condition that the cursor never gets slow down (to lower than the actual finger speed). Only potentially accelerated when the finger moves fast.

**Comment by twaik** [comment]
Ok. For some reason Android's GestureDetector has some other scale factor or I failed to find the place where my code applies some other factor to distance. You can disable scale factor at all after https://github.com/termux/termux-x11/commit/6db747577fa45f5c2b9ca3bdfdc14e0fa88d51c7 .

**Comment by ewt45** [comment]
is this a mistake in the fix?
https://github.com/termux/termux-x11/blob/master/app/src/main/java/com/termux/x11/input/TouchInputHandler.java#L350
where `distanceX` and Y has been multiplied optionally, but when sending them as params to `moveCursorByOffset`, they are multiplied again unconditionally.

after adjust this part of code i made some tests.
1. disable scale factor: 
  - 100% scale: cursor doesn't follow exactly the location of finger, some distance are lost
  - 150% scale: the cursor can merely catch up with the finger.

https://github.com/termux/termux-x11/assets/79033456/1cd99987-9d92-4bc5-966b-fda52598aef6

----
2. enable scale factor
  - 100% scale: cursor moves slower
  - 150% scale: cursor moves slower than slower
  - 200% scale: cursor can hardly move


https://github.com/termux/termux-x11/assets/79033456/057237f9-c4b7-4f67-92a4-4ffcc060ccbd


----
I'm not sure if this is a device specific problem

**Comment by twaik** [comment]
Thank you, fixed this. There is no multiplying twice in the latest build.

**Comment by ewt45** [comment]
got it.
also i find out the reason why the cursor moves slower than finger when scaling is 100% in Trackpad mode., 
the method `moveCursorByOffset` floors the position from float value to int value. so every offset is shrinked a little bit.
https://github.com/termux/termux-x11/blob/master/app/src/main/java/com/termux/x11/input/TouchInputHandler.java#L275

the sub processes of pointer location supports float value, and after removing the (int) conversion, now cursor moves at the same speed with finger on my device. can you please fix this too?

**Comment by twaik** [comment]
You are right. It seems like that int conversion was there since I was experimenting with mouse modes. I'll remove it right now.
