### ISSUE TITLE
[Bug]: Xrandr rotation: reflection "none"

### ISSUE THREAD

**Issue by diejuse** [termux/termux-x11#555]
### Problem description

I want to rotate the screen to "left" or "right" manually, using xrandr.

### What steps will reproduce the bug?

xrandr -o left

### What is the expected behavior?

It should work.

**Comment by twaik** [comment]
It should not.
In normal conditions xrandr (and other programs manipulating display parameters) send command to change display viewport and only after that send command to change display orientation. That does not fit to current application architecture.
