### ISSUE TITLE
Ubuntu 23.04 AArch64 and strange Marco window manager behaviour

### ISSUE THREAD

**Issue by JanuszChmiel** [termux/termux-x11#556]
Dear MR Twaik,
You are belonging among elite C and Java language developers. Your deep understanding of Java and C is really outstanding.
Please, why The nightly build from yesterday produces so strange Marco window manager behaviour.
I Am using Android 8.0 and Huawei 10 Mate lite.
Marco do not support its internal routines for recalling Mate run application dialog, even main menu accessed by using ALT+F1 do not work.
So I had to use Tigervnc again.
I will try to use older .apk but I do not know, if it will be compatible with The latest Termux-x11 nightly available for Termux.\

I have those issues with build dated to 8.2.2024
APK package version number is
1.03.00
I Am using official proot-distro script so I have installed ubuntu-lts. Because according to my opinion, it allow users to use The best tuned trebles while listenning Internet radio whicvh is using Gstreamer for play songs.
I have used -sharedtmp option. I have executed
termux-x11 :0 &
from Termux session.
Then I have typed
proot-distro login --user janusz ubuntu-lts --shared-tmp
export DISPLAY=:0
mate-session &
orca &
Ubuntu and Debian chroot container compatible with Proot contain something special so user do not have to type
dbus-run-session mate-session &
or dbus-launch mate-session &
Some module determines those commands automatically for users. ArchLinux do not offer this benefit for Termux users, unfortunately.

Ubuntu also allow Orca users to get The fastest possible latency between key press and Espeak-ng speech output.
Sure, it also depend on Android kernel and phone or Tablet performance.

**Comment by twaik** [comment]
Not a problem of Termux:X11. Latest build is almost the same as the previous build, simply ignoring some exception raised by some devices at application start.
Check Keyboard options of Termux:X11, probably some flags were reset.

**Comment by JanuszChmiel** [comment]
I will try it again. I have removed older Termux-x11 first and I have installed new .apk. I will try older build what will hhappen.
