### ISSUE TITLE
No implementation found for void com.termux.x11.starter.Starter.checkXdgRuntimeDir()

### ISSUE THREAD

**Issue by waldhef** [termux/termux-x11#56]
Hello,
I'm trying to test the neu Build #115: Commit 7f41b8e, but i get the error above when I run "termux-x11 :0"
Here is the terminal output:

```
~ $ termux-x11 :0
java.lang.UnsatisfiedLinkError: No implementation found for void com.termux.x11.starter.Starter.checkXdgRuntimeDir() (tried Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir and Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir__)
        at com.termux.x11.starter.Starter.checkXdgRuntimeDir(Native Method)
        at com.termux.x11.starter.Starter.onRun(Starter.java:84)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:61)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:762)
```

This happens with all builds with "run without sharedUserId". Testet with Build #109: Commit 1e12d82 and got the same error.
All prior builds works fine except of random crashes,  but this is the nature of beta software :)
Testet Build #99: Commit db575f7 which works fine.

Testet with Termux-app from Github: Build #371: Commit af16e79 and with Termux-app from F-Droid: Version 0.117 (117) 
both the same error.

My test device is a Samsung Galaxy Tab S2 (SM-T815), Android 7.0, Exynos SoC, armv7  

I hope you can fix this. If you need more information, i would be glad to help you. 

Bye

**Comment by waldhef** [comment]
Hello,
I've done some further tests. I installed anbox (android emulator) on my Linux machine and done all the same steps I described above - termux-x11 works fine on this machine.

Here is the neofetch screen of the working machine:

```
~ $ neofetch
         -o          o-            u0_a50@anbox
          +hydNNNNdyh+             ------------
        +mMMMMMMMMMMMMm+           OS: Android 7.1.1 x86_64
      `dMMm:NMMMMMMN:mMMd`         Host: Android Anbox
      hMMMMMMMMMMMMMMMMMMh         Kernel: 5.9.16-1-MANJARO
  ..  yyyyyyyyyyyyyyyyyyyy  ..     Uptime: 1 hour, 12 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.   Packages: 191 (dpkg), 1 (pkg)
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Shell: bash 5.1.8
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Resolution: 1289x950
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Terminal: com.termux
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   CPU: Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS) (4) @ 3.392GHz
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-   Memory: 1978MiB / 3935MiB
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+
      mMMMMMMMMMMMMMMMMMMm
      `/++MMMMh++hMMMM++/`
          MMMMo  oMMMM
          MMMMo  oMMMM
          oNMm-  -mMNs
```



Here is the neofetch screen of my tab, where termux-x11 fail to run:

```
~ $ neofetch
         -o          o-            u0_a290@localhost
          +hydNNNNdyh+             -----------------
        +mMMMMMMMMMMMMm+           OS: Android 7.0 armv7l
      `dMMm:NMMMMMMN:mMMd`         Host: samsung SM-T815
      hMMMMMMMMMMMMMMMMMMh         Kernel: 3.10.9-14049411
  ..  yyyyyyyyyyyyyyyyyyyy  ..     Uptime: 8 days, 22 hours, 28 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.   Packages: 176 (dpkg), 1 (pkg)
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Shell: bash 5.1.8
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   CPU: Samsung EXYNOS5433 (8) @ 1.300GHz
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Memory: 2137MiB / 2762MiB
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+
      mMMMMMMMMMMMMMMMMMMm
      `/++MMMMh++hMMMM++/`
          MMMMo  oMMMM
          MMMMo  oMMMM
          oNMm-  -mMNs
```

The only mayor difference is:

`OS: Android 7.1.1 x86_64` -- works fine
`OS: Android 7.0 armv7l` -- fail

So maybe you have just to add the target "Android 7.0 armv7l" in your IDE or so?

I hope I could help you anyhow, please let me know if you need some more information.

Have a nice day.

**Comment by twaik** [comment]
Thanks for report, I will try to investigate it.

**Comment by twaik** [comment]
Note for myself.
Possible fix is here: https://github.com/RikkaApps/Shizuku/blob/master/shell/src/main/java/rikka/shizuku/shell/ShizukuShellLoader.java
It allows to use native libraries inside apk, without unpacking.

**Comment by agnostic-apollo** [comment]
Great, thanks for confirming. You are welcome.
