### ISSUE TITLE
[Bug]: the lastest built app does not start on Android 13+

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#562]
### Problem description

The newest build of x11 does not open (crash immediately after open) on my device (even with app data cleared). If you do not encounter the same issue, I am happy to print log with `adb`, but please let me know what command I should run (you know `logcat` print way many information). Thanks.

**Comment by twaik** [comment]
Just save `logcat` output to file and post it here.

**Comment by knyipab** [comment]
Sorry, I didn't mean to. Here's the log from `logcat`. 
[termux-x11-crash_1.log](https://github.com/termux/termux-x11/files/14322325/termux-x11-crash_1.log)

**Comment by twaik** [comment]
Please, check https://github.com/termux/termux-x11/actions/runs/7949739741 behaviour.

**Comment by knyipab** [comment]
Thanks a lot! It fixed the issue.
