### ISSUE TITLE
[Feature Request] OpenXR Implementation

### ISSUE THREAD

**Issue by BiatuAutMiahn** [termux/termux-x11#564]
For us VR users out there, maybe fork/branch this into an immersive VR app?

**Comment by twaik** [comment]
Termux:X11 was designed to be used with mouse+keyboard or at least with touchscreen. VR was never planned here. In the case if you are skilled enough you can write it without my help.

**Comment by BiatuAutMiahn** [comment]
@lvonasek can you find me on discord?

**Comment by CharlyGN** [comment]
😯😯😯
