### ISSUE TITLE
[Bug]: Change touchMode from terminal

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#566]
### Problem description

Changing touchMode from terminal not working

### What steps will reproduce the bug?

Running `am broadcast -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e touchMode 2` gives this `Broadcasting: Intent { act=com.termux.x11.CHANGE_PREFERENCE pkg=com.termux.x11 (has extras) }
Broadcast completed: result=1, data="touchMode: can not be set to 2"`

### What is the expected behavior?

Change touchMode from terminal

**Comment by numberokta** [comment]
I think, it's something to do with `app/src/main/java/com/termux/x11/LoriePreferences.java` in line `508`, there is a condition for checking that new value is contain of array values or not. it must check for array **id** instead of **value**.
I test this :
```
am broadcast -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e touchMode Trackpad
```
and it gives Broadcast completed: resault="2", data="done"

**Comment by twaik** [comment]
> it must check for array **id** instead of **value**.

No. Id can mean something else in newer version. I am using value for this intentionally, because it must be compatible across versions.

```
am broadcast -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e touchMode Trackpad
```

Is the right command.

**Comment by numberokta** [comment]
When i run 
```
am broadcast -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e list null
```
it gives this
```
Broadcasting: Intent { act=com.termux.x11.CHANGE_PREFERENCE pkg=com.termux.x11 (has extras) }
Broadcast completed: result=2, data=""displayResolutionMode"="custom"
"displayScale"="100"
"displayResolutionExact"="1280x1024"
"displayResolutionCustom"="1530x720"
"displayStretch"="false"
"Reseed"="true"
"PIP"="false"
"fullscreen"="false"
"forceLandscape"="false"
"hideCutout"="false"
"keepScreenOn"="true"
"touchMode"="1"
"scaleTouchpad"="true"
"showStylusClickOverride"="false"
"showMouseHelper"="false"
"pointerCapture"="false"
"tapToMove"="false"
"showAdditionalKbd"="false"
"hideEKOnVolDown"="false"
"showIMEWhileExternalConnected"="false"
"preferScancodes"="false"
"dexMetaKeyCapture"="false"
"enableAccessibilityService"="null"
"enableAccessibilityServiceAutomatically"="false"
"filterOutWinkey"="false"
"extra_keys_config"="[['ESC','/',{key: '-', popup: '|'},'HOME','UP','END','PGUP'], ['TAB','CTRL','ALT','LEFT','DOWN','RIGHT','PGDN']]"
"clipboardSync"="false"
"requestNotificationPermission"="null"
"
```
the default value of `touchMode` is `1`
and using `Trackpad` as value of `touchMode`, crashed app.
i'm using the last version `Nightly Release 20240221
Latest`
do I have to wait for the new version?

**Comment by twaik** [comment]
I think it is a bug, I'll fix it later.

**Comment by twaik** [comment]
@numberokta check https://github.com/termux/termux-x11/actions/runs/8075013742

**Comment by numberokta** [comment]
> @numberokta check https://github.com/termux/termux-x11/actions/runs/8075013742

thanks
