### ISSUE TITLE
In-Game Key issue

### ISSUE THREAD

**Issue by Alrck** [termux/termux-x11#567]
While running any games in mobox the x-11 special keys are working including ctrl,shift,alt,etc but none of other keys are working like these.

**Comment by TomJo2000** [comment]
Please kindly direct that issue to the upstream project in question.
https://github.com/olegos2/mobox/issues

We have no affiliation with Mobox, it just happens to use Termux as a base.

**Comment by Arjun-AL** [comment]
Ok man no issue but I need to try it on my own by making arrow keys as
special keys to test it will work on games, but the android project is
seriously not compiling the .c files and .h files some are missing nd also
not compiling by clang ,Do you have any idea to compile this app using
android studio I have downloaded all the sub modules by the 2nd git command.


I tried it multiple times but error both in linux and windows tried to
ssitch to gcc also an issue.

**Comment by ewt45** [comment]
i managed to compile it on ubuntu 22 desktop
1. install android studio and it's dependencies 
2. sudo apt install bison gcc-aarch64-linux-gnu
3. git clone termux-x11 and submodules
4. use android studio's gradle sync and build. test key are included in project directory
