### ISSUE TITLE
How to right click in "emulate mouse" mode?

### ISSUE THREAD

**Issue by sukualam** [termux/termux-x11#57]
I dont know the gesture, or there is no gesture for right click in "emulate mouse" mode? 

The right click work in "emulate trackpad' mode. 

Btw, In " direct mode" it looks the multi touch is detected inside my distro, i wonder what the linux software/package to process the multi touch to make gesture (like two finger tap to right click)...

**Comment by twaik** [comment]
Try short two finger tap...

**Comment by sukualam** [comment]
Yes it works

**Comment by twaik** [comment]
Try short triple finger tap...

**Comment by skskss** [comment]
i know but which finger on touchscreen will be assigned for pointer location
