### ISSUE TITLE
I wanna run it with chroot but didn't work and black,Please point out any mistakes I made.

### ISSUE THREAD

**Issue by Sddsfdd** [termux/termux-x11#572]
![IMG_20240302_192846](https://github.com/termux/termux-x11/assets/72536166/20a6fb8b-e70f-4c88-9e66-f8e266602eb1)
![IMG_20240302_192752](https://github.com/termux/termux-x11/assets/72536166/71ff2bd0-5fcc-424d-89e8-aec18266546d)
![Screenshot_2024-03-02-19-29-48-572_com termux-edit](https://github.com/termux/termux-x11/assets/72536166/5c484a47-43ce-4a2b-9748-0051c1ab47a7)
![Screenshot_2024-03-02-19-29-58-121_com termux x11](https://github.com/termux/termux-x11/assets/72536166/980fe76a-4f83-4745-9b5e-7130623cf9b8)
.shortcuts/startchroot_ubuntu.sh is the sh file I use to start it in termux widget

**Comment by twaik** [comment]
Your script is not adapted to newer versions of termux-x11. It expects termux-x11 uses Xwayland. Xwayland support was dropped 9 month ago.

**Comment by Sddsfdd** [comment]
> Your script is not adapted to newer versions of termux-x11. It expects termux-x11 uses Xwayland. Xwayland support was dropped 9 month ago.

okay,so what should I do to adapt it
