### ISSUE TITLE
[Bug]: How to run remote X application on termux-x11?

### ISSUE THREAD

**Issue by foryoung2018** [termux/termux-x11#573]
### Problem description

can't connect to termux-x11 server with TCP

### What steps will reproduce the bug?

run termux-x11 :0 on device, then run a X application on another device with export DISPLAY=xxx:0

got error as below:

huyang@huyang1841:~/android-studio/bin$ firefox
Unable to init server: Broadway display type not supported: 192.168.137.99:0
Error: cannot open display: 192.168.137.99:0

### What is the expected behavior?

remote x application can run on termux-x11 server

**Comment by twaik** [comment]
Not a bug. 
It works fine with both `ssh -X` + ssh server on a remote with X11Forwarding and `termux-x11 :1 -listen tcp` + `DISPLAY=$IP:1 program`. 
Fix your setup.
