### ISSUE TITLE
[Bug]:  Fatal Server Error

### ISSUE THREAD

**Issue by zienaz** [termux/termux-x11#574]
### Problem description

sorry for broken english
i can't start the x server, i got these error message:
```
termux-x11 :0 -ac &
[1] 8413
~ $ _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:109)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
```

and sometime like these:
```
~ $ termux-x11 :0 -ac &
[2] 8488
[1]   Exit 1                  termux-x11 :0 -ac
~ $ java.net.BindException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.IoBridge.bind(IoBridge.java:109)
        at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
_XSERVTrans     at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)SocketUNIXCreateListener: ...SocketCreateListener() failed

_XSERVTrans     at java.net.ServerSocket.bind(ServerSocket.java:377)MakeAllCOTSServerListeners: server already running

        at java.net.ServerSocket.<init>(ServerSocket.java:237)(EE)
        at com.termux.x11.CmdEntryPoint.lambda$spawnListeningThread$1(CmdEntryPoint.java:150)
Fatal server error:

(EE)    at com.termux.x11.CmdEntryPoint.$r8$lambda$vk4ROaNTM8gv2nUkB-fFZSrf_IY(CmdEntryPoint.java:0)
Cannot establish any listening sockets - Make sure an X server isn't already running    at com.termux.x11.CmdEntryPoint$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
(EE)    at java.lang.Thread.run(Thread.java:919)

Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
        at libcore.io.Linux.bind(Native Method)
        at libcore.io.ForwardingOs.bind(ForwardingOs.java:75)
        at libcore.io.IoBridge.bind(IoBridge.java:105)
        ... 8 more
```

What i have tried:
* remove tmpdir
* killall -9 termux-x11 xwayland
* force close termux app
* clear cache termux app
* force close termux x11 app
* clear cache termux x11 app

It's only fix when i reboot the phone, and can only run server once, and i got error message again.

Device: Samsung Galaxy J7 2017,
Rom: Havoc OS GSI Arm64-Aonly
Kernel: 3.18.91-CronosKernel-V5.0-J730X-TREBLE-20200113

### What steps will reproduce the bug?

When i restart the server, i can only run it once after rebooting the phone.

### What is the expected behavior?

Is this because i custom my rom to Arm64-Aonly?
Cause when i using Arm64-AB, i got no error, its run perfectly.

**Comment by twaik** [comment]
`&` in command `termux-x11 :0 -ac &` means that command will run in background.
And `server already running` means you already started it and it runs somewhere in background...

> `killall -9 termux-x11 xwayland`

Termux:X11 does not use xwayland almost a year. I do not know where you read about it...
Use `pkill app_process`...

In the case if you are still getting error you must force-stop termux from Android UI. **Not** swiping termux's task from recents task screen. **Not** pressing "Exit" on termux's notification. 

<details>

![image](https://github.com/termux/termux-x11/assets/9674930/5c0b527c-4f2e-4c49-a3c0-753e936d378f)
</details>

**Comment by zienaz** [comment]
running 'termux-x11 :0' without '&' work, maybe bug is from the rom, because even i 'Force Close' the termux app, i still got 'server already running' message, maybe some process still stuck on memory

**Comment by twaik** [comment]
You are stopping termux app, right? Because stopping Termux:X11 app will have no effect.

**Comment by zienaz** [comment]
yes, this one
![Screenshot_20240306-162227](https://github.com/termux/termux-x11/assets/44515822/ce8a5d77-1287-4aa2-8b35-a520f49d1301)

**Comment by twaik** [comment]
Probably a bug in your firmware. I can not fix this in application.

**Comment by zienaz** [comment]
ok bro, thanks for your respone 👍
