### ISSUE TITLE
[Bug]: FileNotFoundException

### ISSUE THREAD

**Issue by hlder** [termux/termux-x11#576]
### Problem description

I can`t start。

### What steps will reproduce the bug?

![image](https://github.com/termux/termux-x11/assets/7836238/b9f2748d-c861-4589-a901-7013df4ac331)

### What is the expected behavior?

No error

**Comment by ask9027** [comment]
ignore this

**Comment by twaik** [comment]
FileNotFound exception is harmless. https://github.com/termux/termux-x11/actions/runs/8223894036 fixes it.
Also I see you started `termux-x11 :0` with no other program. Termux:X11 itself does not contain any GUI. It is X server. You **must** start some X11 program to display something.
