### ISSUE TITLE
execute shell code directly through termux-x11

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#578]
I think it would be nice if implement a function to execute shell code directly through termux-x11 like this
```
termux-am broadcast --user 0 -a com.termux.x11.CHANGE_PREFERENCE -p com.termux.x11 -e exec "some code"
```
I hope this will helps to work some functions that doesn't work for `android security reasons` like `termux-clipboard-get` that only works on termux terminal itself

**Comment by twaik** [comment]
Not going to be implemented. Not a scope of X server.

**Comment by numberokta** [comment]
Ok. I'm not sure about my idea, can I ask if it works in theory?

**Comment by twaik** [comment]
Probably it could work, but again: it is out of a scope of X server. It is related to `termux-api`.

**Comment by numberokta** [comment]
Thanks, i already open an issue in termux-api

**Comment by twaik** [comment]
Ok, check https://github.com/termux/termux-x11/actions/runs/8281260198 artifact. Android clipboard is captured if:
1. Android clipboard is newer than X11 clipboard.
2. Termux:X11 activity is in foreground.

You can get clipboard content from commandline with tools like `xsel` or `xclip`.

**Comment by numberokta** [comment]
Thanks
