### ISSUE TITLE
[Bug]: monochrome icon not work

### ISSUE THREAD

**Issue by BinTianqi** [termux/termux-x11#585]
### Problem description

![ResizedImage_2024-03-19_21-51-57_1876](https://github.com/termux/termux-x11/assets/146811279/809efb3e-149e-4e00-a4a5-0f9a1de5e215)

### What steps will reproduce the bug?

1. install this app on Android13 or above
2. enable "Themed icons" in settings

### What is the expected behavior?

the launcher icon should follow my system colors

**Comment by BinTianqi** [comment]
this app supports monochrome icon. 
[ic_launcher.xml](https://github.com/termux/termux-x11/blob/master/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5)
```xml
<monochrome android:drawable="@mipmap/ic_launcher_monochrome"/>
```
android system will find `ic_launcher_monochrome` in `mipmap` folder. when api>=26, the system will try to find it in `mipmap-anydpi-v26`, but it doesn't exist, so the system decide to use normal icons.

**Comment by twaik** [comment]
Actually it does not exist in termux-app too, but it still works. @agnostic-apollo maybe you can tell me what is wrong to my app? 😭

**Comment by BinTianqi** [comment]
the app is missing ic_launcher_round.xml file like [this](https://github.com/termux/termux-app/blob/master/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml)

**Comment by twaik** [comment]
Ok, I see that ic_launcher_round.xml is the same as ic_launcher.xml so I'll try to make a copy of ic_launcher.xml in termux-x11 too.

**Comment by BinTianqi** [comment]
when I switch to square icon, it work fine

![ResizedImage_2024-03-25_20-02-11_9708](https://github.com/termux/termux-x11/assets/146811279/280dc685-d07c-4632-b5df-3080618817cf)

**Comment by twaik** [comment]
https://github.com/termux/termux-x11/actions/runs/8419735350

**Comment by twaik** [comment]
Ok, you can test new build.

**Comment by BinTianqi** [comment]
Thank you for making my launcher more beautiful
![ResizedImage_2024-03-25_20-10-32_1800](https://github.com/termux/termux-x11/assets/146811279/dafcedd9-4529-4ce2-a2ec-34641b3f2114)
