### ISSUE TITLE
[Bug]: default cursor doesn't change

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#586]
### Problem description

I'm not sure if this is a bug. default cursor doesn't change for some apps. this issue only happens in x11-repo apps and in proot-distro everything's fine
I khow x11 work like this:
check `~/.gtkrc-2.0` for `gtk2` cursor
check `~/.config/gtk-3.0/settings.ini` for `gtk3` cursor
and check this files for `default` cursor
`~/.icons/default/index.theme`
`~/.local/share/icons/default/index.theme`
`/usr/share/icons/default/index.theme`
I think termux-x11 doesn't check for `default` cursor files.

### What steps will reproduce the bug?

I installed lxappearance and changed cursor but some apps (like rofi, polybar) still using default cursor. I recorded this issue:

https://github.com/termux/termux-x11/assets/20727200/0bce7ead-553e-4020-92b1-7527a6cd6d50

### What is the expected behavior?

termux-x11 use selected cursor like x11.

**Comment by twaik** [comment]
AFAIK X server does not manage cursors. It only displays them.

**Comment by RalfWerner** [comment]
@numberokta Your video corresponds to my expectation after the last update of @twaik. Typical pointer changes are done often by XClients at these Events: `EnterNotify` and `LeaveNotify`. In your video this is in seconds: 6,8,12,13,14,17,19 done. The `drun` window manages 3 different pointers. The phenomenon described [here](https://github.com/termux/termux-x11/issues/569#issuecomment-1988357255) occurs in **second 10** (KB-"off" seems randomly outside of `drun`).

**Comment by numberokta** [comment]
I found the issue, and it's a bug, but it's not related to termux-x11. It's a bug in `termux-packages`, precisely `xcb-util-cursor` package. I looked at source of `build.sh` in `termux-packages` and `configure.ac` must be patched.
`DEF_CURSORPATH="~/.icons:/usr/share/icons:usr/share/pixmaps:/usr/X11R6/lib/X11/icons"` to `DEF_CURSORPATH="~/.icons:@TERMUX_PERFIX/share/icons:@TERMUX_PERFIX/share/pixmaps:@TERMUX_PERFIX/X11R6/lib/X11/icons"`

**Comment by RalfWerner** [comment]
What do you expect, should this change you in your video and in what second?

**Comment by twaik** [comment]
@numberokta test deb from here. https://github.com/termux/termux-packages/actions/runs/8358888914

**Comment by numberokta** [comment]
@twaik thanks.

**Comment by twaik** [comment]
Does it work? I still did not merge it to termux-packages.

**Comment by numberokta** [comment]
It works.

**Comment by RalfWerner** [comment]
@twaik I've been creating Xclients for about 40 years. For the first time, I hear that a XServer cannot change the pointer. It does not coincide with my experience. Rather that it is one of the first actions of a beginner. XCB and XLIB are central interfaces to the XServer and are used in many Xclients. I would be careful to make changes without checking thoroughly.

**Comment by twaik** [comment]
Ok, it is merged. Update will be available in repos in a few hours.

**Comment by RalfWerner** [comment]
> It only displays what X clients request

Correct and that with the `xcb-util`  package (you've changed!?) and in the video about 12 times. As far as I can see that but always **"as expected"**. I'll check also when `pkg up` update it:)
