### ISSUE TITLE
[Bug]: chroot xfce termux x11 does not start normally

### ISSUE THREAD

**Issue by 1918057287** [termux/termux-x11#588]
### Problem description

mount: mounting tmpfs on 7data/local/tmp/chrootubuntu/d ev/shm failed: No such file or directory fusr/bin/startxfce4: X server already running on displa :0
xrdb: Connection refused
Xrdb: Can't open display ":0"
xfce4-Session: Cannot open display: Type xfce4- session - -help' for usage,
1|:/data/local/tmp #
![Screenshot_20240322-130637_ZeroTermux](https://github.com/termux/termux-x11/assets/35589360/c9d6f585-dca7-48f9-94fd-df428d611edf)

### What steps will reproduce the bug?

#!/bin/bash
export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4713
dbus-launch --exit-with-session startxfce4 &

**Comment by twaik** [comment]
Not a bug.
1. `termux-x11` must be started with `-listen tcp`. TCP is disabled by default and MUST be enabled manually in the case if you need it.
2. Do not use `startxfce4`. It tries to start its own X server (typically using command `X`). Use `xfce4-session`.
