### ISSUE TITLE
Can't type caps with soft keyboard

### ISSUE THREAD

**Issue by ImNotTheChiku35** [termux/termux-x11#590]
### Problem description
When using the soft keyboard, I'm unable to input capital letters.

### Steps to reproduce
1. Go to **Preferences**.
2. Turn on "Prefer scancodes when possible".
3. Attempt to input capital letters using the soft keyboard.

### Expected behavior
I expect to be able to input capital letters using the soft keyboard.

### Additional information
- Device: Realme 5 Pro
- Android version: 11
- App version: 1.03.00
- Termux version: 0.118.0+7ea61ee

**Comment by ImNotTheChiku35** [comment]
I found the cause of the issue; it's not a bug. thanks

**Comment by alexytomi** [comment]
I could reproduce with Gboard Version 13.7.12.582282722-release-arm64-v8a but not Samsung keyboard. Seems to be a Gboard issue.

Since those keyboards don't have a shift I only tried the caps lock on the soft keyboard. I also didn't try using termux's extended keyboard for shift/capslock.
