### ISSUE TITLE
Estou enfrentando problema ao tentar acessar 

### ISSUE THREAD

**Issue by Mcgratidao** [termux/termux-x11#591]
Quando rodo o comando "termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"

`.../com.termux/files $ termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"

(xfwm4:5724): xfwm4-WARNING **: 14:05:04.016: Unsupported GL renderer (llvmpipe (LLVM 18.1.2, 128 bits)).

** (xfdesktop:5761): WARNING **: 14:05:08.434: Failed to get system bus: Could not connect: No such file or directory`

Fico recebendo esse erro. Queria saber como resolvo, segui passo a passo para a instalação e mesmo assim estou recebendo um erro

**Comment by twaik** [comment]
1. Official language of all termux repos is **English**. We do not offer support in other languages.
2. Messages you get are warnings, not errors. Probably you are doing something wrong.

**Comment by Mcgratidao** [comment]
When I run the command "termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"

`.../com.termux/files $ termux-x11 :0 -xstartup "dbus-launch --exit-with-session xfce4-session"

(xfwm4:5724): xfwm4-WARNING **: 14:05:04.016: Unsupported GL renderer (llvmpipe (LLVM 18.1.2, 128-bit)).

** (xfdesktop:5761): WARNING **: 14:05:08.434: Failed to get system bus: Could not connect: No such file or directory`

I keep getting this error. I wanted to know how to solve it, I followed the installation step by step and I'm still getting an error

**Comment by twaik** [comment]
They are harmless. I get them all the time.
