### ISSUE TITLE
[Bug]: Keyboard displayes in preference page

### ISSUE THREAD

**Issue by zongou** [termux/termux-x11#593]
### Problem description

Keyboard displays in preference page

### What steps will reproduce the bug?

1. Open app
2. Press Back key to show soft keyboard
3. Tap the preference button

### What is the expected behavior?

Do not show keyboard.

**Comment by twaik** [comment]
I'll add some code to hide keyboard when becomes not focused.

**Comment by zongou** [comment]
More details:
It not only happens in the within that app.
for example, if you are using google keyboard, after repeaing thoese steps but without tappping the preference button,
instead you go to google keyboard settings page, or android system settings page, it triggers that too.

**Comment by zongou** [comment]
My idea to fix this bug:
Setting the flag to SHOW_IMPLICIT for general purpose, and then in the cases the soft keyboard cannot show, set it to SHOW_FORCED.

**Comment by twaik** [comment]
Android framework does not report about IME status. It is shown or not. 
And no, we can not check ime size since
1. It is not possible before Android 10.
2. Because of IME appearing animation on some devices.

**Comment by ask9027** [comment]
share screenshot , in my case there is no keyboard while open preferences as you told

**Comment by zongou** [comment]
> share screenshot , in my case there is no keyboard while open preferences as you told


https://github.com/termux/termux-x11/assets/23202896/0f13f3ee-9c7d-4a24-990f-81f5a3a14f53

**Comment by twaik** [comment]
@zongou check the latest build.

**Comment by zongou** [comment]
> share screenshot , in my case there is no keyboard while open preferences as you told


https://github.com/termux/termux-x11/assets/23202896/032a56f8-60d8-42db-a212-709d42d7018d

**Comment by zongou** [comment]
> @zongou check the latest build.

it indeed hides soft keyboard elsewhere, but i cannot switch keyboard now

https://github.com/termux/termux-x11/assets/23202896/99030c8b-8880-4481-86d2-0d505efb9009

**Comment by twaik** [comment]
Try [this](https://github.com/termux/termux-x11/actions/runs/8598723904).

**Comment by zongou** [comment]
> Try [this](https://github.com/termux/termux-x11/actions/runs/8598723904).

Currently this is no any issue i can find
