### ISSUE TITLE
[Feature Request]: double tap to drag / drag lock in Touchpad emulation

### ISSUE THREAD

**Issue by matejdro** [termux/termux-x11#595]
### Problem description

Currently, it is very difficult to perform dragging gestures with the Touchpad emulation. 

The only way I found is to enable extra mouse button feature, hold down the virtual button with one finger and then drag with another finger, which is pretty cumbersome.

### What steps will reproduce the bug?

1. Attempt to drag an icon or select a text with an emulated touchpad

### What is the expected behavior?

Something like this  (at 1:23):

https://youtu.be/4LFzxpT8mFk?t=83

**Comment by twaik** [comment]
Enable tap-to-drag in preferences...

**Comment by matejdro** [comment]
Doh, I went through the options multiple times and I missed this. Thanks!
