### ISSUE TITLE
[Comfort use]: Zoom in and out with finger . scroll when the mouse pointer hit the end of any side of the screen

### ISSUE THREAD

**Issue by Tanzin01** [termux/termux-x11#597]
As the title says.

Since phones screens are small, it would be really handy to be able zoom in and out with finger .

Also regarding the scrolling, it's nice to be able to scroll left and right when the mouse pointer either hits left or left end of screen, atleast. To be able to scroll up and down would also be more cool likewise.

**Comment by twaik** [comment]
Not going to be implemented.
