### ISSUE TITLE
[Bug]: Screen glitch with Intel vulkan driver

### ISSUE THREAD

**Issue by Xtr126** [termux/termux-x11#600]
### Problem description

Hello, I wondered if Termux:X11 supports non-Adreno GPUs with DRI3.
Intel vulkan driver has this issue although turnip works fine.
Tried with `-legacy-drawing` and `-force-bgra` and got the same result.
Apps that use vulkan glitches out:
Log: [termux_x11_debug.log](https://github.com/termux/termux-x11/files/14940651/termux_x11_debug.log)
![Screenshot_Termux_X11](https://github.com/termux/termux-x11/assets/80520774/ddf9995f-2457-47d5-8366-ac07b3c0d91d)
Tested on Bliss OS 15, Android 12.1

### What steps will reproduce the bug?

I edited mesa-vulkan-icd-freedreno-dri3 in termux-packages and added intel to vulkan driver list to compile Intel vulkan driver.
TERMUX_X11_DEBUG=1 termux-x11  :1
Launch glxgears and vkcube:
DISPLAY=:1  vkcube
MESA_LOADER_DRIVER_OVERRIDE=zink DISPLAY=:1  glxgears

**Comment by twaik** [comment]
Enabling Intel driver in mesa does not magically patch it to support dri3 or something.
Turnip was patched by xMeM to support Termux:X11. 
Closing this because it is bug of mesa, not of Termux:X11.

**Comment by Xtr126** [comment]
Thanks, I thought this patch was in common for all vulkan drivers https://github.com/termux/termux-packages/blob/master/packages/mesa-vulkan-icd-freedreno-dri3/wsi-termux-x11.patch
But without the patch, vkcube simply crashes on anv, so it does something.

**Comment by twaik** [comment]
It does something for freedreno (turnip) icd, not to all vulkan drivers. 
Changes related to all vulkan or GL drivers should sit in patches to regular mesa package...

**Comment by Xtr126** [comment]
Ok I found a fix, if it's helpful to anyone the glitches do not occur with latest Termux:X11 after installing vulkan-wsi-layer and sysvk from https://github.com/termux/termux-packages/issues/19460

**Comment by twaik** [comment]
It is not a fix for intel driver. It is simply completely different driver for GPU...
