### ISSUE TITLE
Game booster and Benchmark

### ISSUE THREAD

**Issue by nakele** [termux/termux-x11#603]
Would it be possible to make android believe termux-x11 be a benchmark or game so that we can benefit from the likes of samsung that improve performance when an app of certain type is launched/focused?

I did a test, I opened a game which my samsung recognise as a game, while observing the GPU Frequency and having Termux-X11 still open. What I noticed is that the GPU frequency go much higher when a game is focused and I can observe increase FPS on the termux-X11 instance as well, quite a bit. Unforturnatelly, when I return the focus to Termux-X11 the GPU drops back to the base / low frequency.

I'll try to make a video about it.

**Comment by twaik** [comment]
> Would it be possible to make android believe termux-x11 be a benchmark or game

No.
