### ISSUE TITLE
[feature request] Option to have same extra key behavior as Termux app

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#604]
Currenty in Termux:X11, when user activates Ctrl key and then presses any key in software keyboard, the Ctrl will preserve to be activated after the keypress. Such behaviour differs in Termux app, in which Ctrl will be deactivated after any keypress. It would be really great and much more convenient if there could be an option to make Termux:X11 extra key behave same as Termux app.

**Comment by twaik** [comment]
@agnostic-apollo can you please how I should modify the extra key bar behaviour to achieve that?

**Comment by agnostic-apollo** [comment]
In Termux app, if you click on a special buttons like `ctrl`, then will be unset if another key is pressed. If you long hold a special button, then it will be locked, and pressing any other key will not unset it automatically, the special key itself must be pressed again to unset it. This is done by calling the `readSpecialButton()` method and passing it `true`.

- https://github.com/termux/termux-app/blob/2f40df91e54662190befe3b981595209944348e8/termux-shared/src/main/java/com/termux/shared/termux/extrakeys/ExtraKeysView.java#L651
https://github.com/termux/termux-app/blob/2f40df91e54662190befe3b981595209944348e8/app/src/main/java/com/termux/app/terminal/TermuxTerminalViewClient.java#L345

- https://github.com/termux/termux-app/commit/2a74d43ca55932045d7f481c35fdffbf4bcc4b69

**Comment by twaik** [comment]
I mean how to make it deactivate active keys in the case if they are not locked? I see `state.setIsActive(false);` in `readSpecialButton`, but I doubt it is the right place.
