### ISSUE TITLE
[feature request] option to intercept system shortcuts only when pointer is also intercepted

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#606]
Firstly, I really appreciate the work of intercepting pointer and system shortcuts and pointer movement. When the pointer interception functionally is turned on, would it be even nicer to not intercept system shortcuts when the pointer is not intercept (returned to Android system)? This will be consistent with the default behaviour of virt-manager in Linux and perhaps many other VM software. The user can  press Alt+Tab to switch to other Android app quickly after pressing Esc to return the pointer back to Android, instead of current behavior of continuing intercepting Alt+Tab. Thank you.

**Comment by twaik** [comment]
And again, Termux:X11 is not related to VMs or similar software.
I'll check what I can do later.
