### ISSUE TITLE
[suggestion] use Ctrl+Alt instead of Esc to return pointer back to Android

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#607]
I am not sure whether it can be technically difficult, but it seems Ctrl+Alt is a better shortcuts (than Esc) to release the pointer to Android. As far as I know, common VM software such as virt-manager and [wmware](https://docs.vmware.com/en/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-6BEDAD0F-A1FC-4F85-8C62-27835C14356A.html) adopt this shortcut to release pointer. It is perhaps because Esc is a very common shortcut for many applications, e.g. closing a prompt, while Ctrl+Alt (without pressing any alphabet key) is not commonly used as shortcuts.

**Comment by twaik** [comment]
Termux:X11 is not related to VM software. 
Also some Android devices and IMEs do not send modifier key events if no alphabet keys were pressed. In this case Esc key is a better choice.

**Comment by knyipab** [comment]
I well understand that X11 is not a VM software and I would like to talk about only design. 

I understand that some device may not be able to use 'Ctrl+Alt`. Would you mind me creating a sub-page called "Unstable feature" and make a pull request? 

Or could we use both `Ctrl+Alt` and `Ctrl+Alt+Home`? FYR, MS RDP uses `Ctrl+Alt+Home` and that can serve as fallback for device that could not use `Ctrl+Alt`.
