### ISSUE TITLE
[Bug]: fullscreen & hide cutout don't give x11 more spaces

### ISSUE THREAD

**Issue by mio-19** [termux/termux-x11#612]
### Problem description

I enabled Fullscreen and Hide display cutout, hoping that X11 desktop will be able to use the space of the status bar, but it didn't.

### What steps will reproduce the bug?

1. Enable two options, disable additional keyboard
2. Start termux-x11
3. Start xfce `dbus-launch --exit-with-session xfce4-session`

**Comment by mio-19** [comment]
![Screenshot_20240423_232146_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/15fc50d9-a990-4dbc-9f31-5eec140cd277)

**Comment by twaik** [comment]
Termux:X11 already uses all documented features to make application use the whole available space.
Probably that is firmware-related behaviour and I can not fix it.

**Comment by mio-19** [comment]
> Termux:X11 already uses all documented features to make application use the whole available space. Probably that is firmware-related behaviour and I can not fix it.

Yes, Termux:X11 used the whole screen, but xfce4 doesn't not.

**Comment by mio-19** [comment]
> Termux:X11 already uses all documented features to make application use the whole available space. Probably that is firmware-related behaviour and I can not fix it.

Yes, Termux:X11 used the whole screen, but xfce4 does not. Probably Termux:x11 doesn't passed the right resolution to xfce4
