### ISSUE TITLE
[FEAT]: Unitary interval increment on Scaled Display Resolution mode

### ISSUE THREAD

**Issue by pikatwinky** [termux/termux-x11#614]
I use this fantastic project in combination with [Mobox](https://github.com/olegos2/mobox) to play games on my phone, in particular games that work in Window Mode. 
Using display resolution mode _scaled_ allows me to control how well a game is shown in a simple way (i'm not a very tech person), but I miss the ability to control in a more fine grained way the % slider movement. Currently the increments are on intervals of 10% (e.g you can use 110% or 120% but not 111%); i wish this increment could be changed to 1% if possible
 
Thanks
![Screenshot_2024-04-24-08-30-38-771_com termux x11-edit](https://github.com/termux/termux-x11/assets/31860235/b9a2f168-919c-4623-9d62-256a662e50a0)

**Comment by twaik** [comment]
Not going to be implemented.
This feature was created with intention to let user choose resolution fast without playing with seekbar. It is pretty much hard to choose right value without this increment value.
In the case if you need more control over resolution you should use "custom" resolution mode option.
