### ISSUE TITLE
[Bug]: Executing java application causes Exception 

### ISSUE THREAD

**Issue by kryptobolt200528** [termux/termux-x11#621]
### Problem description

using openJDK-17,
when executing any gui/cli java application as termux-x11 :1 -xstartup "java [class_name]" we get a ClassNotFound Exception,however the javac commamd work in the above syntax.

However there is no such issues using VNC(particularly tigervnc).

### What steps will reproduce the bug?

Write a java program,change working directory to the one where file is saved compile the java program,Try executing any java program(class file) as termux-x11 :1 -xstartup "java [class name]"

### What is the expected behavior?

java program should compile irrespective of it using cli or not,the javac command works in the way termux-x11 :1 -xstartup "javac [file_name]" and hence the java command should too

**Comment by kryptobolt200528** [comment]
This issue is carried foward when executing through terminal inside a desktop environment in my case Xfce4.
i.e. javac command works in the terminal of the Desktop Environment but java commands throws the classnotfoundexception.

**Comment by twaik** [comment]
Fixed by 74b17233e1c58e1a628c8a777bc762070769309c
