### ISSUE TITLE
[Bug]: fullscreen and hide cutout don't work as intended before restarting

### ISSUE THREAD

**Issue by mio-19** [termux/termux-x11#623]
### Problem description

I will upload screenshots to show the problem.
I am running termux:x11 on Samsung OneUI 6.1, Android 14

commit https://github.com/termux/termux-x11/commit/5489f7c8726855cd55729660c2867139aa2a5a74

### What steps will reproduce the bug?

Immersive only:
![Screenshot_20240507_112114_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/7d051f79-4fe5-4823-ae9d-cc925cdea616)
![Screenshot_20240507_112138_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/80fe17e2-0e3e-49c9-bd4a-c3ac9279540c)
Immersive and hide cutout:
![Screenshot_20240507_112226_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/bf5d53ba-82dc-41e6-b662-7abb0eafb53f)
![Screenshot_20240507_112221_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/1c8b7074-6aab-4c44-9ca5-f45646a63805)
No immersive. no hide cutout (working fine)
![Screenshot_20240507_112349_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/a34c0338-f36c-4a86-bc11-bf1a2a9ad222)

My settings 
![Screenshot_20240507_112517_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/cedcf6e0-2529-48ea-8214-0d1e7ef55ca3)

**Comment by mio-19** [comment]
hide cutout only
![Screenshot_20240507_112912_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/823b1c97-2b51-4a44-a22c-2600a35a7765)
![Screenshot_20240507_112905_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/663be510-5f9d-467e-964e-95acfaffe05c)
No immersive. no hide cutout. landscape (working fine)

![Screenshot_20240507_113022_TermuxX11](https://github.com/termux/termux-x11/assets/57285379/9268c2de-8209-428f-983b-73e9a36da2ce)

**Comment by mio-19** [comment]
I freshly installed termux:x11 on stock lineageos and got similar results.

**Comment by twaik** [comment]
Android does not let applications hide cutout if they do not request fullscreen. 
There is no way to override this system behaviour.

**Comment by mio-19** [comment]
> Android does not let applications hide cutout if they do not request fullscreen. There is no way to override this system behaviour.

The issue is more than this. I got even wider "cutout" when fullscreen is enabled and I got normal cutout when fullscreen and hide cutout are enabled.

**Comment by twaik** [comment]
Unfortunately I can not reproduce it.
I think it is some firmware-related bug.

**Comment by mio-19** [comment]
> Unfortunately I can not reproduce it. I think it is some firmware-related bug.

I don't think OnePlus 6 with official lineageos and Samsung S23 Ultra with OneUI6 could have a same firmware-related bug.

What is your hardware and software?

**Comment by mio-19** [comment]
I don't see evidences showing that this issue is firmware-related. I want to re-open the issue as I think it is a relevant bug. Alternatively I might open more appropriate issue with test results on multiple devices.

**Comment by ewt45** [comment]
with the latest android studio, there is a feature of using device streaming to debug remote device for free.
https://developer.android.com/studio/run/android-device-streaming
there are samsung android14 (one ui 6.0 though) available. i tried it and it seems to have similar bugs?
maybe @twaik  can debug with  it further

with resolution=native
none:
![none](https://github.com/termux/termux-x11/assets/79033456/4ebc9927-7b64-4bf9-bd61-24cad12597e6)

immersive:
![immersive](https://github.com/termux/termux-x11/assets/79033456/014c86b3-22d8-4340-8f4b-ef7def21e5ed)

immersive + hide cutout
![immsersive+hidecutout](https://github.com/termux/termux-x11/assets/79033456/3169ae17-c601-42e7-82a8-1bcbb2eb1912)

**Comment by mio-19** [comment]
@ewt45 Thanks! I haven't correctly restarted termux:x11.
It works correctly after I force killed termux:x11 in android system settings

**Comment by twaik** [comment]
So it seems like this issue may be closed, right?

**Comment by mio-19** [comment]
> So it seems like this issue may be closed, right?

No. This issue is now about the problem before restarting.

A solution might be displaying a toast to tell the user to restart the app so the user know what to do.
