### ISSUE TITLE
[Bug]: incorrect CJK characters input 

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#625]
### Problem description

@twaik
Shall we continue here the discussion of CJK character issues initiated in #620 . 

I tested with the lastest Termux:X11 build and found issues pasting CJK characters using Samsung keyboard. ANd I also tested `tigervnc` + RealVNC Viewer for comparison. I found that: 

* Termux:x11 has different behaviors across applications. `code-oss` and `chromium` see incorrect random re-occurrence of characters, while `mousepad` is robust in handling the key events.  
* In `tigervnc` + RealVNC Viewer, CJK input is very consistent across applications. Its major problem is not sending specific character codes at all (see also its `xev` log). I don't quite know of other mainstream Android vnc viewer that supports CJK keyboard input, so can't be certain the cause is from RealVNC or `tigervnc`. 
* I have no expertise but I feel that this issue is fixable given the test result below. It might be more helpful comparing [x11-zh-sc.log](https://github.com/termux/termux-x11/files/15262667/termux-x11-zh-sc.log) and [vnc-zh-sc.log](https://github.com/termux/termux-x11/files/15262694/tigervnc-realvnc-zh-sc.log). 

### Termux-X11
|  | JP | ZH (trad.) | ZH (simp.) | KR |
| --- | --- | --- | --- | --- |
| input | `入力方法が正常かどうかをテストする` | `測試輸入法是否正常` | `测试输入法是否正常` | `입력 방법이 정상인지 테스트` |
| `mousepad` | `入力方法が正常かどうかをテストする` | `測試輸入法是否正常` | `测试输入法是否正常` | `입력 방법이 정상인지 테스트` |
| `code-oss` | `入力方法が正常正どうかをテがトする`<br/>`をテ方トす正常かどうかが正スかする` | `測試輸入正是否正輸`<br/>`測法輸入法是測試常` | `测试是否法是测正常`<br/>`测试是入法是测正常` | `입력 방법이 정상인지 테이트`<br/>`입력 방법스 트상력지 법스정` | 
| `chromium` | `入力方法が正常かどうか方テスかする`<br/>`をテス法が正入かどうかを正スかどる` | `測試輸否正是否正常`<br/>`入試輸入法是否正輸` | `测试输入正常否正输`<br/>`测法输入法常测正常` | `입력 방테이 정입력지 테스정`<br/>`입인 방법이 정상력지 법이트` | 
| `xev` | [x11-jp.log](https://github.com/termux/termux-x11/files/15262656/termux-x11-jp.log) | [x11-zh-tc.log](https://github.com/termux/termux-x11/files/15262666/termux-x11-zh-tc.log) | [x11-zh-sc.log](https://github.com/termux/termux-x11/files/15262667/termux-x11-zh-sc.log) | [x11-kr.log](https://github.com/termux/termux-x11/files/15262661/termux-x11-kr.log) |

### `tigervnc` + RealVNC Viewer
|  | JP | ZH (trad.) | ZH (simp.) | KR |
| --- | --- | --- | --- | --- |
| input | `入力方法が正常かどうかをテストする` | `測試輸入法是否正常` | `测试输入法是否正常` | `입력 방법이 정상인지 테스트` |
| `mousepad` | `入力方法が正常かか` | `入法是否正常` | `测试输入法是否正常` | `   ` |
| `code-oss` | `入力方法が正常かか` | `入法是否正常` | `测试输入法是否正常` | `   ` |
| `chromium` | `入力方法が正常かか` | `入法是否正常` | `测试输入法是否正常` | `   ` |
| `xev` | [vnc-jp.log](https://github.com/termux/termux-x11/files/15262690/tigervnc-realvnc-jp.log) | [vnc-zh-tc.log](https://github.com/termux/termux-x11/files/15262695/tigervnc-realvnc-zh-tc.log) | [vnc-zh-sc.log](https://github.com/termux/termux-x11/files/15262694/tigervnc-realvnc-zh-sc.log) | [vnc-kr.log](https://github.com/termux/termux-x11/files/15262691/tigervnc-realvnc-kr.log) |

### What steps will reproduce the bug?

You may debug by using Samsung keyboard to paste CJK character string from any translation app such as Google Translate.

**Comment by twaik** [comment]
I am aware about the problem. 
But the code I used for handling raw Unicode was borrowed from tigervnc and improved a little with suggestions of some other contributors.
I simply have no idea what I can do.
I opened 2 issues in tigervnc project but currently they did not commit fixes.
