### ISSUE TITLE
Cannot establish any listening sockets - Make sure an X server isn't already running

### ISSUE THREAD

**Issue by dvlahakis** [termux/termux-x11#63]
Hello. I get the following error when running the commands to start termux-x11. I have downloaded the artifact version of the apk and deb and installed both. I have the fdroid version of termux, latest update

I run termux:x11 and the toast message service was created appears.
I run termux and the following commands:

```
~ $ export XDG_RUNTIME_DIR=${TMPDIR}
~ $ termux-x11 :1 >/dev/null &
[1] 3587
~ $ termux-x11 is already running
Starting Xwayland
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)

[1]+  Exit 1                  termux-x11 :1 > /dev/null
```

Any thoughts on what I might be missing? Thanks!

**Comment by WMCB-Tech** [comment]
likely because of there's another xwayland process running or a vnc server. try killing those processes and try again

**Comment by mjuned47** [comment]
Wayland already running on display 1
Change display number

**Comment by RalfWerner** [comment]
`x0=Xwayland` and `x1=Xvnc` Server can be used paralel. You only need to use different `DISPLAY` e.g. `:0` and `:1`. If `p0=$(pgrep -o $x0)` exist a renewed start is _**not required**_, but  the X11 app is to start _**before**_ `x0`. The VNC client apps are started after the `p1=$(pgrep -o $x1)` process exist.

**Comment by dvlahakis** [comment]
Thanks for the input, it helped me figure out what was going on. I had installed the latest artifact, which comes with an apk and a deb file. I would execute the apk, then run the commands listed on the github info page. I realized running termux-x11 was failing because xwayland or something was running already as everyone pointed out, and @RalfWerner post helped me figure out that by running the apk I was already starting the server, so I was running it twice. So I reran the steps without running the apk manually and was able to stumble on a was to get the server running, as the code lists below. 

I was not able to run xfce4-session on the command line, it fails and kills the server. However, I can run aterm, and then execute xfce4-session within aterm, which works. Also, when aterm exits, the server won't accepts clients anymore, and has to be restarted.

The post by @RalfWerner also indicates there are different versions of the apk to use, is a particular one recommended?

Thanks!


```
~ $ pgrep -u u0_a976 -a
15121 /data/data/com.termux/files/usr/bin/gpg-agent --sh --daemon
19144 /data/data/com.termux/files/usr/bin/bash -l
26137 pulseaudio --start
~ $ export XDG_RUNTIME_DIR=${TMPDIR}
~ $ termux-x11 :0 >/dev/null &
[1] 19733
~ $ res = 0
Activity is started
Got getWaylandFD
{ParcelFileDescriptor: java.io.FileDescriptor@94a9ff}
Lorie requested fd
Got getLogFD
{ParcelFileDescriptor: java.io.FileDescriptor@55243cc}
Got finish request
App sent finishing command
Starting Xwayland
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 569, clipping.
>                   X11 cannot support keycodes above 255.
Errors from xkbcomp are not fatal to the X server

~ $ env DISPLAY=:0 aterm
aterm: Failed to open input method
^Z
[2]+  Stopped                 env DISPLAY=:0 aterm
~ $ pgrep -u u0_a976 -a
15121 /data/data/com.termux/files/usr/bin/gpg-agent --sh --daemon
19144 /data/data/com.termux/files/usr/bin/bash -l
19733 /data/data/com.termux/files/usr/bin/Xwayland :0
20163 aterm
20164 bash
26137 pulseaudio --start
~ $
```

**Comment by RalfWerner** [comment]
My recommendation I had described above and wrote my experience with the current `master` branch in the [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123) Addendum. Since Termux is _Open Source_, there are probably other recommendations. The best would be a merge of the advantages of different versions. Unfortunately, nobody works actually on this topic. But you could _build_ yor own version if you like.

**Comment by dvlahakis** [comment]
Understood, thanks.

Dimitri Vlahakis
e. ***@***.***
c. +19174187640

On November 13, 2021 at 11:21 AM, RalfWerner ***@***.***) wrote:
My recommendation I had described above and wrote my experience with the current master branch in the OTS ( https://github.com/termux/termux-float/issues/37#issuecomment-916777123 ) Addendum. Since Termux is Open Source, there are probably other recommendations. The best would be a merge of the advantages of different versions. Unfortunately, nobody works actually on this topic. But you could build yor own version if you like.

**Comment by RalfWerner** [comment]
Another recommendation: Don't put your Phone no in commits (remove again - edit is not enough - github don't forget)

**Comment by dvlahakis** [comment]
I replied by email and forgot to remove. I'm a fool.

**Comment by twaik** [comment]
It is not a problem of `termux-x11`, it is a problem of `Xwayland`...
To fix this you should recreate TMPDIR like this:
```
rm -rf $TMPDIR
mkdir -p $TMPDIR
```
And then force-stop Termux application (not Termux:X11).
