### ISSUE TITLE
[Bug]: Wrong touching position

### ISSUE THREAD

**Issue by numberokta** [termux/termux-x11#631]
### Problem description

When touchMode is Simulated touchscreen, sometime touching in wrong position.

### What steps will reproduce the bug?

Set touchMode to Simulated touchscreen and try short and long tap to see the difference

https://github.com/termux/termux-x11/assets/20727200/ecebc511-d49a-4452-8b62-1eaa0655de71

### What is the expected behavior?

touching in right position

**Comment by twaik** [comment]
Now you can test the https://github.com/termux/termux-x11/actions/runs/9112246071 artifact.

**Comment by twaik** [comment]
The reason that happened was sending unitialized data/trash in the valuator field of event, so the 3f4b0af46f24e5fb2dfee4aab83c4cc2381e5f26 commit fixes it.
Can not reproduce on my devices after this commit.

**Comment by numberokta** [comment]
thanks
