### ISSUE TITLE
[Feature Request] Want the zoom function of the AVNC app.

### ISSUE THREAD

**Issue by Himeno-Sena-0721** [termux/termux-x11#636]
When I use Termux-X11, I often encounter situations where the text is too small to see clearly. Therefore, I would like a feature similar to the screen zoom function in the AVNC app.

**Comment by twaik** [comment]
Not going to be implemented.
Duplicate of #597

**Comment by twaik** [comment]
If you have problems with text size you can change resolution, X server DPI or DPI setting in your DE.
