### ISSUE TITLE
  dri3 extension makes lavapipe driver failure

### ISSUE THREAD

**Issue by yu-zify** [termux/termux-x11#639]
I found that since Termux-X11 supports the DRI3 extension, the Lavapipe (the Software Vulkan Driver) driver has a problem that show the black window of the lavapipe vulkan program。

such as vkcube:
![Screenshot_2024-05-21-00-20-34-131_com termux x11](https://github.com/termux/termux-x11/assets/99244012/62f00904-2c55-4a5a-85db-e6fbfe1861de)

If I use vnc or an older version of termux-x11,lavapipe  vkcube works fine.
vnc:
![Screenshot_2024-05-21-15-18-45-693_com gaurav avnc](https://github.com/termux/termux-x11/assets/99244012/b569972b-45e9-4c7a-ade8-bf4946a61a0a)

I tried change the code to turn off the dri3 extension to get lavapipe to run successfully as well.
![Screenshot_2024-05-21-15-13-17-267_com kiwibrowser browser](https://github.com/termux/termux-x11/assets/99244012/b25cd1bb-9b49-4151-977f-9567d0f9de5b)
![Screenshot_2024-05-21-15-13-50-722_com kiwibrowser browser](https://github.com/termux/termux-x11/assets/99244012/b038af77-78c0-4a8a-9e88-c0737e4c0d2e)

why is that?

**Comment by yu-zify** [comment]
Thanks,this is useful for devices that don't support Turnip.

**Comment by twaik** [comment]
From now you can use `-disable-dri3` option to make lavapipe work.
