### ISSUE TITLE
[Bug]: Can't move cursor in X11.

### ISSUE THREAD

**Issue by sparklingtube222** [termux/termux-x11#640]
### Problem description

The phone is a note 4 snapdragon, armv7a, running android 9 havocos rooted using magisk. I installed termux and the X11 addon, followed the guide, after starting the x11 server, i noticed i only saw a cursor, i then changed the command to include -legacy-drawing, then I restarted, but noticed i couldnt move the cursor, i tried with scrcpy OTG, and OTG cable, nothing worked, when i tried it on my other phone, it did work.

### What steps will reproduce the bug?

Owning a Note 4.

### What is the expected behavior?

That I am able to move the cursor

**Comment by sparklingtube222** [comment]
It doesnt show the desktop without legacy drawing, I use termux-x11 --legacy-drawing -xstartup xterm or i use xfce4-session, with xterm i also cant move the cursor.

**Comment by ask9027** [comment]
use `TERMUX_X11_DEBUG=1 termux-x11 :0 -ac -xstartup xfce4-session` then send log here

**Comment by sparklingtube222** [comment]
Sorry for the late response, I was doing something, is there a way to save the log in a file automatically or do I just post all the output here?

**Comment by sparklingtube222** [comment]
![image](https://github.com/termux/termux-x11/assets/143890296/4d681915-3b1e-4810-9bf9-bbb23075bd37)
this is the x11 app after using your thing to start it and heres the log: https://pastebin.com/Xn5UmXsp

**Comment by twaik** [comment]
Disable SELinux. 
```
setenforce 0
```

**Comment by sparklingtube222** [comment]
still only cursor and still cant move the cursor

**Comment by twaik** [comment]
Disable SELinux and restart X server.

**Comment by sparklingtube222** [comment]
i added legacy drawing now i can see the xfce but i still cant move the cursor and I did disable Selinux, do i need to restart my phone to get it to apply?

**Comment by twaik** [comment]
No. Restarting device will re-enable SELinux. 
Force-stop termux and termux-x11 apps.
Disable selinux.
Start termux and X server.
After this switch to Termux:X11 activity.

**Comment by sparklingtube222** [comment]
its spamming failed to load module cannot locate libgiognutls.so

**Comment by sparklingtube222** [comment]
failed to get system bus too

**Comment by sparklingtube222** [comment]
its lagging behind, its on 0.4 fps what the fuck

**Comment by twaik** [comment]
> its spamming failed to load module cannot locate libgiognutls.so

> failed to get system bus too

Not related to X server. Fix your environment.
The issue is about mouse moves.

**Comment by twaik** [comment]
So the mouse works?

**Comment by sparklingtube222** [comment]
nope its on 0.4 fps it said in the log

**Comment by twaik** [comment]
> what the

Avoid using bad language please.

**Comment by sparklingtube222** [comment]
sorry, is there any way to optimize it?

**Comment by twaik** [comment]
It reports average FPS. It will not show you high FPS if you do not output something to X server.

**Comment by sparklingtube222** [comment]
so, its freezing, the time now is 41, the x11 shows 34...

**Comment by twaik** [comment]
Again. Does the mouse work? And what exactly do you check?

**Comment by sparklingtube222** [comment]
i try to move the mouse its not moving because the whole x11 froze, the time is stuck

**Comment by sparklingtube222** [comment]
so, if i exit the app and then go back in it updates the image but still cant move the mouse

**Comment by twaik** [comment]
The mouse will not move in the case if screen updating does not work.
Mouse drawing is implemented exactly the same way as screen drawing.
Start termux-x11 with something like glxgears to make sure screen is updating.

**Comment by sparklingtube222** [comment]
how would i do that

**Comment by twaik** [comment]
```
pkg i mesa-demos
termux-x11 :1 -xstartup glxgears
```

**Comment by sparklingtube222** [comment]
with gears

**Comment by twaik** [comment]
Do gears move?

**Comment by sparklingtube222** [comment]
nope

**Comment by twaik** [comment]
Termux:X11 is already doing everything possible to display images on the screen.
However, there are devices whose firmware has been modified by the manufacturer in such a way that Termux:X11 cannot function properly.
Therefore, I want to inform you that your device is not supported.
