### ISSUE TITLE
[Bug]: "Termux:X11 application is not found" despite being there

### ISSUE THREAD

**Issue by DanielKonopka** [termux/termux-x11#645]
### Problem description

Trying to run: ``termux-x11 :1 -xstartup "xfce4-session"`` outputs:

``Termux:X11 application is not found.You should choose latest successful workflow here: https://github.com/termux/termux-x11/actions/workflows/debug_build.ymlAfter this you should download "termux-x11-arm64-v8a-debug" or "termux-x11-universal-debug" artifact and install apk contained in this zip file.``

But the latest debug Termux::X11 application is installed. Could it be because my main Termux app is F-Droid version?

OS: Android 10 (non-root) / EMUI 10.1.1

### What steps will reproduce the bug?

Run: ``termux-x11 :1 -xstartup "xfce4-session"``

### What is the expected behavior?

A running X11 server.

**Comment by twaik** [comment]
Install this.

**Comment by twaik** [comment]
Is problem still reproducible?

**Comment by DanielKonopka** [comment]
Tried both ``app-universal-debug.apk`` and ``app-arm64-v8a-debug.apk``. Still the same.

**Comment by twaik** [comment]
I can try to connect your device directly and find out what is a problem at 5:30 PM (UTC) tomorrow. Can you contact me in telegram (https://t.me/twaik)?

**Comment by DanielKonopka** [comment]
Please reach me at https://t.me/dannyko8

**Comment by twaik** [comment]
Fixed by 99efcc2e41f886c584ee7db8c0622d9294113df4
