### ISSUE TITLE
[Bug]: the xfce pulseaudio plugin not working in Debian

### ISSUE THREAD

**Issue by mhdtyb** [termux/termux-x11#651]
### Problem description

i am on Android 14,using Debian with xfce in proot-distro, i installed all required packages in termux and in proot-distro, i do all required steps, but when i runned the gui everything works exept pulseaudio.
pulseaudio worked in termux (Native GUI in termux), and worked in ubuntu proot-distro, but not worked in Debian
![Screenshot_2024-06-06-14-56-08-38_84d3000e3f4017145260f7618db1d683](https://github.com/termux/termux-x11/assets/161652353/6296a72e-6b32-4c74-ba7a-262f9eb08903)

### What steps will reproduce the bug?

running xfce in Debian proot-distro using Termux:x11

**Comment by twaik** [comment]
Not related to Termux:X11.

**Comment by mhdtyb** [comment]
ok where should i open issue

**Comment by twaik** [comment]
Pulseaudio inside proot-distro will not work. It simply does not have the module required for android audio output, and building it is not possible due to libc incompatibility.
You should run pulseaudio outside of proot-distro with SLES+TCP module and export PULSE_SERVER variable in proot-distro.

**Comment by mhdtyb** [comment]
> Not related to Termux:X11.

> Pulseaudio inside proot-distro will not work. It simply does not have the module required for android audio output, and building it is not possible due to libc incompatibility. You should run pulseaudio outside of proot-distro with SLES+TCP module and export PULSE_SERVER variable in proot-distro.

yes that what i did and it works, i just want to know if it is possible to that without all this steps, but why it worked in ubuntu without that
