### ISSUE TITLE
[BUG]: X server not stopping , _XSERVTransSocketUNIXCreateListener:

### ISSUE THREAD

**Issue by PrashantRawatCoder** [termux/termux-x11#652]
### Problem description

When I started x11 it was fine , (although it took many try to make it working). But after I close previous server and then run `pkill -f com.termux.x11` . Then I try to run x11 again but now it shows error which looks like this :

>` ~ $ termux-x11 :1 -legacy-drawing -xstartup "code-oss"
13822 exited, status=0
~ $ termux-x11 :1 &
[1] 13908
~ $ _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
~ $`

### What steps will reproduce the bug?

I am using termux , without any distro and using termux x11.
I am not using xfce4 instead I installed xwayland and run pygame directly, which worked and pygame windows was working in x11 , but when I tried to run code-oss with same method it exited on first time with status =0 and when I tried it second time then the error came . When I try to kill x11 nothing happens , even after killing termux session nothing happens I have to force stop termux to make it work again.
Run : `termux-x11 :1 -legacy-drawing -xstartup "code-oss"` 
Then it will give error : `13822 exited, status=0`
Then run : `pkill -f com.termux.x11`
Then run : `termux-x11 :1 &`
Then it will give error :
`_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)`

### What is the expected behavior?

After I kill x11 by pkill , then I run it second time then it should run without error.
Or there may be another way to stop x server , can you tell me a way to stop x server .
Thanks for help. Please help. 🥺🥺❤️

**Comment by twaik** [comment]
> after I close previous server and then run `pkill -f com.termux.x11`

Sometimes pkill is not effective in closing termux-x11. But force-stopping termux application (not termux-x11) should help.

> xwayland

Its support dropped 2 years ago.

**Comment by PrashantRawatCoder** [comment]
so , i will have to force stop termux every time i want to stop x server ??
also , thanks to all developers for creating such amazing platform ;)
:
