### ISSUE TITLE
keyinterceptor service issue

### ISSUE THREAD

**Issue by xcccdjsn** [termux/termux-x11#657]
### Problem description

![IMG_20240624_174246](https://github.com/termux/termux-x11/assets/115536576/3a5f6257-3b7f-4373-87cc-0a34daf3a64d)
![Screenshot_2024-06-24-17-44-41-27](https://github.com/termux/termux-x11/assets/115536576/caeae463-1b8b-4742-9a79-5d2e45570997)

I started this service, but why can't open the two settings? 
I am using bluetooth keyboard, but when I pressed 'Esc' or 'win' and other, it always triggers system shortcuts.

### What steps will reproduce the bug?

like above

### What is the expected behavior?

enter vim normal mode with using vim rather than exiting termux-x11 app

**Comment by twaik** [comment]
Can you reproduce it on the latest nightly?

**Comment by twaik** [comment]
@xcccdjsn ?

**Comment by xcccdjsn** [comment]
> @xcccdjsn ?

Yes, now it can be turned on
![Screenshot_2024-07-04-13-47-25-98](https://github.com/termux/termux-x11/assets/115536576/adbefcf6-8ffc-4336-8186-1049a02ee4c5)
but it seems to have some problems, when I use blueteeth keyboard. This service does not work normally like "esc" and "win" will not be received. When I press "ctrl + enter" multi times continuously, this service will not intercept system shortcuts and trigger system shortcuts. I hope that it can receive "win" and "esc"  noramally in it.

**Comment by twaik** [comment]
Unfortunately I can not reproduce it.

**Comment by twaik** [comment]
Ok, I need the log with "TERMUX_X11_DEBUG=1" of termux-x11 not intercepting these events with accessibility service. Use this apk.
[app-universal-debug.zip](https://github.com/user-attachments/files/16094815/app-universal-debug.zip)

**Comment by xcccdjsn** [comment]
It's likely that termux-0.118.1 does not have this setting.
![Screenshot_2024-07-04-15-59-08-06](https://github.com/termux/termux-x11/assets/115536576/937c89f1-3973-4f1d-9835-709c3b6b04d4)

**Comment by twaik** [comment]
termux-x11 and termux-app are completely separate and independent products of the same Github organisations.

https://github.com/termux/termux-x11?tab=readme-ov-file#logs

**Comment by xcccdjsn** [comment]
> termux-x11 and termux-app are completely separate and independent products of the same Github organisation.
> 
> https://github.com/termux/termux-x11?tab=readme-ov-file#logs

I did it, but it does not have any log, this is my scipt.
```shell
virgl_test_server_android &
TERMUX_X11_DEBUG=1 termux-x11 :0 > ~/termux_x11.log &
rm -rf /data/data/com.termux/files/usr/tmp/dbus*
rm -rf /data/data/com.termux/files/usr/tmp/proot*
proot-distro login arch --user xccc --shared-tmp
```
This is my keyboard, it only that "windows" key does not work normally when I use "Window mode" on it.
![IMG20240704183344](https://github.com/termux/termux-x11/assets/115536576/ec65c179-fbb6-484f-99f9-38516a975fba).

If I use "Android mode", "esc" and "windows" all can not work normally.

**Comment by xcccdjsn** [comment]
I always use "windows key" in dwm desktop environment, so this key is useful for me.

**Comment by twaik** [comment]
> I did it, but it does not have any log, this is my scipt.

Probably you are doing something wrong. 
Try to use `TERMUX_X11_XSTARTUP` environment variable or `-xstartup` option of termux-x11.

**Comment by xcccdjsn** [comment]
> > I did it, but it does not have any log, this is my scipt.
> 
> Probably you are doing something wrong. Try to use `TERMUX_X11_XSTARTUP` environment variable or `-xstartup` option of termux-x11.

i use this command `termux-x11 :0 -xstartup "export TERMUX_X11_DEBUG=1" &`, but it outputs "10125 exited, status=0"

**Comment by twaik** [comment]
It does not work that way. 
`TERMUX_X11_DEBUG` is the environment variable which should be set BEFORE termux-x11 is being invoked. 
`-xstartup` option makes termux-x11 invoke your command WHEN X SERVER IS READY.

**Comment by twaik** [comment]
@xcccdjsn any news?

**Comment by twaik** [comment]
@xcccdjsn ?

**Comment by xcccdjsn** [comment]
> @xcccdjsn ?
I did it, the below is debug logs.
"^[]0;xccc@localhost:~^GStarting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.termux.x11/.MainActivity }
^[]0;xccc@localhost:~^G
~"
I make me feel that the intercepting service can not work normally.

**Comment by twaik** [comment]
A single line of log is not helpful .
I need the hole log...

**Comment by xcccdjsn** [comment]
> A single line of log is not helpful . I need the whole log...

It only outputted these messages.

**Comment by twaik** [comment]
Try to get logcat of com.termux.x11 application. AFTER you use not-intercepted keys. https://f-droid.org/packages/com.tananaev.logcat/

**Comment by xcccdjsn** [comment]
> Try to get logcat of com.termux.x11 application. AFTER you use not-intercepted keys. https://f-droid.org/packages/com.tananaev.logcat/

[logcat.txt](https://github.com/user-attachments/files/16202276/logcat.txt)

I am very sory to reply yo you so late, the file above is catched by Logcat app.

**Comment by twaik** [comment]
According to the log you used Win+Home. Is it correct?

**Comment by xcccdjsn** [comment]
> According to the log you used Win+Home. Is it correct?

Yes

**Comment by xcccdjsn** [comment]
> According to the log you used Win+Home. Is it correct?

Yes, but the service does't intercept system shortcuts.

**Comment by twaik** [comment]
It did not intercept HOME key, WIN key was intercepted fine.
Try [this apk](https://github.com/user-attachments/files/16216669/app-universal-debug.zip).

**Comment by xcccdjsn** [comment]
> It did not intercept HOME key, WIN key was intercepted fine. Try [this apk](https://github.com/user-attachments/files/16216669/app-universal-debug.zip).

Ok!

**Comment by xcccdjsn** [comment]
> It did not intercept HOME key, WIN key was intercepted fine. Try [this apk](https://github.com/user-attachments/files/16216669/app-universal-debug.zip).

I may have misunderstood. When you mentioned HOME earlier, I thought it was a shortcut key on the mobile system, which means Win+Enter to enter the home screen. During my testing, I enabled this service, but none of the system shortcuts were blocked.

**Comment by twaik** [comment]
Ok, it seems to be more difficult than I expected. I need to debug this in realtime, with wireless debugging option. 
Can you contact me in telegram? https://t.me/twaik .

**Comment by xcccdjsn** [comment]
> Ok, it seems to be more difficult than I expected. I need to debug this in realtime, with wireless debugging option. Can you contact me in telegram? https://t.me/twaik .

Ok,

**Comment by xcccdjsn** [comment]
> > Ok, it seems to be more difficult than I expected. I need to debug this in realtime, with wireless debugging option. Can you contact me in telegram? https://t.me/twaik .
> 
> Ok,

Sorry, I encountered some issues when I registered for Telegram. Is there any other way to contact you?

**Comment by twaik** [comment]
Discord or Matrix.

**Comment by twaik** [comment]
`.twaik` in Discord and `@.twaik:matrix.org` in Matrix.

**Comment by xcccdjsn** [comment]
> `.twaik` in Discord and `@.twaik:matrix.org` in Matrix.

Your account refus to be added in Discord.
This is my account `294425xccc_55714`

**Comment by twaik** [comment]
Friend request is sent. Waiting for your response.

**Comment by twaik** [comment]
Try the latest nightly with Windows mode on keyboard.

**Comment by xcccdjsn** [comment]
> Try the latest nightly with Windows mode on keyboard.

I just tried it and it worked normally for the first few times, but the system shortcut key will still be triggered after pressing it multiple times.

**Comment by twaik** [comment]
Does it happen only to "Win+Enter" or the same thinghappens to Alt+Tab too?

**Comment by xcccdjsn** [comment]
![Screenshot_2024-07-15-23-38-43-50](https://github.com/user-attachments/assets/ff453789-4f07-4910-b823-ccb70f6630fd)

These shortcuts all can work normally when the service is on.

**Comment by xcccdjsn** [comment]
> Does it happen only to "Win+Enter" or the same thing happens to Alt+Tab too?

Yeah.

**Comment by twaik** [comment]
What is magnifying glass key?

**Comment by xcccdjsn** [comment]
It's win key, you can connect your phone with keyboard, using win and slash key can call up this shortcut key interface .

**Comment by twaik** [comment]
> > Does it happen only to "Win+Enter" or the same thing happens to Alt+Tab too?
> 
> Yeah.

A question containing "or" requires full answer. The word `Yeah` does not answer which option is correct.

**Comment by twaik** [comment]
Does service intercept keys in the case if you wait and start over?
Does KeyInterceptor service being shutdown after that?

**Comment by xcccdjsn** [comment]
> Does service intercept keys in the case if you wait and start over? Does KeyInterceptor service being shutdown after that?

It will be intercepted a few times and then stopped, and the service will not be shut down.

**Comment by twaik** [comment]
> All is correct.

`happens only to` part makes `the same thing happens to` impossible...

**Comment by twaik** [comment]
[app-universal-debug.zip](https://github.com/user-attachments/files/16237819/app-universal-debug.zip)
Try to reproduce it with this build and send me the log.

**Comment by twaik** [comment]
I mean logcat.

**Comment by twaik** [comment]
[app-universal-debug.zip](https://github.com/user-attachments/files/16273901/app-universal-debug.zip)
@xcccdjsn can you please try to reproduce it one more time and extract logcat?

**Comment by twaik** [comment]
Closing this due to the lack of activity.
It seems like in the case if some key combinations were invoked some system window acquires focus so Termux:X11's window becomes unfocused and KeyInterceptor service drops key intercepting.

**Comment by xcccdjsn** [comment]
> Closing this due to the lack of activity. It seems like in the case if some key combinations were invoked some system window acquires focus so Termux:X11's window becomes unfocused and KeyInterceptor service drops key intercepting.

I just tried the latest version, still just open and press win+enter a few times can normally block, but after continuous press, will not be blocked. Have you ever tested it on your cell phone.

**Comment by twaik** [comment]
I asked you to check the specific build...

**Comment by skskss** [comment]
hey is this issue is still open, 
Cause i've been facing same issues recently,
I use blender on prooted debian for daily use.
Usually blender has a great number of keyboard shortcuts,
And when lastly when i had been modeling some stuff.
I noticed my mouse and keyboard flikkering multiple times,
also termux app crashed a couple of times
