### ISSUE TITLE
Can't connect to the x11 server with my Ubuntu server 

### ISSUE THREAD

**Issue by AinzOoalGown0987654321** [termux/termux-x11#662]
As the title states I want to use the x11 server from termux to x11 forward my Ubuntu server and at best from outside of my server but I can't find any resources about it. I tried to setup an display with export DISPLAY=localhost:0 and with my ip both doesn't work I tried xterm & and xclock & and both didn't work if set the settings for ssh x11 forwarding on my server 

I also tried to do it in my local network and it didn't work 

And yes Port forwarding is active and working 

Any suggestions?

**Comment by twaik** [comment]
Not a termux-x11 issue. It is a skill issue. Use `-listen tcp -ac` + exporting DISPLAY with IP on your server.
