### ISSUE TITLE
feature reqest: add startup script

### ISSUE THREAD

**Issue by natebragg** [termux/termux-x11#664]
It's very often the case that users want to always read a certain script when X starts (e.g., .xinitrc).  Other systems provide this functionality, and it would be nice if termux-x11 could, so that we don't have to supply one every time we start it up.

**Comment by twaik** [comment]
`.xinitrc` is a part of `startx` project. Starting environment is not a purpose of X server.
AFAIK there is only one X server which can run `.xstartup` file content and it is tigervnc. But it is pretty much special case.

**Comment by natebragg** [comment]
Yes, I was just giving .xinitrc as an example.  What do you suggest then as a way to run such startup scripts for every time termux-x11 is run?

**Comment by twaik** [comment]
Now you can put `export TERMUX_X11_XSTARTUP=<yourscript>` somewhere in `.bashrc` and your script will run every time termux-x11 starts.

**Comment by twaik** [comment]
Fixed by aa9d5384079b3c359d0a5e613bd0903be67bf858
