### ISSUE TITLE
[feature request] Ability to zoom in & out...

### ISSUE THREAD

**Issue by bushnest** [termux/termux-x11#669]
### Problem description

I am not able to zoom in and out on the screen of Termux-X11.  I tried fiddling with the settings to enable the ability to do that, but am still unable to do that.  Is that ability currently non-existent or is there something that I'm doing wrong?  Thx.

### What steps will reproduce the bug?

n/a

### What is the expected behavior?

The ability to pinch zoom the screen in and out.

**Comment by knyipab** [comment]
Alt + Scroll?

**Comment by twaik** [comment]
Duplicate of #597
