### ISSUE TITLE
How to right click when selecting "Direct touch"?

### ISSUE THREAD

**Issue by amir-hz** [termux/termux-x11#670]
In preferences, in the pointer section, there is **Touchscreen input mode** which in the third option is **Direct Touch**, how do I use right click?
I've tried holding the tap and also double tapping but nothing happens

**Comment by knyipab** [comment]
I share the view with you, but this is probably what Direct Touch is intended to send touch events. The support to touch events on the side of Linux applications, but generally they are designed for desktop and don't handle touch events well. The most seamless touchscreen Linux experience would probably be something like Ubuntu Touch and Plasma Mobile but I doubt if they exist. 

For Linux desktop apps, it's probably great to have another mode called "Modified Direct Touch" which can implement something like "double tap within 1 sec" as double click, and "holding tap for 2sec triggers vibration and release within the next 1 sec" as right click. But that's really subject to twaik's view and time.

**Comment by amir-hz** [comment]
There is a **Simulated touchscreen** option, but right-clicking using two fingers is a bit difficult in narrow spaces, sometimes it goes out of place. In addition, scrolling must use 2 fingers

**Comment by twaik** [comment]
In "Direct touch" mode touch events are delivered as is, all responsibility for handling touch events lies with the applications.

About simulated touchscreen mode and right clicks. Click will be performed in the point of first touch, it does not matter where second touch was performed.
