### ISSUE TITLE
[Bug]: ANDROID 14: X11 Picture Stuck and no any response.

### ISSUE THREAD

**Issue by xiaoyangnoob** [termux/termux-x11#672]
### Problem description

Dear development, Please see the title.

### What steps will reproduce the bug?

Run glmark2

**Comment by twaik** [comment]
That happens because termux app is going to background. It is not possible to fix this on termux-x11 side.
https://github.com/termux/termux-app/issues/3903

**Comment by xiaoyangnoob** [comment]
Okay. Thanks for you response. I'll check about Termux side.

**Comment by twaik** [comment]
@ewt45 @xiaoyangnoob @EdupugantiAkhil @JanuszChmiel @jamesgarry1
it seems like I managed to write some code to fix it, but I need some testing. Can you please help with this?
[app-arm64-v8a-debug.zip](https://github.com/user-attachments/files/18344233/app-arm64-v8a-debug.zip)

**Comment by ewt45** [comment]
unfortunately the problem still appears. and switch to background then foreground or swipe down the notification bar doesn't resume it, it still freeze and an ANR warning popup after a few seconds. sometimes when switching back to foreground the frame is black.
it only resumes after termux app is foreground again.

**Comment by ewt45** [comment]
i only have one huawei tablet, but you can use it if there is a way to connect to it remotely. lets talk it on discord(i;m hardray)

**Comment by RalfWerner** [comment]
@twaik - to your question in [discord](https://discord.com/channels/641256914684084234/955349025102630932/1326293959374405773) (Huawei Y7). I checked it for a whole day with:
**1.03.02-1f23789-08.01.25**. The stalled message (in the middle of the shot) came up 3 times, which could be resolved by connecting the **power cable** or logging in via **ssh**. This version is much more stable than the old one (Nov.24). The one [above](https://github.com/termux/termux-x11/issues/672#issuecomment-2577039622) didn't work for me. However, I hardly use the device anymore (only 16GB) and there are no problems on my other devices, apart from the known ones.
![image](https://github.com/user-attachments/assets/71f6083a-0e98-456b-b39a-9958b54c8d5e)

The trackpad mouse can no longer be moved (on the left), especially with two extra key rows. The fluxbox taskbar is only visible, without extra keys (right shot). Both [*_HELPER](https://github.com/termux/termux-x11/issues/678#issuecomment-2504547290) keys could be used for repositioning (new feature: always visible/movable).
Below is **Termux** _and_ **X11** in the _split screen_ where all the keys _should_ actually look the same (outlined in green).

**Comment by EdupugantiAkhil** [comment]
@twaik can you also share a 32 bit build for me to test

**Comment by jamesgarry1** [comment]
> @ewt45 @xiaoyangnoob @EdupugantiAkhil @JanuszChmiel @jamesgarry1
> 
> it seems like I managed to write some code to fix it, but I need some testing. Can you please help with this?
> 
> [app-arm64-v8a-debug.zip](https://github.com/user-attachments/files/18344233/app-arm64-v8a-debug.zip)
> 
> 

Checks out, works for me.

**Comment by twaik** [comment]
@EdupugantiAkhil You can check this one.
@jamesgarry1 so this artifacts works fine and the latest release hangs, right?

[app.zip](https://github.com/user-attachments/files/18407420/app.zip)

**Comment by EdupugantiAkhil** [comment]
Thank you, @twaik I tested the previous nightly release and I can confirm it works for me

**Comment by jamesgarry1** [comment]
> @EdupugantiAkhil You can check this one.
> 
> @jamesgarry1 so this artifacts works fine and the latest release hangs, right?
> 
> 
> 
> [app.zip](https://github.com/user-attachments/files/18407420/app.zip)
> 
> 

Could be.

**Comment by idkwhobutim** [comment]
@twaik these two didn't work on my phone, im on techno spark go 1(techno kl4, specifically) and can you please dm me on discord? you can remotely control my phone if you want, or tell me what to do so we can try to find a fix for this problem

my discord is **retro_2077**
