### ISSUE TITLE
[Feature request]: Make screen scrollable while using on screen keyboard

### ISSUE THREAD

**Issue by DuilioPerez** [termux/termux-x11#673]
Excuse me to submit this request in this format, but I don't know where to post it. I would like to scroll screen while using on-screen keyboard. This could be usefull while using some applications that request text input, like terminals, text processors and browsers. I usually hide the keyboard to see if I'm typing right, but in this way, the only thing necessary could be scroll the screen

**Comment by twaik** [comment]
Currently screen panning is not going to be implemented. In the case if you want to see the top part of screen you can disable "Reseed screen while soft keyboard is open" option in preferences.

**Comment by twaik** [comment]
Fixed by 209f021b0acf62ba42d09cdd1f08092094ccf756.
