### ISSUE TITLE
[Bug]: yesterday I was open it.Today it shows this 

### ISSUE THREAD

**Issue by Kut5678** [termux/termux-x11#677]
### Problem description

Check these pictures 

### What steps will reproduce the bug?

Pic
![Screenshot_20240719-092151](https://github.com/user-attachments/assets/b6ce8234-4b32-486a-8ae3-0b1b33a504d7)
![Screenshot_20240719-092141](https://github.com/user-attachments/assets/a0964a54-3151-4f5d-9b19-b36ce3a67fc7)

### What is the expected behavior?

Did not working

**Comment by TomJo2000** [comment]
You didn't start the X server in Termux, there is nothing for Termux:X11 to connect to.
