### ISSUE TITLE
How to connect it remotely.

### ISSUE THREAD

**Issue by ImranSangle** [termux/termux-x11#681]
I want to ask, how to connect remotely to the termux-x11. Like if i have termux-x11 running on one device and  termux app on another, i want my termux app's applications to display on another device's termux-x11 screen remotely, how to do that ? Thank you.

**Comment by twaik** [comment]
You can try to start `termux-x11 :0 -listen tcp -ac` and start your app as `DISPLAY=<phone's ip>:0 pcmanfm` on your other device, but it is not worth it. Termux:X11 is not designed for remote connections, it is optimised only for local use. VNC will give much better results.

**Comment by ImranSangle** [comment]
Thank you for your kind information.

**Comment by ImranSangle** [comment]
I have a biggest confusion about the x11 (normal x11 that a Linux pc has), it would be great if you help me clearing that. I want to ask that if x11 works in a client and server manner, who actually do all the rendering thing using the machine's hardware ( like GPU or CPU), is the client that renders the graphics and send the pixel data to the Xserver or it just sends the instructions to the server and the Xserver renders it using the hardware (in local or remote connection) ?

**Comment by ImranSangle** [comment]
I have a biggest confusion about the x11 (normal x11 that a Linux pc has), it would be great if you help me clearing that. I want to ask that if x11 works in a client and server manner, who actually do all the rendering thing using the machine's hardware ( like GPU or CPU), is the client that renders the graphics and send the pixel data to the Xserver or it just sends the instructions to the server and the Xserver renders it using the hardware (in local or remote connection) ?

**Comment by ImranSangle** [comment]
Well thanks again ! My confusion is now cleared. Termux and Termux-x11 is a great app.

**Comment by foryoung2018** [comment]
Pls why I run glxgears cpu usage at 80% when I start dri3 and only 1% on ubuntu, termux-x11 uses software or hardware rendering, or do i need to implement the open_client/open function in dri3 separately
