### ISSUE TITLE
[Feat]: Support send back button to X server from mouse

### ISSUE THREAD

**Issue by EatHatsuneShallots** [termux/termux-x11#685]
Some mouse supports mouse button, these buttons can send the `KEYCODE_BACK` and `KEYCODE_FORWARD` key codes.

NOTE: On some Android devices, the right mouse and middle mouse button (HarmoryOS) used as back button.

**Comment by twaik** [comment]
Not going to be implemented.
There are a lot of devices which send KEYCODE_BACK with SOURCE_MOUSE when you invoke right mouse button instead of sending MotionEvent.ACTION_{UP,DOWN} event with MotionEvent.BUTTON_SECONDARY in details. This change will break mouse behaviour on these devices.

**Comment by EatHatsuneShallots** [comment]
> There are a lot of devices which send KEYCODE_BACK with SOURCE_MOUSE when you invoke right mouse button instead of sending MotionEvent.ACTION_{UP,DOWN} event with MotionEvent.BUTTON_SECONDARY in details. This change will break mouse behaviour on these devices.

However, some devices works right, so this feature should be add to the "Other -> Response to user actions -> Back button" preferences instead of changing the default behavior.
