### ISSUE TITLE
[Bug]: The back button is used as the right button if key source is mouse

### ISSUE THREAD

**Issue by EatHatsuneShallots** [termux/termux-x11#686]
### Problem description

The back button is used as the right button if key source is mouse

**NOTE**: Right and middle mouse buttons on my device works right

### What steps will reproduce the bug?

Send a back event from a mouse

### What is the expected behavior?

Back event is sent to X server

**Comment by twaik** [comment]
No need to post that more than once. 
Duplicate of #685
