### ISSUE TITLE
extra key config problems

### ISSUE THREAD

**Issue by drugdf29** [termux/termux-x11#687]
Hello everyone, I want to add a key combination in termux-x11: alt + enter. After read the documentation on the https://wiki.termux.com/wiki/Touch_Keyboard#Extra_Keys_Row, I  adds {macro: 'ALT ENTER', display: 'key'} in the extra keys config. However, when I tested it, the output seemed to be alt+shift+up enter. Does anyone know what the problem is?

**Comment by RalfWerner** [comment]
A similar question was asked in [Discord](https://discord.com/channels/641256914684084234/955349025102630932/1272650920345468989). I can understand the behavior, replied and asked what **expectation** is connected to the macro.

**Comment by twaik** [comment]
@agnostic-apollo can you please help with this? As far as I understand termux-x11 tries to send "ALT ENTER" as text and X server fails to understand this.

**Comment by twaik** [comment]
Looks like I removed this code when I was porting extra keys implementation.
https://github.com/termux/termux-app/blob/fb01127ff2c95f6fa5f86a77956ca2d68afad9a9/termux-shared/src/main/java/com/termux/shared/termux/terminal/io/TerminalExtraKeys.java#L27-L52

**Comment by twaik** [comment]
Oh, it was not removed, but it was broken.

**Comment by agnostic-apollo** [comment]
So I don't need to look?

**Comment by twaik** [comment]
I still need suggestions how to reset locked keys in the case if I need it.

**Comment by twaik** [comment]
I mean I need, let's say, reset CTRL key in the case if macro with CTRL was sent, because I am sending `CTRL_DOWN, a, CTRL_UP`.

**Comment by twaik** [comment]
Fixed by dc939a2c2e25c0b7f95957ddd2835792510be1ec.

**Comment by agnostic-apollo** [comment]
Didn't I tell you about that sometime.

**Comment by twaik** [comment]
I do not remember it.

**Comment by twaik** [comment]
Oh, now I remembered. It is `mExtraKeysView.readSpecialButton`.
