### ISSUE TITLE
Nix-on-droid support

### ISSUE THREAD

**Issue by mesflit** [termux/termux-x11#688]
Termux-x11 https://github.com/nix-community/nix-on-droid support.
I think it will be very good

**Comment by twaik** [comment]
Termux:X11 is not heavily tied up to Termux ecosystem. 
You can adapt one of three options: chroot or proot setups (explained in readme) or how [termux-x11-nightly](https://github.com/termux/termux-packages/blob/master/x11-packages/termux-x11-nightly/build.sh) package is designed.
I am not part of nix-on-droid project and never used it. But you can try to implement it on your own.

**Comment by TomJo2000** [comment]
`nix-on-droid` is a 3rd party project and we are not involved in its development.
If it works with T:X-11, great.
If it doesn't but you want it to, take it up with the `nix-on-droid` development team.
