### ISSUE TITLE
[Feature Request]: Add an option to allow floating window display above the termux-x11

### ISSUE THREAD

**Issue by Morlinnn** [termux/termux-x11#694]
### Problem description

Is it possible to add an option to allow other application's floating window(draw over other apps) displays above termux-x11 app. 

When termux-x11 shows desktop environment, other application's PiP can be successfully displayed above it, but floating window not.

### What steps will reproduce the bug?

It's not a bug.

All floating windows are hidden when entering termux-x11.

**Comment by RalfWerner** [comment]
There are different ways to create floating windows. If your device has **PopView** option, there are no limits both **Termux** and **X11** can be placed in their own windows or one of the side apps.
There is **float** for Termux, which works as a plugin to Termux on _all_ devices. I took a picture of my SM-P610, where
1: **Chrome** app with this Issue in **PopView**, 2 **X11** (Fullscreen), 3: **Float** and 4: **Termux** can be seen in **PopView**.

![image](https://github.com/user-attachments/assets/fe09e216-2a70-4bb3-816d-c568cb5c2eec)
Keyboard is unique for all apps, but EK-KB is different and **PopView** is adapted to the KB _toggle_ but is not included in **Float** plugin.

**Comment by twaik** [comment]
Termux:X11 does not hide any floating windows and does not block them. Seems to be your device's quirk.
