### ISSUE TITLE
FreePascal + Lazarus It almost works but fails to start..

### ISSUE THREAD

**Issue by PTz0uAH** [termux/termux-x11#695]
Hoi Termux devs/fans..

I was very happy I got FreePascal 3.3.1 from trunk working and wanted also to build Lazarus for Termux-X11..

Hence I needed to adapt the FPC/LAZ source code for Termux usage and finally completed the Lazarus X11 GTK2 build..

As I am very eager to get Lazarus to work on XFCE4 It seems I missed something and got stuck testing it..

Any help is welcome to get it working without proot/croot so, when it all works out, we might have a distributable deb for de community.. 

with kind regards.. Peter

![Screenshot_20240810-113531](https://github.com/user-attachments/assets/a9261049-9b17-42ad-a9bd-dcebe9051796)
![Screenshot_20240810-121812](https://github.com/user-attachments/assets/6cb63046-a9d2-499e-a017-aae94071ea81)

**Comment by twaik** [comment]
Not related to X server functionality.

**Comment by PTz0uAH** [comment]
@twaik as I am new to Termux could you please give a direction where to post this question?

**Comment by twaik** [comment]
1. Update your environment with `pkg up`.
2. https://github.com/termux/termux-packages
