### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by spz2020** [termux/termux-x11#70]
## Transcript

```
Welcome to Termux!

Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on libera.chat

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

~ $ cat tx11
#!/data/data/com.termux/files/usr/bin/bash
export XDG_RUNTIME_DIR=${TMPDIR}
termux-x11 :1 >/dev/null &
env DISPLAY=:1 xfce4-session
~ $ export XDG_RUNTIME_DIR=${TMPDIR}
~ $ termux-x11 :1 >/dev/null &
[1] 30213
~ $ java.lang.UnsatisfiedLinkError: No implementation found for void com.termux.x11.starter.Starter.checkXdgRuntimeDir() (tried Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir and Java_com_termux_x11_starter_Starter_checkXdgRuntimeDir__)
        at com.termux.x11.starter.Starter.checkXdgRuntimeDir(Native Method)
        at com.termux.x11.starter.Starter.onRun(Starter.java:84)
        at com.termux.x11.starter.Starter.lambda$main$0(Starter.java:61)
        at com.termux.x11.starter.Starter$$ExternalSyntheticLambda1.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:776)

~ $ env DISPLAY=:1 xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
~ $ env DISPLAY=:1 xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
~ $ export DISPLAY=:1
~ $ env DISPLAY=:1 xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
~ $ xfce4-session
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
~ $
```
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUGGABLE_BUILD**: `true`  
**APK_RELEASE**: `Github`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `B6DA01480EEFD5FBF2CD3771B8D1021EC791304BDD6C4BF41D3FAABAD48EE5E1`  
##

### Software

**OS_VERSION**: `3.18.31-g07dc527`  
**SDK_INT**: `24`  
**RELEASE**: `7.0`  
**ID**: `HONORDLI-AL10`  
**DISPLAY**: `Delhi-AL10C00B180`  
**INCREMENTAL**: `C00B180`  
**SECURITY_PATCH**: `2018-10-01`  
**IS_DEBUGGABLE**: `0`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `HUAWEI`  
**BRAND**: `HONOR`  
**MODEL**: `DLI-AL10`  
**PRODUCT**: `DLI-AL10`  
**BOARD**: `DLI-AL10`  
**HARDWARE**: `qcom`  
**DEVICE**: `HWDLI-Q`  
**SUPPORTED_ABIS**: `armeabi-v7a, armeabi`  
##

#### sources.list
`deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main`
#### x11-repo (sources.list.d/x11.list)
`deb https://mirrors.ustc.edu.cn/termux/apt/termux-x11 x11 main`  
##

### Updatable Packages

All packages up to date
##

##

## Termux Files Info

**TERMUX_REQUIRED_FILES_DIR_PATH ($PREFIX)**: `/data/data/com.termux/files`  
**ANDROID_ASSIGNED_FILES_DIR_PATH**: `/data/user/0/com.termux/files`  

```
$ echo 'ls info:'
/system/bin/ls -lhdZ '/data/data' '/data/user/0' '/data/data/com.termux' '/data/user/0/com.termux' '/data/data/com.termux/files' '/data/user/0/com.termux/files' '/data/user/0/com.termux/files' '/data/user/com.termux/files' '/data/data/com.termux/files/usr-staging' '/data/data/com.termux/files/usr' '/data/data/com.termux/files/home' '/data/data/com.termux/files/usr/bin/login' 2>&1
echo; echo 'mount info:'
/system/bin/grep -E '( /data )|( /data/data )|( /data/user/[0-9]+ )' /proc/self/mountinfo 2>&1 | /system/bin/grep -v '/data_mirror' 2>&1

ls info:
ls: /data/user/com.termux/files: No such file or directory
ls: /data/data/com.termux/files/usr-staging: No such file or directory
drwxrwx--x 210 system  system  u:object_r:system_data_file:s0         20K 2021-12-15 22:10 /data/data
drwx------   5 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-16 08:08 /data/data/com.termux
drwx------   5 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-15 18:49 /data/data/com.termux/files
drwx------   3 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-16 10:51 /data/data/com.termux/files/home
drwx------  12 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-16 10:43 /data/data/com.termux/files/usr
-rwx------   1 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 1.4K 2021-12-16 02:21 /data/data/com.termux/files/usr/bin/login
lrwxrwxrwx   1 root    root    u:object_r:system_data_file:s0          10 1970-01-14 12:58 /data/user/0 -> /data/data
drwx------   5 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-16 08:08 /data/user/0/com.termux
drwx------   5 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-15 18:49 /data/user/0/com.termux/files
drwx------   5 u0_a214 u0_a214 u:object_r:app_data_file:s0:c512,c768 4.0K 2021-12-15 18:49 /data/user/0/com.termux/files

mount info:
825 798 259:30 / /data rw,nosuid,nodev,noatime master:25 - f2fs /dev/block/bootdevice/by-name/userdata rw,seclabel,background_gc=on,discard,user_xattr,inline_xattr,acl,inline_data,extent_cache,active_logs=6

```
##

## Logcat Dump

```
$ /system/bin/logcat -d -t 3000 2>&1

```
##

**Comment by WMCB-Tech** [comment]
Try running those commands individually to see what's really happening. check `htop` see if there's really an `Xwayland` process

**Comment by ZhymabekRoman** [comment]
Try to update termux-x11 application and all Termux packages.

**Comment by waldhef** [comment]
Hello @spz2020
I have the same problem. Here is my bug report: https://github.com/termux/termux-x11/issues/56
As I described in my post this bug happens with all builds with "run without sharedUserId".
You can try to run a slightly older version e.g. build #99, commit db575f7 works fine for me.
Be aware, there is no companion deb file in the package of build #99, you have to install it first from repo, with:
`pkg install termux-x11`

Hope this helps until this bug is fixed.

**Comment by suhan-paradkar** [comment]
Looks like the java code can't find native implementation...

**Comment by StevenAlexander44** [comment]
Are you trying to just have a simple xfce session?

**Comment by spz2020** [comment]
,,,
commit db575f7 works fine for me.
,,,
how download？

**Comment by spz2020** [comment]
em .. it can't download 
![Screenshot_2022-01-07-19-19-14](https://user-images.githubusercontent.com/74664513/148536780-926158b1-e5a1-40ba-8989-340ce3c87228.jpg)

**Comment by waldhef** [comment]
Try 1.0 basic version. @RalfWerner provided an download link in this thread: https://github.com/termux/termux-x11/issues/54
Be sure to use termux from github.

**Comment by twaik** [comment]
Duplicate https://github.com/termux/termux-x11/issues/56.
