### ISSUE TITLE
[Bug]: why I only can start xserver with "-listen tcp"?

### ISSUE THREAD

**Issue by foryoung2018** [termux/termux-x11#701]
### Problem description

I tried don't with that, then can't connect to xserver, and also, "ss -x"  can't find this unix domain socket.

### What steps will reproduce the bug?

termux-x11 :1 & with or without "-listen tcp"

**Comment by twaik** [comment]
Why exactly you think it does not work without `-listen tcp`

**Comment by twaik** [comment]
Unix socket is located under `$TMPDIR/.X11-unix`.

**Comment by foryoung2018** [comment]
I change display to 1000, but can't connect to X11. Only works with "-listen tcp".  I confirm that unix path, it's right there.

export DISPLAY=:1000
xterm

xrdb: Connection refused
xrdb: Can't open display ':1000'
xterm: Xt error: Can't open display: :1000

**Comment by twaik** [comment]
Why do you need display 1000? Use something within the range 0 - 63.

**Comment by foryoung2018** [comment]
And then,  I confuse what is this  dbus socket file used to?

:/data/data/com.termux/files/usr/tmp # ls -la
total 16
drwx------  3 u0_a169 u0_a169 4096 2024-08-15 14:13 .
drwx------ 11 u0_a169 u0_a169 4096 2024-08-15 11:03 ..
-r--r--r--  1 u0_a169 u0_a169   11 2024-08-15 14:12 .X0-lock
drwxrwxrwt  2 u0_a169 u0_a169 4096 2024-08-15 14:12 .X11-unix
srwxrwxrwx  1 u0_a169 u0_a169    0 2024-08-15 14:13 dbus-OdKV3UXIwo

**Comment by twaik** [comment]
It is not related to X server.
