### ISSUE TITLE
[Bug]: termux-x11 Segmentation fault after rotating the screen

### ISSUE THREAD

**Issue by yu-zify** [termux/termux-x11#702]
### Problem description

When playing supertuxkart, rotate the screen in the game, and then exit the game, termux-x11 Segmentation fault.

[termux-x11-debug.txt](https://github.com/user-attachments/files/16639419/termux-x11-debug.txt)

I also tried the previous build action and found [https://github.com/termux/termux-x11/actions/runs/9270059674](url) is starting to have problems.
Before [https://github.com/termux/termux-x11/actions/runs/9266628752](url) has no problems.

### What steps will reproduce the bug?

1. install supertuxkart and xfvm4 in termux
2. run termux-x11,xfvm4 and supertuxkart
3. turn on full screen in supertuxkart 
4. rotate the screen and click exit button

https://github.com/user-attachments/assets/d3c7837f-43d9-470f-9e05-bd21e6ae4182

### What is the expected behavior?

termux-x11 still work after exit game

**Comment by twaik** [comment]
Does it happen with turnip?

**Comment by twaik** [comment]
Can you reproduce it on the latest version?

**Comment by twaik** [comment]
Also I did not find supertuxkart for termux, only for proot-distro.

**Comment by yu-zify** [comment]
It may not be related to any GPU drivers because it is the same with llvmpipe.
The latest version also has segmentation faults.
 Supertuxkart is in tur-repo, it can also be tested by running supertuxkart in proot-distro.
