### ISSUE TITLE
Need to install on Nougat - ZE551ML

### ISSUE THREAD

**Issue by anonimo82** [termux/termux-x11#703]
Hello everyone. 
As in title, I need to install on an Asus ZenFone 2.
Unfortunately, I get errors, which I guess are related to my available Android version. 
(error during package analysis)

Is it there anywhere an old build to install for this situation?
Or could I build it myself?

Thanks in advance for any help.

Regards, have a nice day.

**Comment by anonimo82** [comment]
Nevermind, excuse me.
I made it to flash an Oreo ROM by the way.

Thanks anyhow

**Comment by twaik** [comment]
Minimal supported Android version is 8.0.

**Comment by twaik** [comment]
Fixed by 44b08a3a9fd0d60a8d0f53afedd73c7c7a025c68.
