### ISSUE TITLE
[Bug]: Gboard 14.4.07+ will jam the SHIFT key when using Chinese IME and physical keyboard

### ISSUE THREAD

**Issue by knyipab** [termux/termux-x11#707]
### Problem description

SHIFT key can be stuck in the newer version of Gboard. 

### What steps will reproduce the bug?

No matter whether "Workaround to enable CJK Gboard" is turned on or not, when using Gboard 14.4.07+ with a physical keyboard and having both Chinese and English IME in languages settings, pressing SHIFT key will make the SHIFT key stuck in Termux:X11, causing trouble using any UI thereafter. It couldn't release the stuck SHIFT unless killing the whole `termux-x11` session. This causes huge trouble to Termux:X11 phsyical keyboard users who have Gboard Chinese and English IME, regardless of the config of "Workaround to enable CJK Gboard".

**Comment by knyipab** [comment]
It's more of Gboard issue and seems to be fixed with Gboard 14.6.03+. I hope they won't introduce that features again. 

For those who use version between Gboard 14.4.07 ~ 14.6.03, the workaround for physical keyboard sticky SHIFT in Chinese IME will be: to press `SHIFT+left arrow` and `SHIFT+8` (i.e. asterisk), which should quit the sticky SHIFT temporarily.

**Comment by TingyiChen** [comment]
On latest termux-x11 and gboard(14.7.04), with "Workaround to enable CJK Gboard" on and Chinese IME enabled, pressing backspace will make this key stuck. Did anyone meet this issue before? If I remove Chinese IME from gboard, then this issue is gone.

**Comment by TingyiChen** [comment]
No. Using OnePlus Pad Pro here.
