### ISSUE TITLE
move to discussions: automatic window placement xywh 0,0,100%,50% in .Xdefaults or somewhere else?

### ISSUE THREAD

**Issue by john-peterson** [termux/termux-x11#714]
# enable discussions section in project settings 

I would rather have this in discussions to get away from the issues section

it's a simple change in the project settings much appreciated 

https://github.com/termux/termux-x11/discussions/new

# now to my issue 

this  doesn't work 

~~~
~/.Xdefaults
*geometry: 100%x50%+0+0
~~~

i found no way to automate this for all windows 

~~~
whnd=$(xdotool getwindowfocus);xdotool windowmove $whnd 0 0;xdotool windowsize $whnd 100% 50%
~~~

i use only one window at a time

**Comment by twaik** [comment]
Not a X server issue.
