### ISSUE TITLE
x11 forwarding

### ISSUE THREAD

**Issue by rodajc** [termux/termux-x11#717]
Is x11 forwarding over ssh supposed to work? I get:

`X11 forwarding request failed on channel 0`

.Xauthority had to be created manually which wasn't a good sign.

**Comment by twaik** [comment]
X11 forwarding is a feature of SSH servers. It is not related to X server itself.

**Comment by rodajc** [comment]
Your reply made me check the SSH server config. It works now after adding:

`X11Forwarding yes`

Simply beautiful. Thank you.
