### ISSUE TITLE
[ihategoogle]: Google Play store won't install the app because it thinks it's a virus

### ISSUE THREAD

**Issue by luizao-rizz** [termux/termux-x11#718]
### Problem description

Google Play store won't install app because it thinks it's a virus that steals your money

### What steps will reproduce the bug?

downloading an APK with Google Play protect enabled

### What is the expected behavior?

was expected to install the application normally

**Comment by twaik** [comment]
I do not think we can fix this. Termux:X11 uses non-SDK functions and a lot of permissions, no wonder virus scanners think it is suspicious.

**Comment by twaik** [comment]
I was wrong, Termux:X11 does not request a lot of permissions, but combination of Accessibility Service and `android.permission.INTERNET` may be suspicious. And requesting `android.permission.WRITE_SECURE_SETTINGS` is also suspicious. There is no way we can avoid detecting Termux:X11, termux itself or other plugins as potential threats.
