### ISSUE TITLE
Oversized scaling in VLC media player

### ISSUE THREAD

**Issue by NotteShock** [termux/termux-x11#72]
I'm using termux-x11 with udroid by RandomCoderOrg and the scaling is **HUGE!** when I'm using it with termux-x11 and it's obvious that it's only shown in vlc media player with termux-x11 
![Screenshot_2021-12-22-15-54-10-307_com termux x11](https://user-images.githubusercontent.com/85934291/147065516-3ca31423-6d22-4c4a-8fb1-9952f6985e38.jpg)
in vnc it looks normal
![Screenshot_2021-12-22-15-55-47-040_com realvnc viewer android](https://user-images.githubusercontent.com/85934291/147065542-1a9429cf-1cfb-4180-a73a-36b0c64fc6f8.jpg)
(sorry for my bad english though)

**Comment by WMCB-Tech** [comment]
It is expected behavior
check
https://github.com/termux/termux-x11#font-or-scaling-is-too-big
