### ISSUE TITLE
Add support for completely hiding status bar?

### ISSUE THREAD

**Issue by icejix** [termux/termux-x11#726]
Hey, trying to use a Linux desktop on my Android phone, but I've had a few issues with this app. Mainly, I think the status bar appearing when I swipe down is very annoying, and hinders my ability to manage the desktop properly. For example, after dragging a window to the top of the screen, I'd like to drag it downwards, but the status bar appears instead. Is there a setting that can be added to allow for status bar and gestures being disabled while an x session is running?

Also, maybe you'd like this in a separate issue, but for me, the backspace key on the on-screen keyboard is not working at all. Tested two different OSKs, no output in xev either.

**Comment by twaik** [comment]
Hiding status bar completely or preventing it from appearing is not supported by Android. Not going to be implemented.
