### ISSUE TITLE
[Idea]: 

### ISSUE THREAD

**Issue by Snap888** [termux/termux-x11#734]
### Problem description

can you tell me how I can launch x-11 from the activity with the permission I need? I want to use the sample code (am start --user 0 -n com.termux.x11/.MainActivity --es resolution "$res &>/dev/null )
where res=800x600 (or other value )

### What steps will reproduce the bug?

am start --user 0 -n com.termux.x11/.MainActivity --es resolution $res &>/dev/null

**Comment by twaik** [comment]
Use `termux-x11-preference`.

**Comment by Snap888** [comment]
> Использовать `termux-x11-preference`.

Can you explain how I can use this in the terminal?

**Comment by twaik** [comment]
First of all run `termux-x11-preference list` to get the list of available keys, then `termux-x11-preference "<key>:<value>".
