### ISSUE TITLE
[Bug]: proot cant start termux-x11 

### ISSUE THREAD

**Issue by Fmert24** [termux/termux-x11#738]
### Problem description

proot giving error and dosnt start termux-x11

### What steps will reproduce the bug?

crate and login proot distro
try to start termux-x11

### What is the expected behavior?

termux -x11 to start
but proot distro gives this error
proot error:
 '/system/bin/app_process64' is a 64-bit program whereas this version of proot handles 32-bit programs only

**Comment by twaik** [comment]
Not a termux-x11 problem.
