### ISSUE TITLE
[Bug]: glxgears run on termux-x11  80% 1cpu

### ISSUE THREAD

**Issue by foryoung2018** [termux/termux-x11#739]
### Problem description

Pls why I run glxgears cpu usage at 80% when I start dri3 and only 1% on ubuntu, termux-x11 uses software or hardware rendering, or do i need to implement the open_client/open function in dri3 separately

### What steps will reproduce the bug?

termux-x11 :0 
glxgears

**Comment by foryoung2018** [comment]
what about this log mean?
DRI3: Modifier is not RAW_MMAPPABLE_FD or AHARDWAREBUFFER_SOCKET_FD

**Comment by twaik** [comment]
That means your mesa implementation is not designed to work with termux-x11.

**Comment by foryoung2018** [comment]
and how about these two CARD64 used to?

`static PixmapPtr loriePixmapFromFds(ScreenPtr screen, CARD8 num_fds, const int *fds, CARD16 width, CARD16 height,
                                    const CARD32 *strides, const CARD32 *offsets, CARD8 depth, __unused CARD8 bpp, CARD64 modifier) {
    const CARD64 AHARDWAREBUFFER_SOCKET_FD = 1255;
    const CARD64 RAW_MMAPPABLE_FD = 1274;`

**Comment by twaik** [comment]
> const CARD64 RAW_MMAPPABLE_FD = 1274;

https://github.com/termux/termux-packages/blob/master/packages/mesa-vulkan-icd-freedreno-dri3/wsi-termux-x11.patch



> const CARD64 AHARDWAREBUFFER_SOCKET_FD = 1255;

That one was used in early versions of xmem's wsi vulkan layer. It reads AHardwareBuffer from socketpair after you send it with `AHardwareBuffer_sendHandleToUnixSocket`

**Comment by foryoung2018** [comment]
@twaik I want to make a fully support dri3 version on termux-x11, what should I do?
Many thanks for your help.
