### ISSUE TITLE
Missing termux-startx11 executable 

### ISSUE THREAD

**Issue by Snothy** [termux/termux-x11#74]
Running latest versions of Termux and Termux X11. Initially I get an 'allow-external-apps' error. Once I fix that by setting the property to true, I get an error that the executable '/data/data/com.termux/files/usr/libexec/termux-x11/termux-startx11 is missing.
I've installed the 'x11-repo & termux-x11' packages. Error code is 150.

**Comment by twaik** [comment]
`termux-x11` package in repo is out of date. Try to use the last artifact.

**Comment by CapMau** [comment]
Hello, 
Running into the same issue, i used the lastest artifact for termux-x11 and still get the same error

**Comment by twaik** [comment]
Did you install .deb package?
