### ISSUE TITLE
[question] can i set the refresh rate above 30hz?

### ISSUE THREAD

**Issue by Welpyes** [termux/termux-x11#741]
yeah i dont know how to do it? is it possible?

**Comment by twaik** [comment]
Termux:X11 gets refresh rate of screen and uses it, there is no way to override it.

**Comment by Welpyes** [comment]
> Termux:X11 gets refresh rate of screen and uses it, there is no way to override it.

i have a samsung s9+ and it doesn't seem to be the case. is this a proot-distro issue?
![Screenshot_20241029-225706_TermuxX11](https://github.com/user-attachments/assets/96e3d128-c2e4-4037-b078-6bd676dd479c)

**Comment by twaik** [comment]
That means android reports android does not report assigned display or report 30 FPS.
https://github.com/termux/termux-x11/blob/354acbd3b054d0af118b09695a2b3202987a1343/app/src/main/java/com/termux/x11/MainActivity.java#L189
That code gets FPS of system or fallbacks to 30.
