### ISSUE TITLE
[Discussion] How do you intercept Alt+F4 keypress?

### ISSUE THREAD

**Issue by elesbb** [termux/termux-x11#745]
Hello! Love the app.

I have a question tho, how do you intercept the ALT+F4 keyboard sequence when using a hardware keyboard?

When I press it in my app, it causes the activity to close. I would also like to intercept the ALT+F4 keysequence.

I have looked at your source code and can't exactly figure it out, my only guess is there is a native hook intercepting it, however I'm unsure how it works exactly. I always thought when using native code, you send stuff from java to the native code, not the other way around.

Would really love your assistance. Thanks!

**Comment by twaik** [comment]
There is an option to intercept system shortcutsbin preferences.

**Comment by elesbb** [comment]
I see. It is a Samsung dex thing not an android thing.

Thank you so very much!
