### ISSUE TITLE
[Bug]: Caps Lock key not working and slow Korean input when using "USB & Bluetooth keyboard"

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#746]
### Problem description

After installing the latest version of `Termux-x11 App` from Actions, an issue was identified where the The issue was identified where the `Caps Lock key` does not work, and Korean input is slow when using `USB & Bluetooth keyboard`.

For `Korean input (fcitx5-hangul)`, it was fine in the previous version, but with the latest version, input only appears on the screen after typing twice.

https://github.com/user-attachments/assets/3e4fb526-eced-4fb1-b29e-d90007838369

The previous version I used is as follows (version with the Tab S9 Ultra keyboard cover issue fixed):
https://github.com/user-attachments/files/16056053/app-arm64-v8a-debug.zip

### What steps will reproduce the bug?

The issue occurs when installing the latest version from Actions.

**Comment by twaik** [comment]
Can you please check slow input again? I backported some unicode handling related code from tigervnc so it should work much better.

**Comment by hansm629** [comment]
@twaik 
I'll test it out after work!

**Comment by hansm629** [comment]
@twaik
https://github.com/termux/termux-x11/actions/runs/12254284630

Tested in the latest version
`Caps Lock` key does not work
**Korean** input is delayed

**Comment by hansm629** [comment]
@twaik 
I found the cause!

When I enabled the "`Hardware keyboard scancodes workaround`" toggle switch,
the symptom occurred!

When I turned off the toggle switch, the symptom did not occur!

![Screenshot_20241211_020330_TermuxX11](https://github.com/user-attachments/assets/25014485-44da-4ed0-9213-bcdcd09e7f7a)

**Comment by hansm629** [comment]
@twaik 
For now, there will be no problem if you turn off the option and use it, so I think you can close the issue. What do you think?
