### ISSUE TITLE
termux-x11 has just been installed yet I get: Termux:X11 is not installed

### ISSUE THREAD

**Issue by fusion809** [termux/termux-x11#75]
I just installed termux-x11 on my phone and when I run termux-x11 I get the error:

```bash
Termux:X11 is not installed
```

. And I have no idea what to do, I'm guessing this is some sort of bug in this software.

**Comment by twaik** [comment]
Please, try to install both .apk and .deb from latest artifact.

**Comment by fusion809** [comment]
Works now, thanks.

**Comment by AnasSdiq** [comment]
How do I install termux-x11.deb?

**Comment by AnasSdiq** [comment]
How do I install termux-x11.deb?

**Comment by MrAdityaAlok** [comment]
@AnasSdiq From README.md

> For X applications to work, you must install Termux-x11 companion package. You can do that by doing
> ```
> pkg install termux-x11
> ```
> Or by downloading an artifact from [last successful build](https://github.com/termux/termux-x11/actions/workflows/debug_build.yml) and installing *.apk and *.deb files.

**Comment by alsakuttle** [comment]
~~why is this pinned~~

**Comment by MrAdityaAlok** [comment]
@alsakuttle Thank you for notifying me. I too do not remember why I pinned this 😄, maybe by mistake.
