### ISSUE TITLE
s-pen not recognized in proot debian xfce.

### ISSUE THREAD

**Issue by Lucalme** [termux/termux-x11#752]
I'm using proot debian with xfce on the samsung tab S7-FE, but i don't have the option to use my stylus inside termux-x11. i thought i would ask here because perhaps i am missing something? Here's the screenshots of the "device menu" (aka mouse and keyboard) and also the options i get inside of gimp.
![xfce "Mouse and keyboard"](https://github.com/user-attachments/assets/20358dbc-3306-4188-a540-20c74af0d8aa)
![gimp device picker](https://github.com/user-attachments/assets/23b4144b-e10c-4b3c-a32e-f38f1302be2b)

**Comment by twaik** [comment]
Does it work fine in termux's xfce and gimp?

**Comment by twaik** [comment]
Unfortunately I have no idea what happens in proot and how to debug it. Since it works in termux I think I should just close the issue. Sorry for inconvenience.
