### ISSUE TITLE
[Bug]: ld.lld: error: duplicate symbol: XkbKeyNameText

### ISSUE THREAD

**Issue by 17857697984** [termux/termux-x11#757]
### Problem description

ld.lld: error: duplicate symbol: XkbKeyNameText
>>> defined at xkbtext.c:389 (/Users/guobinghua/Desktop/steam-emu/termux-x11/app/src/main/cpp/libxkbfile/src/xkbtext.c:389)
>>>            xkbtext.c.o:(XkbKeyNameText) in archive libxkbcomp.a
>>> defined at xkbtext.c:367 (/Users/guobinghua/Desktop/steam-emu/termux-x11/app/src/main/cpp/xserver/xkb/xkbtext.c:367)
>>>            xkbtext.c.o:(.text.XkbKeyNameText+0x0) in archive libxserver_xkb.a

### What steps will reproduce the bug?

build use Android studio in macOS

**Comment by twaik** [comment]
The program was designed to be built on linux host. 
I never tested building on macos and probably will not fix this because I have no devices for testing it.
My suggestion is that the patch for xkbcomp was not applied.
