### ISSUE TITLE
Instructions in README fail to launch Xfce4 due to permission errors

### ISSUE THREAD

**Issue by fusion809** [termux/termux-x11#76]
I've tried launching Xfce4 using the instructions in the README, namely:

```bash
~ $ export XDG_RUNTIME_DIR=${TMPDIR}
~ $ termux-x11 :1 >/dev/null &
~ $ env DISPLAY=:1 xfce4-session
```

and the second of these lines gives a permission denied error. Any ideas how to launch Xfce4 with this?

**Comment by twaik** [comment]
Please, try without `>/dev/null` and post the log.

**Comment by fusion809** [comment]
Ah, without the /dev/null it works fine, thanks.
