### ISSUE TITLE
[Bug]/[Feature Request]: Picture in Picture mode should hide the "additional keyboard"

### ISSUE THREAD

**Issue by 96fps** [termux/termux-x11#762]
### Problem description

When you enter picture in picture mode you are not able to use the "additional keyboard" (utility that shows arrow keys/etc), but it stays on screen and takes up the majority of the reduced PiP frame.

### What steps will reproduce the bug?

Enable the additional keyboard (on by default)
Enable PiP mode under "output"
Activate PiP mode

### What is the expected behavior?

The additional keyboard overlay should auto-hide itself.

Also (optional/extra feature): Since the activation of the picture-in-picture mode triggers a resize of the virtual display, it might be useful to allow the user to pick a second resolution scaling factor for pip mode (for example, they may use 2:1 scaling when the app is full screen but it could switch to 1:1 when in PiP mode).

**Comment by twaik** [comment]
Try the latest version please.
