### ISSUE TITLE
Bring up proprietary driver on termux-x11 proot linux

### ISSUE THREAD

**Issue by mshzhb** [termux/termux-x11#763]
Hi folks,  our samsung proprietary driver's offscreen rendering is working now on termux-x11 proot linux.
However, onscreen has some issues with xcb_dri3_open_reply
Here is the error code: DRI3 related

error_code = 0x8 (BadMatch)
major_code = 0x93 (dri3 related)
minor_code = 0x1 (open)

Appreciate your help!

Thanks,
Tong

**Comment by twaik** [comment]
Not going to be implemented. 
Termux:X11 does not support and will not support DRM/KMS because Android does not have any public APIs for this.
Also https://github.com/termux/termux-packages/discussions/22451#discussioncomment-11491792.

**Comment by twaik** [comment]
There is an option to send mmappable fd the same way it is done in xMeM's turnip version.

**Comment by twaik** [comment]
I merged PR which lets us use lavapipe without `-disable-dri3` option, probably it lets you use your driver too. Can you please check it?

**Comment by mshzhb** [comment]
Hi @twaik,

Thank you so much for your help! Since I’m still new to this environment, could you kindly elaborate on the next steps? Should I update termux-x11 directly using the pkg command, or do I need to compile the repository myself?

Thanks again!
