### ISSUE TITLE
[Bug]: Unable to read preferences

### ISSUE THREAD

**Issue by jace** [termux/termux-x11#769]
### Problem description

I'm unable to read preferences using `termux-x11-preference` even when inside the X11 environment.

### What steps will reproduce the bug?

```shell
$ termux-x11-preference list
list: Unexpected result 
Broadcasting: Intent { act=com.termux.x11.CHANGE_PREFERENCE pkg=com.termux.x11 (has extras) }
Broadcast sent without waiting for result

$ termux-x11-preference
/data/data/com.termux/files/usr/bin/termux-x11-preference [list] {key:value} [{key2:value2}]...
```

### What is the expected behavior?

Preferences should be displayed.

**Comment by RalfWerner** [comment]
possibly the same problem as #758?

**Comment by jace** [comment]
I'd like a way to read current settings for backups, which doesn't seem possible at the moment. This discussion could continue in #758.

**Comment by twaik** [comment]
Fixed by https://github.com/termux/termux-x11/commit/efb2d97a46adf1657bacf395c38166a648260066 and https://github.com/termux/termux-packages/commit/26ccf3afd77831d86b2265bc0e73b63d6fba8464 .
