### ISSUE TITLE
How do you get a keyboard in termux-x11?

### ISSUE THREAD

**Issue by fusion809** [termux/termux-x11#77]
I've been running an Xfce4 session under termux-x11 but when I have a terminal open and I press my cursor in the terminal I expect a keyboard to pop up so I can type a command in. Likewise when I open up Firefox, and click the address bar I expect a keyboard to pop up, but in both cases it doesn't. Is there a way of changing this behaviour?

**Comment by fusion809** [comment]
I've found a workaround, using the onboard app, but it's not really optimized for mobile screens.

**Comment by twaik** [comment]
Try to press back button on the phone.
