### ISSUE TITLE
[Transfer]: Wayland support, without XWayland (experimental).

### ISSUE THREAD

**Issue by mexsrc** [termux/termux-x11#770]
> [!NOTE]
> This issue show you the GUIs that supported ``wayland``. But you can continue ``xwayland`` occasionally, *until Termux X11's transition into Wayland support completed as **"Termux WL"*** (**"WL"** abbreviation for **"Wayland"**, codenamed **"Westmux"** (the combination between **"Westminster"**, **"Much"**, and **"X"**)).

# Wayland needs.
## Wayland support under Termux-availabled GUI.
- [x] ``xfce4`` (aimed *due the release of ``xfce4`` 4.20*).
- [x] ``lxqt``.
- [x] ``mate`` (experimental).
- [ ] ``openbox``.
- [ ] ``fluxbox``.
- [ ] ``picom``.
- [x] ``sway``.
- [ ] ``rofi``.
- [ ] ``dmenu``.
- [ ] ``i3``.
- [ ] ``polybar``.
- [ ] ``bspwm``.
- [ ]  ``dwm``.
- [ ] ``e16``.
- [ ] ``awesome``.
- [ ] ``icewm``.
- [x] ``firefox``.
- [ ] ``fvwm``.
- [ ] ``jwm``.
- [ ] ``wmaker``.

## Wayland's GUI replacement.
``mate`` → ``cinnamon`` (non-experimental).
``openbox`` → ``waybox``.
``icewm`` → ``laikawm``.
``fluxbox`` → ``maui``.
``picom`` → ``river``.
<details>
  <summary>Picom's family replacement.</summary>
  Just kidding :).
</details>

**Comment by twaik** [comment]
1. Termux:X11's name slightly hints you it is for X11, not for Wayland.
2. It is X server. It is not directly or indirectly related to any software you can run with it.

**Comment by mexsrc** [comment]
> 1. Termux:X11's name slightly hints you it is for X11, not for Wayland.

@twaik just develop *"Termux:Wayland"*, bro.

**Comment by twaik** [comment]
Why should I?

**Comment by twaik** [comment]
It is not as simple as you think...

**Comment by mexsrc** [comment]
> Why should I?
@twaik because you're have ``sway``, as *it's not supported by Termux:X11*. I'm need those ``wayland`` WM in *Termux*.

**Comment by twaik** [comment]
I do not have it. And termux-x11 is X server, it is not directly or in directly related to any project you can or can not run with it.

**Comment by mexsrc** [comment]
> I do not have it.

*It's in your own repository*, but no one *post* them for Termux in ``r/unixporn``:
```
x11/sway 1.10-0
    i3-compatible Wayland compositor
```

**Comment by twaik** [comment]
It is in repository of organisation. Not in my own...

**Comment by Biswa96** [comment]
You can use sway inside weston in termux-x11.

**Comment by mexsrc** [comment]
> You can use sway inside Weston

@Biswa96 you're sure *you can run ``weston`` inside ``xwayland``*?.

If you're need, response [``xweston``](https://github.com/ackalker/Xweston) into them.

**Comment by Biswa96** [comment]
You will be running weston inside x server in termux-x11.

**Comment by twaik** [comment]
1. What the point of running X server (Xwayland) on top of weston inside of other X server (termux-x11).
2. Not the best place for advertising third party software.

**Comment by Eveeifyeve** [comment]
> Why should I?

I think you might want to reconsider now since a lot of distros are now starting to use wayland and it is stable enough to be able to use for example gnome is now wayland not x11 and it is being used in ubuntu which is one of the largest linux distros on the market and having this support at least officially would be nice for people who want to use wayland on termux and not x11.

**Comment by twaik** [comment]
No means no.

**Comment by JustCryen** [comment]
Last .apk release of termux-gui seems to be from 2023.  
Seems a little bit stagnated.  
It's also way less documented, what should I do to get it to work?  
Newest apk also refuses to install for me.
