### ISSUE TITLE
[Bug]: Xlorie log spam when cursor is at loading 

### ISSUE THREAD

**Issue by 813ethan** [termux/termux-x11#772]
### Problem description

Xlorie seems to be spamming logs when cursor is at loading status

https://github.com/user-attachments/assets/3e5754c8-33cb-48ef-ad28-c1e56d55b71b

### What steps will reproduce the bug?

make the mouse cursor at load in xfce4
check `logcat`

### What is the expected behavior?

Xlorie should not be spamming logs

**Comment by twaik** [comment]
I can not reproduce it on my devices. But probably it will be fixed after moving renderer out of X server process.

**Comment by 813ethan** [comment]
alright then
