### ISSUE TITLE
[Bug]: Samsung OneUI7(Android 15) Dex Mode Alt+Tab work issue

### ISSUE THREAD

**Issue by hansm629** [termux/termux-x11#773]
### Problem description

Samsung recently started `OneUI7 (Android 15)` beta on the `S24 series`.

When I try using Termux-X11 in Dex mode,
when I press `Alt+Tab` via an external keyboard (USB or Bluetooth),

the window switches within `Android`, not within the `X11 server`.

Do need an update to support `OneUI7 (Android 15)`?

### What steps will reproduce the bug?

https://github.com/user-attachments/assets/3ad8117e-9c06-4837-b143-3ebfc04c3edf

**Comment by twaik** [comment]
Did you enable "Intercept system shortcuts" for Dex?

**Comment by hansm629** [comment]
@twaik 
![Screenshot_20241224_001146_TermuxX11](https://github.com/user-attachments/assets/b0742133-d3d8-43fa-aec0-9a98ec7fa0d1)

Yes is enable
But not work 😢

**Comment by twaik** [comment]
Seems like it is a firmware bug.
Probably you should report to Samsung that `com.samsung.android.view.SemWindowManager.requestMetaKeyEvent` no longer works in new firmware update. 
I am closing this since I am not able to bypass or fix this.

**Comment by hansm629** [comment]
@twaik 
I'll report the issue to Samsung. Should I just say "`com.samsung.android.view.SemWindowManager.requestMetaKeyEvent`" doesn't work?

**Comment by twaik** [comment]
Probably.
