### ISSUE TITLE
[Bug]: mate-session trapped without debugging error.

### ISSUE THREAD

**Issue by mexsrc** [termux/termux-x11#775]
### Problem description

> [!NOTE]
> This HTML code *is resulted in the description of this post*, because this is option *to create Github variant of those Discord post*.

---

<!DOCTYPE html>
<html>
<body>
<div align="left" style="display: block; white-space: pre-wrap;">

When i execute <code>mate-session</code>, it doesn't debugging it's error, <em>but print this message</em> in <code>aterm</code> (without <code>alias</code>):

<code>Trap</code>

If you're tell me decompiler that support Termux, <em>i investigate into <code>mate-session</code> in this folder</em>:
<code>/data/data/com.termux/files/usr/bin</code>

</div>

### What steps will reproduce the bug?

<!DOCTYPE html>
<html>
<body>
<div align="left" style="display: block; white-space: pre-wrap;">

1. Install <code>mate</code> by executing this command:

<code>pacman -Syy $(pacman -Ssq mate | grep -F "mate" | tail -n +2) marco --noconfirm</code>
2. Execute this command:
<code>dbus-launch --exit-with-session mate-session</code>

</div>
</body>
</html>

**Comment by twaik** [comment]
Not related to X server.

**Comment by mexsrc** [comment]
<blockquote>
Not related to X server.
</blockquote>

@twaik why, this post mean I have black screen, bro.
![Screenshot_2024-12-29-13-29-08-72_00df01c412509efb9bd6450c382822af](https://github.com/user-attachments/assets/88cca7c1-ce07-41bc-939c-3177e920a30d)

**Comment by twaik** [comment]
It is related to termux package, not to X server. Please, file an issue in appropriate repo.
