### ISSUE TITLE
Why is the release page always empty?

### ISSUE THREAD

**Issue by Nikitf777** [termux/termux-x11#777]
Where can I find an apk file for installing it? There's nothing every time I open the repo. If it is intended, please explain it in `README.MD`, because I'm so confused. Or/and add guide for building from source, so I can build it myself.

![Screenshot_20241231-015341_GitHub.png](https://github.com/user-attachments/assets/56cdf645-f2e9-44a4-9dd1-edc49a459b9a)

**Comment by ask9027** [comment]
https://github.com/termux/termux-x11/releases/

release page

**Comment by Nikitf777** [comment]
> https://github.com/termux/termux-x11/releases/
> 
> release page

I checked several times yesterday and every time it was empty

**Comment by ask9027** [comment]
> > https://github.com/termux/termux-x11/releases/
> > release page
> 
> I checked several times yesterday and every time it was empty

open in browser

**Comment by Nikitf777** [comment]
> open in browser

I tried in the browser too but there was nothing. However, now I can see it in both the GitHub app and in the browser.

**Comment by twaik** [comment]
Probably for some reason you seen draft release created by mistake. I removed it a while ago.
