### ISSUE TITLE
glxgears on mesa-turnip-kgsl termux-x11

### ISSUE THREAD

**Issue by wormstest** [termux/termux-x11#79]
Hello, i compiled mesa-turnip-kgsl on Debian 11 proot. Termux-x11 is start xfce4 without OpenGL. glxgears not work. Print: segerror.

**Comment by twaik** [comment]
Termux::X11 does not support OpenGL.

**Comment by wormstest** [comment]
I compiled zink on termux, llvmpipe worked this Debian. glxgears is 300 fps. Termux is glxgears gpu 400 fps. Debian mesa-turnip-kgsl glxgears seg fault

**Comment by twaik** [comment]
It is impossible to make it work without fundamental modification of code.
