### ISSUE TITLE
I keep getting these results.

### ISSUE THREAD

**Issue by SDRausty** [termux/termux-x11#8]
I keep getting these results:

`$ ~/buildAPKs/build.github.bash https://github.com/twaik`
`Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAPKS.db`                                                         `Processing ~/buildAPKs/var/db/BNAMES: Replacing twaik 20200111 27450755 761 9 4  in ~/buildAPKs/var/db/BNAMES: Adding BNAMES to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAMES.db  DONE`                                         
AND 
                                                                                    `$ ~/buildAPKs/build.github.bash https://github.com/termux`
`Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAPKS.db`                                                         `Processing ~/buildAPKs/var/db/log/BNAMESNAPKs: Replacing termux 20200111 21668790 765 13 4  in ~/buildAPKs/var/db/log/BNAMESNAPKs: Adding log/BNAMESNAPKs to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAMES.db  DONE`

In veiw of the fact that:
```
$ l ~/storage/downloads/builtAPKs/github.orgs.termux.20200111/
total 18064
drwxrwx---  2 root     4096 Jan 11 07:18 .
drwxrwx--- 10 root     4096 Jan 11 07:28 ..
-rw-rw----  1 root    17185 Jan 11 07:18 com.example.termuxam.1578745107.apk
-rw-rw----  1 root    28750 Jan 11 07:15 com.termux.failsafe.1578744942.apk
-rw-rw----  1 root 18394991 Jan 11 07:17 com.termux.styling.1578744981.apk
-rw-rw----  1 root    36690 Jan 11 07:15 com.termux.terminal.1578744849.apk
```
AND
```
$ l ~/storage/downloads/builtAPKs/github.users.twaik.20200111/
total 264
drwxrwx---  2 root  4096 Jan 11 07:00 .
drwxrwx--- 10 root  4096 Jan 11 07:28 ..
-rw-rw----  1 root 23060 Jan 11 06:17 com.example.SanAngeles.1578741469.apk
-rw-rw----  1 root 23065 Jan 11 06:58 com.example.SanAngeles.1578743902.apk
-rw-rw----  1 root  4292 Jan 11 06:18 com.sion.sparkle.1578741479.apk
-rw-rw----  1 root  4293 Jan 11 06:58 com.sion.sparkle.1578743913.apk
-rw-rw----  1 root 36327 Jan 11 06:18 com.termux.terminal.1578741497.apk
-rw-rw----  1 root 36328 Jan 11 06:59 com.termux.terminal.1578743952.apk
-rw-rw----  1 root 60902 Jan 11 06:19 org.x.android.1578741584.apk
-rw-rw----  1 root 60897 Jan 11 07:00 org.x.android.1578744028.apk
```
AND 

[![Screenshot_20200108-222645.png](https://raw.githubusercontent.com/BuildAPKs/docsBuildAPKs/master/bitpics/screenshots/Screenshot_20200108-222645.png)](https://buildapks.github.io/docsBuildAPKs/init)

Reference: https://github.com/twaik/xorg-bionic-android/issues/2 Are better results possible? 

Cross reference: https://github.com/twaik/termux-x11/issues/6

> Are better results possible? 

Can the gradle dependencies be trimmed from the source code of this project?

**Comment by xeffyr** [comment]
Regarding screenshot at https://github.com/termux/termux-x11/issues/8#issue-548425214 - make sure that native code (\*.so files) are built and packaged into APK.

**Comment by SDRausty** [comment]
Can you outline the arch quemu method please?

**Comment by SDRausty** [comment]
> Can you outline the arch quemu method please?


Can the gradle dependencies be trimmed from the source code of this project?
Can the gradle dependencies be trimmed from the source code of this project?

No they can't.

I see a lot of frustration about building Termux apk
https://github.com/RalfWerner/integrated-process/tree/master/api29
Install arch in QEMU x86_64 and use it from here.
There you will be able to use NDK/SDK which are needed to build Termux apps.
I see a lot of frustration about building Termux apk
no
Then what the problem with building APK on VPS or CI/CD or even in QEMU (if really want on-device build) ?
why? the goal is reachable (building from source) today
We don't have problems with building our sources.
Building Termux apps without gradle on device is unsupported and this is not our target.
sur ordinateur traditionnel
Building Termux apps without gradle on device is unsupported and this is not our target.
it would be nice if it was supported
QEMU (if really want on-device build)
$ ~/buildAPKs/build.github.bash https://github.com/twaik
Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAPKS.db Processing ~/buildAPKs/var/db/BNAMES: Replacing twaik 20200111 27450755 761 9 4 in ~/buildAPKs/var/db/BNAMES: Adding BNAMES to /data/data/com.termux/files/home/buildAPKs/sources/github/users/twaik/var/conf/NAMES.db DONE
$ ~/buildAPKs/build.github.bash https://github.com/termux
Writing 4 built APKs found to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAPKS.db Processing ~/buildAPKs/var/db/log/BNAMESNAPKs: Replacing termux 20200111 21668790 765 13 4 in ~/buildAPKs/var/db/log/BNAMESNAPKs: Adding log/BNAMESNAPKs to /data/data/com.termux/files/home/buildAPKs/sources/github/orgs/termux/var/conf/NAMES.db DONE
Screenshot_20200108-222645.png
builds (does not work) builds
reference termux/termux-x11#8
It does not work because you have missed one thing.
You need to compile stuff under https://github.com/termux/termux-x11/tree/master/app/src/main/jni.
Otherwise application will not work.
Can you outline the arch quemu method please?
Is there a native Termux packages app that compiles these https://github.com/termux/termux-x11/blob/master/app/src/main/jni/Android.mk type of files?
I see a lot of frustration about building Termux apk
i love :heart: the stability Termux is developing
you might be mistaking frustration for the fact that I am working on this goal for years now @xeffyr
one of many goals that I am working on
hopefully they will be achieved
Termux is a Journey
Can you outline the arch quemu method please?

Install qemu-system-x86_64-headless and qemu-utils packages.
Download ISO file, e.g. from https://www.archlinux.org/download/.
Create HDD image. (can be done with qemu-img, how - lots of information on the Internet)
Launch QEMU. Easiest way is qemu-system-x86_64 -hda hdd.img -cdrom some_live_cd.iso -m 1G.
Another variant - https://github.com/xeffyr/alpine-term/releases, uses Alpine instead of Arch and is a bit faster. You can install docker and pull the termux/package-builder docker image that has NDK/SDK and Java installed.

Don't forget that cost of launching OS under QEMU is low performance (~100 times slower than host device).

Is there a native Termux packages app that compiles these

NDK is the official way to compile these files.

you might be mistaking frustration for the fact that I am working on this goal for years now
hopefully they will be achieved

Maybe, if you will correctly understand necessary requirements to achieve your goal.

Thank you @xeffyr !
about building Termux apk
'twas done 2 yrs ago; https://github.com/BuildAPKs/buildAPKsTermuxApp with dependencies included

update from https://gitter.im/termux/termux
