### ISSUE TITLE
Can it be as perfect as lorie is 

### ISSUE THREAD

**Issue by seisdr** [termux/termux-x11#80]
Also why Lorie is not working on android 11 or 12

**Comment by seisdr** [comment]
I mean I did test this app and it's bad

**Comment by WMCB-Tech** [comment]
Termux:X11 works fine on my Android 11 device. do you have specific problem why it's bad?

**Comment by seisdr** [comment]
After running multiple x applications it freezes and refuse any other connection

**Comment by seisdr** [comment]
On android 8

**Comment by RalfWerner** [comment]
I work on different devices for about 3 years with this App. The problem you described I only have on my **Huawei**-Phone. And have called it **SSM** = "Stupid Stalled Mode".

It can be solved by connecting a power cable (workaround). The author of the app (could not repeat it) and also I has abandoned after a few months, as it happens only on _this_ device. If you are interested in some dialogues about the topic:
https://github.com/twaik/termux-x11-outdated/issues/1, https://github.com/termux/termux-packages/issues/3535, https://github.com/RalfWerner/integrated-process/issues/1

**Comment by seisdr** [comment]
Alright on Android R it starts but I can access x server or the app is setting the app is just a process running in background with no way to restart or close , can Lorie work on Android R because I like Lorie

**Comment by seisdr** [comment]
```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
u0_a275   6882  0.0  0.0 2126996 4660 pts/0    S<s   1970   0:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a275   7285  0.0  1.0 4476596 119420 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  10699  0.0  0.0 2126996 3020 pts/0    S<    1970   0:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a275  10700  1.6  0.0 2124548 3260 pts/0    S<    1970   0:24 /data/data/com.termux/files/usr/bin/proot -0 -l --qemu=/dat
u0_a275  10702  0.0  0.1 4410156 12132 pts/0   S<l   1970   0:00 /data/data/com.termux/files/usr/bin/qemu-i386 -E LD_LIBRARY
u0_a275  12468  0.0  1.0 4476596 119432 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  14371  0.0  1.0 4476596 120008 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  14462  0.0  1.0 4476596 119320 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  15342  2.8  0.5 4411364 70600 pts/0   S<l+  1970   0:32 /data/data/com.termux/files/usr/bin/qemu-i386 -E LD_LIBRARY
u0_a275  15570  7.6  0.1 4410504 15708 pts/0   S<l+  1970   1:21 /data/data/com.termux/files/usr/bin/qemu-i386 -E LD_LIBRARY
u0_a275  20548  0.0  1.0 4476596 119196 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  22099  0.5  1.0 4476596 119440 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  22605  1.4  1.0 4476596 119732 ?      Sl    1970   0:00 /system/bin/app_process / com.termux.x11.starter.Starter :0
u0_a275  22824  0.0  0.0 2126996 4796 pts/1    S<s   1970   0:00 /data/data/com.termux/files/usr/bin/bash -l
u0_a275  22855  0.0  0.0 2124992 3108 pts/1    R<+   1970   0:00 ps aux
```

**Comment by seisdr** [comment]
![Screenshot_2022-01-15-10-39-44-58_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/45742462/149613934-c73a4d58-7259-43e7-97ea-67a77e7da90c.jpg)

**Comment by RalfWerner** [comment]
Your [Process Check](https://github.com/termux/termux-x11/issues/80#issuecomment-1013318462) shows the incomplete termux.x11 start and your [Termux Shot](https://github.com/termux/termux-x11/issues/80#issuecomment-1013636101) shows failed attempts to start an `XFCE4` XClient process with different `DISPLAY` settings. At the same time, the start of the **X11 App** with the PIP=on **Preference** is recognizable (black box). I did not find a question about your commits.

With [OTS](https://github.com/termux/termux-float/issues/37#issuecomment-916777123) I can successfully start XClients on all devices. Was my [workaround tip](https://github.com/termux/termux-x11/issues/80#issuecomment-1008312602) above helpful above for you?

**Comment by seisdr** [comment]
No this is not the Huawei device
I'm trying to use xfce or off a qemu emulator

**Comment by RalfWerner** [comment]
> No this is not the Huawei device

... what else? ... and stop SSM/freeze by power cable?

The current X11 start is very [expensive](https://github.com/termux/termux-x11/pull/19#issuecomment-998576293) and with `qemu` I have no experience except performance loss, as well as with `proot`. But  @wmcbtech30 can certainly help you.

**Comment by seisdr** [comment]
I did use older build of x11 termux it's now working with termux but using proot and qemu it doesn't detect the display port or doesn't find the x server

**Comment by seisdr** [comment]
And why can't I export display as 'DISPLAY=127.0.0.1:0' this doesn't work

**Comment by RalfWerner** [comment]
It's the same as `export DISPLAY=:0` and `XDG_RUNTIME_DIR` has to export additionally (same path).

**Comment by seisdr** [comment]
Oh now it works 
![Screenshot_2022-01-15-13-16-17-35_00df01c412509efb9bd6450c382822af](https://user-images.githubusercontent.com/45742462/149618218-f89784a0-ef0b-4199-86c6-653d247788a2.jpg)

**Comment by RalfWerner** [comment]
Nice - so close this issue
