### ISSUE TITLE
Be able to set screen resolution like in VNC and XSDL

### ISSUE THREAD

**Issue by NotteShock** [termux/termux-x11#81]

**Comment by NotteShock** [comment]
i know that but it's kinda small on my phone's screen and i prefer smaller resolution, i don't like how it will use the native resolution

**Comment by NotteShock** [comment]
also if I can't change the resolution manually then i'd prefer using vnc/xsdl instead

**Comment by NotteShock** [comment]
looks like there's no priority for this, closing

**Comment by RalfWerner** [comment]
If your root screen this size has been this is set automatic by X11 and 600x800 if you rotate!

**Comment by NotteShock** [comment]
no i mean my root device screen is a lot larger and i want it to be 800x600 instead

**Comment by NotteShock** [comment]
native resolution is too big and the fonts is too small (i knows the hidpi mode) but i want smaller resolution

**Comment by xmusjackson** [comment]
I also believe some sort of resolution scaling feature would be useful, perhaps an option in the preferences menu to scale resolution to 1/2 or 1/3. The LG G8 is a 6.1 inch screen and the resolution reported by xrandr is 2858x1436. If I choose a good DE with HiDPI support and make sure I only use HiDPI apps, I'll be fine. But if I use any app that has a hardcoded interface, items can become extremely hard to see and even click on. One such example is Runelite. Not only is the interface quite difficult to use at this resolution, but the software rendered graphics are rendering at this high resolution and framerate is directly impacted.

**Comment by RalfWerner** [comment]
@xmusjackson The apps *VNC and XSDL are not_ true_ XServers with Multitouch (Direct Mode) and Configure Events, but they only emulate this. The 2/3 finger actions of these apps have no direct interaction with the XClients. That's better at X11. E.g if your XClient=Window Manager supports scaling, this also used even if different screen split settings or PiP are used.
