### ISSUE TITLE
Got "Termux Plugin Execution Command Error" notification after starting Termux:X11 application

### ISSUE THREAD

**Issue by AntiHeadacheGuy** [termux/termux-x11#82]
Hello. When I start up Termux:X11, I got Termux Plugin Execution Command Error notification. Here is the report info:

## Report Info

**User Action**: `plugin execution command`  
**Sender**: `RunCommandService`  
**Report Timestamp**: `2022-01-13 09:52:35 UTC`  
##

## RUN_COMMAND Execution Intent Command

**Previous State**: `Pre-Execution`  
**Current State**: `Failed`  
**Executable**: `/data/data/com.termux/files/usr/libexec/termux-x11/termux-startx11`  
**Arguments:** -  
**Working Directory**: -  
**inBackground**: `true`  
**isFailsafe**: `false`  
**Session Action**: -  
**isPluginExecutionCommand**: `true`  

**Result PendingIntent Creator:** -  

**Stdout**: -  
**Stderr**: -  
**Exit Code**: -  

**Error Code**: `2`  
**Error Message**:
````
RunCommandService require `allow-external-apps` property to be set to `true` in `~/.termux/termux.properties` file.
````

### StackTraces

`-`
##

### Plugin API Help

Visit https://github.com/termux/termux-app/wiki/RUN_COMMAND-Intent for more info on RUN_COMMAND Intent usage.
##

## Termux App Info

**APP_NAME**: `Termux`  
**PACKAGE_NAME**: `com.termux`  
**VERSION_NAME**: `0.117`  
**VERSION_CODE**: `117`  
**TARGET_SDK**: `28`  
**IS_DEBUG_BUILD**: `false`  
**APK_RELEASE**: `F-Droid`  
**SIGNING_CERTIFICATE_SHA256_DIGEST**: `228FB2CFE90831C1499EC3CCAF61E96E8E1CE70766B9474672CE427334D41C42`  
##

### Software

**OS_VERSION**: `4.9.282-LineageOS+`  
**SDK_INT**: `30`  
**RELEASE**: `11`  
**ID**: `RD2A.211001.002`  
**DISPLAY**: `RD2A.211001.002`  
**INCREMENTAL**: `2`  
**SECURITY_PATCH**: `2021-11-05`  
**IS_DEBUGGABLE**: `0`  
**IS_TREBLE_ENABLED**: `true`  
**TYPE**: `user`  
**TAGS**: `release-keys`  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `Xiaomi`  
**MODEL**: `Redmi 7`  
**PRODUCT**: `dot_onclite`  
**BOARD**: `MSM8953`  
**HARDWARE**: `qcom`  
**DEVICE**: `onclite`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

When I execute `termux-x11 :1 > /dev/null`, There is no output inside terminal. I tried `termux-x11 :1` and it says if I doesn't install Termux:X11, but I already installed Termux:X11 app. What should I do to get Termux:X11 working?

**Comment by twaik** [comment]
`RunCommandService require `allow-external-apps` property to be set to `true` in `~/.termux/termux.properties` file.`
