### ISSUE TITLE
Battery drain in background

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-x11#88]
When termux-x11 is running in the background, it eats away at the battery life. I haven't been actively using Termux-x11, and it used 30% overnight.

 The application should be basically idle when in the background. 
<details>

![Screenshot_20220130-174359](https://user-images.githubusercontent.com/6258309/151721065-45cf6d2c-aa01-4a12-aae4-abf0edd80c90.png)
</details>

**Comment by wmcbtech30** [comment]
it would continuously run in the background and it's intended for normal X operations to work in the background otherwise it would be interrupted. likely in #12. termux x11 would have gotten high in cpu usage depending on what you use. remember to exit out of it when not in use

**Comment by twaik** [comment]
@easyaspi314 Can you please check if it happens with latest build [here](https://github.com/twaik/termux-x11/actions)? In these builds you can simply close Android application since it does not handle server anymore.
