### ISSUE TITLE
KDE is very big scale

### ISSUE THREAD

**Issue by Ilya114** [termux/termux-x11#89]
Hello, I installed KDE, and scale very big. How to fix?
![Screenshot_2022-02-06-15-10-17-228_com termux x11](https://user-images.githubusercontent.com/93242944/152684823-94adeda9-6222-48f9-ab88-b6bb5fed966a.jpg)

**Comment by miikodev** [comment]
You can try adjusting the DPI, see the README of the repository there is more talking about it.

**Comment by wormstest** [comment]
Scale is minimum

**Comment by miikodev** [comment]
testing in desktop environments (XFCE, LXQt, MATE) I have the same problem.

**Comment by miikodev** [comment]
I'm not sure but I think it's the geometry (like vncserver -geometry 1280x720)

**Comment by ask9027** [comment]
In xfce4 replace text of .config/xfce4/xfconf/xfce-perchannel-xml/displays.xml to this displays.txt after that you can adjust screen resolution in displays.xml
[displays.txt](https://github.com/termux/termux-x11/files/8395919/displays.txt)

**Comment by twaik** [comment]
This issue is not about xfce4, it is about kde.

**Comment by dontknowhy** [comment]
it's kwin's problem(it seems like a shared library file problem,kwin can't find it)
(I deleted a distro for this.QAQ)

**Comment by ask9027** [comment]
try to change DPI and restart session

**Comment by dontknowhy** [comment]
> try to change DPI and restart session

no 
nothing
I replaced it with xfce4

**Comment by dontknowhy** [comment]
> > try to change DPI and restart session
> 
> no 
> nothing
> I replaced it with xfce4

PS:you can change fonts DPI for normal use

**Comment by twaik** [comment]
I am pretty sure I found a way to fix this and implement something like display resolution changing feature, but I need some help with writing gui/preferences for this, because I do not know how to implement Android GUIs. It here somebody who can help me with this? @agnostic-apollo ? polkaulfield ? @suhan-paradkar ?

**Comment by twaik** [comment]
Can you please confirm if it happens on latest build?

**Comment by twaik** [comment]
In latest build you can specify resolution. DPI is set to 96 by default.
