### ISSUE TITLE
Parole media player can't play a mp4 file | missing codec name quicktime demuxer

### ISSUE THREAD

**Issue by ivam3** [termux/termux-x11#93]
When I tried to play a video file.mp4 the media player Parole on xfce4 with wayland termux app drop a pop-up mentioned that codec QuickTime demuxer is missing bringing an option to download it but it failed too.

I was searching it on APT/PKG but it's available so I going to Google but I just funded a package .deb to arm64 arch and I have aarch64 ... 

There's another way to get it !!?

![Screenshot_20220219-215446_TermuxWayland](https://user-images.githubusercontent.com/27752315/154828019-7791f636-35c5-4e25-abc7-22237fa7d0f0.jpg)

:::::::TERMUX-INFO:::::::
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.4.177-22602103 #1 SMP PREEMPT Fri Oct 15 00:57:06 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A305G
Xlib:  extension "DPMS" missing on display ":0.0".

![Screenshot_20220219-215512_TermuxWayland](https://user-images.githubusercontent.com/27752315/154828024-5cf4c4de-945f-4e10-b835-5eebb1b4d207.jpg)

**Comment by twaik** [comment]
Not related to `termux-x11`.

**Comment by ivam3** [comment]
Why not if ?
its running on termux wayland app and the package is in official termux apt repositories ? Can you explain me the reason why it was closed or where i have to report it

**Comment by Grimler91** [comment]
> Why not? if its running on termux wayland app and the package is in official termux apt repositories ? Can you explain me the reason why it was closed or where i have to report it

If issue is with parole then make a report in [x11-packages](https://github.com/termux/x11-packages/), the repository that contains parole. In this case it doesn't look like an issue with parole though, it is simply letting you know that the codec package is missing. 

Please open a package request/feature request for the missing codec to be added. Would also be great if you could research where the corresponding sources are, or if it is a configure option that needs to be added to some package
